### ISSUE TITLE
broadcom sonic errors：No module named 'sonic_platform'

### ISSUE THREAD

**Issue by zhengbiqing** [Azure/sonic-buildimage#10563]
#### Steps to reproduce the issue:
1. boot system on sonic-broadcom.bin
2.
3.

#### Describe the results you received:

ERROR 1:
zbq@sonic:~$ ishow platform firmware status
2004lTraceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fwutil/__init__.py", line 2, in <module>
    from sonic_platform.platform import Platform
ModuleNotFoundError: No module named 'sonic_platform'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fwutil", line 5, in <module>
    from fwutil.main import cli
  File "/usr/local/lib/python3.9/dist-packages/fwutil/__init__.py", line 5, in <module>
    raise ImportError("Required module not found: {}".format(str(e)))
ImportError: Required module not found: No module named 'sonic_platform'

ERROR 2:
2004l2004hzbq@sonic:~$ sudo moniitsummary -B
2004lMonit 5.20.0 uptime: 14m
 Service Name                     Status                      Type          
 sonic                            Running                     System        
 rsyslog                          Running                     Process       
 root-overlay                     Accessible                  Filesystem    
 var-log                          Accessible                  Filesystem    
 routeCheck                       Status ok                   Program       
 diskCheck                        Status ok                   Program       
 container_checker                Status failed               Program       
 vnetRouteCheck                   Status ok                   Program       
 container_memory_telemetry       Status ok                   Program  

ERROR 3:
2004hzbq@sonic:~$ show platform psustatus
2004lError: Failed to get the number of PSUs
Error: Failed to get PSU status
Error: failed to get PSU status from state DB
2004hzbq@sonic:~$ show platform psustatusfan 
2004lFan Not detected
2004hzbq@sonic:~$ show platform temperature 
2004lThermal Not detected
2004hzbq@sonic:~$ show platform syseeprom
2004lTraceback (most recent call last):
  File "/usr/local/bin/decode-syseeprom", line 18, in <module>
    import sonic_platform
ModuleNotFoundError: No module named 'sonic_platform'

and so on.

#### Output of `show version`:

```
2004l2004hzbq@sonic:~$ show version
2004l
SONiC Software Version: SONiC.202111.0-dirty-20220404.220806
Distribution: Debian 11.3
Kernel: 5.10.0-8-2-amd64
Build commit: b3478972c
Build date: Tue Apr  5 08:27:06 UTC 2022
Built by: zbq@ubuntu

Platform: x86_64-accton_as9716_32d-r0
HwSKU: Accton-AS9716-32D
ASIC: broadcom
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 06:38:53 up  1:00,  1 user,  load average: 0.15, 0.20, 0.18

Docker images:
REPOSITORY                    TAG                              IMAGE ID       SIZE
docker-orchagent              202111.0-dirty-20220404.220806   20dc5405b5b4   459MB
docker-orchagent              latest                           20dc5405b5b4   455MB
docker-teamd                  202111.0-dirty-20220404.220806   49d53fbcf18c   441MB
docker-teamd                  latest                           49d53fbcf18c   441MB
docker-sflow                  202111.0-dirty-20220404.220806   d42d94d923cb   442MB
docker-sflow                  latest                           d42d94d923cb   442MB
docker-fpm-frr                202111.0-dirty-20220404.220806   37005c684d2d   459MB
docker-fpm-frr                latest                           37005c684d2d   459MB
docker-nat                    202111.0-dirty-20220404.220806   4a31b3049149   443MB
docker-nat                    latest                           4a31b3049149   443MB
docker-macsec                 202111.0-dirty-20220404.220806   fabcb43704db   444MB
docker-macsec                 latest                           fabcb43704db   444MB
docker-iccpd                  202111.0-dirty-20220404.220806   e7137ad8439d   441MB
docker-iccpd                  latest                           e7137ad8439d   441MB
docker-dhcp-relay             latest                           36aa37aff72f   440MB
docker-platform-monitor       202111.0-dirty-20220404.220806   af6a20340075   691MB
docker-platform-monitor       latest                           af6a20340075   691MB
docker-syncd-brcm             202111.0-dirty-20220404.220806   ce030e54fe0c   805MB
docker-syncd-brcm             latest                           ce030e54fe0c   805MB
docker-gbsyncd-credo          202111.0-dirty-20220404.220806   f43636570c7d   481MB
docker-gbsyncd-credo          latest                           f43636570c7d   481MB
docker-snmp                   202111.0-dirty-20220404.220806   e64b38966462   470MB
docker-snmp                   latest                           e64b38966462   470MB
docker-sonic-mgmt-framework   202111.0-dirty-20220404.220806   1ad9434b8922   582MB
docker-sonic-mgmt-framework   latest                           1ad9434b8922   582MB
docker-sonic-telemetry        202111.0-dirty-20220404.220806   d333efb03827   515MB
docker-sonic-telemetry        latest                           d333efb03827   515MB
docker-router-advertiser      202111.0-dirty-20220404.220806   8009d8d2484c   427MB
docker-router-advertiser      latest                           8009d8d2484c   427MB
docker-lldp                   202111.0-dirty-20220404.220806   0ebb542c9921   467MB
docker-lldp                   latest                           0ebb542c9921   467MB
docker-mux                    202111.0-dirty-20220404.220806   1793fee4a928   479MB
docker-mux                    latest                           1793fee4a928   479MB
docker-database               202111.0-dirty-20220404.220806   df25b739d3b6   427MB
docker-database               latest                           df25b739d3b6   427MB
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prsunny** [comment]
[Issue Triage] Looks like a platform specific issue. Can you check if it works on master?

**Comment by jostar-yang** [comment]
This issue should only happen on 202111br. Master image is fine.  202111bra and master use kernel 5.10. But some as9716 drv compile fail due to kernel doesn't support these api. We has fixed it and send PR. The code has merged to master. But it not sync to 202111br.

**Comment by jostar-yang** [comment]
I git clone code at 5/20 from master code  and build to image. Load image to as9716 and show platoform cmd is fine.

**Comment by jostar-yang** [comment]
If you still need to use 202111br, you need to get code from master.
It need to merge below for as9716 drv,
https://github.com/Azure/sonic-buildimage/tree/master/platform/broadcom/sonic-platform-modules-accton/as9716-32d/modules
It also need to merge below code,
https://github.com/Azure/sonic-buildimage/tree/master/platform/pddf

Please make clean and rebuild image to check again.
