### ISSUE TITLE
[multiasic] Issue is shown on "sudo sfputil show presence" on a multiasic platform with minigraph generated config_db files

### ISSUE THREAD

**Issue by mlok-nokia** [Azure/sonic-buildimage#10569]
After sonic-buildimage picked up PR https://github.com/Azure/sonic-platform-common/pull/264,  command "sudo sfpulti show presence" and "eeprom" show the following back trace.   After an investigation:  On the multasic platform,  minigraph generates a partial port info (doesn't contains INDEX -- "physical_port")  and inserts to a PORT table in the CONFIG_DB in the host database if the port's external connection is specified in connection graph.  The get_port_config(hwsku, platform) call is able to get partial port info from host database in the multiasic platform.   Hence, PORT table is found in host database, and will not go the instance database get the port info.  And the logic ```fallback to hwsku/platform.json, fallback to port_config.ini.```  will not happened in this case.  If the configuration which is generated by minigraph is correct, then the get_port_config() or read_porttab_mappings() logic needs to be rewritten to support it on the multiasic platform.  

BTW, it seems the following line in the sfputilhelper.py not doing what it supposes to do (remove internal ports) --'logical' is empty in this case
 
```
logical = [name for name in logical 
                      if not name.startswith((backplane_prefix(), inband_prefix(), recirc_prefix()))]
```
```
Traceback (most recent call last):
  File "/usr/local/bin/sfputil", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sfputil/main.py", line 639, in presence
    physical_port_list = logical_port_name_to_physical_port_list(logical_port_name)
  File "/usr/local/lib/python3.9/dist-packages/sfputil/main.py", line 426, in logical_port_name_to_physical_port_list
    return platform_sfputil.get_logical_to_physical(port_name)
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_sfp/sfputilhelper.py", line 116, in get_logical_to_physical
    return self.logical_to_physical[logical_port]
KeyError: 'Ethernet3'

```

**Comment by prsunny** [comment]
@abdosi for viz

**Comment by dgsudharsan** [comment]
Can we add UT covering the scenario for multi-asic scenario? Not all vendors have multi-asic platforms and if there are no UT to cover the cases it may be difficult to test the scenarios.

**Comment by abdosi** [comment]
@anamehra @shyam77git for viz
cc @judyjoseph / @rlhui

**Comment by rlhui** [comment]
@mlok-nokia, kindly share a PR if you have it? Thanks.
