### ISSUE TITLE
Accton-AS7726-32X Show Platform Commands Not Working

### ISSUE THREAD

**Issue by AStrangwood** [Azure/sonic-buildimage#10845]
#### Description

show platform commands either show no info or error about python. This was fixed and working since https://github.com/Azure/sonic-buildimage/pull/10215 was merged but it now seems to be broken again in master.

#### Steps to reproduce the issue:
1. show platform fan

#### Describe the results you received:

```
admin@switch02:~$ show platform fan
Fan Not detected

admin@switch02:~$ show platform firmware
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fwutil/__init__.py", line 2, in <module>
    from sonic_platform.platform import Platform
ModuleNotFoundError: No module named 'sonic_platform'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fwutil", line 5, in <module>
    from fwutil.main import cli
  File "/usr/local/lib/python3.9/dist-packages/fwutil/__init__.py", line 5, in <module>
    raise ImportError("Required module not found: {}".format(str(e)))
ImportError: Required module not found: No module named 'sonic_platform'

admin@switch02:~$ show platform psustatus
Error: Failed to get the number of PSUs
Error: Failed to get PSU status
Error: failed to get PSU status from state DB

admin@switch02:~$ show platform summary
Platform: x86_64-accton_as7726_32x-r0
HwSKU: Accton-AS7726-32X
ASIC: broadcom
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A

admin@switch02:~$ show platform syseeprom
Traceback (most recent call last):
  File "/usr/local/bin/decode-syseeprom", line 18, in <module>
    import sonic_platform
ModuleNotFoundError: No module named 'sonic_platform'

admin@switch02:~$ show platform temperature
Thermal Not detected
```

#### Output of `show version`:

```
SONiC Software Version: SONiC.master.96407-8ec8900d3
Distribution: Debian 11.3
Kernel: 5.10.0-8-2-amd64
Build commit: 8ec8900d3
Build date: Fri May  6 11:53:44 UTC 2022
Built by: AzDevOps@sonic-build-workers-001HF0

Platform: x86_64-accton_as7726_32x-r0
HwSKU: Accton-AS7726-32X
ASIC: broadcom
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 14:07:04 up 6 min,  1 user,  load average: 0.40, 0.49, 0.28
Date: Thu 24 Mar 2022 14:07:04

Docker images:
REPOSITORY                    TAG                      IMAGE ID       SIZE
docker-syncd-brcm             latest                   54e49427824c   784MB
docker-syncd-brcm             master.96407-8ec8900d3   54e49427824c   784MB
docker-gbsyncd-credo          latest                   02495013f53c   423MB
docker-gbsyncd-credo          master.96407-8ec8900d3   02495013f53c   423MB
docker-dhcp-relay             latest                   1c23774fa0fe   444MB
docker-sonic-telemetry        latest                   4a98acb6458c   515MB
docker-sonic-telemetry        master.96407-8ec8900d3   4a98acb6458c   515MB
docker-mux                    latest                   2f5d6a2ac99f   483MB
docker-mux                    master.96407-8ec8900d3   2f5d6a2ac99f   483MB
docker-database               latest                   5b106b633f23   435MB
docker-database               master.96407-8ec8900d3   5b106b633f23   435MB
docker-router-advertiser      latest                   415d54cd17fc   435MB
docker-router-advertiser      master.96407-8ec8900d3   415d54cd17fc   435MB
docker-macsec                 latest                   638c8be3a70e   452MB
docker-macsec                 master.96407-8ec8900d3   638c8be3a70e   452MB
docker-orchagent              latest                   5b3bc12e4cad   439MB
docker-orchagent              master.96407-8ec8900d3   5b3bc12e4cad   439MB
docker-teamd                  latest                   7823dad31751   420MB
docker-teamd                  master.96407-8ec8900d3   7823dad31751   420MB
docker-sflow                  latest                   e79b51be7ca9   421MB
docker-sflow                  master.96407-8ec8900d3   e79b51be7ca9   421MB
docker-nat                    latest                   193f4b2360b7   423MB
docker-nat                    master.96407-8ec8900d3   193f4b2360b7   423MB
docker-fpm-frr                latest                   0922d4ba882d   439MB
docker-fpm-frr                master.96407-8ec8900d3   0922d4ba882d   439MB
docker-sonic-mgmt-framework   latest                   f9e3cebd4ced   550MB
docker-sonic-mgmt-framework   master.96407-8ec8900d3   f9e3cebd4ced   550MB
docker-snmp                   latest                   bbfccee731f2   449MB
docker-snmp                   master.96407-8ec8900d3   bbfccee731f2   449MB
docker-platform-monitor       latest                   8dc55fc5c474   519MB
docker-platform-monitor       master.96407-8ec8900d3   8dc55fc5c474   519MB
docker-lldp                   latest                   ec9317a3c4c0   446MB
docker-lldp                   master.96407-8ec8900d3   ec9317a3c4c0   446MB
```

**Comment by jostar-yang** [comment]
Does you code has merger below RP?
https://github.com/Azure/sonic-buildimage/pull/10669
There is some issue with PDDF, it will cause problem to sonic_platform.
If no sonic_platform, related cmd can't show these data.

**Comment by jostar-yang** [comment]
I git clone at 2022/5/20 and build code. After build done image to load to as7726, show platform are fine. 
root@as7726-32x-19u:~# show platform fan
  Drawer    LED         FAN    Speed    Direction    Presence    Status          Timestamp
--------  -----  ----------  -------  -----------  ----------  --------  -----------------
Fantray1  green  Fantray1_1      38%      EXHAUST     Present        OK  20220523 06:43:57
Fantray1  green  Fantray1_2      38%      EXHAUST     Present        OK  20220523 06:43:57
Fantray2  green  Fantray2_1      38%      EXHAUST     Present        OK  20220523 06:43:57
Fantray2  green  Fantray2_2      38%      EXHAUST     Present        OK  20220523 06:43:57

So please update code and your issue should be fixed.

**Comment by jostar-yang** [comment]
root@as7726-32x-19u:~# show platform temp
                  Sensor    Temperature    High TH    Low TH    Crit High TH    Crit Low TH    Warning          Timestamp
------------------------  -------------  ---------  --------  --------------  -------------  ---------  -----------------
           CB_temp(0x4B)           21.5       80.0       N/A             N/A            N/A      False  20220523 06:43:58
           FB_temp(0x4C)           21.5       80.0       N/A             N/A            N/A      False  20220523 06:43:58
  MB_FrontMAC_temp(0x49)           23.5       80.0       N/A             N/A            N/A      False  20220523 06:43:58


root@as7726-32x-19u:~# show platform psustatus
PSU    Model       Serial              HW Rev      Voltage (V)    Current (A)    Power (W)  Status    LED
-----  ----------  ------------------  --------  -------------  -------------  -----------  --------  -----
PSU 1  FSF019-611  FSF0192105002864    N/A                0.00           0.00         0.00  NOT OK    off
PSU 2  YM-2651Y    SA070V581905000055  N/A               12.08          10.16       120.00  OK        green

**Comment by jostar-yang** [comment]
root@as7726-32x-19u:~# show platform summary
Platform: x86_64-accton_as7726_32x-r0
HwSKU: Accton-AS7726-32X
ASIC: broadcom
ASIC Count: 1
Serial Number: 772632X1911006
Model Number: FP3ZZ7632074A
Hardware Revision: N/A

**Comment by lgzcoollg** [comment]
I got similar issue at AS7716-32X at SONiC.202405.612889-a2ea2a9dd. pls help #19913

**Comment by hannescam** [comment]
I have this problem too with a AS5812-54X running SONiC.master.645186-367495d03 (the newest link on the supported devices page)

**Comment by clammers** [comment]
Seems that it could be fixed with this PR [#25325](https://github.com/sonic-net/sonic-buildimage/pull/25325)
