### ISSUE TITLE
[multi-asic]: load minigraph is failing on multi-asic vs with latest master branch image

### ISSUE THREAD

**Issue by SuvarnaMeenakshi** [Azure/sonic-buildimage#11269]
#### Description

The multi-asic  image  from Jun19th does not see any issue: https://dev.azure.com/mssonic/build/_build/results?buildId=112200&view=results
The multi-asic image from Jun 22 has this issue https://dev.azure.com/mssonic/build/_build/results?buildId=113368&view=results
#### Steps to reproduce the issue:
1. Take sonic-4asic-vs.img.gz from https://dev.azure.com/mssonic/build/_build/results?buildId=113368&view=results pipeline, copy this as sonic-vs.img.gz if ~/sonic-vm/images/
2. Bring up 4-asic vs testbed cd /data/sonic-mgmt/ansible
./testbed-cli.sh -t vtestbed.yaml -m veos_vtb -k ceos add-topo vms-kvm-four-asic-t1-lag password.txt
3. deploy-mg:
4. ./testbed-cli.sh -t vtestbed.yaml -m veos_vtb deploy-mg vms-kvm-four-asic-t1-lag veos_vtb password.txt

#### Describe the results you received:
```
sudo config load_minigraph -y
Stopping SONiC target ...
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json   --write-to-db
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json  -n asic0 --write-to-db
Warning: Failed to get device ID from asic.conf file for asic0
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json  -n asic1 --write-to-db
Warning: Failed to get device ID from asic.conf file for asic1
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json  -n asic2 --write-to-db
Warning: Failed to get device ID from asic.conf file for asic2
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json  -n asic3 --write-to-db
Warning: Failed to get device ID from asic.conf file for asic3
Running command: /usr/local/bin/sonic-cfggen -d -y /etc/sonic/sonic_version.yml -t /usr/share/sonic/templates/sonic-environment.j2,/etc/sonic/sonic-environment
Running command: config qos reload --no-dynamic-buffer
Running command: /usr/local/bin/sonic-cfggen -n asic0 -d --write-to-db -t /usr/share/sonic/device/x86_64-kvm_x86_64-r0/msft_four_asic_vs/0/buffers.json.j2,config-db -t /usr/share/sonic/device/x86_64-kvm_x86_64-r0/msft_four_asic_vs/0/qos.json.j2,config-db -y /etc/sonic/sonic_version.yml
Running command: /usr/local/bin/sonic-cfggen -n asic1 -d --write-to-db -t /usr/share/sonic/device/x86_64-kvm_x86_64-r0/msft_four_asic_vs/1/buffers.json.j2,config-db -t /usr/share/sonic/device/x86_64-kvm_x86_64-r0/msft_four_asic_vs/1/qos.json.j2,config-db -y /etc/sonic/sonic_version.yml
Running command: /usr/local/bin/sonic-cfggen -n asic2 -d --write-to-db -t /usr/share/sonic/device/x86_64-kvm_x86_64-r0/msft_four_asic_vs/2/buffers.json.j2,config-db -t /usr/share/sonic/device/x86_64-kvm_x86_64-r0/msft_four_asic_vs/2/qos.json.j2,config-db -y /etc/sonic/sonic_version.yml
Running command: /usr/local/bin/sonic-cfggen -n asic3 -d --write-to-db -t /usr/share/sonic/device/x86_64-kvm_x86_64-r0/msft_four_asic_vs/3/buffers.json.j2,config-db -t /usr/share/sonic/device/x86_64-kvm_x86_64-r0/msft_four_asic_vs/3/qos.json.j2,config-db -y /etc/sonic/sonic_version.yml
Running command: pfcwd start_default
Traceback (most recent call last):
  File "/usr/local/bin/pfcwd", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 57, in new_func
    obj = ctx.ensure_object(object_type)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 477, in ensure_object
    self.obj = rv = object_type()
  File "/usr/local/lib/python3.9/dist-packages/utilities_common/db.py", line 36, in __init__
    multi_asic.connect_config_db_for_ns(ns)
  File "/usr/local/lib/python3.9/dist-packages/sonic_py_common/multi_asic.py", line 43, in connect_config_db_for_ns
    config_db = swsscommon.ConfigDBConnector(namespace=namespace)
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1945, in __init__
    super(ConfigDBConnector, self).__init__(use_unix_socket_path = use_unix_socket_path, namespace = namespace)
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1575, in __init__
    for db_name in self.get_db_list():
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1511, in get_db_list
    return _swsscommon.SonicV2Connector_Native_get_db_list(self)
RuntimeError: :- validateNamespace: Initialize global DB config using API SonicDBConfig::initializeGlobalConfig
```

#### Describe the results you expected:
config load_minigraph should go through without an error:
pfcwd start_default -- was not causing error earlier, but is showing issue now.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by SuvarnaMeenakshi** [comment]
Do not see this issue without https://github.com/Azure/sonic-buildimage/commit/c1d0d2e0234a5e8adb921f8978fd3a6760fea967

**Comment by liuh-80** [comment]
The issue may relate with this PR:
https://github.com/Azure/sonic-utilities/pull/2183

This PR change InterfaceAliasConverter() to lazy initialize. and InterfaceAliasConverter() will try load DB config if it's not initialized.

Then pfcwd seems not initialize DB config by itself, so when InterfaceAliasConverter() change to lazy initialize, pfcwd breaked.

To fix this issue, pfcwd need initialize config with load_db_config() method in it's main() function.

**Comment by liuh-80** [comment]
Close because fixed by this PR: https://github.com/Azure/sonic-utilities/pull/2238
