### ISSUE TITLE
Other images cannot be installed on Arista devices from current master branch image

### ISSUE THREAD

**Issue by saiarcot895** [Azure/sonic-buildimage#13808]
#### Steps to reproduce the issue:
1. On a Arista device, load an image from the master branch
2. Try to install any different image

#### Describe the results you received:

```
No errors detected in compressed data of /tmp/sonic_image.swi.
Verifing image SONiC-OS-20201231.89 signature...
Traceback (most recent call last):
  File "/usr/local/bin/sonic-installer", line 8, in <module>
    sys.exit(sonic_installer())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sonic_installer/main.py", line 582, in install
    if not bootloader.verify_image_sign(image_path):
AttributeError: 'AbootBootloader' object has no attribute 'verify_image_sign'
```

#### Describe the results you expected:

Image should've been successfully installed.

#### Output of `show version`:

```
SONiC Software Version: SONiC.master.217163-43683d8ce
Distribution: Debian 11.6
Kernel: 5.10.0-18-2-amd64
Build commit: 43683d8ce
Build date: Sun Feb 12 12:24:53 UTC 2023
Built by: AzDevOps@vmss-soni000H4S
 
Platform: x86_64-arista_7050cx3_32s
HwSKU: Arista-7050CX3-32S-C32
ASIC: broadcom
ASIC Count: 1
Serial Number: JPE21041573
Model Number: DCS-7050CX3-32S
Hardware Revision: 01.00
Uptime: 07:24:12 up 44 min,  1 user,  load average: 0.88, 0.81, 0.76
Date: Tue 14 Feb 2023 07:24:12
 
Docker images:
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-orchagent              latest                    644681abb907   385MB
docker-orchagent              master.217163-43683d8ce   644681abb907   385MB
docker-fpm-frr                latest                    419b30e66c96   403MB
docker-fpm-frr                master.217163-43683d8ce   419b30e66c96   403MB
docker-teamd                  latest                    460f613c8ddb   374MB
docker-teamd                  master.217163-43683d8ce   460f613c8ddb   374MB
docker-macsec                 latest                    2db6dc44cb6c   376MB
docker-syncd-brcm             latest                    a1087110378f   701MB
docker-syncd-brcm             master.217163-43683d8ce   a1087110378f   701MB
docker-gbsyncd-broncos        latest                    cc247b65918d   405MB
docker-gbsyncd-broncos        master.217163-43683d8ce   cc247b65918d   405MB
docker-gbsyncd-credo          latest                    45999a94a005   376MB
docker-gbsyncd-credo          master.217163-43683d8ce   45999a94a005   376MB
docker-dhcp-relay             latest                    9d171a2c8e8f   366MB
docker-eventd                 latest                    7b9c7a5f2198   357MB
docker-eventd                 master.217163-43683d8ce   7b9c7a5f2198   357MB
docker-snmp                   latest                    9577a9e7d4d0   397MB
docker-snmp                   master.217163-43683d8ce   9577a9e7d4d0   397MB
docker-sonic-p4rt             latest                    4559c7c536ac   927MB
docker-sonic-p4rt             master.217163-43683d8ce   4559c7c536ac   927MB
docker-sonic-telemetry        latest                    ac606bd57c33   655MB
docker-sonic-telemetry        master.217163-43683d8ce   ac606bd57c33   655MB
docker-platform-monitor       latest                    81c6f199e888   479MB
docker-platform-monitor       master.217163-43683d8ce   81c6f199e888   479MB
docker-router-advertiser      latest                    da66bd9ec7a0   357MB
docker-router-advertiser      master.217163-43683d8ce   da66bd9ec7a0   357MB
docker-lldp                   latest                    85549fa32605   399MB
docker-lldp                   master.217163-43683d8ce   85549fa32605   399MB
```
#### Additional information you deem important (e.g. issue happens only occasionally):

This appears to be caused by sonic-net/sonic-utilities#2337. The PR added an implementation for GRUB bootloaders, but not the Aboot bootloader or uboot bootloader (which, I think but am not sure, is used for ARM). Because of this, other images cannot even be installed.

**Comment by saiarcot895** [comment]
@ycoheNvidia FYI

**Comment by saiarcot895** [comment]
I see sonic-net/sonic-utilities#2646 will fix this issue.

**Comment by judyjoseph** [comment]
There is a new PR created https://github.com/sonic-net/sonic-utilities/pull/2698
