### ISSUE TITLE
How to add a description for PortChannel

### ISSUE THREAD

**Issue by louishot** [Azure/sonic-buildimage#14530]
Hello,

How to add a description for PortChannel?

`I did sudo config interface description PortChannel0 myportname123` doesn't work, and it will broken 'show interfaces status' command
And also I can't find a command to delete the description for interface, I can only delete it in redis to fix it.
```
Traceback (most recent call last):
  File "/usr/local/bin/intfutil", line 941, in <module>
    main()
  File "/usr/local/bin/intfutil", line 921, in main
    interface_stat.display_intf_status()
  File "/usr/local/bin/intfutil", line 488, in display_intf_status
    self.get_intf_status()
  File "/usr/local/lib/python3.9/dist-packages/utilities_common/multi_asic.py", line 151, in wrapped_run_on_all_asics
    func(self,  *args, **kwargs)
  File "/usr/local/bin/intfutil", line 579, in get_intf_status
    self.table += self.generate_intf_status()
  File "/usr/local/bin/intfutil", line 528, in generate_intf_status
    port_oper_speed_get(self.db, key)))
  File "/usr/local/bin/intfutil", line 203, in port_oper_speed_get
    return port_speed_parse(oper_speed, optics_type)
  File "/usr/local/bin/intfutil", line 149, in port_speed_parse
    speed = int(in_speed)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by vmittal-msft** [comment]
Please provide more information about the issue. e.g. image version etc

**Comment by louishot** [comment]
> Please provide more information about the issue. e.g. image version etc
I using SONiC 202111
