### ISSUE TITLE
  make target/python-wheels/bookworm/sonic_config_engine-1.0-py3-none-any.whl fails on master for marvell amd64

### ISSUE THREAD

**Issue by CraftyChimera** [Azure/sonic-buildimage#20614]
#### Description
 The following tests fail while trying to build on master for marvell amd64:

```
FAILED tests/test_cfggen.py::TestCfgGen::test_minigraph_packet_chassis_acl_local_host - subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml', '--print-data']' returned non-zero exit status 1.
FAILED tests/test_chassis_cfggen.py::TestVoqChassisSup::test_device_metadata - subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/chassis_data/voq_chassis_data/voq_chassis_sup.xml', '-p', '', '--var-json', 'DEVICE_METADATA']' returned non-zero exit status 1.
FAILED tests/test_chassis_cfggen.py::TestVoqChassisSup::test_mgmt_port - subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/chassis_data/voq_chassis_data/voq_chassis_sup.xml', '-p', '', '--var-json', 'MGMT_PORT']' returned non-zero exit status 1.
FAILED tests/test_chassis_cfggen.py::TestVoqChassisSup::test_ntp - subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/chassis_data/voq_chassis_data/voq_chassis_sup.xml', '-p', '', '--var-json', 'NTP_SERVER']' returned non-zero exit status 1.
FAILED tests/test_chassis_cfggen.py::TestVoqChassisSup::test_print_data - subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/chassis_data/voq_chassis_data/voq_chassis_sup.xml', '-p', '', '--print-data']' returned non-zero exit status 1.
FAILED tests/test_chassis_cfggen.py::TestVoqChassisSup::test_tacacs - subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/chassis_data/voq_chassis_data/voq_chassis_sup.xml', '-p', '', '--var-json', 'TACPLUS_SERVER']' returned non-zero exit status 1.
FAILED tests/test_j2files.py::TestJ2Files::test_buffers_dell6100_render_template - AssertionError: --- /sonic/src/sonic-config-engine/tests/sample_output/py3/buffers-dell6100.json	2024-10-22 10:00:05.660381371 +0000
FAILED tests/test_multinpu_cfggen.py::TestMultiNpuCfgGen::test_hwsku_option_port_list_configdb - subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-k', 'multi-npu-asic', '-n', 'asic0', '-v', 'PORT.keys()|list']' returned non-zero exit status 1.
FAILED tests/test_multinpu_cfggen.py::TestMultiNpuCfgGen::test_hwsku_option_port_list_port_config_ini - subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-k', 'multi-npu-asic', '-n', 'asic0', '-v', 'PORT.keys()|list']' returned non-zero exit status 1.
================== 9 failed, 297 passed in 244.24s (0:04:04) ===================

```
Most of these tests fail with OSError("Failed to locate platform directory"). I believe this might be related to #18180, since trying to silence the tests gave me the same results as the OP in that issue

#### Steps to reproduce the issue:
1. make init
2. make configure BLDENV=bookworm DOCKER_BUILDKIT=0 PLATFORM=marvell
3. make target/python-wheels/bookworm/sonic_config_engine-1.0-py3-none-any.whl SONIC_BUILD_JOBS=15 NOBUSTER=1 NOBULLSEYE=1 BLDENV=bookworm PLATFORM=marvell

#### Describe the results you received:
Build failure

#### Describe the results you expected:
Build to succeed

#### Output of `show version`:
NA
#### Output of `show techsupport`:
NA

#### Additional information you deem important (e.g. issue happens only occasionally):
[output_make.txt](https://github.com/user-attachments/files/17517449/output_make.txt)

**Comment by arlakshm** [comment]
Can you repro this issue consistently?

**Comment by CraftyChimera** [comment]
Yes. The build always fails at this step for me

**Comment by maksymxglubokiy** [comment]
I experience the same problem.

**Comment by wwicak** [comment]
whoever encounter this problem, I have simillar issue, it turns out, because I use venv in my build folder. When I deactivate the python venv, the build worked

**Comment by fhibler** [comment]
Exactly the same issue here. Tried different env vars already, but none seems to work. I don't have a venv in my build folder.
Although my build is for `PLATFORM=vs`

Environment: Ubuntu 22.04.5 aarch64
Building for arm64

Chain of build commands:
```
git clone --recurse-submodules https://github.com/sonic-net/sonic-buildimage.git $HOME/sonic-buildimage
cd sonic-buildimage
git checkout 202505
git fetch

NOBUSTER=1 SONIC_BUILD_JOBS=4 make init PLATFORM=vs PLATFORM_ARCH=arm64
NOBUSTER=1 SONIC_BUILD_JOBS=4 make configure PLATFORM=vs PLATFORM_ARCH=arm64
NOBUSTER=1 SONIC_BUILD_JOBS=4 make PLATFORM=vs PLATFORM_ARCH=arm64 target/docker-sonic-vs.gz
```

Fail Log:
```
[ FAIL LOG START ] [ target/python-wheels/bookworm/sonic_config_engine-1.0-py3-none-any.whl ]
Build start time: Tue Dec 16 16:31:05 UTC 2025
[ REASON ] :      target/python-wheels/bookworm/sonic_config_engine-1.0-py3-none-any.whl does not exist   NON-EXISTENT PREREQUISITES: target/python-wheels/bookworm/sonic_py_common-1.0-py3-none-any.whl-install target/python-wheels/bookworm/sonic_yang_mgmt-1.0-py3-none-any.whl-install target/python-wheels/bookworm/sonic_yang_models-1.0-py3-none-any.whl-install target/debs/bookworm/libyang_1.0.73_arm64.deb-install target/debs/bookworm/libyang-cpp_1.0.73_arm64.deb-install target/debs/bookworm/python3-yang_1.0.73_arm64.deb-install target/debs/bookworm/python3-swsscommon_1.0.0_arm64.deb-install 
[ FLAGS  FILE    ] : [] 
[ FLAGS  DEPENDS ] : [] 
[ FLAGS  DIFF    ] : [] 
/sonic/src/sonic-config-engine /sonic
Defaulting to user installation because normal site-packages is not writeable
Processing /sonic/src/sonic-config-engine
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: Jinja2>=2.10 in /usr/lib/python3/dist-packages (from sonic-config-engine==1.0) (3.1.2)
Collecting bitarray==2.8.1 (from sonic-config-engine==1.0)
  Downloading bitarray-2.8.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (32 kB)
Collecting ipaddress==1.0.23 (from sonic-config-engine==1.0)
  Downloading ipaddress-1.0.23-py2.py3-none-any.whl.metadata (923 bytes)
Collecting lxml==4.9.1 (from sonic-config-engine==1.0)
  Downloading lxml-4.9.1.tar.gz (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting netaddr==0.8.0 (from sonic-config-engine==1.0)
  Downloading netaddr-0.8.0-py2.py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: pyyaml==6.0.1 in /var/florian/.local/lib/python3.11/site-packages (from sonic-config-engine==1.0) (6.0.1)
Requirement already satisfied: sonic-py-common in /usr/local/lib/python3.11/dist-packages (from sonic-config-engine==1.0) (1.0)
Requirement already satisfied: sonic-yang-mgmt>=1.0 in /usr/local/lib/python3.11/dist-packages (from sonic-config-engine==1.0) (1.0)
Requirement already satisfied: sonic-yang-models>=1.0 in /usr/local/lib/python3.11/dist-packages (from sonic-config-engine==1.0) (1.0)
Requirement already satisfied: ijson==3.2.3 in /var/florian/.local/lib/python3.11/site-packages (from sonic-yang-mgmt>=1.0->sonic-config-engine==1.0) (3.2.3)
Requirement already satisfied: jsondiff>=1.2.0 in /var/florian/.local/lib/python3.11/site-packages (from sonic-yang-mgmt>=1.0->sonic-config-engine==1.0) (2.2.1)
Requirement already satisfied: jsonpointer>=1.9 in /var/florian/.local/lib/python3.11/site-packages (from sonic-yang-mgmt>=1.0->sonic-config-engine==1.0) (3.0.0)
Requirement already satisfied: tabulate==0.9.0 in /var/florian/.local/lib/python3.11/site-packages (from sonic-yang-mgmt>=1.0->sonic-config-engine==1.0) (0.9.0)
Requirement already satisfied: xmltodict==0.12.0 in /var/florian/.local/lib/python3.11/site-packages (from sonic-yang-mgmt>=1.0->sonic-config-engine==1.0) (0.12.0)
Requirement already satisfied: natsort in /var/florian/.local/lib/python3.11/site-packages (from sonic-py-common->sonic-config-engine==1.0) (8.4.0)
Requirement already satisfied: redis-dump-load in /usr/local/lib/python3.11/dist-packages (from sonic-py-common->sonic-config-engine==1.0) (1.1)
Requirement already satisfied: redis in /usr/local/lib/python3.11/dist-packages (from redis-dump-load->sonic-py-common->sonic-config-engine==1.0) (5.2.1)
Requirement already satisfied: async-timeout>=4.0.3 in /usr/local/lib/python3.11/dist-packages (from redis->redis-dump-load->sonic-py-common->sonic-config-engine==1.0) (5.0.1)
Downloading bitarray-2.8.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (297 kB)
Downloading ipaddress-1.0.23-py2.py3-none-any.whl (18 kB)
Downloading netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 2.4 MB/s eta 0:00:00
Building wheels for collected packages: sonic-config-engine, lxml
  Building wheel for sonic-config-engine (setup.py): started
  Building wheel for sonic-config-engine (setup.py): finished with status 'done'
  Created wheel for sonic-config-engine: filename=sonic_config_engine-1.0-py3-none-any.whl size=72013 sha256=7a3a728ce2828a9cd2cf882fa3b885d3e080613406915221f741b2e20aa8015c
  Stored in directory: /var/florian/.cache/pip/wheels/d6/20/93/958810a489f45ce9d949eeca5cc8fcd1aee2bac31fd65ca95f
  Building wheel for lxml (setup.py): started
  Building wheel for lxml (setup.py): finished with status 'done'
  Created wheel for lxml: filename=lxml-4.9.1-cp311-cp311-linux_aarch64.whl size=6851179 sha256=c37bb40f992c75b8f9a890738d4892c40d2c0c8a43d7dbbeb3f023074db410bb
  Stored in directory: /var/florian/.cache/pip/wheels/1a/37/70/9f9495db92c8112a4502d3b8ecb858b269e1f1d6c10003be30
Successfully built sonic-config-engine lxml
Installing collected packages: netaddr, ipaddress, bitarray, lxml, sonic-config-engine
  WARNING: The script netaddr is installed in '/var/florian/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyangbind 0.8.2 requires enum34, which is not installed.
Successfully installed bitarray-2.8.1 ipaddress-1.0.23 lxml-4.9.1 netaddr-0.8.0 sonic-config-engine-1.0

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python3 -m pip install --upgrade pip
Found existing installation: sonic-config-engine 1.0
Uninstalling sonic-config-engine-1.0:
  Successfully uninstalled sonic-config-engine-1.0
Defaulting to user installation because normal site-packages is not writeable
Processing /sonic/src/sonic-config-engine
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: Jinja2>=2.10 in /usr/lib/python3/dist-packages (from sonic-config-engine==1.0) (3.1.2)
Requirement already satisfied: bitarray==2.8.1 in /var/florian/.local/lib/python3.11/site-packages (from sonic-config-engine==1.0) (2.8.1)
Requirement already satisfied: ipaddress==1.0.23 in /var/florian/.local/lib/python3.11/site-packages (from sonic-config-engine==1.0) (1.0.23)
Requirement already satisfied: lxml==4.9.1 in /var/florian/.local/lib/python3.11/site-packages (from sonic-config-engine==1.0) (4.9.1)
Requirement already satisfied: netaddr==0.8.0 in /var/florian/.local/lib/python3.11/site-packages (from sonic-config-engine==1.0) (0.8.0)
Requirement already satisfied: pyyaml==6.0.1 in /var/florian/.local/lib/python3.11/site-packages (from sonic-config-engine==1.0) (6.0.1)
Requirement already satisfied: sonic-py-common in /usr/local/lib/python3.11/dist-packages (from sonic-config-engine==1.0) (1.0)
Requirement already satisfied: sonic-yang-mgmt>=1.0 in /usr/local/lib/python3.11/dist-packages (from sonic-config-engine==1.0) (1.0)
Requirement already satisfied: sonic-yang-models>=1.0 in /usr/local/lib/python3.11/dist-packages (from sonic-config-engine==1.0) (1.0)
WARNING: sonic-config-engine 1.0 does not provide the extra 'testing'
Requirement already satisfied: ijson==3.2.3 in /var/florian/.local/lib/python3.11/site-packages (from sonic-yang-mgmt>=1.0->sonic-config-engine==1.0) (3.2.3)
Requirement already satisfied: jsondiff>=1.2.0 in /var/florian/.local/lib/python3.11/site-packages (from sonic-yang-mgmt>=1.0->sonic-config-engine==1.0) (2.2.1)
Requirement already satisfied: jsonpointer>=1.9 in /var/florian/.local/lib/python3.11/site-packages (from sonic-yang-mgmt>=1.0->sonic-config-engine==1.0) (3.0.0)
Requirement already satisfied: tabulate==0.9.0 in /var/florian/.local/lib/python3.11/site-packages (from sonic-yang-mgmt>=1.0->sonic-config-engine==1.0) (0.9.0)
Requirement already satisfied: xmltodict==0.12.0 in /var/florian/.local/lib/python3.11/site-packages (from sonic-yang-mgmt>=1.0->sonic-config-engine==1.0) (0.12.0)
Requirement already satisfied: natsort in /var/florian/.local/lib/python3.11/site-packages (from sonic-py-common->sonic-config-engine==1.0) (8.4.0)
Requirement already satisfied: redis-dump-load in /usr/local/lib/python3.11/dist-packages (from sonic-py-common->sonic-config-engine==1.0) (1.1)
Requirement already satisfied: redis in /usr/local/lib/python3.11/dist-packages (from redis-dump-load->sonic-py-common->sonic-config-engine==1.0) (5.2.1)
Requirement already satisfied: async-timeout>=4.0.3 in /usr/local/lib/python3.11/dist-packages (from redis->redis-dump-load->sonic-py-common->sonic-config-engine==1.0) (5.0.1)
Building wheels for collected packages: sonic-config-engine
  Building wheel for sonic-config-engine (setup.py): started
  Building wheel for sonic-config-engine (setup.py): finished with status 'done'
  Created wheel for sonic-config-engine: filename=sonic_config_engine-1.0-py3-none-any.whl size=72013 sha256=5fa0e0e77177d51d9e956e889825a4cb097f355da2236fd660fae0231e01e9d5
  Stored in directory: /var/florian/.cache/pip/wheels/d6/20/93/958810a489f45ce9d949eeca5cc8fcd1aee2bac31fd65ca95f
Successfully built sonic-config-engine
Installing collected packages: sonic-config-engine
Successfully installed sonic-config-engine-1.0

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python3 -m pip install --upgrade pip
Found existing installation: sonic-config-engine 1.0
Uninstalling sonic-config-engine-1.0:
  Successfully uninstalled sonic-config-engine-1.0
============================= test session starts ==============================
platform linux -- Python 3.11.2, pytest-7.2.1, pluggy-1.0.0+repack
rootdir: /sonic/src/sonic-config-engine
plugins: pyfakefs-5.7.4, cov-4.0.0
collected 311 items

tests/test_cfggen.py ............................................F...... [ 16%]
.................................                                        [ 27%]
tests/test_cfggen_from_yang.py ..................                        [ 32%]
tests/test_cfggen_pfx_filter.py .                                        [ 33%]
tests/test_cfggen_platformJson.py ......                                 [ 35%]
tests/test_cfggen_t2_chassis_fe.py ......                                [ 36%]
tests/test_chassis_cfggen.py ........................................... [ 50%]
..............                                                           [ 55%]
tests/test_frr.py ......                                                 [ 57%]
tests/test_j2files.py ...............................................    [ 72%]
tests/test_j2files_t2_chassis_fe.py ...                                  [ 73%]
tests/test_minigraph_case.py ........................................... [ 87%]
                                                                         [ 87%]
tests/test_multinpu_cfggen.py ........................................   [100%]

=================================== FAILURES ===================================
___________ TestCfgGen.test_minigraph_packet_chassis_acl_local_host ____________

self = <tests.test_cfggen.TestCfgGen testMethod=test_minigraph_packet_chassis_acl_local_host>

    def test_minigraph_packet_chassis_acl_local_host(self):
        # CFGGEN_UNIT_TESTING is set to '2' in the set_up function
        # this causes the port_table to have ports from the previous test
        # causing yang validation to fail
    
        os.environ["CFGGEN_UNIT_TESTING"] = ""
        argument = ['-m', self.packet_chassis_graph, '-v', "ACL_TABLE"]
>       output = self.run_script(argument)

tests/test_cfggen.py:1032: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_cfggen.py:63: in run_script
    self.assertTrue(self.yang.validate(argument))
tests/common_utils.py:88: in validate
    output = subprocess.check_output(cmd).decode()
/usr/lib/python3.11/subprocess.py:466: in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

input = None, capture_output = False, timeout = None, check = True
popenargs = (['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml', '--print-data'],)
kwargs = {'stdout': -1}
process = <Popen: returncode: 1 args: ['python3', '/sonic/src/sonic-config-engine/test...>
stdout = b'', stderr = None, retcode = 1

    def run(*popenargs,
            input=None, capture_output=False, timeout=None, check=False, **kwargs):
        """Run command with arguments and return a CompletedProcess instance.
    
        The returned instance will have attributes args, returncode, stdout and
        stderr. By default, stdout and stderr are not captured, and those attributes
        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them,
        or pass capture_output=True to capture both.
    
        If check is True and the exit code was non-zero, it raises a
        CalledProcessError. The CalledProcessError object will have the return code
        in the returncode attribute, and output & stderr attributes if those streams
        were captured.
    
        If timeout is given, and the process takes too long, a TimeoutExpired
        exception will be raised.
    
        There is an optional argument "input", allowing you to
        pass bytes or a string to the subprocess's stdin.  If you use this argument
        you may not also use the Popen constructor's "stdin" argument, as
        it will be used internally.
    
        By default, all communication is in bytes, and therefore any "input" should
        be bytes, and the stdout and stderr will be bytes. If in text mode, any
        "input" should be a string, and stdout and stderr will be strings decoded
        according to locale encoding, or by "encoding" if set. Text mode is
        triggered by setting any of text, encoding, errors or universal_newlines.
    
        The other arguments are the same as for the Popen constructor.
        """
        if input is not None:
            if kwargs.get('stdin') is not None:
                raise ValueError('stdin and input arguments may not both be used.')
            kwargs['stdin'] = PIPE
    
        if capture_output:
            if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:
                raise ValueError('stdout and stderr arguments may not be used '
                                 'with capture_output.')
            kwargs['stdout'] = PIPE
            kwargs['stderr'] = PIPE
    
        with Popen(*popenargs, **kwargs) as process:
            try:
                stdout, stderr = process.communicate(input, timeout=timeout)
            except TimeoutExpired as exc:
                process.kill()
                if _mswindows:
                    # Windows accumulates the output in a single blocking
                    # read() call run on child threads, with the timeout
                    # being done in a join() on those threads.  communicate()
                    # _after_ kill() is required to collect that and add it
                    # to the exception.
                    exc.stdout, exc.stderr = process.communicate()
                else:
                    # POSIX _communicate already populated the output so
                    # far into the TimeoutExpired exception.
                    process.wait()
                raise
            except:  # Including KeyboardInterrupt, communicate handled that.
                process.kill()
                # We don't call process.wait() as .__exit__ does that for us.
                raise
            retcode = process.poll()
            if check and retcode:
>               raise CalledProcessError(retcode, process.args,
                                         output=stdout, stderr=stderr)
E               subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml', '--print-data']' returned non-zero exit status 1.

/usr/lib/python3.11/subprocess.py:571: CalledProcessError
----------------------------- Captured stdout call -----------------------------

    Running sonic-cfggen -m /sonic/src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml -v ACL_TABLE

    Validating yang schema
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/sonic/src/sonic-config-engine/tests/../sonic-cfggen", line 530, in <module>
    main()
  File "/sonic/src/sonic-config-engine/tests/../sonic-cfggen", line 404, in main
    deep_update(data, parse_xml(minigraph, platform, asic_name=asic_name))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sonic/src/sonic-config-engine/minigraph.py", line 2064, in parse_xml
    (ports, alias_map, alias_asic_map) = get_port_config(hwsku=hwsku, platform=platform, port_config_file=port_config_file, asic_name=asic_name, hwsku_config_file=hwsku_config_file)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sonic/src/sonic-config-engine/portconfig.py", line 193, in get_port_config
    port_config_file = device_info.get_path_to_port_config_file(hwsku, asic_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sonic_py_common/device_info.py", line 443, in get_path_to_port_config_file
    platform_path = get_path_to_platform_dir()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sonic_py_common/device_info.py", line 264, in get_path_to_platform_dir
    raise OSError("Failed to locate platform directory")
OSError: Failed to locate platform directory
=========================== short test summary info ============================
FAILED tests/test_cfggen.py::TestCfgGen::test_minigraph_packet_chassis_acl_local_host - subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml', '--print-data']' returned non-zero exit status 1.
================== 1 failed, 310 passed in 169.07s (0:02:49) ===================
[  FAIL LOG END  ] [ target/python-wheels/bookworm/sonic_config_engine-1.0-py3-none-any.whl ]
make: *** [slave.mk:948: target/python-wheels/bookworm/sonic_config_engine-1.0-py3-none-any.whl] Error 1
```

Any help is appreciated.

**Comment by skv0816-ciena** [comment]
Running the build in an Ubuntu container for sonic-vs.bin still shows the issue 
Command used:
make PLATFORM=vs PLATFORM_ARCH=amd64 configure
make PLATFORM=vs target/sonic-vs.bin
 I'm new to the SONiC community. Could you help me understand? For now, I am commenting out these test cases 

`
=================================== FAILURES ===================================
___________ TestCfgGen.test_minigraph_packet_chassis_acl_local_host ____________

self = <tests.test_cfggen.TestCfgGen testMethod=test_minigraph_packet_chassis_acl_local_host>

    def test_minigraph_packet_chassis_acl_local_host(self):
        # CFGGEN_UNIT_TESTING is set to '2' in the set_up function
        # this causes the port_table to have ports from the previous test
        # causing yang validation to fail
    
        os.environ["CFGGEN_UNIT_TESTING"] = ""
        argument = ['-m', self.packet_chassis_graph, '-v', "ACL_TABLE"]
>       output = self.run_script(argument)

tests/test_cfggen.py:1032: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_cfggen.py:63: in run_script
    self.assertTrue(self.yang.validate(argument))
tests/common_utils.py:88: in validate
    output = subprocess.check_output(cmd).decode()
/usr/lib/python3.13/subprocess.py:472: in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

input = None, capture_output = False, timeout = None, check = True
popenargs = (['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml', '--print-data'],)
kwargs = {'stdout': -1}
process = <Popen: returncode: 1 args: ['python3', '/sonic/src/sonic-config-engine/test...>
stdout = b'', stderr = None, retcode = 1

    def run(*popenargs,
            input=None, capture_output=False, timeout=None, check=False, **kwargs):
        """Run command with arguments and return a CompletedProcess instance.
    
        The returned instance will have attributes args, returncode, stdout and
        stderr. By default, stdout and stderr are not captured, and those attributes
        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them,
        or pass capture_output=True to capture both.
    
        If check is True and the exit code was non-zero, it raises a
        CalledProcessError. The CalledProcessError object will have the return code
        in the returncode attribute, and output & stderr attributes if those streams
        were captured.
    
        If timeout (seconds) is given and the process takes too long,
         a TimeoutExpired exception will be raised.
    
        There is an optional argument "input", allowing you to
        pass bytes or a string to the subprocess's stdin.  If you use this argument
        you may not also use the Popen constructor's "stdin" argument, as
        it will be used internally.
    
        By default, all communication is in bytes, and therefore any "input" should
        be bytes, and the stdout and stderr will be bytes. If in text mode, any
        "input" should be a string, and stdout and stderr will be strings decoded
        according to locale encoding, or by "encoding" if set. Text mode is
        triggered by setting any of text, encoding, errors or universal_newlines.
    
        The other arguments are the same as for the Popen constructor.
        """
        if input is not None:
            if kwargs.get('stdin') is not None:
                raise ValueError('stdin and input arguments may not both be used.')
            kwargs['stdin'] = PIPE
    
        if capture_output:
            if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:
                raise ValueError('stdout and stderr arguments may not be used '
                                 'with capture_output.')
            kwargs['stdout'] = PIPE
            kwargs['stderr'] = PIPE
    
        with Popen(*popenargs, **kwargs) as process:
            try:
                stdout, stderr = process.communicate(input, timeout=timeout)
            except TimeoutExpired as exc:
                process.kill()
                if _mswindows:
                    # Windows accumulates the output in a single blocking
                    # read() call run on child threads, with the timeout
                    # being done in a join() on those threads.  communicate()
                    # _after_ kill() is required to collect that and add it
                    # to the exception.
                    exc.stdout, exc.stderr = process.communicate()
                else:
                    # POSIX _communicate already populated the output so
                    # far into the TimeoutExpired exception.
                    process.wait()
                raise
            except:  # Including KeyboardInterrupt, communicate handled that.
                process.kill()
                # We don't call process.wait() as .__exit__ does that for us.
                raise
            retcode = process.poll()
            if check and retcode:
>               raise CalledProcessError(retcode, process.args,
                                         output=stdout, stderr=stderr)
E               subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml', '--print-data']' returned non-zero exit status 1.

/usr/lib/python3.13/subprocess.py:577: CalledProcessError
----------------------------- Captured stdout call -----------------------------

    Running sonic-cfggen -m /sonic/src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml -v ACL_TABLE

    Validating yang schema
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/sonic/src/sonic-config-engine/tests/../sonic-cfggen", line 549, in <module>
    main()
    ~~~~^^
  File "/sonic/src/sonic-config-engine/tests/../sonic-cfggen", line 419, in main
    deep_update(data, parse_xml(minigraph, platform, asic_name=asic_name))
                      ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sonic/src/sonic-config-engine/minigraph.py", line 2064, in parse_xml
    (ports, alias_map, alias_asic_map) = get_port_config(hwsku=hwsku, platform=platform, port_config_file=port_config_file, asic_name=asic_name, hwsku_config_file=hwsku_config_file)
                                         ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sonic/src/sonic-config-engine/portconfig.py", line 193, in get_port_config
    port_config_file = device_info.get_path_to_port_config_file(hwsku, asic_id)
  File "/usr/local/lib/python3.13/dist-packages/sonic_py_common/device_info.py", line 471, in get_path_to_port_config_file
    platform_path = get_path_to_platform_dir()
  File "/usr/local/lib/python3.13/dist-packages/sonic_py_common/device_info.py", line 292, in get_path_to_platform_dir
    raise OSError("Failed to locate platform directory")
OSError: Failed to locate platform directory
=============================== warnings summary ===============================
<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute

<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute

<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: builtin type swigvarlink has no __module__ attribute

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_cfggen.py::TestCfgGen::test_minigraph_packet_chassis_acl_local_host - subprocess.CalledProcessError: Command '['python3', '/sonic/src/sonic-config-engine/tests/../sonic-cfggen', '-m', '/sonic/src/sonic-config-engine/tests/sample-chassis-packet-lc-graph.xml', '--print-data']' returned non-zero exit status 1.
============ 1 failed, 327 passed, 3 warnings in 291.65s (0:04:51) =============
[  FAIL LOG END  ] [ target/python-wheels/trixie/sonic_config_engine-1.0-py3-none-any.whl ]
make: *** [slave.mk:1085: target/python-wheels/trixie/sonic_config_engine-1.0-py3-none-any.whl] Error 1
make: *** Waiting for unfinished jobs....
make[1]: *** [Makefile.work:695: target/sonic-vs.bin] Error 2
make[1]: Leaving directory '/localdisk/sonic/sonic-buildimage'
make: *** [Makefile:51: target/sonic-vs.bin] Error 2
`
