### ISSUE TITLE
AssertionError: Assertion failed for start.sh: RUNNING not in STARTING

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#2136]
**Description**

supervisord crashed due to clock moved backward.

```
Sep 27 09:44:37.256048 hostname INFO supervisord: start.sh teamd: started
Sep 27 09:44:37.272313 hostname INFO teamd.sh[4245]: Traceback (most recent call last):
Sep 27 09:44:37.272802 hostname INFO teamd.sh[4245]: File "/usr/bin/supervisord", line 9, in <module>
Sep 27 09:44:37.273493 hostname INFO teamd.sh[4245]: load_entry_point('supervisor==3.3.3', 'console_scripts', 'supervisord')()
Sep 27 09:44:37.273906 hostname INFO teamd.sh[4245]: File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 363, in main
Sep 27 09:44:37.274271 hostname INFO teamd.sh[4245]: go(options)
Sep 27 09:44:37.274637 hostname INFO teamd.sh[4245]: File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 373, in go
Sep 27 09:44:37.275001 hostname INFO teamd.sh[4245]: d.main()
Sep 27 09:44:37.275388 hostname INFO teamd.sh[4245]: File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 84, in main
Sep 27 09:44:37.275763 hostname INFO teamd.sh[4245]: self.run()
Sep 27 09:44:37.276154 hostname INFO teamd.sh[4245]: File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 101, in run
Sep 27 09:44:37.276525 hostname INFO teamd.sh[4245]: self.runforever()
Sep 27 09:44:37.276892 hostname INFO teamd.sh[4245]: File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 253, in runforever
Sep 27 09:44:37.277268 hostname INFO teamd.sh[4245]: self.reap()
Sep 27 09:44:37.277636 hostname INFO teamd.sh[4245]: File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 289, in reap
Sep 27 09:44:37.278005 hostname INFO teamd.sh[4245]: process.finish(pid, sts)
Sep 27 09:44:37.278379 hostname INFO teamd.sh[4245]: File "/usr/lib/python2.7/dist-packages/supervisor/process.py", line 527, in finish
Sep 27 09:44:37.278757 hostname INFO teamd.sh[4245]: self._assertInState(ProcessStates.STARTING)
Sep 27 09:44:37.279137 hostname INFO teamd.sh[4245]: File "/usr/lib/python2.7/dist-packages/supervisor/process.py", line 179, in _assertInState
Sep 27 09:44:37.279508 hostname INFO teamd.sh[4245]: self.config.name, current_state, allowable_states))
Sep 27 09:44:37.279885 hostname INFO teamd.sh[4245]: AssertionError: Assertion failed for start.sh: RUNNING not in STARTING
```
time shift backward after teamd docker starts

```
Sep 27 09:44:40.973916 hostname INFO snmp.sh[4299]: 2018-09-27 09:44:40,973 INFO spawned: 'snmpd' with pid 33
Sep 27 09:44:27.315683 hostname INFO systemd[1]: Time has been changed
Sep 27 09:44:27.464486 hostname INFO snmpd-config-updater: Platform is not an Arista platform. Exiting...
```

supervisord version 3.3.3

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
#762

**Comment by stcheng** [comment]
This bug is still open.

**Comment by jleveque** [comment]
Fixed in https://github.com/Azure/sonic-buildimage/pull/2624
