### ISSUE TITLE
Traceback error seen while issuing show interface commands with if_names

### ISSUE THREAD

**Issue by mfriyas** [Azure/sonic-buildimage#2641]
Description:-

In dell s6100 loaded with latest master build , while issuing show interface status and show interfaces description commands with interface names getting traceback error.

Issue Logs:-

root@sonic-s6100-01:/home/admin# show interfaces status fortyGigE1/1/1
Traceback (most recent call last):
  File "/usr/bin/intfutil", line 206, in <module>
    main(sys.argv[1:])
  File "/usr/bin/intfutil", line 199, in main
    interface_stat = IntfStatus(intf_name)
  File "/usr/bin/intfutil", line 131, in __init__
    appl_db_keys = appl_db_keys_get(self.appl_db, intf_name)
  File "/usr/bin/intfutil", line 42, in appl_db_keys_get
    appl_db_keys = db.keys(appl_db.APPL_DB, "PORT_TABLE:%s" % intf_name)          fortyGigE1/ /fortyGigE1/1/1 l name 'db' is not defined                       o fortyGigE1/1/1     

root@sonic-s6100-01:/home/admin# show interfaces description fortyGigE1/1/1
Traceback (most recent call last):
  File "/usr/bin/intfutil", line 206, in <module>
    main(sys.argv[1:])
  File "/usr/bin/intfutil", line 201, in main
    interface_desc = IntfDescription(intf_name)
  File "/usr/bin/intfutil", line 178, in __init__
    appl_db_keys = appl_db_keys_get(self.appl_db, intf_name)
  File "/usr/bin/intfutil", line 42, in appl_db_keys_get
    appl_db_keys = db.keys(appl_db.APPL_DB, "PORT_TABLE:%s" % intf_name)
NameError: global name 'db' is not defined

show version:-

root@sonic-s6100-01:/home/admin# show version
SONiC Software Version: SONiC.HEAD.879-8300408
Distribution: Debian 9.8
Kernel: 4.9.0-8-2-amd64
Build commit: 8300408
Build date: Mon Feb 25 14:44:16 UTC 2019
Built by: johnar@jenkins-worker-4

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.879-8300408    a33cb194138c        360MB
docker-syncd-brcm          latest              a33cb194138c        360MB
docker-orchagent-brcm      HEAD.879-8300408    634f14b71691        285MB
docker-orchagent-brcm      latest              634f14b71691        285MB
docker-lldp-sv2            HEAD.879-8300408    fbf0558cd46b        273MB
docker-lldp-sv2            latest              fbf0558cd46b        273MB
docker-dhcp-relay          HEAD.879-8300408    3c1bce153e31        255MB
docker-dhcp-relay          latest              3c1bce153e31        255MB
docker-database            HEAD.879-8300408    eed55ff42ddc        290MB
docker-database            latest              eed55ff42ddc        290MB
docker-snmp-sv2            HEAD.879-8300408    9b36f1d316fc        293MB
docker-snmp-sv2            latest              9b36f1d316fc        293MB
docker-teamd               HEAD.879-8300408    de9158350dc7        273MB
docker-teamd               latest              de9158350dc7        273MB
docker-router-advertiser   HEAD.879-8300408    7a3fb62c37bf        288MB
docker-router-advertiser   latest              7a3fb62c37bf        288MB
docker-platform-monitor    HEAD.879-8300408    b605d8e11903        285MB
docker-platform-monitor    latest              b605d8e11903        285MB
docker-fpm-quagga          HEAD.879-8300408    8b530eeb31fc        280MB
docker-fpm-quagga          latest              8b530eeb31fc        280MB

root@sonic-s6100-01:/home/admin#

**Comment by xinliu-seattle** [comment]
@mfriyas: we will be able to fix this. can you propose a test to catch this?

**Comment by xinliu-seattle** [comment]
@tsvanduyn Travis assign this bug to you, thanks!

**Comment by lguohan** [comment]
fixed in https://github.com/Azure/sonic-utilities/pull/479

**Comment by lguohan** [comment]
fixed in Azure/sonic-utilities#440
