### ISSUE TITLE
swss stretch update broke restore_neighbors.py for neigh service

### ISSUE THREAD

**Issue by jipanyang** [Azure/sonic-buildimage#2735]
**Description**
Not seen with old version of swss docker.

With new swss docker,  read_routes6() of linux.py for scapy translate ipv6 address `2000:0:0:100::1` into invalid format of `2000::100::1`

**Steps to reproduce the issue:**
1. 
root@ASW-A1-1:/home/admin# ip add add 2000:0:0:100::1/56 dev lo
root@ASW-A1-1:/home/admin# 
root@ASW-A1-1:/home/admin# 

2.
root@ASW-A1-1:/home/admin# cat /proc/net/if_inet6
`20000000000001000000000000000001 01 38 00 80       lo`
00000000000000000000000000000001 01 80 10 80       lo
30010000000000000000000000000001 01 80 00 80       lo
fe8000000000000002e0ecfffece1d76 02 40 20 80     eth0
root@ASW-A1-1:/home/admin# 

3. 
```
root@ASW-A1-1:/home/admin# docker exec -it swss /usr/bin/restore_neighbors.py
Traceback (most recent call last):
  File "/usr/bin/restore_neighbors.py", line 25, in <module>
    from scapy.all import conf, in6_getnsma, inet_pton, inet_ntop, in6_getnsmac, get_if_hwaddr, Ether, ARP, IPv6, ICMPv6ND_NS, ICMPv6NDOptSrcLLAddr
  File "/usr/lib/python2.7/dist-packages/scapy/all.py", line 28, in <module>
    from scapy.route6 import *
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 275, in <module>
    _res = conf.route6.route("::/0")
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 216, in route
    if in6_isincluded(dst, p, plen):
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 653, in in6_isincluded
    zero = inet_pton(socket.AF_INET6, prefix)
  File "/usr/lib/python2.7/dist-packages/scapy/pton_ntop.py", line 40, in inet_pton
    raise Exception("Illegal syntax for IP address")
Exception: Illegal syntax for IP address
```

```
root@ASW-A1-1:/home/admin# show version
SONiC Software Version: SONiC.HEAD.916-fd3f611
Distribution: Debian 9.8
Kernel: 4.9.0-8-2-amd64
Build commit: fd3f611
Build date: Tue Apr  2 22:13:17 UTC 2019
Built by: johnar@jenkins-worker-3

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.916-fd3f611    b10b2956de94        361MB
docker-syncd-brcm          latest              b10b2956de94        361MB
docker-lldp-sv2            HEAD.916-fd3f611    919b8773169a        274MB
docker-lldp-sv2            latest              919b8773169a        274MB
docker-dhcp-relay          HEAD.916-fd3f611    6d2f5e867e25        256MB
docker-dhcp-relay          latest              6d2f5e867e25        256MB
docker-teamd               HEAD.916-fd3f611    132599ea2974        274MB
docker-teamd               latest              132599ea2974        274MB
docker-snmp-sv2            HEAD.916-fd3f611    2b1703f8e93c        294MB
docker-snmp-sv2            latest              2b1703f8e93c        294MB
docker-fpm-quagga          HEAD.916-fd3f611    4fda7adfc830        281MB
docker-fpm-quagga          latest              4fda7adfc830        281MB
docker-orchagent-brcm      HEAD.916-fd3f611    70aa2fca5572        315MB
docker-orchagent-brcm      latest              70aa2fca5572        315MB
docker-router-advertiser   HEAD.916-fd3f611    2b403dca1af4        279MB
docker-router-advertiser   latest              2b403dca1af4        279MB
docker-database            HEAD.916-fd3f611    36a965a077fe        280MB
docker-database            latest              36a965a077fe        280MB
docker-sonic-telemetry     HEAD.916-fd3f611    ea2b320d951f        300MB
docker-sonic-telemetry     latest              ea2b320d951f        300MB
docker-platform-monitor    HEAD.916-fd3f611    0a58e9257a87        323MB
docker-platform-monitor    latest              0a58e9257a87        323MB

root@ASW-A1-1:/home/admin# 
```

**Comment by jipanyang** [comment]
It looks the exact same issue: https://github.com/secdev/scapy/issues/359
Fixed with https://github.com/secdev/scapy/pull/363

**Comment by jipanyang** [comment]
The previous version:
```

root@sonic:/# scapy
INFO: Can't import python gnuplot wrapper . Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python Crypto lib. Won't be able to decrypt WEP.
INFO: Can't import python Crypto lib. Disabled certificate manipulation tools
Welcome to Scapy (2.2.0)

```

Current version: (what version ??)
```
root@ASW-A1-1:/home/admin# scapy
INFO: Can't import matplotlib. Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python Crypto lib. Won't be able to decrypt WEP.
INFO: Can't import python Crypto lib. Disabled certificate manipulation tools
INFO: Can't import python ecdsa lib. Disabled certificate manipulation tools
Welcome to Scapy (unknown.version)
>>> 
```
