### ISSUE TITLE
snmp AgentX socket bind failed

### ISSUE THREAD

**Issue by wangxin** [Azure/sonic-buildimage#3986]
**Description**

In syslog of SONiC switch, below error can be constantly observed:

```
Jan  7 07:30:10.069789 sonic_switch INFO snmp#snmp-subagent [ax_interface] INFO: Attempting AgentX socket bind...
Jan  7 07:30:10.070425 sonic_switch ERR snmp#snmp-subagent [ax_interface] ERROR: Socket bind failed. "Is 'snmpd' running?". Retrying in 3 seconds...
```

This issue is only observed on master image. This error message failed many test cases because of loganalyzer.

**Steps to reproduce the issue:**
1. No special step is required. Just check /var/log/syslog.
2.
3.

**Describe the results you received:**
Error message `ERR snmp#snmp-subagent [ax_interface] ERROR: Socket bind failed. "Is 'snmpd' running?"` in syslog

**Describe the results you expected:**
No such issue and error log.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
```
$ show version

SONiC Software Version: SONiC.HEAD.164-12212467
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: 12212467
Build date: Sun Jan  5 05:53:09 UTC 2020
Built by: johnar@jenkins-worker-7

Platform: x86_64-mlnx_msn2700-r0
HwSKU: ACS-MSN2700
ASIC: mellanox
Serial Number: MT1822K07815
Uptime: 07:49:47 up  8:51,  1 user,  load average: 4.29, 4.36, 4.49

Docker images:
REPOSITORY                    TAG                 IMAGE ID            SIZE
docker-syncd-mlnx             HEAD.164-12212467   bb9a5d6982ab        377MB
docker-syncd-mlnx             latest              bb9a5d6982ab        377MB
docker-platform-monitor       HEAD.164-12212467   ee0256482773        569MB
docker-platform-monitor       latest              ee0256482773        569MB
docker-fpm-frr                HEAD.164-12212467   877caa29466a        325MB
docker-fpm-frr                latest              877caa29466a        325MB
docker-sflow                  HEAD.164-12212467   855c1c0629bc        305MB
docker-sflow                  latest              855c1c0629bc        305MB
docker-lldp-sv2               HEAD.164-12212467   bb358f8d389c        303MB
docker-lldp-sv2               latest              bb358f8d389c        303MB
docker-orchagent              HEAD.164-12212467   c63f0ed23e05        323MB
docker-orchagent              latest              c63f0ed23e05        323MB
docker-dhcp-relay             HEAD.164-12212467   ff963b77f067        290MB
docker-dhcp-relay             latest              ff963b77f067        290MB
docker-database               HEAD.164-12212467   579b8e5a9108        282MB
docker-database               latest              579b8e5a9108        282MB
docker-snmp-sv2               HEAD.164-12212467   648de813c3c8        339MB
docker-snmp-sv2               latest              648de813c3c8        339MB
docker-teamd                  HEAD.164-12212467   0e2c02696fe3        305MB
docker-teamd                  latest              0e2c02696fe3        305MB
docker-sonic-mgmt-framework   HEAD.164-12212467   be8fabb24421        330MB
docker-sonic-mgmt-framework   latest              be8fabb24421        330MB
docker-sonic-telemetry        HEAD.164-12212467   b5071cfd0dd8        343MB
docker-sonic-telemetry        latest              b5071cfd0dd8        343MB
docker-router-advertiser      HEAD.164-12212467   cbdd2a63a6f4        282MB
docker-router-advertiser      latest              cbdd2a63a6f4        282MB
```

    **Attach debug file `sudo generate_dump`:**

**Comment by liat-grozovik** [comment]
Need to be fixed for 201911 release

**Comment by volodymyrsamotiy** [comment]
This issue is also observed on latest ```201811``` SONiC image (e. g. ```SONiC.HEAD.29-0a2e9da```)

**Comment by qiluo-msft** [comment]
I tested https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-201811/29/artifact/target/sonic-mellanox.bin and it works fine.

I tested https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all/164/artifact/target/sonic-mellanox.bin and the bug is reproducible.

```
admin@sonic:~$ docker exec -it snmp bash
root@sonic:/# vi /usr/bin/start.sh
root@sonic:/# sonic-cfggen -d -y /etc/sonic/snmp.yml -t /usr/share/sonic/templates/snmpd.conf.j2
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 318, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 254, in main
    additional_data = yaml.load(stream)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "/etc/sonic/snmp.yml", line 1, column 1
expected <block end>, but found '<scalar>'
  in "/etc/sonic/snmp.yml", line 3, column 25
```

**Comment by qiluo-msft** [comment]
This bug is introduced by https://github.com/Azure/sonic-buildimage/pull/3928
And later fixed by https://github.com/Azure/sonic-buildimage/pull/4002

I tested https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all/169/artifact/target/sonic-mellanox.bin and confirm it is working.

Please be aware the bug is exposed by a ill-format `/etc/sonic/snmp.yml`, and if you use `sonic_installer` to install another image, the old config will be copied to new image. So please clean it before you test.
