### ISSUE TITLE
Warm reboot from 201811 to 201911 failed due to directed-connected route entries without nexthop address.

### ISSUE THREAD

**Issue by stephenxs** [Azure/sonic-buildimage#4399]
**Description**
Warm reboot from 201811 to 201911 failed due to route entries without nexthop address.

**Steps to reproduce the issue:**
1. Install 201911 image on system running 201811
2. warm reboot system

**Describe the results you received:**
orchagent segment failed.
log:
```
Apr  8 06:28:40.561810 arc-switch1004 NOTICE swss#orchagent: :- setPortPvid: Set pvid 1000 to port: Ethernet50
Apr  8 06:28:40.562214 arc-switch1004 NOTICE swss#orchagent: :- setHostIntfsStripTag: Set SAI_HOSTIF_VLAN_TAG_KEEP to host interface: Ethernet52
Apr  8 06:28:40.562349 arc-switch1004 NOTICE swss#orchagent: :- addBridgePort: Add bridge port Ethernet52 to default 1Q bridge
Apr  8 06:28:40.562792 arc-switch1004 NOTICE swss#orchagent: :- addVlanMember: Add member Ethernet52 to VLAN Vlan1000 vid:1000 pid1000000000698
Apr  8 06:28:40.564265 arc-switch1004 NOTICE swss#orchagent: :- setPortPvid: Set pvid 1000 to port: Ethernet52
Apr  8 06:28:40.564265 arc-switch1004 NOTICE swss#orchagent: :- setHostIntfsStripTag: Set SAI_HOSTIF_VLAN_TAG_KEEP to host interface: Ethernet54
Apr  8 06:28:40.564265 arc-switch1004 NOTICE swss#orchagent: :- addBridgePort: Add bridge port Ethernet54 to default 1Q bridge
Apr  8 06:28:40.564265 arc-switch1004 NOTICE swss#orchagent: :- addVlanMember: Add member Ethernet54 to VLAN Vlan1000 vid:1000 pid10000000006b9
Apr  8 06:28:40.564265 arc-switch1004 NOTICE swss#orchagent: :- setPortPvid: Set pvid 1000 to port: Ethernet54
Apr  8 06:28:40.564754 arc-switch1004 NOTICE swss#orchagent: :- setHostIntfsStripTag: Set SAI_HOSTIF_VLAN_TAG_KEEP to host interface: Ethernet56
Apr  8 06:28:40.564890 arc-switch1004 NOTICE swss#orchagent: :- addBridgePort: Add bridge port Ethernet56 to default 1Q bridge
Apr  8 06:28:40.565276 arc-switch1004 NOTICE swss#orchagent: :- addVlanMember: Add member Ethernet56 to VLAN Vlan1000 vid:1000 pid10000000005d2
Apr  8 06:28:40.565513 arc-switch1004 NOTICE swss#orchagent: :- setPortPvid: Set pvid 1000 to port: Ethernet56
Apr  8 06:28:40.566015 arc-switch1004 NOTICE swss#orchagent: :- setHostIntfsStripTag: Set SAI_HOSTIF_VLAN_TAG_KEEP to host interface: Ethernet6
Apr  8 06:28:40.566178 arc-switch1004 NOTICE swss#orchagent: :- addBridgePort: Add bridge port Ethernet6 to default 1Q bridge
Apr  8 06:28:40.566521 arc-switch1004 NOTICE swss#orchagent: :- addVlanMember: Add member Ethernet6 to VLAN Vlan1000 vid:1000 pid100000000094d
Apr  8 06:28:40.566754 arc-switch1004 NOTICE swss#orchagent: :- setPortPvid: Set pvid 1000 to port: Ethernet6
Apr  8 06:28:40.567291 arc-switch1004 NOTICE swss#orchagent: :- setHostIntfsStripTag: Set SAI_HOSTIF_VLAN_TAG_KEEP to host interface: Ethernet8
Apr  8 06:28:40.567422 arc-switch1004 NOTICE swss#orchagent: :- addBridgePort: Add bridge port Ethernet8 to default 1Q bridge
Apr  8 06:28:40.567885 arc-switch1004 NOTICE swss#orchagent: :- addVlanMember: Add member Ethernet8 to VLAN Vlan1000 vid:1000 pid1000000000866
Apr  8 06:28:40.570028 arc-switch1004 NOTICE swss#orchagent: :- setPortPvid: Set pvid 1000 to port: Ethernet8
Apr  8 06:28:40.572027 arc-switch1004 INFO kernel: [   77.457480] orchagent[4646]: segfault at 0 ip 000055d618e3a2c5 sp 00007ffc7b02f9e0 error 4 in orchagent[55d618dff000+1c2000]
```
gdb info
```
Reading symbols from /usr/bin/orchagent...Reading symbols from /usr/lib/debug/.build-id/f9/f7c948d51b9b792fdf96ca65f87d419dda12ca.debug...done.
done.
[New LWP 37]
[New LWP 54]
[New LWP 55]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/orchagent -d /var/log/swss -b 8192'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055d618e3a2c5 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider (__a=..., __dat=<optimized out>, this=<optimized out>)
    at /usr/include/c++/6/bits/basic_string.h:110
110     /usr/include/c++/6/bits/basic_string.h: No such file or directory.
[Current thread is 1 (Thread 0x7f30057416c0 (LWP 37))]
(gdb) bt
#0  0x000055d618e3a2c5 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider (__a=..., __dat=<optimized out>, this=<optimized out>)
    at /usr/include/c++/6/bits/basic_string.h:110
#1  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (__str=..., this=0x7ffc7b02fcf0) at /usr/include/c++/6/bits/basic_string.h:399
#2  std::operator+<char, std::char_traits<char>, std::allocator<char> > (__rhs=64 '@', __lhs=..., this=<optimized out>) at /usr/include/c++/6/bits/basic_string.h:5001
#3  RouteOrch::doTask (this=0x55d61a8db8b0, consumer=...) at routeorch.cpp:490
#4  0x000055d618e29e32 in Orch::doTask (this=0x55d61a8db8b0) at orch.cpp:419
#5  0x000055d618e224fd in OrchDaemon::warmRestoreAndSyncUp (this=this@entry=0x55d61a8a2e30) at orchdaemon.cpp:549
#6  0x000055d618e26938 in OrchDaemon::init (this=0x7ffc00000047) at orchdaemon.cpp:401
#7  0x000055d618e0feb1 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:311
(gdb)
```

According to the source code, it can crash if it receives a routing entry with empty nexthop.
in `void RouteOrch::doTask(Consumer& consumer)`
```
            for (auto i : kfvFieldsValues(t))
            {
                if (fvField(i) == "nexthop")
                    ips = fvValue(i);

                if (fvField(i) == "ifname")
                    aliases = fvValue(i);
            }
            vector<string> ipv = tokenize(ips, ',');
            vector<string> alsv = tokenize(aliases, ',');

            for (auto alias : alsv)
            {
                if (alias == "eth0" || alias == "lo" || alias == "docker0")
                {
                    excp_intfs_flag = true;
                    break;
                }
            }

            // TODO: cannot trust m_portsOrch->getPortIdByAlias because sometimes alias is empty
            if (excp_intfs_flag)
            {
                /* If any existing routes are updated to point to the
                 * above interfaces, remove them from the ASIC. */
                if (removeRoute(vrf_id, ip_prefix))
                    it = consumer.m_toSync.erase(it);
                else
                    it++;
                continue;
            }

            string nhg_str = ipv[0] + NH_DELIMITER + alsv[0];//this line causes error
            for (uint32_t i = 1; i < ipv.size(); i++)
            {
                nhg_str += NHG_DELIMITER + ipv[i] + NH_DELIMITER + alsv[i];
            }

```
From the sonic dump there are following entries in APPL_DB. I suspect they cause the crash.
```
  "ROUTE_TABLE:10.0.0.56/31": {
    "type": "hash",
    "value": {
      "ifname": "PortChannel0001",
      "nexthop": ""
    }
  },
  "ROUTE_TABLE:10.0.0.58/31": {
    "type": "hash",
    "value": {
      "ifname": "PortChannel0002",
      "nexthop": ""
    }
  },
  "ROUTE_TABLE:10.0.0.60/31": {
    "type": "hash",
    "value": {
      "ifname": "PortChannel0003",
      "nexthop": ""
    }
  },
  "ROUTE_TABLE:10.0.0.62/31": {
    "type": "hash",
    "value": {
      "ifname": "PortChannel0004",
      "nexthop": ""
    }
  },

  "ROUTE_TABLE:127.0.0.0/8": {
    "type": "hash",
    "value": {
      "ifname": "lo",
      "nexthop": ""
    }
  },
  "ROUTE_TABLE:192.168.0.0/21": {
    "type": "hash",
    "value": {
      "ifname": "Vlan1000",
      "nexthop": ""
    }
  },

```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `show version`:**

```

admin@arc-switch1004:~$ show version

SONiC Software Version: SONiC.HEAD.0-dirty-20200407.121233
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: 249265ad
Build date: Tue Apr  7 06:33:17 UTC 2020
Built by: kebol@arc-build-server-2

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700-D48C8
ASIC: mellanox
Serial Number: MT1822K07823
Uptime: 13:40:55 up 22 min,  1 user,  load average: 0.97, 0.81, 0.93

Docker images:
REPOSITORY                    TAG                            IMAGE ID            SIZE
docker-syncd-mlnx             HEAD.0-dirty-20200407.121233   a8c51f1141a3        383MB
docker-syncd-mlnx             latest                         a8c51f1141a3        383MB
docker-router-advertiser      HEAD.0-dirty-20200407.121233   c228771a23d4        283MB
docker-router-advertiser      latest                         c228771a23d4        283MB
docker-platform-monitor       HEAD.0-dirty-20200407.121233   86fabb434565        628MB
docker-platform-monitor       latest                         86fabb434565        628MB
docker-fpm-frr                HEAD.0-dirty-20200407.121233   d5dbc9f4988b        327MB
docker-fpm-frr                latest                         d5dbc9f4988b        327MB
docker-lldp-sv2               HEAD.0-dirty-20200407.121233   dac0f386ea2d        304MB
docker-lldp-sv2               latest                         dac0f386ea2d        304MB
docker-dhcp-relay             HEAD.0-dirty-20200407.121233   757410483e93        293MB
docker-dhcp-relay             latest                         757410483e93        293MB
docker-database               HEAD.0-dirty-20200407.121233   ac7684a5969e        283MB
docker-database               latest                         ac7684a5969e        283MB
docker-sflow                  HEAD.0-dirty-20200407.121233   0490a8ade857        308MB
docker-sflow                  latest                         0490a8ade857        308MB
docker-teamd                  HEAD.0-dirty-20200407.121233   b3242c1f1f3f        307MB
docker-teamd                  latest                         b3242c1f1f3f        307MB
docker-snmp-sv2               HEAD.0-dirty-20200407.121233   b197a084c2b2        340MB
docker-snmp-sv2               latest                         b197a084c2b2        340MB
docker-orchagent              HEAD.0-dirty-20200407.121233   422bb10beebe        326MB
docker-orchagent              latest                         422bb10beebe        326MB
docker-nat                    HEAD.0-dirty-20200407.121233   a5ca9f43bed4        309MB
docker-nat                    latest                         a5ca9f43bed4        309MB
docker-sonic-mgmt-framework   HEAD.0-dirty-20200407.121233   1713225fe846        421MB
docker-sonic-mgmt-framework   latest                         1713225fe846        421MB
docker-sonic-telemetry        HEAD.0-dirty-20200407.121233   d474172e495b        344MB
docker-sonic-telemetry        latest                         d474172e495b        344MB

```

**Attach debug file `sudo generate_dump`:**

[sonic_dump_arc-switch1004_20200408_083950.tar.gz](https://github.com/Azure/sonic-buildimage/files/4450869/sonic_dump_arc-switch1004_20200408_083950.tar.gz)

**Comment by lguohan** [comment]
@stephenxs , thanks for reporting this issue. it looks like there is a schema change in the appdb from 201811 to 201911.

In 201911 and master, the schema change to 
```
127.0.0.1:6379> hgetall "ROUTE_TABLE:10.0.0.60/31"
1) "nexthop"
2) "0.0.0.0"
3) "ifname"
4) "PortChannel0003"
```

it looks like due to this change. https://github.com/Azure/sonic-swss/commit/bd3675114c1c81c26c93bb5db18426112a95713c

@prsunny , can you take a look?

**Comment by stephenxs** [comment]
Hi @lguohan, @prsunny 
Thanks.
Some additional info:
The segment fault is because in 201811 nexthop of directly connected routing entries in the ROUTE_TABLE are "" while in 201911 "0.0.0.0" is expected.
After avoiding the coredump, there are further error logs during warm reboot
```
Apr  9 05:50:39.720373 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- postBake: Start MirrorOrch post-baking
Apr  9 05:50:39.746475 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: There are pending consumer tasks after restore:
Apr  9 05:50:39.746475 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: INTF_TABLE:PortChannel0001:10.0.0.56/31|SET|scope:global|family:IPv4
Apr  9 05:50:39.746475 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: INTF_TABLE:PortChannel0001:FC00::71/126|SET|scope:global|family:IPv6
Apr  9 05:50:39.746475 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: INTF_TABLE:PortChannel0002:10.0.0.58/31|SET|scope:global|family:IPv4
Apr  9 05:50:39.746475 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: INTF_TABLE:PortChannel0002:FC00::75/126|SET|scope:global|family:IPv6
Apr  9 05:50:39.746475 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: INTF_TABLE:PortChannel0003:10.0.0.60/31|SET|scope:global|family:IPv4
Apr  9 05:50:39.746537 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: INTF_TABLE:PortChannel0003:FC00::79/126|SET|scope:global|family:IPv6
Apr  9 05:50:39.746537 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: INTF_TABLE:PortChannel0004:10.0.0.62/31|SET|scope:global|family:IPv4
Apr  9 05:50:39.746666 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: INTF_TABLE:PortChannel0004:FC00::7D/126|SET|scope:global|family:IPv6
Apr  9 05:50:39.746666 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: INTF_TABLE:Vlan1000:192.168.0.1/21|SET|scope:global|family:IPv4
Apr  9 05:50:39.746681 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: INTF_TABLE:lo:10.1.0.32/32|SET|scope:global|family:IPv4
Apr  9 05:50:39.746769 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: INTF_TABLE:lo:FC00:1::32/128|SET|scope:global|family:IPv6
Apr  9 05:50:39.746769 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: NEIGH_TABLE:PortChannel0001:10.0.0.57|SET|neigh:52:54:00:dc:d5:c2|family:IPv4
Apr  9 05:50:39.746783 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: NEIGH_TABLE:PortChannel0001:fc00::72|SET|neigh:52:54:00:dc:d5:c2|family:IPv6
Apr  9 05:50:39.746783 mtbc-sonic-01-2410 NOTICE swss#orchagent: :- warmRestoreValidation: NEIGH_TABLE:PortChannel0002:10.0.0.59|SET|neigh:52:54:00:ee:76
```

**Comment by xinliu-seattle** [comment]
please bring this to the warm reboot bi-weekly subgroup meeting for investigation.

**Comment by prsunny** [comment]
Request @tylerlinp to take a look

**Comment by tylerlinp** [comment]
@prsunny Yes, Guohan is right, This is because of the schema change. The schema change is required in the VRF implementation.  The VRF implementation does not support the old format but during warmboot the old format is not converted to new format.

Warmboot from 201811 to 201911 may have other problems in other areas as well, not sure if in SONiC community we have to support this operation.

For VRF to support this, we have a proposal to support this, we will have a PR for review in a week or two.

**Comment by lguohan** [comment]
@tylerlinp , thanks for the analysis. warmboot form 201811 to 201911 is a hard requirement. can you do schema transform during the warmboot upgrade. @yxieca , maybe can you pointed out the place that @tylerlinp can inject such logic?
