### ISSUE TITLE
SONiC.HEAD.225-487a734c has the "ERR lldp" issue

### ISSUE THREAD

**Issue by Linda5067** [Azure/sonic-buildimage#4427]
**Description**

**Steps to reproduce the issue:**
1. Boot into SONiC
2. Execute "# show logging |grep ERR |grep lldp"
3. Then you can see lots of the lldp err messages.

**Describe the results you received:**
Execute the "show logging |grep ERR |grep lldp" command can see lots of the lldp err message.

**Describe the results you expected:**
No any LLDP error message.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    SONiC Software Version: SONiC.HEAD.225-487a734c
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: 487a734c
Build date: Mon Mar 16 06:53:45 UTC 2020
Built by: johnar@jenkins-worker-4

Platform: x86_64-accton_as7712_32x-r0
HwSKU: Accton-AS7712-32X
ASIC: broadcom
Traceback (most recent call last):
  File "/usr/bin/decode-syseeprom", line 175, in <module>
    exit(main())
  File "/usr/bin/decode-syseeprom", line 58, in main
    or t.getattr('read_eeprom_db', None) == None:
AttributeError: 'board' object has no attribute 'getattr'
Serial Number:
Uptime: 21:30:45 up 6 min,  1 user,  load average: 1.26, 1.13, 0.59

Docker images:
REPOSITORY                    TAG                 IMAGE ID            SIZE
docker-syncd-brcm             HEAD.225-487a734c   d2fee1ded54d        431MB
docker-syncd-brcm             latest              d2fee1ded54d        431MB
docker-router-advertiser      HEAD.225-487a734c   5f43a373efcc        283MB
docker-router-advertiser      latest              5f43a373efcc        283MB
docker-platform-monitor       HEAD.225-487a734c   a8adb2fbcf3f        335MB
docker-platform-monitor       latest              a8adb2fbcf3f        335MB
docker-lldp-sv2               HEAD.225-487a734c   0c126aa7c128        305MB
docker-lldp-sv2               latest              0c126aa7c128        305MB
docker-dhcp-relay             HEAD.225-487a734c   8b80562aedea        293MB
docker-dhcp-relay             latest              8b80562aedea        293MB
docker-database               HEAD.225-487a734c   679f54845811        283MB
docker-database               latest              679f54845811        283MB
docker-orchagent              HEAD.225-487a734c   791ebb190cd8        326MB
docker-orchagent              latest              791ebb190cd8        326MB
docker-sonic-telemetry        HEAD.225-487a734c   297d786bdc89        345MB
docker-sonic-telemetry        latest              297d786bdc89        345MB
docker-sonic-mgmt-framework   HEAD.225-487a734c   35e07237e125        421MB
docker-sonic-mgmt-framework   latest              35e07237e125        421MB
docker-fpm-frr                HEAD.225-487a734c   996376f2d695        328MB
docker-fpm-frr                latest              996376f2d695        328MB
docker-sflow                  HEAD.225-487a734c   97265fd2f5ca        308MB
docker-sflow                  latest              97265fd2f5ca        308MB
docker-snmp-sv2               HEAD.225-487a734c   7680db15e204        340MB
docker-snmp-sv2               latest              7680db15e204        340MB
docker-teamd                  HEAD.225-487a734c   ced744b583e1        308MB
docker-teamd                  latest              ced744b583e1        308MB
docker-nat                    HEAD.225-487a734c   692bad5efb38        309MB
docker-nat                    latest              692bad5efb38        309MB
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by xinliu-seattle** [comment]
need lldp failure info, please provide >show tech file.

**Comment by Linda5067** [comment]
Add the error information as below:

admin@AS7712-32X:~$ show logging |grep ERR |grep lldp
Nov  9 21:24:31.245623 AS7712-32X ERR monit[544]: 'lldpd_monitor' process is not running
Nov  9 21:24:31.256438 AS7712-32X ERR monit[544]: 'lldp_syncd' process is not running
Nov  9 21:24:31.267264 AS7712-32X ERR monit[544]: 'lldpmgrd' process is not running
Nov  9 21:25:05.674493 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet108' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.675432 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet64' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.680379 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet84' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.681344 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet60' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.682304 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet72' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.683198 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet68' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.684211 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet92' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.688399 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet44' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.689561 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet8' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.690696 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet80' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.691759 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet36' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.692895 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet104' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.693957 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet100' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.695057 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet96' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.696224 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet88' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.699806 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet20' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.700946 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet124' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.701972 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet24' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.703116 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet116' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.704234 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet52' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.705319 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet0' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.706398 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet120' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.707455 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet12' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.708596 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet48' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.715206 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet4' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.715296 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet28' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.715344 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet16' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.715395 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet32' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.715451 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet40' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.715541 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet76' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.716584 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet112' not found in PORT_TABLE table in App DB
Nov  9 21:25:05.717827 AS7712-32X ERR lldp#lldpmgrd: Port 'Ethernet56' not found in PORT_TABLE table in App DB
admin@AS7712-32X:~$
