### ISSUE TITLE
sonic-db-cli is broken on latest master

### ISSUE THREAD

**Issue by stepanblyschak** [Azure/sonic-buildimage#4632]
**Description**

```
admin@arc-switch1025:~$ sonic-db-cli CONFIG_DB KEYS \*
Traceback (most recent call last):
  File "/usr/local/bin/sonic-db-cli", line 131, in <module>
    main()
  File "/usr/local/bin/sonic-db-cli", line 114, in main
    execute_cmd(args.db_or_op, args.cmd, args.namespace, args.unixsocket)
  File "/usr/local/bin/sonic-db-cli", line 82, in execute_cmd
    print("\n".join(resp))
TypeError: sequence item 0: expected str instance, bytes found
admin@arc-switch1025:~$ sonic-db-cli CONFIG_DB HGET "PORT|Ethernet0" lanes
b'0,1,2,3'
admin@arc-switch1025:~$ 

```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
traceback when executing keys command. If executing hget command the output is with prefix b'' which most SONiC scripts won't expect.

**Describe the results you expected:**
keys command works without traceback. If executing get/hget the output is a pure string, without prefix b''.

**Additional information you deem important (e.g. issue happens only occasionally):**

This probably happened because sonic-db-cli is now using python3 from buster. python3 changed strings from bytes to unicode. Probably that is the issue.

    **Output of `show version`:**

```
admin@arc-switch1025:~$ show ver

SONiC Software Version: SONiC.master.288-eb97dccb
Distribution: Debian 10.4
Kernel: 4.19.0-6-amd64
Build commit: eb97dccb
Build date: Thu May 21 10:53:08 UTC 2020
Built by: johnar@jenkins-worker-7

Platform: x86_64-mlnx_msn2700-r0
HwSKU: ACS-MSN2700
ASIC: mellanox
Serial Number: MT1822K07815
Uptime: 14:14:02 up 6 min,  1 user,  load average: 1.92, 1.59, 0.86

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-sonic-telemetry        latest                0c75d59e297f        409MB
docker-sonic-telemetry        master.288-eb97dccb   0c75d59e297f        409MB
docker-sonic-mgmt-framework   latest                ea3063debff4        485MB
docker-sonic-mgmt-framework   master.288-eb97dccb   ea3063debff4        485MB
docker-lldp-sv2               latest                7f703951f470        372MB
docker-lldp-sv2               master.288-eb97dccb   7f703951f470        372MB
docker-snmp-sv2               latest                b3af3fcbf8ee        385MB
docker-snmp-sv2               master.288-eb97dccb   b3af3fcbf8ee        385MB
docker-teamd                  latest                a2ebfe1598ac        311MB
docker-teamd                  master.288-eb97dccb   a2ebfe1598ac        311MB
docker-syncd-mlnx             latest                c70f8a7dda24        391MB
docker-syncd-mlnx             master.288-eb97dccb   c70f8a7dda24        391MB
docker-sflow                  latest                b0bc65f1c186        312MB
docker-sflow                  master.288-eb97dccb   b0bc65f1c186        312MB
docker-router-advertiser      latest                e73dd993d374        290MB
docker-router-advertiser      master.288-eb97dccb   e73dd993d374        290MB
docker-platform-monitor       latest                7dcab5a2cee6        428MB
docker-platform-monitor       master.288-eb97dccb   7dcab5a2cee6        428MB
docker-orchagent              latest                c2c825be7333        329MB
docker-orchagent              master.288-eb97dccb   c2c825be7333        329MB
docker-nat                    latest                4e4197f4d9b1        312MB
docker-nat                    master.288-eb97dccb   4e4197f4d9b1        312MB
docker-fpm-frr                latest                79457df5d33d        331MB
docker-fpm-frr                master.288-eb97dccb   79457df5d33d        331MB
docker-dhcp-relay             latest                0ec993f7a629        300MB
docker-dhcp-relay             master.288-eb97dccb   0ec993f7a629        300MB
docker-database               latest                2e29b48e9e68        290MB
docker-database               master.288-eb97dccb   2e29b48e9e68        290MB
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by dzhangalibaba** [comment]
there is a fix PR , https://github.com/Azure/sonic-py-swsssdk/pull/71
