### ISSUE TITLE
iptables blocking access to /32 Loopback address

### ISSUE THREAD

**Issue by scottlaird** [Azure/sonic-buildimage#4797]
**Description**

The default iptables rules on SONiC block access to the .0 address of each interface netblock.  When Loopback is configured with a /32, this produces a rule that blocks all incoming traffic to loopback *except* for BGP and DHCP.  This is likely also an issue with /31 links, but not with /30 or larger.

**Steps to reproduce the issue:**
1.  Set loopback to a /32.  Example:
```
    "LOOPBACK_INTERFACE": {
        "Loopback0": {}, 
        "Loopback0|10.0.0.4/32": {}, 
        "Loopback0|2001:470:e959::3/128": {}
    }, 
```
2. Attempt to ssh, snmpwalk, etc the loopback interface and fail.
3. Run iptables -L -v -n and see this:
```
# iptables -L -v -n
Chain INPUT (policy ACCEPT 3199 packets, 357K bytes)
 pkts bytes target     prot opt in     out     source               destination         
  12M 1345M ACCEPT     all  --  lo     *       127.0.0.1            0.0.0.0/0           
57309   18M ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 372K 2757M ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8
  408 34272 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 0
  104  9620 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 3
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 11
14284 6250K ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp spts:67:68 dpts:67:68
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp spts:546:547 dpts:546:547
  768 46740 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:179
   42  1680 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp spt:179
10504  701K DROP       all  --  *      *       0.0.0.0/0            10.0.0.4            
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.8           
... 
```

**Describe the results you received:**

All traffic to loopback is blocked (except things that are explicitly allowed, above).

**Describe the results you expected:**

I expected to be able to send traffic to the loopback, or to be able to configure this at a minimum.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `show version`:**

```
# show version

SONiC Software Version: SONiC.master.310-a748daea
Distribution: Debian 10.4
Kernel: 4.19.0-6-amd64
Build commit: a748daea
Build date: Sat Jun 13 10:12:11 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-accton_as7326_56x-r0
HwSKU: Accton-AS7326-56X
ASIC: broadcom
Serial Number: 732656X1846013
Uptime: 00:37:17 up 23:08,  2 users,  load average: 1.38, 1.35, 1.35

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-sonic-mgmt-framework   latest                765d650f105f        486MB
docker-sonic-mgmt-framework   master.310-a748daea   765d650f105f        486MB
docker-router-advertiser      latest                105dc9e73b44        347MB
docker-router-advertiser      master.310-a748daea   105dc9e73b44        347MB
docker-lldp                   latest                2f2479c7d482        373MB
docker-lldp                   master.310-a748daea   2f2479c7d482        373MB
docker-database               latest                b3f02e02d003        346MB
docker-database               master.310-a748daea   b3f02e02d003        346MB
docker-sonic-telemetry        latest                b46261f07321        410MB
docker-sonic-telemetry        master.310-a748daea   b46261f07321        410MB
docker-snmp                   latest                db45e7531ce5        385MB
docker-snmp                   master.310-a748daea   db45e7531ce5        385MB
docker-teamd                  latest                1813cd84ad3b        312MB
docker-teamd                  master.310-a748daea   1813cd84ad3b        312MB
docker-syncd-brcm             latest                5eeca25b3391        439MB
docker-syncd-brcm             master.310-a748daea   5eeca25b3391        439MB
docker-sflow                  latest                9c0663ae35f8        313MB
docker-sflow                  master.310-a748daea   9c0663ae35f8        313MB
docker-platform-monitor       latest                fc4796e4c396        355MB
docker-platform-monitor       master.310-a748daea   fc4796e4c396        355MB
docker-orchagent              latest                98564ff3a891        331MB
docker-orchagent              master.310-a748daea   98564ff3a891        331MB
docker-nat                    latest                16b62a26b3ae        314MB
docker-nat                    master.310-a748daea   16b62a26b3ae        314MB
docker-fpm-frr                latest                d217cb04b291        332MB
docker-fpm-frr                master.310-a748daea   d217cb04b291        332MB
docker-dhcp-relay             latest                1f173bac0239        301MB
docker-dhcp-relay             master.310-a748daea   1f173bac0239        301MB
```

**Attach debug file `sudo generate_dump`:**

It fails to complete but seems to generate output in `/var/dump`.

[sonic_dump_sw25_20200618_003852.tar.gz](https://github.com/Azure/sonic-buildimage/files/4795684/sonic_dump_sw25_20200618_003852.tar.gz)

**Comment by lguohan** [comment]
@jleveque , is this intended?

**Comment by jleveque** [comment]
@scottlaird: Have you configured any control plane ACL rules on the device? We are now blocking all "IP-2-me" traffic by default on our loopback and P2P interfaces. Services like SSH and SNMP are expected to be allowed from sources as needed by adding control plane ACL rules for those services. Currently, BGP and DHCP are allowed by default, but eventually those protocols may become configurable by control plane ACLs, as well.

**Comment by scottlaird** [comment]
I haven't configured any control plane ACLs yet.  Is there documentation or a sample config somewhere?

Oddly, the iptables rules for this for my other interfaces (/30s) don't actually block anything useful, as they're all blocking the network address (.0) not the local address.  Maybe this works correctly with /31s?

Example:

```
$ sudo iptables -L -v -n
...
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.252          
...
$ ip addr show dev Ethernet76
70: Ethernet76: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:6a:97:8a:71:68 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.253/30 brd 10.0.1.255 scope global Ethernet76
       valid_lft forever preferred_lft forever
    inet6 fe80::ba6a:97ff:fe8a:7168/64 scope link 
       valid_lft forever preferred_lft forever
```

The local address on the /30 is 10.0.1.253, but the iptables rule blocks 10.0.1.252.

**Comment by jleveque** [comment]
> Oddly, the iptables rules for this for my other interfaces (/30s) don't actually block anything useful, as they're all blocking the network address (.0) not the local address. Maybe this works correctly with /31s?

This is odd. We'll need to look into this further. Feel free to take a look if you have the time and interest.

I'm not sure how complete our documentation is for configuring ACLs, but basically you need to define the ACL tables in your config_db.json file and load it, then create a JSON file (we'll call it /etc/sonic/acl.json) which will contain your ACL rules, with content similar to the following (this file contains two SSH, two SNMP and two NTP ACL rules). Note that the keys ("SNMP_ACL", etc.) must match the name of an ACL table in your config_db.json file. Then simply run `sudo acl-loader update full /etc/sonic/acl.json` to load and apply the ACL rules:

```
{
    "acl": {
        "acl-sets": {
            "acl-set": {
                "SNMP_ACL": {
                    "acl-entries": {
                        "acl-entry": {
                            "1": {
                                "config": {
                                    "sequence-id": 1
                                },
                                "actions": {
                                    "config": {
                                        "forwarding-action": "ACCEPT"
                                    }
                                },
                                "ip": {
                                    "config": {
                                        "protocol": "IP_UDP",
                                        "source-ip-address": "10.0.0.1/24"
                                    }
                                }
                            },
                            "2": {
                                "config": {
                                    "sequence-id": 2
                                },
                                "actions": {
                                    "config": {
                                        "forwarding-action": "ACCEPT"
                                    }
                                },
                                "ip": {
                                    "config": {
                                        "protocol": "IP_UDP",
                                        "source-ip-address": "192.168.1.100/32"
                                    }
                                }
                            }
                        }
                    },
                    "config": {
                        "name": "SNMP_ACL"
                    }
                },
                "SSH_ACL": {
                    "acl-entries": {
                        "acl-entry": {
                            "1": {
                                "config": {
                                    "sequence-id": 1
                                },
                                "actions": {
                                    "config": {
                                        "forwarding-action": "ACCEPT"
                                    }
                                },
                                "ip": {
                                    "config": {
                                        "protocol": "IP_TCP",
                                        "source-ip-address": "10.0.0.1/24"
                                    }
                                }
                            },
                            "2": {
                                "config": {
                                    "sequence-id": 2
                                },
                                "actions": {
                                    "config": {
                                        "forwarding-action": "ACCEPT"
                                    }
                                },
                                "ip": {
                                    "config": {
                                        "protocol": "IP_TCP",
                                        "source-ip-address": "192.168.1.100/32"
                                    }
                                }
                            }
                        }
                    },
                    "config": {
                        "name": "SSH_ACL"
                    }
                },
                "NTP_ACL": {
                    "acl-entries": {
                        "acl-entry": {
                            "1": {
                                "config": {
                                    "sequence-id": 1
                                },
                                "actions": {
                                    "config": {
                                        "forwarding-action": "ACCEPT"
                                    }
                                },
                                "ip": {
                                    "config": {
                                        "protocol": "IP_TCP",
                                        "source-ip-address": "10.0.0.1/24"
                                    }
                                }
                            },
                            "2": {
                                "config": {
                                    "sequence-id": 2
                                },
                                "actions": {
                                    "config": {
                                        "forwarding-action": "ACCEPT"
                                    }
                                },
                                "ip": {
                                    "config": {
                                        "protocol": "IP_TCP",
                                        "source-ip-address": "192.168.1.100/32"
                                    }
                                }
                            }
                        }
                    },
                    "config": {
                        "name": "NTP_ACL"
                    }
                }
            }
        }
    }
}

```

**Comment by scottlaird** [comment]
Okay, I went through and created SNMP_ACL and SSH_ACL via 'sudo config acl add table <name> L3'.  Then I lightly modified the ACL config above and ran acl-loader update full.

Running 'acl-loader show table' shows the new new ACL tables.  Running 'acl-loader show rule' shows the rules from the file.

I still can't SSH into the switch via the loopback /32, and can't scrape SNMP.  It doesn't look like iptables changed at all, other than random counter increases.  Manually dropping the iptables entry for the loopback /32 fixes things, but it'll obviously re-break at the next reboot, if not sooner.

**Comment by jleveque** [comment]
`L3` is not the appropriate ACL table type for control plane ACLs. it should be `CTRLPLANE`. The control plane ACL manager will only process rules in tables of type `CTRLPLANE`. `L3` is for data plane ACLs.

**Comment by scottlaird** [comment]
That was an entertaining process.  It doesn't look like `config acl add <name> CTRLPLANE` actually works right.  The generated ACL entries are missing a `services` field, and this crashes a lot of code.  This took a while to work through.

I deleted the old tables and created new ones with the same name and type CTRLPLANE using 'config acl add'.  Then I tried loading them, but something was clearly wrong:

```
# acl-loader update full /etc/sonic/acl.json
# acl-loader  show table
Traceback (most recent call last):
  File "/usr/bin/acl-loader", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/acl_loader/main.py", line 856, in table
    acl_loader.show_table(table_name)
  File "/usr/lib/python2.7/dist-packages/acl_loader/main.py", line 696, in show_table
    services = natsorted(val["services"])KeyError: 'services'
```

At this point, I rebooted, just to clear out old state and make debugging slightly easier.  It didn't improve anything.  I manually added a 'services' block to each table in `/etc/sonic/config_db.json`:

```
    "ACL_TABLE": {
        "SNMP_ACL": {
            "policy_desc": "SNMP_ACL",
             "ports": [
                "Ethernet35",
                 ...
                "Ethernet26"
            ],
             "services": [
                "SNMP"
            ],
             "stage": "ingress",
             "type": "CTRLPLANE"
        }, 
```

Then I re-ran the ACL loader; now I can see tables and rules:

```
# acl-loader  show table
Name      Type       Binding    Description    Stage
--------  ---------  ---------  -------------  -------
SSH_ACL   CTRLPLANE  SSH        SSH_ACL        ingress
SNMP_ACL  CTRLPLANE  SNMP       SNMP_ACL       ingress
# acl-loader  show rule
Table     Rule          Priority    Action    Match
--------  ------------  ----------  --------  ------------------
SNMP_ACL  RULE_1        9999        ACCEPT    IP_PROTOCOL: 17
                                              SRC_IP: 10.0.0.0/8
SSH_ACL   RULE_1        9999        ACCEPT    IP_PROTOCOL: 6
                                              SRC_IP: 10.0.0.0/8
SSH_ACL   DEFAULT_RULE  1           DROP      ETHER_TYPE: 2048
SNMP_ACL  DEFAULT_RULE  1           DROP      ETHER_TYPE: 2048
```

So that's better.  But now I'm completely missing iptables entries:

```
# iptables -L -v -n
Chain INPUT (policy ACCEPT 986K packets, 118M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 985K packets, 123M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
# Warning: iptables-legacy tables present, use iptables-legacy to see them
```

This is after a `config reload`.  A bit of log grepping suggests that caclmgrd crashed (silently) while the services blocks were missing.  Restarting it manually seems to fix everything:

```
# iptables -L -v -n
Chain INPUT (policy ACCEPT 1035K packets, 124M bytes)
 pkts bytes target     prot opt in     out     source               destination         
 1187  145K ACCEPT     all  --  lo     *       127.0.0.1            0.0.0.0/0           
   52  3515 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    3   444 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 0
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 3
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 11
    5  2123 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp spts:67:68 dpts:67:68
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp spts:546:547 dpts:546:547
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:179
    2   142 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp spt:179
    1    88 ACCEPT     tcp  --  *      *       10.0.0.0/8           0.0.0.0/0            tcp dpt:22
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
    0     0 ACCEPT     tcp  --  *      *       10.0.0.0/8           0.0.0.0/0            tcp dpt:161
    0     0 ACCEPT     udp  --  *      *       10.0.0.0/8           0.0.0.0/0            udp dpt:161
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:161
    0     0 DROP       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:161
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.0.4            
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.8            
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.20           
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.44           
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.28           
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.16           
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.244          
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.56           
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.0            
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.248          
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.24           
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.4            
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.32           
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.252          
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.36           
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.40           
    0     0 DROP       all  --  *      *       0.0.0.0/0            10.0.1.12           
   22  1520 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            TTL match TTL < 2
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 1035K packets, 129M bytes)
 pkts bytes target     prot opt in     out     source               destination         
```

It looks like `caclmgrd` needs better error handling, and probably something restarting it when it dies.  Also, the missing 'services' field isn't exactly a great UX.  I'll file issues for them in a bit, and may look at fixing one or both when I have a bit more time.  Thanks for the help.

**Comment by jleveque** [comment]
Glad to know you finally got it working. Sorry about all the hurdles. I believe you're correct that `config acl add` does not support the current "service ACL" model of control plane ACLs because it does not understand the concept of a "service". Please do open issues for these, and if you do find the time to make some fixes, it would be appreciated!

**Comment by xinliu-seattle** [comment]
@scottlaird please close this and open a new issue on config acl add does not support the current "service ACL" model of control plane ACLs because it does not understand the concept of a "service".
