### ISSUE TITLE
portstat fails

### ISSUE THREAD

**Issue by marian-pritsak** [Azure/sonic-buildimage#482]
```
# portstat 
Traceback (most recent call last):
  File "/usr/bin/portstat", line 320, in <module>
    main()
  File "/usr/bin/portstat", line 273, in main
    cnstat_dict = portstat.get_cnstat()
  File "/usr/bin/portstat", line 77, in get_cnstat
    cnstat_dict[port] = get_counters(counter_port_name_map[port])
  File "/usr/bin/portstat", line 67, in get_counters
    fields[pos] += int(self.db.get(self.db.COUNTERS_DB, full_table_id, counter_name))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

Reproduced on Mellanox platform.
Can anyone try it on another to help locate the problem?

**Comment by NStetskovych** [comment]
AS7512:
```
admin@sonic:~$ sudo portstat
Traceback (most recent call last):
  File "/usr/bin/portstat", line 320, in <module>
    main()
  File "/usr/bin/portstat", line 273, in main
    cnstat_dict = portstat.get_cnstat()
  File "/usr/bin/portstat", line 77, in get_cnstat
    cnstat_dict[port] = get_counters(counter_port_name_map[port])
  File "/usr/bin/portstat", line 67, in get_counters
    fields[pos] += int(self.db.get(self.db.COUNTERS_DB, full_table_id, counter_name))
TypeError: int() argument must be a string or a number, not 'NoneType'

```

**Comment by sihuihan88** [comment]
The reason is that there is no SAI_PORT_STAT_ETHER_RX_OVERSIZE_PKTS/ SAI_PORT_STAT_ETHER_TX_OVERSIZE_PKTS counter info in the database which are used to calculate RX_OVR and TX_OVR. Can you check the why there is no such info in the system? 
At the same time, I will set the stat to NA if no counter exists.

**Comment by sihuihan88** [comment]
https://github.com/Azure/sonic-utilities/pull/29 resolves this issue

**Comment by stcheng** [comment]
@marian-pritsak please verify

**Comment by marian-pritsak** [comment]
Works, thanks
