### ISSUE TITLE
[201811] sonic Image broken recently

### ISSUE THREAD

**Issue by zhenggen-xu** [Azure/sonic-buildimage#4848]
**Description**

**Steps to reproduce the issue:**
1. Download and install:  https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-201811/298/artifact/target/sonic-broadcom.bin

2.  sudo sonic-cfggen -H -k Seastone-DX010-50 --preset=t1 > config.json.t1
     sudo config reload config.json.t1 -y

3, docker not started correctly

**Describe the results you received:**
```
admin@lnos-x1-a-csw03:~$ bcmcmd ps
connecting stream socket: No such file or directory
```

```
Jun 25 06:18:46.020284 lnos-x1-a-csw03 INFO swss#supervisord: start.sh Traceback (most recent call last):
Jun 25 06:18:46.020507 lnos-x1-a-csw03 INFO swss#supervisord: start.sh   File "/usr/local/bin/sonic-cfggen", line 24, in <module>
Jun 25 06:18:46.020608 lnos-x1-a-csw03 INFO swss#supervisord: start.sh     import netaddr
Jun 25 06:18:46.020690 lnos-x1-a-csw03 INFO swss#supervisord: start.sh   File "/usr/local/lib/python2.7/dist-packages/netaddr/__init__.py", line 18, in <module>
Jun 25 06:18:46.020773 lnos-x1-a-csw03 INFO swss#supervisord: start.sh     from netaddr.core import (AddrConversionError, AddrFormatError,
Jun 25 06:18:46.020854 lnos-x1-a-csw03 INFO swss#supervisord: start.sh   File "/usr/local/lib/python2.7/dist-packages/netaddr/core.py", line 11, in <module>
Jun 25 06:18:46.020934 lnos-x1-a-csw03 INFO swss#supervisord: start.sh     from netaddr.compat import _callable, _iter_dict_keys
Jun 25 06:18:46.021014 lnos-x1-a-csw03 INFO swss#supervisord: start.sh   File "/usr/local/lib/python2.7/dist-packages/netaddr/compat.py", line 119, in <module>
Jun 25 06:18:46.021123 lnos-x1-a-csw03 INFO swss#supervisord: start.sh     import importlib_resources as _importlib_resources
Jun 25 06:18:46.021208 lnos-x1-a-csw03 INFO swss#supervisord: start.sh   File "/usr/local/lib/python2.7/dist-packages/importlib_resources/__init__.py", line 5, in <module>
Jun 25 06:18:46.021288 lnos-x1-a-csw03 INFO swss#supervisord: start.sh     from ._compat import metadata
Jun 25 06:18:46.021369 lnos-x1-a-csw03 INFO swss#supervisord: start.sh   File "/usr/local/lib/python2.7/dist-packages/importlib_resources/_compat.py", line 9, in <module>
Jun 25 06:18:46.021448 lnos-x1-a-csw03 INFO swss#supervisord: start.sh     from pathlib2 import Path, PurePath                         # type: ignore
Jun 25 06:18:46.021528 lnos-x1-a-csw03 INFO swss#supervisord: start.sh   File "/usr/local/lib/python2.7/dist-packages/pathlib2/__init__.py", line 13, in <module>
Jun 25 06:18:46.021610 lnos-x1-a-csw03 INFO swss#supervisord: start.sh     import six
Jun 25 06:18:46.021692 lnos-x1-a-csw03 INFO swss#supervisord: start.sh ImportError: No module named six

```
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
admin@lnos-x1-a-csw03:~$ show version 

SONiC Software Version: SONiC.HEAD.298-6fc6220
Distribution: Debian 9.12
Kernel: 4.9.0-9-amd64
Build commit: 6fc6220
Build date: Wed Jun 24 21:52:53 UTC 2020
Built by: johnar@jenkins-worker-11

Platform: x86_64-cel_seastone-r0
HwSKU: Seastone-DX010-50
ASIC: broadcom
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
resolved in https://github.com/Azure/sonic-buildimage/commit/d04ad415b4926f6eebf4f3d656931484450bc704
