### ISSUE TITLE
"sonic-installer install " command not working in sonic mainline

### ISSUE THREAD

**Issue by BaluAlluru** [Azure/sonic-buildimage#4992]
**Steps to reproduce the issue:**
1. load sonic Jenkins image 350 on the box.
2. execute the command "sonic-installer install "
3. Observe Error "NameError: name 'cli' is not defined" 

**Describe the results you received:**
root@sonic:/home/admin# sonic-installer install /home/admin/sonic-broadcom.bin
Traceback (most recent call last):
  File "/usr/bin/sonic-installer", line 8, in <module>
    from sonic_installer.main import sonic_installer
  File "/usr/lib/python2.7/dist-packages/sonic_installer/main.py", line 610, in <module>
    @cli.command('verify-next-image')
NameError: name 'cli' is not defined

**Describe the results you expected:**
root@sonic:/home/admin# sudo sonic_installer install /home/admin/sonic-broadcom.bin
New image will be installed, continue? [y/N]: y
Installing image SONiC-OS-master.0-adad5499 and setting it as default...
Command: bash /home/admin/sonic-broadcom.bin
Verifying image checksum ... OK.
Preparing image archive ... OK.
Installing SONiC in SONiC
....

**Additional information you deem important (e.g. issue happens only occasionally):**

root@sonic:/home/admin# show version

SONiC Software Version: SONiC.master.350-1ca47da4
Distribution: Debian 10.4
Kernel: 4.19.0-9-2-amd64
Build commit: 1ca47da4
Build date: Thu Jul 16 20:16:33 UTC 2020
Built by: johnar@jenkins-worker-11

    

    **Attach debug file `sudo generate_dump`:**

   
[sonic_dump_sonic_20200717_223808.tar.gz](https://github.com/Azure/sonic-buildimage/files/4938467/sonic_dump_sonic_20200717_223808.tar.gz)

**Comment by rlhui** [comment]
@jleveque - Hi Joe, could this be related to a recent change   https://github.com/Azure/sonic-utilities/pull/983? Thanks.

**Comment by jleveque** [comment]
@rlhui: Yes. The root group name was changed from `cli` to `sonic_installer` inhttps://github.com/Azure/sonic-utilities/pull/983. However, `verify-next-image` subcommand was being added in an already-open PR https://github.com/Azure/sonic-utilities/pull/979/ at the time. It did not get updated before merge. I have opened a PR to align this command here: https://github.com/Azure/sonic-utilities/pull/995
