### ISSUE TITLE
Warm and fast reboot process throws error - "RuntimeError: Eeprom is not Programmed"

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#5118]
**Description**

**Steps to reproduce the issue**
1. Installed latest master broadcom image from public repo. At the time of issue, the image used was - https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/373/artifact/target/sonic-broadcom.bin
2. Issue warm/fast reboot on the device.
3. The error will be thrown before the device actually performs reboot (warm/fast).

**Describe the results you received**
```
$ sudo warm-reboot 
Warning: 'sonic_installer' command is deprecated and will be removed in the future
Please use 'sonic-installer' instead
Warning: Stopping telemetry.service, but it can still be activated by:
  telemetry.timer
Traceback (most recent call last):
  File "/usr/bin/watchdogutil", line 12, in <module>
    sys.exit(watchdogutil())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/watchdogutil/main.py", line 92, in watchdogutil
    err = load_platform_watchdog()
  File "/usr/lib/python2.7/dist-packages/watchdogutil/main.py", line 64, in load_platform_watchdog
    platform = sonic_platform.platform.Platform()
  File "/usr/local/lib/python2.7/dist-packages/sonic_platform/platform.py", line 25, in __init__
    self._chassis = Chassis()
  File "/usr/local/lib/python2.7/dist-packages/sonic_platform/chassis.py", line 62, in __init__
    self._eeprom = Eeprom()
  File "/usr/local/lib/python2.7/dist-packages/sonic_platform/eeprom.py", line 42, in __init__
    raise RuntimeError("Eeprom is not Programmed")
RuntimeError: Eeprom is not Programmed
```

**Describe the results you expected**
No errors should be seen during reboot.

**Additional information you deem important (e.g. issue happens only occasionally)**

**Output of `show version`**

```
SONiC Software Version: SONiC.master.373-0a409ff6
Distribution: Debian 10.5
Kernel: 4.19.0-9-2-amd64
Build commit: 0a409ff6
Build date: Wed Aug  5 16:30:59 UTC 2020
Built by: johnar@jenkins-worker-11
```

**Comment by sujinmkang** [comment]
fix : https://github.com/Azure/sonic-utilities/pull/1037
