### ISSUE TITLE
Failed to run show platform firmware status on Arista7260

### ISSUE THREAD

**Issue by bingwang-ms** [Azure/sonic-buildimage#5134]
**Description**
Command **show platform firmware status** ran failed on Arista 7260.

**Steps to reproduce the issue:**
1. Just issue **show platform firmware status** and then the error will show.

**Describe the results you received:**
```
admin@str-7260cx3-acs-1:~$ sudo show platform firmware status
Traceback (most recent call last):
  File "/usr/bin/fwutil", line 8, in <module>
    from fwutil.main import cli
  File "/usr/lib/python2.7/dist-packages/fwutil/__init__.py", line 5, in <module>
    raise ImportError("Required module not found: {}".format(str(e)))
ImportError: Required module not found: No module named platform
```

**Describe the results you expected:**
 The firmware info is expected.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
```
   SONiC Software Version: SONiC.20191130.43
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: 0720b9140
Build date: Mon Aug  3 03:13:48 UTC 2020
Built by: sonicbld@jenkins-slave-phx-2

Platform: x86_64-arista_7260cx3_64
HwSKU: Arista-7260CX3-D108C8
ASIC: broadcom
Serial Number: SSJ17444852
Uptime: 02:56:12 up  1:48,  1 user,  load average: 2.57, 2.72, 2.56

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-snmp-sv2            20191130.43         b22f76eed3c2        348MB
docker-snmp-sv2            latest              b22f76eed3c2        348MB
docker-fpm-frr             20191130.43         906a6e3eb10c        335MB
docker-fpm-frr             latest              906a6e3eb10c        335MB
docker-acms                20191130.43         b70a6cf16e4c        181MB
docker-acms                latest              b70a6cf16e4c        181MB
docker-lldp-sv2            20191130.43         4b86fd938afe        312MB
docker-lldp-sv2            latest              4b86fd938afe        312MB
docker-orchagent           20191130.43         47edc03313c6        331MB
docker-orchagent           latest              47edc03313c6        331MB
docker-teamd               20191130.43         3e88085fda7d        313MB
docker-teamd               latest              3e88085fda7d        313MB
docker-syncd-brcm          20191130.43         d745e1c7a6fa        436MB
docker-syncd-brcm          latest              d745e1c7a6fa        436MB
docker-platform-monitor    20191130.43         4985ff548d24        356MB
docker-platform-monitor    latest              4985ff548d24        356MB
docker-database            20191130.43         04c894407aef        289MB
docker-database            latest              04c894407aef        289MB
docker-dhcp-relay          20191130.43         391c169370ef        299MB
docker-dhcp-relay          latest              391c169370ef        299MB
docker-router-advertiser   20191130.43         f37bfdfb4e44        289MB
docker-router-advertiser   latest              f37bfdfb4e44        289MB
k8s.gcr.io/kube-proxy      v1.18.6             c3d62d6fe412        117MB
quay.io/coreos/flannel     v0.12.0-amd64       4e9f801d2217        52.8MB
k8s.gcr.io/pause           3.2                 80d28bedfe5d        683kB
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by Staphylo** [comment]
I believe we can close this issue. It was fixed by https://github.com/aristanetworks/sonic/commit/dc31c69bfbbe9ee3315431b9b78fd0b550834116
I tested with the latest 201911 image and all the `show platform firmware` CLI seem to work.
It is expected for these CLIs to have an empty output for now as we do not yet implement the ComponentBase API.

```
root@sonic:/home/admin# show platform firmware status
Chassis    Module    Component    Version    Description
---------  --------  -----------  ---------  -------------

root@sonic:/home/admin# show platform firmware updates
Error: [Errno 2] No such file or directory: '/usr/share/sonic/device/x86_64-arista_7260cx3_64/platform_components.json'. Aborting...
Aborted!

root@sonic:/home/admin# show platform firmware version
fwutil version 2.0.0.0

root@gd231:/home/admin# show version

SONiC Software Version: SONiC.201911.189-a754e4b1
Distribution: Debian 9.13
Kernel: 4.9.0-14-2-amd64
Build commit: a754e4b1
Build date: Sat Apr 24 04:19:36 UTC 2021
Built by: johnar@jenkins-worker-1

Platform: x86_64-arista_7260cx3_64
HwSKU: Arista-7260CX3-D108C8
ASIC: broadcom
```

**Comment by bingwang-ms** [comment]
Thanks @Staphylo .
