### ISSUE TITLE
ERR syslog about snmp-subagent [ax_interface] "self.vlanmac_ifindex_map[vlanmac] = mibs.get_index_from_str(self.if_id_map[port_id])#012KeyError: b'20000000009b6']"

### ISSUE THREAD

**Issue by tim-rj** [Azure/sonic-buildimage#5345]
**Description**

ERR syslog about snmp-subagent [ax_interface] "self.vlanmac_ifindex_map[vlanmac] = mibs.get_index_from_str(self.if_id_map[port_id])#012KeyError: b'20000000009b6']"

**Steps to reproduce the issue:**
1. Upgrade the device to master,Check syslog, whether there is abnormal log

**Describe the results you received:**
 

```
Sep  9 14:04:09.946377 sonic ERR snmp#snmp-subagent message repeated 14 times: [ [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.7/dist-packages/ax_interface/mib.py", line 43, in start#012    self.update_data()#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/ietf/rfc4363.py", line 75, in update_data#012    self.vlanmac_ifindex_map[vlanmac] = mibs.get_index_from_str(self.if_id_map[port_id])#012KeyError: b'20000000009b6']
Sep  9 14:04:09.946377 sonic WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: Invalid mgmt IP 12.1.1.2,12::2
Sep  9 14:04:09.946377 sonic WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: Invalid management IP 12.1.1.2,12::2
Sep  9 14:04:12.065035 sonic ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.7/dist-packages/ax_interface/mib.py", line 43, in start#012    self.update_data()#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/ietf/rfc4363.py", line 75, in update_data#012    self.vlanmac_ifindex_map[vlanmac] = mibs.get_index_from_str(self.if_id_map[port_id])#012KeyError: b'20000000009b6'
root@sonic:/home/admin# ^C
root@sonic:/home/admin# show ip interfaces 
Interface    Master           IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
-----------  ---------------  -------------------  ------------  --------------  -------------
Ethernet49                    10.0.0.96/31         up/up         ARISTA21T0      10.0.0.97
Ethernet51   PortChannel0001  10.0.0.100/31        up/up         ARISTA23T0      10.0.0.101
Loopback0                     10.1.0.1/32          up/up         N/A             N/A
Vlan2                         12.1.1.1/16          up/up         N/A             N/A
docker0                       240.127.1.1/24       up/down       N/A             N/A
lo                            127.0.0.1/8          up/up         N/A             N/A
root@sonic:/home/admin# show ipv6 interfaces 
Interface        Master           IPv6 address/mask                             Admin/Oper    BGP Neighbor    Neighbor IP
---------------  ---------------  --------------------------------------------  ------------  --------------  -------------
Bridge                            fe80::c0cc:94ff:fe9f:56bd%Bridge/64           up/up         N/A             N/A
Ethernet49                        10::96/64                                     up/up         ARISTA21T0      10::97
                                  fe80::5a69:6cff:fefb:2122%Ethernet49/64       up/up         N/A             N/A
Ethernet51       PortChannel0001  fe80::5a69:6cff:fefb:2122%Ethernet51/64       up/up         N/A             N/A
Loopback0                         10::1/128                                     up/up         N/A             N/A
                                  fe80::38bf:46ff:fef5:8458%Loopback0/64        up/up         N/A             N/A
PortChannel0001  Bridge           fe80::5a69:6cff:fefb:2122%PortChannel0001/64  up/up         N/A             N/A
Vlan2                             12::1/64                                      up/up         N/A             N/A
                                  fe80::5a69:6cff:fefb:2122%Vlan2/64            up/up         N/A             N/A
eth0                              fe80::5a69:6cff:fefb:2122%eth0/64             up/up         N/A             N/A
lo                                ::1/128                                       up/up         N/A             N/A

```

**Describe the results you expected:**
no print err log

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
root@sonic:/home/admin# show version 

SONiC Software Version: SONiC.master.399-07b9d7f4
Distribution: Debian 10.5
Kernel: 4.19.0-9-2-amd64
Build commit: 07b9d7f4
Build date: Sun Aug 30 07:41:30 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-ruijie_b6510-48vs8cq-r0
HwSKU: B6510-48VS8CQ
ASIC: broadcom
Serial Number: G1W10072
Uptime: 17:26:38 up  2:51,  1 user,  load average: 0.46, 0.37, 0.29

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-teamd                  latest                0da13af040db        386MB
docker-teamd                  master.399-07b9d7f4   0da13af040db        386MB
docker-sonic-mgmt-framework   latest                b3309c50c848        481MB
docker-sonic-mgmt-framework   master.399-07b9d7f4   b3309c50c848        481MB
docker-router-advertiser      latest                81563660196e        355MB
docker-router-advertiser      master.399-07b9d7f4   81563660196e        355MB
docker-platform-monitor       latest                bfc946290aa4        429MB
docker-platform-monitor       master.399-07b9d7f4   bfc946290aa4        429MB
docker-lldp                   latest                17607fd34cc8        383MB
docker-lldp                   master.399-07b9d7f4   17607fd34cc8        383MB
docker-dhcp-relay             latest                57d5a7e2d58d        362MB
docker-dhcp-relay             master.399-07b9d7f4   57d5a7e2d58d        362MB
docker-database               latest                ddb145fe6d62        355MB
docker-database               master.399-07b9d7f4   ddb145fe6d62        355MB
docker-orchagent              latest                2b0a4c92794f        400MB
docker-orchagent              master.399-07b9d7f4   2b0a4c92794f        400MB
docker-nat                    latest                eb5c6b6736c2        389MB
docker-nat                    master.399-07b9d7f4   eb5c6b6736c2        389MB
docker-sonic-telemetry        latest                6c4292e948fd        425MB
docker-sonic-telemetry        master.399-07b9d7f4   6c4292e948fd        425MB
docker-fpm-frr                latest                076744e3f438        402MB
docker-fpm-frr                master.399-07b9d7f4   076744e3f438        402MB
docker-sflow                  latest                1046ede2b365        390MB
docker-sflow                  master.399-07b9d7f4   1046ede2b365        390MB
docker-snmp                   latest                ffbf20d1540a        395MB
docker-snmp                   master.399-07b9d7f4   ffbf20d1540a        395MB
docker-syncd-brcm             latest                d62f6c218ce2        447MB
docker-syncd-brcm             master.399-07b9d7f4   d62f6c218ce2        447MB

root@sonic:/home/admin# 
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by anshuv-mfst** [comment]
Can you please upload show techsupport output. @tim-rj

**Comment by tim-rj** [comment]
[show tech.text.log](https://github.com/Azure/sonic-buildimage/files/5237365/show.tech.text.log)

**Comment by qiluo-msft** [comment]
The code in f66288d5 are trying to solve another issue relating SAI 0.9.4.
Could you please check if this issue exists on latest image?
