### ISSUE TITLE
show reboot-cause not working while syslog print "WARNING systemd[1]: process-reboot-cause.service: Failed with result 'exit-code'"

### ISSUE THREAD

**Issue by tim-rj** [Azure/sonic-buildimage#5354]
**Description**

show reboot-cause not working while syslog print "WARNING systemd[1]: process-reboot-cause.service: Failed with result 'exit-code'"

**Steps to reproduce the issue:**
1. reboot the system and  after system Get up,then show reboot-cause

**Describe the results you received:**
 

```
root@sonic:/var/core# show reboot-cause
Unable to determine cause of previous reboot


syslog print
Sep 10 10:30:07.501045 sonic INFO systemd[1]: Started Reboot cause determination service.
Sep 10 10:30:07.642230 sonic INFO process-reboot-cause: Starting up...
Sep 10 10:30:07.644816 sonic INFO process-reboot-cause: No reboot cause found from /proc/cmdline
Sep 10 10:30:07.645146 sonic INFO process-reboot-cause[4041]: Traceback (most recent call last):
Sep 10 10:30:07.645341 sonic INFO process-reboot-cause[4041]:   File "/usr/bin/process-reboot-cause", line 201, in <module>
Sep 10 10:30:07.645522 sonic INFO process-reboot-cause[4041]:     main()
Sep 10 10:30:07.645728 sonic INFO process-reboot-cause[4041]:   File "/usr/bin/process-reboot-cause", line 164, in main
Sep 10 10:30:07.645930 sonic INFO process-reboot-cause[4041]:     hardware_reboot_cause = find_hardware_reboot_cause()
Sep 10 10:30:07.646111 sonic INFO process-reboot-cause[4041]:   File "/usr/bin/process-reboot-cause", line 116, in find_hardware_reboot_cause
Sep 10 10:30:07.646290 sonic INFO process-reboot-cause[4041]:     platform = sonic_platform.platform.Platform()
Sep 10 10:30:07.646468 sonic INFO process-reboot-cause[4041]: AttributeError: 'module' object has no attribute 'platform'
Sep 10 10:30:07.664954 sonic NOTICE systemd[1]: process-reboot-cause.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 10:30:07.665412 sonic WARNING systemd[1]: process-reboot-cause.service: Failed with result 'exit-code'.


```

**Describe the results you expected:**
show reboot-cause can work

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
root@sonic:/home/admin# show version 

SONiC Software Version: SONiC.master.399-07b9d7f4
Distribution: Debian 10.5
Kernel: 4.19.0-9-2-amd64
Build commit: 07b9d7f4
Build date: Sun Aug 30 07:41:30 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-ruijie_b6510-48vs8cq-r0
HwSKU: B6510-48VS8CQ
ASIC: broadcom
Serial Number: G1W10072
Uptime: 17:26:38 up  2:51,  1 user,  load average: 0.46, 0.37, 0.29

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-teamd                  latest                0da13af040db        386MB
docker-teamd                  master.399-07b9d7f4   0da13af040db        386MB
docker-sonic-mgmt-framework   latest                b3309c50c848        481MB
docker-sonic-mgmt-framework   master.399-07b9d7f4   b3309c50c848        481MB
docker-router-advertiser      latest                81563660196e        355MB
docker-router-advertiser      master.399-07b9d7f4   81563660196e        355MB
docker-platform-monitor       latest                bfc946290aa4        429MB
docker-platform-monitor       master.399-07b9d7f4   bfc946290aa4        429MB
docker-lldp                   latest                17607fd34cc8        383MB
docker-lldp                   master.399-07b9d7f4   17607fd34cc8        383MB
docker-dhcp-relay             latest                57d5a7e2d58d        362MB
docker-dhcp-relay             master.399-07b9d7f4   57d5a7e2d58d        362MB
docker-database               latest                ddb145fe6d62        355MB
docker-database               master.399-07b9d7f4   ddb145fe6d62        355MB
docker-orchagent              latest                2b0a4c92794f        400MB
docker-orchagent              master.399-07b9d7f4   2b0a4c92794f        400MB
docker-nat                    latest                eb5c6b6736c2        389MB
docker-nat                    master.399-07b9d7f4   eb5c6b6736c2        389MB
docker-sonic-telemetry        latest                6c4292e948fd        425MB
docker-sonic-telemetry        master.399-07b9d7f4   6c4292e948fd        425MB
docker-fpm-frr                latest                076744e3f438        402MB
docker-fpm-frr                master.399-07b9d7f4   076744e3f438        402MB
docker-sflow                  latest                1046ede2b365        390MB
docker-sflow                  master.399-07b9d7f4   1046ede2b365        390MB
docker-snmp                   latest                ffbf20d1540a        395MB
docker-snmp                   master.399-07b9d7f4   ffbf20d1540a        395MB
docker-syncd-brcm             latest                d62f6c218ce2        447MB
docker-syncd-brcm             master.399-07b9d7f4   d62f6c218ce2        447MB

root@sonic:/home/admin# 
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by anshuv-mfst** [comment]
Issue is not seen in 201911 and seen in master. 
Platform might not have support for showing reboot cause. (might be missing module) 

@tim-rj to confirm.

**Comment by vsenchyshyn** [comment]
@anshuv-mfst If you run **sudo which reboot** on 201911 you'll see that it points to **/usr/bin/reboot** script which writes the appropriate message to the root cause file and therefore **show reboot-cause** shows correct result
```
admin@tasmania-swc5-bxdsw:~$ sudo which reboot
/usr/bin/reboot
admin@tasmania-swc5-bxdsw:~$ show reboot-cause 
User issued 'reboot' command [User: admin, Time: Tue Sep 22 00:52:29 UTC 2020]
```

On master the **reboot** command points to  **/usr/sbin/reboot** which is a binary. Therefore root cause is not written anywhere. 
```
admin@sonic:~$ sudo which reboot
/usr/sbin/reboot
admin@sonic:~$ less /usr/sbin/reboot
"/usr/sbin/reboot" may be a binary file.  See it anyway? 
```

At the same time for admin user the path to reboot is correct:
```
admin@sonic:~$ which reboot
/usr/bin/reboot
```

**Comment by tim-rj** [comment]
new api need to adapt, close this issue.
