### ISSUE TITLE
[201911]show ipv6 bgp summary does not work when add a BGPV6 neighbor in the FRR module

### ISSUE THREAD

**Issue by tim-rj** [Azure/sonic-buildimage#5440]
**Description**

show ipv6 bgp summary does not work when add a BGPV6 neighbor in the FRR module

**Steps to reproduce the issue:**
1. add a BGPV6 neighbor in the FRR module
2.show ipv6 bgp summary

```
root@sonic:/home/admin# show ip bgp summary 

IPv4 Unicast Summary:
BGP router identifier 10.1.0.1, local AS number 65100 vrf-id 0
BGP table version 10104
RIB entries 20207, using 3718088 bytes of memory
Peers 11, using 230120 KiB of memory
Peer groups 4, using 256 bytes of memory


Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down      State/PfxRcd  NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.0.97      4  64021         19         28         0      0       0  00:02:52            10000  ARISTA21T0
10.10.49.2     4  64021          9         28         0      0       0  00:02:52               12  ARISTA21T0
10.10.49.3     4  64021          9         28         0      0       0  00:02:52               11  ARISTA21T0
10.10.49.4     4  64021          9         28         0      0       0  00:02:52               11  ARISTA21T0
10.10.49.5     4  64021          9         28         0      0       0  00:02:52               11  ARISTA21T0
10.10.49.6     4  64021          9         28         0      0       0  00:02:52               11  ARISTA21T0
10.10.49.7     4  64021          9         28         0      0       0  00:02:52               11  ARISTA21T0
10.10.49.8     4  64021          9         28         0      0       0  00:02:52               11  ARISTA21T0
10.10.49.9     4  64021          9         28         0      0       0  00:02:52               11  ARISTA21T0
10.10.49.10    4  64021          9         28         0      0       0  00:02:52               11  ARISTA21T0
55.1.1.1       4  65101         72         72         0      0       0  00:02:52                1  master

Total number of neighbors 11
root@sonic:/home/admin# show ipv6 bgp summary 

IPv6 Unicast Summary:
BGP router identifier 10.1.0.1, local AS number 65100 vrf-id 0
BGP table version 2
RIB entries 3, using 552 bytes of memory
Peers 1, using 20920 KiB of memory
Peer groups 4, using 256 bytes of memory


Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down    State/PfxRcd    NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10::97         4  64021          0          0         0      0       0  never      Active          ARISTA21T0

Total number of neighbors 1
root@sonic:/home/admin# vtysh 

Hello, this is FRRouting (version 7.2.1-sonic).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

sonic# configure terminal 
sonic(config)# router bgp 65100
sonic(config-router)#  neighbor 55::1 remote-as 65101
sonic(config-router)#  neighbor 55::1 peer-group PEER_V6
sonic(config-router)#  neighbor 55::1 description master
sonic(config-router)# 
sonic(config-router)#  address-family ipv6 unicast
sonic(config-router-af)# neighbor 55::1 activate
sonic(config-router-af)# exit
sonic(config-router)# exit
sonic(config)# exit
sonic# exit
root@sonic:/home/admin# show ipv6 bgp summary 
Traceback (most recent call last):
  File "/usr/bin/show", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/show/bgp_frr_v6.py", line 24, in summary
    bgp_summary = bgp_util.get_bgp_summary_from_all_bgp_instances(constants.IPV6, namespace, display)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 194, in get_bgp_summary_from_all_bgp_instances
    process_bgp_summary_json(bgp_summary, cmd_output_json[key], device)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 296, in process_bgp_summary_json
    peer_ip, static_neighbors, dynamic_neighbors)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 88, in get_bgp_neighbor_ip_to_name
    elif is_ipv4_address(unicode(ip)):
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 23, in is_ipv4_address
    except ipaddress.AddressValueError as err:
AttributeError: 'unicode' object has no attribute 'AddressValueError'
root@sonic:/home/admin# exit


```

**Describe the results you received:**
show ipv6 bgp summary does not work when add a BGPV6 neighbor in the FRR module

```

root@sonic:/home/admin# show ipv6 bgp summary 
Traceback (most recent call last):
  File "/usr/bin/show", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/show/bgp_frr_v6.py", line 24, in summary
    bgp_summary = bgp_util.get_bgp_summary_from_all_bgp_instances(constants.IPV6, namespace, display)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 194, in get_bgp_summary_from_all_bgp_instances
    process_bgp_summary_json(bgp_summary, cmd_output_json[key], device)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 296, in process_bgp_summary_json
    peer_ip, static_neighbors, dynamic_neighbors)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 88, in get_bgp_neighbor_ip_to_name
    elif is_ipv4_address(unicode(ip)):
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 23, in is_ipv4_address
    except ipaddress.AddressValueError as err:
AttributeError: 'unicode' object has no attribute 'AddressValueError'
root@sonic:/home/admin# exit
```

**Describe the results you expected:**
show ipv6 bgp summary can work when add a BGPV6 neighbor in the FRR module

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
root@sonic:/home/admin# show version 

SONiC Software Version: SONiC.HEAD.182-75068f3a
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: 75068f3a
Build date: Tue Sep 15 20:56:19 UTC 2020
Built by: johnar@jenkins-worker-7

Platform: x86_64-ruijie_b6510-48vs8cq-r0
HwSKU: B6510-48VS8CQ
ASIC: broadcom
Serial Number: G1W10072
Uptime: 15:32:00 up 8 min,  1 user,  load average: 0.56, 2.74, 1.68

Docker images:
REPOSITORY                    TAG                 IMAGE ID            SIZE
docker-syncd-brcm             HEAD.182-75068f3a   e0a8a1e70567        436MB
docker-syncd-brcm             latest              e0a8a1e70567        436MB
docker-platform-monitor       HEAD.182-75068f3a   7a0b4c32e32a        357MB
docker-platform-monitor       latest              7a0b4c32e32a        357MB
docker-router-advertiser      HEAD.182-75068f3a   5b68a457b247        289MB
docker-router-advertiser      latest              5b68a457b247        289MB
docker-fpm-frr                HEAD.182-75068f3a   d68563ab47ff        334MB
docker-fpm-frr                latest              d68563ab47ff        334MB
docker-sflow                  HEAD.182-75068f3a   efaf9fdec8fb        314MB
docker-sflow                  latest              efaf9fdec8fb        314MB
docker-lldp-sv2               HEAD.182-75068f3a   eb734d856002        311MB
docker-lldp-sv2               latest              eb734d856002        311MB
docker-orchagent              HEAD.182-75068f3a   31ab84cddd9b        333MB
docker-orchagent              latest              31ab84cddd9b        333MB
docker-dhcp-relay             HEAD.182-75068f3a   0416f768a8aa        299MB
docker-dhcp-relay             latest              0416f768a8aa        299MB
docker-database               HEAD.182-75068f3a   6be94df5546f        289MB
docker-database               latest              6be94df5546f        289MB
docker-snmp-sv2               HEAD.182-75068f3a   7f94958e28db        347MB
docker-snmp-sv2               latest              7f94958e28db        347MB
docker-teamd                  HEAD.182-75068f3a   d1db1b60ffec        314MB
docker-teamd                  latest              d1db1b60ffec        314MB
docker-nat                    HEAD.182-75068f3a   a08bed4749c5        316MB
docker-nat                    latest              a08bed4749c5        316MB
docker-sonic-mgmt-framework   HEAD.182-75068f3a   4f9ba411a805        430MB
docker-sonic-mgmt-framework   latest              4f9ba411a805        430MB
docker-sonic-telemetry        HEAD.182-75068f3a   ad6b2e2569f2        353MB
docker-sonic-telemetry        latest              ad6b2e2569f2        353MB
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by tim-rj** [comment]
Has fixed on master month ago, please cherry pick commit id: fce546d86c0374b5fb090b4ba0970c3a8796801e

**Comment by anshuv-mfst** [comment]
@pavel-shirshov - could you please take a look. Thanks.

**Comment by pavel-shirshov** [comment]
@arlakshm Can you please take a look into the issue?
I see you made a change to the code recently
https://github.com/Azure/sonic-utilities/pull/1064

**Comment by arlakshm** [comment]
@tim-rj, Can you please attach the config_db.json
