### ISSUE TITLE
[warm-reboot] traceback's appears in CLI output while performing warm-reboot

### ISSUE THREAD

**Issue by MaxYaremchuk** [Azure/sonic-buildimage#5442]
**Description**
Traceback appears in the CLI output while performing warm-rebooting

**Steps to reproduce the issue:**
1. Install SONiC.201911.193-75068f3a
2. Execute  warm-reboot -v

**Describe the results you received:**
Although warm-reboot is being carried out successfully there is traceback output
```
#  warm-reboot -v
Fri Sep 18 16:26:10 UTC 2020 Prepare MLNX ASIC to fastfast-reboot: install new FW if required
Fri Sep 18 16:26:11 UTC 2020 Pausing orchagent ...
Fri Sep 18 16:26:11 UTC 2020 Stopping nat ...
Dumping conntrack entries failed
Error response from daemon: Cannot kill container: nat: No such container: nat
Fri Sep 18 16:26:11 UTC 2020 Stopped nat ...
Fri Sep 18 16:26:11 UTC 2020 Stopping radv ...
Fri Sep 18 16:26:11 UTC 2020 Stopping bgp ...
Fri Sep 18 16:26:11 UTC 2020 Stopped bgp ...
Fri Sep 18 16:26:13 UTC 2020 Initialize pre-shutdown ...
Fri Sep 18 16:26:14 UTC 2020 Requesting pre-shutdown ...
Fri Sep 18 16:26:14 UTC 2020 Waiting for pre-shutdown ...
Fri Sep 18 16:26:17 UTC 2020 Pre-shutdown succeeded ...
Fri Sep 18 16:26:17 UTC 2020 Backing up database ...
Fri Sep 18 16:26:18 UTC 2020 Stopping teamd ...
Fri Sep 18 16:26:18 UTC 2020 Stopped teamd ...
Fri Sep 18 16:26:18 UTC 2020 Stopping syncd ...
Fri Sep 18 16:26:27 UTC 2020 Stopped syncd ...
Fri Sep 18 16:26:27 UTC 2020 Stopping all remaining containers ...
Warning: Stopping telemetry.service, but it can still be activated by:
  telemetry.timer
Fri Sep 18 16:26:29 UTC 2020 Stopped all remaining containers ...
Fri Sep 18 16:26:31 UTC 2020 Enabling Watchdog before fastfast-reboot
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 380, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 297, in main
    configdb.connect()
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/configdb.py", line 74, in connect
    self.db_connect('CONFIG_DB', wait_for_init, retry_on)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/configdb.py", line 69, in db_connect
    SonicV2Connector.connect(self, self.db_name, retry_on)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/dbconnector.py", line 250, in connect
    self.dbintf.connect(db_id, retry_on)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 171, in connect
    self._onetime_connect(db_id)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 183, in _onetime_connect
    client.config_set('notify-keyspace-events', self.KEYSPACE_EVENTS)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 719, in config_set
    return self.execute_command('CONFIG SET', name, value)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 380, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 297, in main
    configdb.connect()
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/configdb.py", line 74, in connect
    self.db_connect('CONFIG_DB', wait_for_init, retry_on)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/configdb.py", line 69, in db_connect
    SonicV2Connector.connect(self, self.db_name, retry_on)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/dbconnector.py", line 250, in connect
    self.dbintf.connect(db_id, retry_on)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 171, in connect
    self._onetime_connect(db_id)
  File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 183, in _onetime_connect
    client.config_set('notify-keyspace-events', self.KEYSPACE_EVENTS)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 719, in config_set
    return self.execute_command('CONFIG SET', name, value)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
Watchdog armed for 180 seconds
Fri Sep 18 16:26:32 UTC 2020 Rebooting with /sbin/kexec -e to SONiC-OS-201911.193-75068f3a ...
```

**Output of `show version`:**
```
SONiC Software Version: SONiC.201911.193-75068f3a
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: 75068f3a
Build date: Wed Sep 16 04:52:46 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-mlnx_msn4700-r0
HwSKU: ACS-MSN4700
```
[sonic_dump_20200918_163104.part-001.zip](https://github.com/Azure/sonic-buildimage/files/5267009/sonic_dump_20200918_163104.part-001.zip)
[sonic_dump_20200918_163104.part-002.zip](https://github.com/Azure/sonic-buildimage/files/5267027/sonic_dump_20200918_163104.part-002.zip)
[sonic_dump_20200918_163104.part-003.zip](https://github.com/Azure/sonic-buildimage/files/5267037/sonic_dump_20200918_163104.part-003.zip)
[sonic_dump_20200918_163104.part-004.zip](https://github.com/Azure/sonic-buildimage/files/5267052/sonic_dump_20200918_163104.part-004.zip)
[sonic_dump_20200918_163104.part-005.zip](https://github.com/Azure/sonic-buildimage/files/5267056/sonic_dump_20200918_163104.part-005.zip)

Before unpacking files, please rename all parts of archive in this way:
sonic_dump_20200918_163104.zip.001
sonic_dump_20200918_163104.zip.002
sonic_dump_20200918_163104.zip.003
sonic_dump_20200918_163104.zip.004
sonic_dump_20200918_163104.zip.005

**Comment by prsunny** [comment]
Same issue as https://github.com/Azure/sonic-buildimage/issues/5439

**Comment by prsunny** [comment]
could you please execute "warmboot -x" and provide the output?

**Comment by prsunny** [comment]
Closing this as PRs are merged to master. Please wait for the image and re-open if the issue still persists.
