### ISSUE TITLE
[monit/buffermgrd] monit reporting errors from buffermgrd

### ISSUE THREAD

**Issue by bingwang-ms** [Azure/sonic-buildimage#5488]
**Description**
Some new ERROR logs are found in SONiC.master.425-4006ce71 and cause test error.
```
Sep 29 05:46:33.473514 str-dx010-acs-4 ERR monit[511]: 'swss|buffermgrd' status failed (1) -- Traceback (most recent call last):#012  File "/usr/bin/process_checker", line 57, in <module>#012    main()#012  File "/usr/bin/process_checker", line 53, in main#012    check_process_existence(args.container_name, ' '.join(args.process_cmdline))#012  File "/usr/bin/process_checker", line 31, in check_process_existence#012    if ((' '.join(process.cmdline())).startswith(process_cmdline) and process.status() in ["running", "sleeping"]):#012  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 694, in cmdline#012    return self._proc.cmdline()#012  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1522, in wrapper#012    raise NoSuchProcess(self.pid, self._name)#012psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=5604)
```
For ```swss|buffermgrd``` logs, I guess it's caused by unhandled exception in the process_checker script.

**Output of `show version`:**

```
SONiC Software Version: SONiC.master.425-4006ce71
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 4006ce71
Build date: Sun Sep 27 07:52:44 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-cel_seastone-r0
HwSKU: Celestica-DX010-C32
ASIC: broadcom
Serial Number: DX010F2B118711MS100007
Uptime: 05:59:14 up  2:53,  1 user,  load average: 0.86, 1.72, 1.98

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-teamd                  latest                20617ff1849b        391MB
docker-teamd                  master.425-4006ce71   20617ff1849b        391MB
docker-sonic-mgmt-framework   latest                04e712b877e4        486MB
docker-sonic-mgmt-framework   master.425-4006ce71   04e712b877e4        486MB
docker-router-advertiser      latest                793cb0e5c2fa        359MB
docker-router-advertiser      master.425-4006ce71   793cb0e5c2fa        359MB
docker-platform-monitor       latest                f867f6e00a19        434MB
docker-platform-monitor       master.425-4006ce71   f867f6e00a19        434MB
docker-lldp                   latest                2ec74daaf081        388MB
docker-lldp                   master.425-4006ce71   2ec74daaf081        388MB
docker-dhcp-relay             latest                56b4112e9427        366MB
docker-dhcp-relay             master.425-4006ce71   56b4112e9427        366MB
docker-database               latest                32598ba6c32e        359MB
docker-database               master.425-4006ce71   32598ba6c32e        359MB
docker-orchagent              latest                bd1d90cb1a3f        405MB
docker-orchagent              master.425-4006ce71   bd1d90cb1a3f        405MB
docker-nat                    latest                de766da20285        394MB
docker-nat                    master.425-4006ce71   de766da20285        394MB
docker-sonic-telemetry        latest                3d34711e992d        429MB
docker-sonic-telemetry        master.425-4006ce71   3d34711e992d        429MB
docker-fpm-frr                latest                b79fad0eb74e        407MB
docker-fpm-frr                master.425-4006ce71   b79fad0eb74e        407MB
docker-sflow                  latest                418e8407b585        395MB
docker-sflow                  master.425-4006ce71   418e8407b585        395MB
docker-snmp                   latest                075ee0d414ab        399MB
docker-snmp                   master.425-4006ce71   075ee0d414ab        399MB
docker-syncd-brcm             latest                b93785e0dca0        447MB
docker-syncd-brcm             master.425-4006ce71   b93785e0dca0        447MB

 ```

**Comment by daall** [comment]
Opened #5501 and #5502 for the snmp and bgp errors.

**Comment by daall** [comment]
@bingwang-ms can you add whether the buffermgrd error was found in a specific test or if this is a general issue?

**Comment by bingwang-ms** [comment]
> @bingwang-ms can you add whether the buffermgrd error was found in a specific test or if this is a general issue?

Yes. I think it was a general issue in **process_checker** script. I was not running test cases.

**Comment by bingwang-ms** [comment]
Fixed in https://github.com/Azure/sonic-buildimage/pull/5716
