### ISSUE TITLE
After the device started, show interfaces status  occasionally appeared abnormal

### ISSUE THREAD

**Issue by tim-rj** [Azure/sonic-buildimage#5581]
**Description**

After the device started, show interfaces status  occasionally appeared abnormal

**Steps to reproduce the issue:**
1.reboot
2.show interfaces status 

**Describe the results you received:**
```
admin@sonic:~$ sudo show int st
Traceback (most recent call last):
  File "/usr/bin/intfutil", line 522, in <module>
    main()
  File "/usr/bin/intfutil", line 514, in main
    interface_stat.display_intf_status()
  File "/usr/bin/intfutil", line 355, in display_intf_status
    self.get_intf_status()
  File "/usr/lib/python2.7/dist-packages/utilities_common/multi_asic.py", line 125, in wrapped_run_on_all_asics
    func(self,  *args, **kwargs)
  File "/usr/bin/intfutil", line 436, in get_intf_status
    self.portchannel_speed_dict = po_speed_dict(self.po_int_dict, self.db)
  File "/usr/bin/intfutil", line 250, in po_speed_dict
    interface_speed = '{}G'.format(interface_speed[:-3])
TypeError: 'NoneType' object has no attribute '__getitem__'
admin@sonic:~$ show int status 
Traceback (most recent call last):
  File "/usr/bin/intfutil", line 522, in <module>
    main()
  File "/usr/bin/intfutil", line 514, in main
    interface_stat.display_intf_status()
  File "/usr/bin/intfutil", line 355, in display_intf_status
    self.get_intf_status()
  File "/usr/lib/python2.7/dist-packages/utilities_common/multi_asic.py", line 125, in wrapped_run_on_all_asics
    func(self,  *args, **kwargs)
  File "/usr/bin/intfutil", line 436, in get_intf_status
    self.portchannel_speed_dict = po_speed_dict(self.po_int_dict, self.db)
  File "/usr/bin/intfutil", line 250, in po_speed_dict
    interface_speed = '{}G'.format(interface_speed[:-3])
TypeError: 'NoneType' object has no attribute '__getitem__'
admin@sonic:~$ show int status 
      Interface            Lanes    Speed    MTU    FEC               Alias             Vlan    Oper    Admin             Type    Asym PFC
---------------  ---------------  -------  -----  -----  ------------------  ---------------  ------  -------  ---------------  ----------
      Ethernet1                1      25G   9100    N/A   twentyfiveGigE0/1            trunk    down       up   SFP/SFP+/SFP28         N/A
      Ethernet2                2      25G   9100    N/A   twentyfiveGigE0/2           routed    down       up   SFP/SFP+/SFP28         N/A
      Ethernet3                3      25G   9100    N/A   twentyfiveGigE0/3           routed    down       up   SFP/SFP+/SFP28         N/A
      Ethernet4                4      25G   9100    N/A   twentyfiveGigE0/4           routed    down       up   SFP/SFP+/SFP28         N/A
      Ethernet5                5      25G   9100    N/A   twentyfiveGigE0/5           routed    down       up   SFP/SFP+/SFP28         N/A
      Ethernet6                6      25G   9100    N/A   twentyfiveGigE0/6           routed    down       up              N/A         N/A
      Ethernet7                7      25G   9100    N/A   twentyfiveGigE0/7           routed    down       up              N/A         N/A
      Ethernet8                8      25G   9100    N/A   twentyfiveGigE0/8           routed    down       up              N/A         N/A
      Ethernet9               13      25G   9100    N/A   twentyfiveGigE0/9           routed    down       up              N/A         N/A
     Ethernet10               14      25G   9100    N/A  twentyfiveGigE0/10           routed    down       up              N/A         N/A
     Ethernet11               15      25G   9100    N/A  twentyfiveGigE0/11           routed    down       up   SFP/SFP+/SFP28         N/A
     Ethernet12               16      25G   9100    N/A  twentyfiveGigE0/12           routed    down       up              N/A         N/A
     Ethernet13               21      25G   9100    N/A  twentyfiveGigE0/13           routed    down       up   SFP/SFP+/SFP28         N/A
     Ethernet14               22      25G   9100    N/A  twentyfiveGigE0/14           routed    down       up              N/A         N/A
     Ethernet15               23      25G   9100    N/A  twentyfiveGigE0/15           routed    down       up              N/A         N/A
     Ethernet16               24      25G   9100    N/A  twentyfiveGigE0/16           routed    down       up              N/A         N/A
     Ethernet17               29      25G   9100    N/A  twentyfiveGigE0/17           routed    down       up              N/A         N/A
     Ethernet18               30      25G   9100    N/A  twentyfiveGigE0/18           routed    down       up              N/A         N/A
     Ethernet19               31      25G   9100    N/A  twentyfiveGigE0/19           routed    down       up              N/A         N/A
     Ethernet20               32      25G   9100    N/A  twentyfiveGigE0/20           routed    down       up              N/A         N/A
     Ethernet21               33      25G   9100    N/A  twentyfiveGigE0/21           routed    down       up              N/A         N/A
     Ethernet22               34      25G   9100    N/A  twentyfiveGigE0/22           routed    down       up              N/A         N/A
     Ethernet23               35      25G   9100    N/A  twentyfiveGigE0/23           routed    down       up              N/A         N/A
     Ethernet24               36      25G   9100    N/A  twentyfiveGigE0/24           routed    down       up              N/A         N/A
     Ethernet25               41      25G   9100    N/A  twentyfiveGigE0/25           routed    down       up              N/A         N/A
     Ethernet26               42      25G   9100    N/A  twentyfiveGigE0/26           routed    down       up              N/A         N/A
     Ethernet27               43      25G   9100    N/A  twentyfiveGigE0/27           routed    down       up              N/A         N/A
     Ethernet28               44      25G   9100    N/A  twentyfiveGigE0/28           routed    down       up              N/A         N/A
     Ethernet29               49      25G   9100    N/A  twentyfiveGigE0/29           routed    down       up              N/A         N/A
     Ethernet30               50      25G   9100    N/A  twentyfiveGigE0/30           routed    down       up              N/A         N/A
     Ethernet31               51      25G   9100    N/A  twentyfiveGigE0/31           routed    down       up              N/A         N/A
     Ethernet32               52      25G   9100    N/A  twentyfiveGigE0/32           routed    down       up              N/A         N/A
     Ethernet33               57      25G   9100    N/A  twentyfiveGigE0/33           routed    down       up              N/A         N/A
     Ethernet34               58      25G   9100    N/A  twentyfiveGigE0/34           routed    down       up              N/A         N/A
     Ethernet35               59      25G   9100    N/A  twentyfiveGigE0/35           routed    down       up              N/A         N/A
     Ethernet36               60      25G   9100    N/A  twentyfiveGigE0/36           routed    down       up              N/A         N/A
     Ethernet37               61      25G   9100    N/A  twentyfiveGigE0/37           routed    down       up              N/A         N/A
     Ethernet38               62      25G   9100    N/A  twentyfiveGigE0/38           routed    down       up              N/A         N/A
     Ethernet39               63      25G   9100    N/A  twentyfiveGigE0/39           routed    down       up              N/A         N/A
     Ethernet40               64      25G   9100    N/A  twentyfiveGigE0/40           routed    down       up              N/A         N/A
     Ethernet41               65      25G   9100    N/A  twentyfiveGigE0/41           routed    down       up              N/A         N/A
     Ethernet42               66      25G   9100    N/A  twentyfiveGigE0/42           routed    down       up              N/A         N/A
     Ethernet43               67      25G   9100    N/A  twentyfiveGigE0/43           routed    down       up              N/A         N/A
     Ethernet44               68      25G   9100    N/A  twentyfiveGigE0/44           routed    down       up              N/A         N/A
     Ethernet45               69      25G   9100    N/A  twentyfiveGigE0/45           routed    down       up              N/A         N/A
     Ethernet46               70      25G   9100    N/A  twentyfiveGigE0/46           routed    down       up              N/A         N/A
     Ethernet47               71      25G   9100    N/A  twentyfiveGigE0/47           routed    down       up              N/A         N/A
     Ethernet48               72      25G   9100    N/A  twentyfiveGigE0/48           routed    down       up              N/A         N/A
     Ethernet49      85,86,87,88     100G   9100    N/A      hundredGigE0/1           routed    down       up              N/A         N/A
     Ethernet50      77,78,79,80     100G   9100    N/A      hundredGigE0/2           routed    down       up              N/A         N/A
     Ethernet51     97,98,99,100     100G   9100    N/A      hundredGigE0/3  PortChannel0001    down       up  QSFP28 or later         N/A
     Ethernet52      93,94,95,96     100G   9100    N/A      hundredGigE0/4           routed    down       up              N/A         N/A
     Ethernet53  113,114,115,116     100G   9100    N/A      hundredGigE0/5           routed    down       up              N/A         N/A
     Ethernet54  105,106,107,108     100G   9100    N/A      hundredGigE0/6           routed    down       up  QSFP28 or later         N/A
     Ethernet55  121,122,123,124     100G   9100    N/A      hundredGigE0/7           routed    down       up              N/A         N/A
     Ethernet56  125,126,127,128     100G   9100    N/A      hundredGigE0/8           routed    down       up              N/A         N/A
PortChannel0001              N/A     100G   9100    N/A                 N/A           routed    down       up              N/A         N/A
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
   root@sonic:/home/admin#  show version 

SONiC Software Version: SONiC.HEAD.4838-85c6af9b8
Distribution: Debian 10.5
Kernel: 4.19.0-9-2-amd64
Build commit: 85c6af9b8
Build date: Mon Sep 14 02:50:51 UTC 2020
Built by: johnar@jenkins-worker-2

Platform: x86_64-ruijie_b6510-48vs8cq-r0
HwSKU: B6510-48VS8CQ
ASIC: broadcom
Serial Number: G1W10072
Uptime: 16:28:01 up 40 min,  1 user,  load average: 0.07, 0.29, 0.29

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-teamd                  HEAD.4838-85c6af9b8   cbe8a238e137        391MB
docker-teamd                  latest                cbe8a238e137        391MB
docker-syncd-brcm             HEAD.4838-85c6af9b8   57ad734395fb        447MB
docker-syncd-brcm             latest                57ad734395fb        447MB
docker-router-advertiser      HEAD.4838-85c6af9b8   6b3d699a4ce7        359MB
docker-router-advertiser      latest                6b3d699a4ce7        359MB
docker-platform-monitor       HEAD.4838-85c6af9b8   d7f0c56c85d7        433MB
docker-platform-monitor       latest                d7f0c56c85d7        433MB
docker-lldp                   HEAD.4838-85c6af9b8   703bb9b21aea        387MB
docker-lldp                   latest                703bb9b21aea        387MB
docker-dhcp-relay             HEAD.4838-85c6af9b8   5048e803a4ef        366MB
docker-dhcp-relay             latest                5048e803a4ef        366MB
docker-database               HEAD.4838-85c6af9b8   27d40780a295        359MB
docker-database               latest                27d40780a295        359MB
docker-orchagent              HEAD.4838-85c6af9b8   c08dc0793211        404MB
docker-orchagent              latest                c08dc0793211        404MB
docker-nat                    HEAD.4838-85c6af9b8   57f979e8317a        393MB
docker-nat                    latest                57f979e8317a        393MB
docker-fpm-frr                HEAD.4838-85c6af9b8   5e332df47ce9        406MB
docker-fpm-frr                latest                5e332df47ce9        406MB
docker-sflow                  HEAD.4838-85c6af9b8   eb4a57fa8e50        394MB
docker-sflow                  latest                eb4a57fa8e50        394MB
docker-snmp                   HEAD.4838-85c6af9b8   0e0f3c6df371        399MB
docker-snmp                   latest                0e0f3c6df371        399MB
docker-sonic-mgmt-framework   HEAD.4838-85c6af9b8   1f5649a9c283        486MB
docker-sonic-mgmt-framework   latest                1f5649a9c283        486MB
docker-sonic-telemetry        HEAD.4838-85c6af9b8   530eecbf2274        429MB
docker-sonic-telemetry        latest                530eecbf2274        429MB

    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by anshuv-mfst** [comment]
Expected behavior, please wait for system to populate the tables & stabilize after boot.
