### ISSUE TITLE
redis-dump -d 6 -k JINJA2_CACHE error

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#5587]
**Description**

**Steps to reproduce the issue:**
1. redis-dump -d 6 -k JINJA2_CACHE
2.
3.

**Describe the results you received:**
```
admin@sonic:~$ redis-dump -d 6 -k JINJA2_CACHE
{Traceback (most recent call last):
  File "/usr/local/bin/redis-dump", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/redisdl.py", line 666, in main
    do_dump(options)
  File "/usr/local/lib/python2.7/dist-packages/redisdl.py", line 587, in do_dump
    dump(output, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/redisdl.py", line 173, in dump
    for key, type, ttl, value in _reader(r, pretty, encoding, keys):
  File "/usr/local/lib/python2.7/dist-packages/redisdl.py", line 283, in _reader
    pretty=pretty, encoding=encoding):
  File "/usr/local/lib/python2.7/dist-packages/redisdl.py", line 341, in _read_keys
    value = reader.handle_response(results[i*3], pretty, encoding)
  File "/usr/local/lib/python2.7/dist-packages/redisdl.py", line 241, in handle_response
    value[k.decode(encoding)] = response[k].decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 2: invalid start byte
```

**Describe the results you expected:**
it should not have issue. 

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
admin@str2-7050cx3-acs-03:~$ show version

SONiC Software Version: SONiC.master.436-d03de95e
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
introduced in https://github.com/Azure/sonic-buildimage/pull/3658

**Comment by lguohan** [comment]
I am not sure if JINJA2_CACHE belongs to state db.
