### ISSUE TITLE
[watchdog] Watchdog not work on Celestica-DX010

### ISSUE THREAD

**Issue by bingwang-ms** [Azure/sonic-buildimage#5597]
**Description**
Watchdog not work on Celestica-DX010.

**Steps to reproduce the issue:**
1. Arm a watchdog for 5 seconds timeout 
```
root@str-dx010-acs-4:~# watchdogutil arm -s 5
Watchdog armed for 5 seconds
root@str-dx010-acs-4:~# echo $?
0
```
There is no WARNING or ERROR

2. Check watchdog status
```
root@str-dx010-acs-4:~# watchdogutil status
Status: Unarmed
```
The returned status is unarmed, which should be armed in step 1.

3. An error is reported when attempting to disarm watchdog
```
root@str-dx010-acs-4:~# watchdogutil disarm
Failed to disarm Watchdog
```
And the DUT is not rebooted as expected.

**Describe the results you received:**
Watchdog not work as expected on Celestica-DX010.

**Describe the results you expected:**
Watchdog works normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
root@str-dx010-acs-4:~# show version

SONiC Software Version: SONiC.master.441-5e97574e
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 5e97574e
Build date: Sun Oct 11 07:56:58 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-cel_seastone-r0
HwSKU: Celestica-DX010-C32
ASIC: broadcom
Serial Number: DX010F2B118711MS100007
Uptime: 10:55:37 up  2:39,  2 users,  load average: 2.97, 2.74, 2.23

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-teamd                  latest                b64e23596b0c        394MB
docker-teamd                  master.441-5e97574e   b64e23596b0c        394MB
docker-sonic-mgmt-framework   latest                f4108fcdf83a        486MB
docker-sonic-mgmt-framework   master.441-5e97574e   f4108fcdf83a        486MB
docker-router-advertiser      latest                df77be56193a        359MB
docker-router-advertiser      master.441-5e97574e   df77be56193a        359MB
docker-platform-monitor       latest                caf88f414a2d        441MB
docker-platform-monitor       master.441-5e97574e   caf88f414a2d        441MB
docker-lldp                   latest                167c14768744        388MB
docker-lldp                   master.441-5e97574e   167c14768744        388MB
docker-dhcp-relay             latest                c3a85ba7865b        366MB
docker-dhcp-relay             master.441-5e97574e   c3a85ba7865b        366MB
docker-database               latest                bf20c891675f        359MB
docker-database               master.441-5e97574e   bf20c891675f        359MB
docker-orchagent              latest                8162b9a31fe8        407MB
docker-orchagent              master.441-5e97574e   8162b9a31fe8        407MB
docker-nat                    latest                23171afd199c        396MB
docker-nat                    master.441-5e97574e   23171afd199c        396MB
docker-sonic-telemetry        latest                48268a2c6b47        429MB
docker-sonic-telemetry        master.441-5e97574e   48268a2c6b47        429MB
docker-fpm-frr                latest                8c99da5360ac        410MB
docker-fpm-frr                master.441-5e97574e   8c99da5360ac        410MB
docker-sflow                  latest                8c7530901b5d        397MB
docker-sflow                  master.441-5e97574e   8c7530901b5d        397MB
docker-snmp                   latest                0ad3a19d96a7        399MB
docker-snmp                   master.441-5e97574e   0ad3a19d96a7        399MB
docker-syncd-brcm             latest                9ff9b866d0fe        542MB
docker-syncd-brcm             master.441-5e97574e   9ff9b866d0fe        542MB
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by bingwang-ms** [comment]
I think the issue still exists on lattest image, but the error is different.
```
root@str-dx010-acs-4:~# watchdogutil arm -s 5
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/watchdogutil/main.py", line 13, in <module>
    import sonic_platform
ModuleNotFoundError: No module named 'sonic_platform'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/watchdogutil", line 6, in <module>
    from watchdogutil.main import watchdogutil
  File "/usr/local/lib/python3.7/dist-packages/watchdogutil/main.py", line 16, in <module>
    raise ImportError("%s - required module not found" % str(e))
ImportError: No module named 'sonic_platform' - required module not found
```

**Comment by daall** [comment]
It sounds like this is now blocked by #6068

**Comment by jleveque** [comment]
Watchdogutil is now Python 3 (as is all of sonic-utilities). Thus, watchdogutil will not work on Celestica platforms until they provide a Python 3 sonic-platform package. This is being tracked by https://github.com/Azure/sonic-buildimage/issues/6068. Thus, I am closing this issue.
