### ISSUE TITLE
healthd crash: ImportError: No module named sonic_platform.platform

### ISSUE THREAD

**Issue by vboykox** [Azure/sonic-buildimage#5610]
**Description**
Receiving next log in /var/log/syslog
```
Traceback (most recent call last):
  File "/usr/local/bin/healthd", line 108, in <module>
    main()
  File "/usr/local/bin/healthd", line 104, in main
    health_monitor.run()
  File "/usr/local/bin/healthd", line 71, in run
    import sonic_platform.platform
ImportError: No module named sonic_platform.platform
```

**Steps to reproduce the issue:**
1. Deploy 
2. see /var/log/syslog

**Describe the results you received:**
the heathd monitor does not crash

**Describe the results you expected:**
The daemon is started inside PMON container or the sonic_platform package is installed to the host fs.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
```
SONiC Software Version: SONiC.master.5-dirty-20201013.025725
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: bba5df05
Build date: Tue Oct 13 07:09:25 UTC 2020
Built by: johnar@jenkins-worker-8
```
Introduced by:
https://github.com/Azure/sonic-buildimage/pull/4835

**Comment by Junchao-Mellanox** [comment]
Hi, this feature requred to load platform API on host side, please see design document: https://github.com/Azure/SONiC/blob/master/doc/system_health_monitoring/system-health-HLD.md#4-platform-api-and-pmon-related-change-to-support-this-new-service
