### ISSUE TITLE
[201911] Config reload fails: global name 'clicommon' is not defined

### ISSUE THREAD

**Issue by nazariig** [Azure/sonic-buildimage#5636]
**Description**
Config reload fails on `201911` branch:
```
Reloading Monit configuration ...
Traceback (most recent call last):
  File "/usr/bin/config", line 12, in <module>
    sys.exit(config())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/config/main.py", line 916, in reload
    _restart_services()
  File "/usr/lib/python2.7/dist-packages/config/main.py", line 638, in _restart_services
    clicommon.run_command("sudo monit reload")
NameError: global name 'clicommon' is not defined
```
**The bug was introduced by hash:** https://github.com/Azure/sonic-buildimage/commit/a7ed68319b7b7982f662df004de78b3a9b58a435
**sonic-utilities diff:** [clicommon.run_command("sudo monit reload")](https://github.com/Azure/sonic-utilities/compare/8a9bfe8736c6812cad347b5bb0c2360581cc4d83...ea0205e4d6ac0228f386196b1d88f29fae930630#diff-8bb4eed8e9e1f9974cbb7b46799411ecc318bae391f48735e7ad84a8122809a0R638)

**Steps to reproduce the issue:**
1. config reload -y

**Describe the results you received:**
```
root@sonic:/home/admin# config reload -y
Executing stop of service telemetry...
Warning: Stopping telemetry.service, but it can still be activated by:
  telemetry.timer
Executing stop of service swss...
Executing stop of service lldp...
Executing stop of service bgp...
Executing stop of service hostcfgd...
Executing stop of service nat...
Running command: /usr/local/bin/sonic-cfggen -j /etc/sonic/init_cfg.json -j /etc/sonic/config_db.json --write-to-db
Running command: /usr/bin/db_migrator.py -o migrate
Executing reset-failed of service bgp...
Executing reset-failed of service dhcp_relay...
Executing reset-failed of service hostcfgd...
Executing reset-failed of service hostname-config...
Executing reset-failed of service interfaces-config...
Executing reset-failed of service lldp...
Executing reset-failed of service nat...
Executing reset-failed of service ntp-config...
Executing reset-failed of service pmon...
Executing reset-failed of service radv...
Executing reset-failed of service rsyslog-config...
Executing reset-failed of service sflow...
Executing reset-failed of service snmp...
Executing reset-failed of service swss...
Executing reset-failed of service syncd...
Executing reset-failed of service teamd...
Executing reset-failed of service telemetry...
Executing restart of service hostname-config...
Executing restart of service interfaces-config...
Executing restart of service ntp-config...
Executing restart of service rsyslog-config...
Executing restart of service swss...
Executing restart of service bgp...
Executing restart of service lldp...
Executing restart of service hostcfgd...
Executing restart of service telemetry...
Reloading Monit configuration ...
Traceback (most recent call last):
  File "/usr/bin/config", line 12, in <module>
    sys.exit(config())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/config/main.py", line 916, in reload
    _restart_services()
  File "/usr/lib/python2.7/dist-packages/config/main.py", line 638, in _restart_services
    clicommon.run_command("sudo monit reload")
NameError: global name 'clicommon' is not defined
```

**Describe the results you expected:**
Config reload should not fail

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `show version`:**
```
(paste your output here)
```

**Attach debug file `sudo generate_dump`:**
```
(paste your output here)
```

**Comment by nazariig** [comment]
The bug is fixed with: 36ea042cb9dafd601f0b6f117a9d2095ae1fc721
