### ISSUE TITLE
Issues while parsing port_config.ini

### ISSUE THREAD

**Issue by ciju-juniper** [Azure/sonic-buildimage#5696]
**Problem description**
Recently the parsing of port_config.ini is broken in SONiC. Earlier (till a few weeks back), we could give a column in port_config.ini for "fec". Now it has been observed that sonic-cfggen throws an error during boot and none of the docker images are loaded. When 'fec' column is removed from port_config.ini, things are fine.

This scenario is important when the switches are booted initially without any configuration. In some platforms, depending on the type of optics/cables connected, the In-band ports need to be configured with 'FEC: rs' option. Now with this breakage, ports which will require 'FEC' configuration will not come up initially. This is a blocker for in-band ZTP to work on those platforms.

**How to re-create the problem**
Add a column in port_config.ini file with 'FEC' setting. For example, this a line taken out from the platform file QFX5200-32C-S (sonic-buildimage/device/juniper/x86_64-juniper_qfx5200-r0/Juniper-QFX5200-32C-S/port_config.ini)

#name      |       lanes         |         alias        |          index       |    speed      |   fec
----------|---------------|---------------|----------------|------------|------| 
Ethernet0  |     49,50,51,52       |    hundredGigE1/1    |     0          |    100000    |    rs

**Discussion over the mailing list**
Found a recent commit in 201911 branch that may have introduced this issue.  Commit 2cc98b4bacc3e0d49286786872ef3ef335d056fb introduced through https://github.com/Azure/sonic-buildimage/pull/5010 
  
Reached out to @tahmed-dev and and he has suggested to open this PR. 
Why: The PR introduced environment variable for few switch attributes and are immutable. Among those is the hwsku. I’ve seen port_config.ini being in a folder named after the hwsku and so based on the description, adding fec column should now affect the file availability.

Will attach the 'show tech' o/p & logs shortly.

**Comment by tahmed-dev** [comment]
@ciju-juniper Updated the description due to a typo. I mean adding fec should not affect the availability of the port_config.ini. If the PR in question is the issues, the file will not be found if the pathname contains the hwsku. Since the file is found, I do not think that PR is the underlying cause.

**Comment by ciju-juniper** [comment]
@tahmed-dev I've a working image that was built on Oct-3. I don't have the exact commit id on which it was built as it had some local commits.

How do we debug this problem further? Please let me know if you have any suggestions.

**Comment by ciju-juniper** [comment]
It does look to me that the breakage is in some common library. Were there any recent updates to  any of the parsing libraries that can even overwrite the references from 201911 branch?

**Comment by ciju-juniper** [comment]
@lguohan @abdosi @jleveque  Please take a look

**Comment by ciju-juniper** [comment]
None of the sonic specific commands are working if this issue happens. So I'm not able to take 'show techsupport'. Please let me know if any of the files are required to debug this further.

The following traceback is seen in the /var/log/syslog:

Oct 22 17:40:26 sonic config-setup[1238]: True
Oct 22 17:40:26 sonic config-setup[1238]: True
Oct 22 17:40:26 sonic config-setup[1238]: Traceback (most recent call last):
Oct 22 17:40:26 sonic config-setup[1238]: Traceback (most recent call last):
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/local/bin/sonic-cfggen", line 380, in <module>
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/local/bin/sonic-cfggen", line 380, in <module>
Oct 22 17:40:26 sonic config-setup[1238]:     main()
Oct 22 17:40:26 sonic config-setup[1238]:     main()
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/local/bin/sonic-cfggen", line 265, in main
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/local/bin/sonic-cfggen", line 265, in main
Oct 22 17:40:26 sonic config-setup[1238]:     deep_update(data, FormatConverter.to_deserialized(json.load(stream)))
Oct 22 17:40:26 sonic config-setup[1238]:     deep_update(data, FormatConverter.to_deserialized(json.load(stream)))
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/lib/python2.7/json/__init__.py", line 291, in load
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/lib/python2.7/json/__init__.py", line 291, in load
Oct 22 17:40:26 sonic config-setup[1238]:     **kw)
Oct 22 17:40:26 sonic config-setup[1238]:     **kw)
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
Oct 22 17:40:26 sonic config-setup[1238]:     return _default_decoder.decode(s)
Oct 22 17:40:26 sonic config-setup[1238]:     return _default_decoder.decode(s)
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
Oct 22 17:40:26 sonic config-setup[1238]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Oct 22 17:40:26 sonic config-setup[1238]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
Oct 22 17:40:26 sonic config-setup[1238]:   File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
Oct 22 17:40:26 sonic config-setup[1238]:     obj, end = self.scan_once(s, idx)
Oct 22 17:40:26 sonic config-setup[1238]:     obj, end = self.scan_once(s, idx)
Oct 22 17:40:26 sonic config-setup[1238]: ValueError: Expecting , delimiter: line 18 column 17 (char 495)
Oct 22 17:40:26 sonic config-setup[1238]: ValueError: Expecting , delimiter: line 18 column 17 (char 495)

**Comment by ciju-juniper** [comment]
Just an update as it may help to debug better:

I had this change in the /usr/lib/ztp/templates/ztp-config.j2

`{% if PORT[port].fec is defined and PORT[port].fec != "" %}`
`                "fec": "{{ PORT[port].fec }}",`
`{% endif %}`

After removing this change, sonic services are loaded, but 'FEC: rs' setting is still not applied. 

@rajendra-dendukuri  Look like, ztp is not able to get the 'FEC' settings.  I had seen this working fine in the previous images.

**Comment by ciju-juniper** [comment]
Here is the 'show techsupport' after removing the 'fec' from ztp template
[sonic_dump_sonic_20201022_181911.tar.gz](https://github.com/Azure/sonic-buildimage/files/5421982/sonic_dump_sonic_20201022_181911.tar.gz)

**Comment by tahmed-dev** [comment]
> Just an update as it may help to debug better:
> 
> I had this change in the /usr/lib/ztp/templates/ztp-config.j2
> 
> `{% if PORT[port].fec is defined and PORT[port].fec != "" %}`
> ` "fec": "{{ PORT[port].fec }}",`
> `{% endif %}`
> 
> After removing this change, sonic services are loaded, but 'FEC: rs' setting is still not applied.
> 
> @rajendra-dendukuri Look like, ztp is not able to get the 'FEC' settings. I had seen this working fine in the previous images.

I do not see the ztp change on [master](https://github.com/Azure/sonic-ztp/blob/master/src/usr/lib/ztp/templates/ztp-config.j2)

**Comment by ciju-juniper** [comment]
@tahmed-dev No change for ZTP code, but ztp is not able to get the complete data from port_config.ini. I think there are some script breakage.

**Comment by rajendra-dendukuri** [comment]
> > Just an update as it may help to debug better:
> > I had this change in the /usr/lib/ztp/templates/ztp-config.j2
> > `{% if PORT[port].fec is defined and PORT[port].fec != "" %}`
> > ` "fec": "{{ PORT[port].fec }}",`
> > `{% endif %}`
> > After removing this change, sonic services are loaded, but 'FEC: rs' setting is still not applied.
> > @rajendra-dendukuri Look like, ztp is not able to get the 'FEC' settings. I had seen this working fine in the previous images.
> 
> I do not see the ztp change on [master](https://github.com/Azure/sonic-ztp/blob/master/src/usr/lib/ztp/templates/ztp-config.j2)

@tahmed-dev we want to make the change and ensure it works before rolling it out the change in the sonic-ztp repo. Can you please help us here.

**Comment by anshuv-mfst** [comment]
Issue is not seen without ZTP. 
@SuvarnaMeenakshi - could you please look into this issue.

**Comment by SuvarnaMeenakshi** [comment]
Having checked 201911/202020 and master branch images, I don't see a parsing issue.
I see that when FEC column is added in port_config.ini:
SONiC Software Version: SONiC.2020.0-b82c0fc6
    "PORT": {
        "Ethernet0": {
            "alias": "fortyGigE0/0",
            "description": "fortyGigE0/0",
            "fec": "rs",
            "index": "0",
            "lanes": "25,26,27,28",
            "mtu": "9100",
            "pfc_asym": "off",
            "speed": "40000"
        },

**Comment by ciju-juniper** [comment]
@SuvarnaMeenakshi Issue was observed in PORT[] dictionary table in the /usr/lib/ztp/templates/ztp-config.j2 when the 'fec' column was added. Had you put the changes similar to the one in the comment https://github.com/Azure/sonic-buildimage/issues/5696#issuecomment-714388985 ?

I will anyway check with a new image and see if its' fixed.
