### ISSUE TITLE
[vnet] Orchagent crash after warm-reboot if VNET configured

### ISSUE THREAD

**Issue by volodymyrsamotiy** [Azure/sonic-buildimage#5706]
**Description**
Orchagent crash after warm-reboot if VNET configured

**Steps to reproduce the issue:**
1. Apply config with VxLAN tunnel and VNET configured
```
root@sonic:/home/admin# cat vnet.conf.json
{
    "VXLAN_TUNNEL": {
        "tunnel_v4": {
            "src_ip": "10.1.0.32"
        }
    },

    "VNET": {
        "Vnet1": {
            "vxlan_tunnel": "tunnel_v4",
            "vni": "10001",
            "peer_list": ""
        }
    }
}
root@sonic:/home/admin# config load -y vnet.conf.json
Running command: /usr/local/bin/sonic-cfggen -j vnet.conf.json --write-to-db
```
2. Perform ```warm-reboot```
3. Once switch is up observe that segmentation fault happened in orchagent
```
root@sonic:/home/admin# grep segfault /var/log/syslog
... INFO kernel: [  109.745313] orchagent[4929]: segfault at b0 ip 00005654b4c30450 sp 00007fff4d144158 error 4 in orchagent[5654b4b27000+1bc000]
```
**Describe the results you received:**
Segmentation fault in orchagent
```
Thread 1 "orchagent" received signal SIGSEGV, Segmentation fault.
VNetVrfObject::getVRidIngress (this=this@entry=0x0) at vnetorch.cpp:53
53      vnetorch.cpp: No such file or directory.
(gdb) bt
#0  VNetVrfObject::getVRidIngress (this=this@entry=0x0) at vnetorch.cpp:53
#1  0x0000555b63be2e3c in VNetVrfObject::getDecapMapId (this=0x0) at vnetorch.h:155
#2  VNetOrch::addOperation (this=0x555b64f3ae70, request=...) at vnetorch.cpp:457
#3  0x0000555b63aff0ba in Orch2::doTask (this=0x555b64f3ae70, consumer=...) at orch.cpp:569
#4  0x0000555b63b0517a in Consumer::execute (this=0x555b64f3c420) at orch.cpp:180
#5  0x0000555b63af7e92 in OrchDaemon::start (this=0x555b64f19e70) at orchdaemon.cpp:458
#6  0x0000555b63ae51b2 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:346
```

**Describe the results you expected:**
```warm-reboot``` should work with VNET config

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    SONiC-OS-201911.209-bea968bb
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by prsunny** [comment]
Thanks Volodymyr for the backtrace. I think the root-cause is due to nullptr access when vnet config is pushed while it exists. Could you please check this linked PR?

**Comment by anshuv-mfst** [comment]
Hi @volodymyrsamotiy - please check with the fix and close if issue is no longer seen.
