### ISSUE TITLE
[201911][vnet] show vnet [neighbors | routes [all | tunnel]] crashed

### ISSUE THREAD

**Issue by CLUDev** [Azure/sonic-buildimage#5795]
**Description**

**Steps to reproduce the issue:**
1. show vnet neighbors
2. show vnet routes all
3. show vnet routes tunnel

**Describe the results you received:**

    root@VTEP1:/home/admin# show vnet neighbors
    Traceback (most recent call last):
      File "/usr/bin/show", line 12, in <module>
        sys.exit(cli())
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/show/main.py", line 2936, in neighbors
        tbl, intf, ip = nbr.split(":", 2)
    ValueError: need more than 1 value to unpack

    root@VTEP1:/home/admin# show vnet routes all
    Traceback (most recent call last):
      File "/usr/bin/show", line 12, in <module>
        sys.exit(cli())
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/show/main.py", line 2980, in all
        val = appl_db.get_all(appl_db.APPL_DB, k)
      File "/usr/local/lib/python2.7/dist-packages/swsssdk/dbconnector.py", line 308, in get_all
        return super(SonicV2Connector, self).get_all(db_id, _hash, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 38, in wrapped
        ret_data = f(inst, db_id, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 299, in get_all
        table = client.hgetall(_hash)
      File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1967, in hgetall
        return self.execute_command('HGETALL', name)
      File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 668, in execute_command
        return self.parse_response(connection, command_name, **options)
      File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 680, in parse_response
        response = connection.read_response()
      File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 629, in read_response
        raise response
    redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value

    root@VTEP1:/home/admin# show vnet routes tunnel
    Traceback (most recent call last):
      File "/usr/bin/show", line 12, in <module>
        sys.exit(cli())
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/show/main.py", line 3023, in tunnel
        val = appl_db.get_all(appl_db.APPL_DB, k)
      File "/usr/local/lib/python2.7/dist-packages/swsssdk/dbconnector.py", line 308, in get_all
        return super(SonicV2Connector, self).get_all(db_id, _hash, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 38, in wrapped
        ret_data = f(inst, db_id, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/swsssdk/interface.py", line 299, in get_all
        table = client.hgetall(_hash)
      File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1967, in hgetall
        return self.execute_command('HGETALL', name)
      File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 668, in execute_command
        return self.parse_response(connection, command_name, **options)
      File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 680, in parse_response
        response = connection.read_response()
      File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 629, in read_response
        raise response
    redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value

**Describe the results you expected:**

    root@VTEP2:~# show vnet neighbor
    Vnet_3000    neighbor    mac_address    interfaces
    -----------  ----------  -------------  ------------
    
    root@VTEP2:~# show vnet routes all
    vnet name    prefix          nexthop    interface
    -----------  --------------  ---------  -----------
    Vnet_3000    100.100.1.2/24             Ethernet11

    vnet name    prefix          endpoint    mac address    vni
    -----------  --------------  ----------  -------------  -----
    Vnet_3000    100.100.4.2/24  10.10.10.1

    root@VTEP2:~# show vnet routes tunnel
    vnet name    prefix          endpoint    mac address    vni
    -----------  --------------  ----------  -------------  -----
    Vnet_3000    100.100.4.2/24  10.10.10.1

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    root@VTEP2:~# show version
    SONiC Software Version: SONiC.sonic-brcm-ga-201911-1
    Distribution: Debian 9.12
    Kernel: 4.9.0-11-2-amd64
    ```

    **Attach debug file `sudo generate_dump`:**
    ```
       Debug source file: /src/sonic-utilities/show/main.py
       [root cause] wrong regex for searching neighbor table name
       ------------------------------------------------------------
       file: show/main.py
       ------------------------------------------------------------      
      (i) show vnet neighbors           
          @vnet.command()
          def neighbors():
          <...omit...>
          nbrs = appl_db.keys(appl_db.APPL_DB, "NEIGH_TABLE*") <= wrong regex

     (ii & iii) show vnet routes all / tunnel
          @routes.command()
          def all(): | def tunnel():
          <...omit...>
          vnet_rt_keys = appl_db.keys(appl_db.APPL_DB, 
                         "VNET_ROUTE_TUNNEL_TABLE*")  <= wrong regex
       <<Solution>>
        Use these regex to search for the tables
        (i) "NEIGH_TABLE:*"
        (ii & iii) "VNET_ROUTE_TUNNEL_TABLE:*"

    ```

**Comment by anshuv-mfst** [comment]
Please provide more information:
1. Is orchagent is in running state, i.e. after configuration does it crashes?
2. provide show tech support output
3. Need to confirm if this is SAI issue (BRCM).

**Comment by CLUDev** [comment]
> Please provide more information:
> 
> 1. Is orchagent is in running state, i.e. after configuration does it crashes?
> 2. provide show tech support output
> 3. Need to confirm if this is SAI issue (BRCM).

    1. orchagent is not running
       [syslog]
       Nov 12 12:02:41.337078 sonic ERR monit[600]: 'orchagent' process is not running
       Nov 12 12:02:41.348722 sonic ERR monit[600]: 'sflowmgrd' process is not running

2. Tech Support Output 
[sonic_dump_sonic_20201112_152504.tar.gz](https://github.com/Azure/sonic-buildimage/files/5528935/sonic_dump_sonic_20201112_152504.tar.gz)

3. It does not seem to be an SAI issue

[Reason]
When query _"NEIGH_TABLE*"_ or _"VNET_ROUTE_TUNNEL_TABLE*"_ from APPDB, 
it may contain a combination of table names with and without ":"

    127.0.0.1:6379> keys NEIGH_TABLE*
    1) "NEIGH_TABLE_DEL_SET"
    2) "NEIGH_TABLE_KEY_SET"

    127.0.0.1:6379> keys VNET_ROUTE_TUNNEL_TABLE*
    1) "VNET_ROUTE_TUNNEL_TABLE_KEY_SET"
    2) "VNET_ROUTE_TUNNEL_TABLE:Vnet_2000:100.100.3.0/24"

However, _/src/sonic-utilities/show/main.py_ split the table name with ":" 
without checking if the table name contains ":" or not, 
which caused the cli command yields an exception.
`tbl, intf, ip = nbr.split(":", 2)`

[Suggestion]
We can add ":" to the APPDB query term to prevent the CLI command from crashing
_"NEIGH_TABLE:*"_
_"VNET_ROUTE_TUNNEL_TABLE:*"_

Or we can add a ":" condition check before splitting the table name

The test result is as shown in the expected results field.

**Comment by prsunny** [comment]
Thanks @CLUDev . Would you help fix it in sonic-utilities?

**Comment by CLUDev** [comment]
> Thanks @CLUDev . Would you help fix it in sonic-utilities?

@prsunny OK, will do.

**Comment by CLUDev** [comment]
Hi @prsunny [PR#1263](https://github.com/Azure/sonic-utilities/pull/1263) is created in "sonic-utilities" to fix this issue

**Comment by CLUDev** [comment]
Hi @prsunny, thanks for merging PR#1263 to "sonic-utilities"
How often would the latest commit of "sonic-utilities" be  updated to "sonic-buildimage" in "master" branch?
Do I have to manually update the PR#1263 fix to "201911" branch to close this issue?

**Comment by prsunny** [comment]
Fix merged
