### ISSUE TITLE
[Celestica] /sys/class/i2c-adapter/i2c-12/12-0050/eeprom is missing on DUT

### ISSUE THREAD

**Issue by bingwang-ms** [Azure/sonic-buildimage#5877]
**Description**
The file ```/sys/class/i2c-adapter/i2c-12/12-0050/eeprom``` is missing on DUT, and ```thermalctld``` failed to start due to this.
```
syslog.19.gz:Nov  9 17:55:32.775528 str-dx010-acs-4 INFO pmon#supervisord: thermalctld     self.__initialize_eeprom()
syslog.19.gz:Nov  9 17:55:32.775613 str-dx010-acs-4 INFO pmon#supervisord: thermalctld   File "/usr/local/lib/python2.7/dist-packages/sonic_platform/chassis.py", line 77, in __initialize_eeprom
syslog.19.gz:Nov  9 17:55:32.775613 str-dx010-acs-4 INFO pmon#supervisord: thermalctld     self._eeprom = Tlv()
syslog.19.gz:Nov  9 17:55:32.775613 str-dx010-acs-4 INFO pmon#supervisord: thermalctld   File "/usr/local/lib/python2.7/dist-packages/sonic_platform/eeprom.py", line 36, in __init__
syslog.19.gz:Nov  9 17:55:32.775664 str-dx010-acs-4 INFO pmon#supervisord: thermalctld     self._eeprom = self._load_eeprom()
syslog.19.gz:Nov  9 17:55:32.775664 str-dx010-acs-4 INFO pmon#supervisord: thermalctld   File "/usr/local/lib/python2.7/dist-packages/sonic_platform/eeprom.py", line 86, in _load_eeprom
syslog.19.gz:Nov  9 17:55:32.775691 str-dx010-acs-4 INFO pmon#supervisord: thermalctld     e = self.read_eeprom()
syslog.19.gz:Nov  9 17:55:32.775691 str-dx010-acs-4 INFO pmon#supervisord: thermalctld   File "/usr/local/lib/python2.7/dist-packages/sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py", line 290, in read_eeprom
syslog.19.gz:Nov  9 17:55:32.776582 str-dx010-acs-4 INFO pmon#supervisord: thermalctld     h = self.read_eeprom_bytes(self._TLV_INFO_HDR_LEN)
syslog.19.gz:Nov  9 17:55:32.776582 str-dx010-acs-4 INFO pmon#supervisord: thermalctld   File "/usr/local/lib/python2.7/dist-packages/sonic_platform_base/sonic_eeprom/eeprom_base.py", line 263, in read_eeprom_bytes
syslog.19.gz:Nov  9 17:55:32.776827 str-dx010-acs-4 INFO pmon#supervisord: thermalctld     raise IOError("Failed to read eeprom : %s" % (str(e)))
syslog.19.gz:Nov  9 17:55:32.776827 str-dx010-acs-4 INFO pmon#supervisord: thermalctld IOError: Failed to read eeprom : [Errno 2] No such file or directory: '/sys/class/i2c-adapter/i2c-12/12-0050/eeprom'
syslog.19.gz:Nov  9 17:55:36.675004 str-dx010-acs-4 INFO pmon#supervisord 2020-11-09 17:55:29,972 INFO spawned:
```
And ```psud``` raised an error either. I'm not sure if it was caused by above issue.
```
Nov 10 03:37:01.522211 str-dx010-acs-4 INFO pmon#supervisord: psud Traceback (most recent call last):
Nov 10 03:37:01.522467 str-dx010-acs-4 INFO pmon#supervisord: psud   File "/usr/local/bin/psud", line 441, in <module>
Nov 10 03:37:01.522690 str-dx010-acs-4 INFO pmon#supervisord: psud     main()
Nov 10 03:37:01.522798 str-dx010-acs-4 INFO pmon#supervisord: psud   File "/usr/local/bin/psud", line 437, in main
Nov 10 03:37:01.522853 str-dx010-acs-4 INFO pmon#supervisord: psud     psud.run()
Nov 10 03:37:01.522906 str-dx010-acs-4 INFO pmon#supervisord: psud   File "/usr/local/bin/psud", line 270, in run
Nov 10 03:37:01.523175 str-dx010-acs-4 INFO pmon#supervisord: psud     psu_db_update(psu_tbl, psu_num)
Nov 10 03:37:01.523316 str-dx010-acs-4 INFO pmon#supervisord: psud   File "/usr/local/bin/psud", line 99, in psu_db_update
Nov 10 03:37:01.523432 str-dx010-acs-4 INFO pmon#supervisord: psud     'true' if _wrapper_get_psus_presence(psu_index) else 'false'),
Nov 10 03:37:01.523797 str-dx010-acs-4 INFO pmon#supervisord: psud   File "/usr/local/bin/psud", line 80, in _wrapper_get_psus_presence
Nov 10 03:37:01.523910 str-dx010-acs-4 INFO pmon#supervisord: psud     return platform_psuutil.get_psu_presence(psu_index)
Nov 10 03:37:01.523963 str-dx010-acs-4 INFO pmon#supervisord: psud   File "/usr/share/sonic/platform/plugins/psuutil.py", line 82, in get_psu_presence
Nov 10 03:37:01.524018 str-dx010-acs-4 INFO pmon#supervisord: psud     return int(raw, 10) == 0
Nov 10 03:37:01.524070 str-dx010-acs-4 INFO pmon#supervisord: psud ValueError: invalid literal for int() with base 10: ''
```
The absence of ```psud``` will cause ```pmon``` reload, and then stuck in failed loop. 
This issue was observed on SONiC.master.478-23b0e07d and SONiC.master.480-385dfc49, Celestica platform.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
SONiC Software Version: SONiC.master.480-385dfc49
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 385dfc49
Build date: Mon Nov  9 18:37:17 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-cel_seastone-r0
HwSKU: Celestica-DX010-C32
ASIC: broadcom
/usr/local/bin/decode-syseeprom : ERROR : Failed to read eeprom : [Errno 2] No such file or directory: '/sys/class/i2c-adapter/i2c-12/12-0050/eeprom'
Serial Number: 
Uptime: 02:58:28 up 23 min,  1 user,  load average: 1.81, 1.72, 1.34

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-snmp                   latest                bc41d17fecf8        458MB
docker-snmp                   master.480-385dfc49   bc41d17fecf8        458MB
docker-teamd                  latest                d1831f8b2e30        454MB
docker-teamd                  master.480-385dfc49   d1831f8b2e30        454MB
docker-sonic-mgmt-framework   latest                cba61af7bcd7        582MB
docker-sonic-mgmt-framework   master.480-385dfc49   cba61af7bcd7        582MB
docker-router-advertiser      latest                6aba51bdf6a0        421MB
docker-router-advertiser      master.480-385dfc49   6aba51bdf6a0        421MB
docker-platform-monitor       latest                e5460d6eee11        532MB
docker-platform-monitor       master.480-385dfc49   e5460d6eee11        532MB
docker-lldp                   latest                dacc4e6f448d        485MB
docker-lldp                   master.480-385dfc49   dacc4e6f448d        485MB
docker-dhcp-relay             latest                c41e90e135b1        428MB
docker-dhcp-relay             master.480-385dfc49   c41e90e135b1        428MB
docker-database               latest                300c0f65826f        421MB
docker-database               master.480-385dfc49   300c0f65826f        421MB
docker-orchagent              latest                3f6286012010        468MB
docker-orchagent              master.480-385dfc49   3f6286012010        468MB
docker-nat                    latest                7f8f28ed3662        457MB
docker-nat                    master.480-385dfc49   7f8f28ed3662        457MB
docker-sonic-telemetry        latest                8018201c62ec        491MB
docker-sonic-telemetry        master.480-385dfc49   8018201c62ec        491MB
docker-fpm-frr                latest                819e1f475225        471MB
docker-fpm-frr                master.480-385dfc49   819e1f475225        471MB
docker-sflow                  latest                06a6080353c9        455MB
docker-sflow                  master.480-385dfc49   06a6080353c9        455MB
docker-syncd-brcm             latest                ca7c64d7964b        527MB
docker-syncd-brcm             master.480-385dfc49   ca7c64d7964b        527MB
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
@bingwang-ms, is build 476 good?

**Comment by bingwang-ms** [comment]
Yes. I've verified that 476 is good. The file exists on 476, and pmon is good.

**Comment by lguohan** [comment]
it looks like the issue is introduced in this https://github.com/Azure/sonic-linux-kernel/commit/02f41e8e0459ae9733a122633dbf85874c2f3183 

on dx010 platform it uses i2c_mux_pca954x . but the the above pr also enabled i2c_mux_pca9541, there is some conflict to cause the i2c probe failure. 

Nov 10 08:14:52.839345 str-dx010-acs-4 WARNING kernel: [   10.900019] pca954x 0-0071: probe failed

the temp solution is to create a `/etc/modprobe.d/blacklist.conf`

```
blacklist i2c_mux_pca9541 
```

**Comment by bingwang-ms** [comment]
Thanks @lguohan . Already add a temp fix to DUT to workaround this issue.

**Comment by yxieca** [comment]
#5891  is a smaller impact change suggested by pca9541 expert. This change achieves the same effect as #5881 on Celestica dx010 platform and only impact dx010 platform.

**Comment by bingwang-ms** [comment]
Fixed.
