### ISSUE TITLE
config reload failed on vs image

### ISSUE THREAD

**Issue by stephenxs** [Azure/sonic-buildimage#5959]
**Description**
config reload failed on vs image

**Steps to reproduce the issue:**
1. start vs image
2. execute "config reload"
3.

**Describe the results you received:**
```
root@dev-r730-03:~/stephens# docker exec -ti vs-normal bash
root@003bcd822266:/# show int st
  Interface            Lanes    Speed    MTU    FEC           Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  ---------------  -------  -----  -----  --------------  ------  ------  -------  ------  ----------
  Ethernet0      25,26,27,28     100G   9100    N/A    fortyGigE0/0  routed    down     down     N/A         N/A
  Ethernet4      29,30,31,32     100G   9100    N/A    fortyGigE0/4  routed    down     down     N/A         N/A
  Ethernet8      33,34,35,36     100G   9100    N/A    fortyGigE0/8  routed    down     down     N/A         N/A
 Ethernet12      37,38,39,40     100G   9100    N/A   fortyGigE0/12  routed    down     down     N/A         N/A
 Ethernet16      45,46,47,48     100G   9100    N/A   fortyGigE0/16  routed    down     down     N/A         N/A
 Ethernet20      41,42,43,44     100G   9100    N/A   fortyGigE0/20  routed    down     down     N/A         N/A
 Ethernet24          1,2,3,4     100G   9100    N/A   fortyGigE0/24  routed    down     down     N/A         N/A
 Ethernet28          5,6,7,8     100G   9100    N/A   fortyGigE0/28  routed    down     down     N/A         N/A
 Ethernet32      13,14,15,16     100G   9100    N/A   fortyGigE0/32  routed    down     down     N/A         N/A
 Ethernet36       9,10,11,12     100G   9100    N/A   fortyGigE0/36  routed    down     down     N/A         N/A
 Ethernet40      17,18,19,20     100G   9100    N/A   fortyGigE0/40  routed    down     down     N/A         N/A
 Ethernet44      21,22,23,24     100G   9100    N/A   fortyGigE0/44  routed    down     down     N/A         N/A
 Ethernet48      53,54,55,56     100G   9100    N/A   fortyGigE0/48  routed    down     down     N/A         N/A
 Ethernet52      49,50,51,52     100G   9100    N/A   fortyGigE0/52  routed    down     down     N/A         N/A
 Ethernet56      57,58,59,60     100G   9100    N/A   fortyGigE0/56  routed    down     down     N/A         N/A
 Ethernet60      61,62,63,64     100G   9100    N/A   fortyGigE0/60  routed    down     down     N/A         N/A
 Ethernet64      69,70,71,72     100G   9100    N/A   fortyGigE0/64  routed    down     down     N/A         N/A
 Ethernet68      65,66,67,68     100G   9100    N/A   fortyGigE0/68  routed    down     down     N/A         N/A
 Ethernet72      73,74,75,76     100G   9100    N/A   fortyGigE0/72  routed    down     down     N/A         N/A
 Ethernet76      77,78,79,80     100G   9100    N/A   fortyGigE0/76  routed    down     down     N/A         N/A
 Ethernet80  109,110,111,112     100G   9100    N/A   fortyGigE0/80  routed    down     down     N/A         N/A
 Ethernet84  105,106,107,108     100G   9100    N/A   fortyGigE0/84  routed    down     down     N/A         N/A
 Ethernet88  113,114,115,116     100G   9100    N/A   fortyGigE0/88  routed    down     down     N/A         N/A
 Ethernet92  117,118,119,120     100G   9100    N/A   fortyGigE0/92  routed    down     down     N/A         N/A
 Ethernet96  125,126,127,128     100G   9100    N/A   fortyGigE0/96  routed    down     down     N/A         N/A
Ethernet100  121,122,123,124     100G   9100    N/A  fortyGigE0/100  routed    down     down     N/A         N/A
Ethernet104      81,82,83,84     100G   9100    N/A  fortyGigE0/104  routed    down     down     N/A         N/A
Ethernet108      85,86,87,88     100G   9100    N/A  fortyGigE0/108  routed    down     down     N/A         N/A
Ethernet112      93,94,95,96     100G   9100    N/A  fortyGigE0/112  routed    down     down     N/A         N/A
Ethernet116      89,90,91,92     100G   9100    N/A  fortyGigE0/116  routed    down     down     N/A         N/A
Ethernet120  101,102,103,104     100G   9100    N/A  fortyGigE0/120  routed    down     down     N/A         N/A
Ethernet124     97,98,99,100     100G   9100    N/A  fortyGigE0/124  routed    down     down     N/A         N/A
root@003bcd822266:/# config reload -y
Traceback (most recent call last):
  File "/usr/local/bin/config", line 8, in <module>
    sys.exit(config())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/config/main.py", line 1051, in reload
    _stop_services(db.cfgdb)
  File "/usr/local/lib/python2.7/dist-packages/config/main.py", line 690, in _stop_services
    execute_systemctl(services_to_stop, SYSTEMCTL_ACTION_STOP)
  File "/usr/local/lib/python2.7/dist-packages/config/main.py", line 216, in execute_systemctl
    generated_services_list, generated_multi_instance_services = _get_sonic_generated_services(num_asic)
TypeError: 'NoneType' object is not iterable
```

**Describe the results you expected:**
It should not failed

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
    show version also failed.
    ```
    root@003bcd822266:/# show version
    /bin/sh: 1: sudo: not found

    SONiC Software Version: SONiC.
    Traceback (most recent call last):
    File "/usr/local/bin/show", line 8, in <module>
        sys.exit(cli())
    File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
    File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/show/main.py", line 1146, in version
        click.echo("Distribution: Debian {}".format(version_info['debian_version']))
    KeyError: 'debian_version'
    root@003bcd822266:/# 
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by vazhel** [comment]
Hello,

Could you check the file ( /etc/sonic/generated_services.conf ) exists on your vs-normal docker?
Is it master branch?

**Comment by anshuv-mfst** [comment]
Liat: Issue is seen only in master branch. 

@lguohan - could you please provide input.

**Comment by stephenxs** [comment]
> /etc/sonic/generated_services.conf

No, it doesn't.
Yes, it is the master branch.

**Comment by vazhel** [comment]
I see that it is mandatory file. It includes list of services that should be restarted by 'config reload' command.
This file is generated as part of target platform building process. 
It is very strange that you don't have this file.

Could you check your building logs in the folder sonic-buildimage/target, file <target_name>.bin.log
For instance: sonc-buildimage/target/sonic-mellanox.bin.log

Try to find rows where this file is generated and check errors.
Like this.
`+ sudo tee -a ./fsroot/etc/sonic/generated_services.conf
+ echo ntp-config.service`

**Comment by liat-grozovik** [comment]
@stephenxs can you please check if the config reload is working when running an official vsimage from public jenkins?

**Comment by stephenxs** [comment]
> @stephenxs can you please check if the config reload is working when running an official vsimage from public jenkins?
I did weeks ago when I first encountered the issue. The issue was reproduced on the official vsimage.
BTW, now I have another way to switch the buffer model on the fly on the vs image. Even though it has some limitations but it's good enough to make the test run.
