### ISSUE TITLE
PMON crashing with master image 494

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-buildimage#5974]
**Description**

**Steps to reproduce the issue:**
1. run nightly test
2.
3.

**Describe the results you received:**
pmon crashing prevented any test from running/passing

**Describe the results you expected:**
run nightly test and have most testcases passing at this stage.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
SONiC Software Version: SONiC.master.494-b595a6ea
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: b595a6ea
Build date: Wed Nov 18 09:49:17 UTC 2020
Built by: johnar@jenkins-worker-8
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
Nov 19 15:51:16.367041 str2-7050cx3-acs-06 INFO pmon#supervisord: thermalctld Traceback (most recent call last):
Nov 19 15:51:16.367143 str2-7050cx3-acs-06 INFO pmon#supervisord: thermalctld   File "/usr/local/bin/thermalctld", line 19, in <module>
Nov 19 15:51:16.367185 str2-7050cx3-acs-06 INFO pmon#supervisord: thermalctld     if os.environ["THERMALCTLD_UNIT_TESTING"] == "1":
Nov 19 15:51:16.367226 str2-7050cx3-acs-06 INFO pmon#supervisord: thermalctld   File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
Nov 19 15:51:16.367264 str2-7050cx3-acs-06 INFO pmon#supervisord: thermalctld     raise KeyError(key)
Nov 19 15:51:16.367302 str2-7050cx3-acs-06 INFO pmon#supervisord: thermalctld KeyError: 'THERMALCTLD_UNIT_TESTING'
Nov 19 15:51:16.424943 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd Traceback (most recent call last):
Nov 19 15:51:16.425037 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd   File "/usr/local/bin/xcvrd", line 5, in <module>
Nov 19 15:51:16.425077 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd     from xcvrd.xcvrd import main
Nov 19 15:51:16.425116 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/xcvrd/xcvrd.py", line 24, in <module>
Nov 19 15:51:16.425155 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd     from .xcvrd_utilities import y_cable_helper
Nov 19 15:51:16.425194 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/xcvrd/xcvrd_utilities/y_cable_helper.py", line 11, in <module>
Nov 19 15:51:16.425232 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd     from sonic_y_cable import y_cable
Nov 19 15:51:16.425273 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/sonic_y_cable/y_cable.py", line 10, in <module>
Nov 19 15:51:16.425311 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd     import sonic_platform.platform
Nov 19 15:51:16.425349 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd   File "/usr/lib/python2.7/dist-packages/sonic_platform/__init__.py", line 8, in <module>
Nov 19 15:51:16.425386 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd     from . import (
Nov 19 15:51:16.425424 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd   File "/usr/lib/python2.7/dist-packages/arista/utils/sonic_platform/chassis.py", line 15, in <module>
Nov 19 15:51:16.425462 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd     from arista.utils.sonic_platform.psu import Psu
Nov 19 15:51:16.425499 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd   File "/usr/lib/python2.7/dist-packages/arista/utils/sonic_platform/psu.py", line 6, in <module>
Nov 19 15:51:16.425537 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd     from sonic_platform_base.psu_base import PsuBase
Nov 19 15:51:16.425574 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/sonic_platform_base/psu_base.py", line 11, in <module>
Nov 19 15:51:16.425612 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd     class PsuBase(device_base.DeviceBase):
Nov 19 15:51:16.425670 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/sonic_platform_base/psu_base.py", line 30, in PsuBase
Nov 19 15:51:16.425842 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd     psu_master_led_color = STATUS_LED_COLOR_OFF
Nov 19 15:51:16.425882 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd NameError: name 'STATUS_LED_COLOR_OFF' is not defined
Nov 19 15:51:16.435636 str2-7050cx3-acs-06 INFO pmon#supervisord: psud Traceback (most recent call last):
Nov 19 15:51:16.435737 str2-7050cx3-acs-06 INFO pmon#supervisord: psud   File "/usr/local/bin/psud", line 21, in <module>
Nov 19 15:51:16.435777 str2-7050cx3-acs-06 INFO pmon#supervisord: psud     if os.environ["PSUD_UNIT_TESTING"] == "1":
Nov 19 15:51:16.435818 str2-7050cx3-acs-06 INFO pmon#supervisord: psud   File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
Nov 19 15:51:16.435857 str2-7050cx3-acs-06 INFO pmon#supervisord: psud     raise KeyError(key)
Nov 19 15:51:16.435895 str2-7050cx3-acs-06 INFO pmon#supervisord: psud KeyError: 'PSUD_UNIT_TESTING'
Nov 19 15:51:16.502233 str2-7050cx3-acs-06 NOTICE pmon#syseepromd[36]: :- loadRedisScript: lua script loaded, sha: a8da2cfe2f7323ca3ecee51ab8475add8368f8b7
Nov 19 15:51:16.515770 str2-7050cx3-acs-06 INFO pmon#supervisor-proc-exit-listener: Process xcvrd exited unxepectedly. Terminating supervisor...
Nov 19 15:51:16.521049 str2-7050cx3-acs-06 NOTICE pmon#syseepromd[36]: :- loadRedisScript: lua script loaded, sha: a8da2cfe2f7323ca3ecee51ab8475add8368f8b7
Nov 19 15:51:16.521160 str2-7050cx3-acs-06 WARNING pmon#syseepromd[36]: Failed to load platform-specific eeprom from sonic_platform package due to NameError("name 'STATUS_LED_COLOR_OFF' is not defined",)
Nov 19 15:51:16.549542 str2-7050cx3-acs-06 INFO pmon#supervisor-proc-exit-listener: Process psud exited unxepectedly. Terminating supervisor...
Nov 19 15:51:16.557696 str2-7050cx3-acs-06 ERR pmon#ledd[32]: :- initializeGlobalConfig: Sonic database config global file doesn't exist at /var/run/redis/sonic-db/database_global.json
Nov 19 15:51:16.562807 str2-7050cx3-acs-06 NOTICE pmon#ledd[32]: :- loadRedisScript: lua script loaded, sha: a8da2cfe2f7323ca3ecee51ab8475add8368f8b7    ```

**Comment by vaibhavhd** [comment]
This also appears to have traces of `NameError` in `psu_base.py` that are now fixed by https://github.com/Azure/sonic-platform-common/pull/143
The latest image should not report below errors that are logged in this issue:
```
Nov 19 15:51:16.425670 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd File "/usr/local/lib/python2.7/dist-packages/sonic_platform_base/psu_base.py", line 30, in PsuBase
Nov 19 15:51:16.425842 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd psu_master_led_color = STATUS_LED_COLOR_OFF
Nov 19 15:51:16.425882 str2-7050cx3-acs-06 INFO pmon#supervisord: xcvrd NameError: name 'STATUS_LED_COLOR_OFF' is not defined
```

**Comment by bingwang-ms** [comment]
Same issue was observed on DX010-4, T0. But the error message is different
```
Nov 19 20:50:23.817441 str-dx010-acs-4 INFO pmon#supervisord: psud Traceback (most recent call last):
Nov 19 20:50:23.817685 str-dx010-acs-4 INFO pmon#supervisord: psud   File "/usr/local/bin/psud", line 21, in <module>
Nov 19 20:50:23.817842 str-dx010-acs-4 INFO pmon#supervisord: psud     if os.environ["PSUD_UNIT_TESTING"] == "1":
Nov 19 20:50:23.817986 str-dx010-acs-4 INFO pmon#supervisord: psud   File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
Nov 19 20:50:23.818132 str-dx010-acs-4 INFO pmon#supervisord: psud     raise KeyError(key)
Nov 19 20:50:23.818276 str-dx010-acs-4 INFO pmon#supervisord: psud KeyError: 'PSUD_UNIT_TESTING'
Nov 19 20:50:23.843735 str-dx010-acs-4 NOTICE pmon#syseepromd[33]: :- loadRedisScript: lua script loaded, sha: a8da2cfe2f7323ca3ecee51ab8475add8368f8b7
Nov 19 20:50:23.864579 str-dx010-acs-4 INFO pmon#supervisord: thermalctld Traceback (most recent call last):
Nov 19 20:50:23.868578 str-dx010-acs-4 INFO pmon#supervisord: thermalctld   File "/usr/local/bin/thermalctld", line 19, in <module>
Nov 19 20:50:23.869248 str-dx010-acs-4 INFO pmon#supervisord: thermalctld     
Nov 19 20:50:23.869933 str-dx010-acs-4 INFO pmon#supervisord: thermalctld if os.environ["THERMALCTLD_UNIT_TESTING"] == "1":
Nov 19 20:50:23.870756 str-dx010-acs-4 INFO pmon#supervisord: thermalctld   File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
Nov 19 20:50:23.891878 str-dx010-acs-4 INFO pmon#supervisord: thermalctld     raise KeyError(key)
Nov 19 20:50:23.892824 str-dx010-acs-4 INFO pmon#supervisord: thermalctld KeyError: 'THERMALCTLD_UNIT_TESTING'
Nov 19 20:50:23.938261 str-dx010-acs-4 INFO pmon#supervisor-proc-exit-listener: Process psud exited unxepectedly. Terminating supervisor...
Nov 19 20:50:24.029900 str-dx010-acs-4 NOTICE pmon#syseepromd[33]: :- loadRedisScript: lua script loaded, sha: a8da2cfe2f7323ca3ecee51ab8475add8368f8b7
Nov 19 20:50:24.030143 str-dx010-acs-4 WARNING pmon#syseepromd[33]: Failed to load platform-specific eeprom from sonic_platform package due to NameError("name 'STATUS_LED_COLOR_OFF' is not defined",)
Nov 19 20:50:24.049614 str-dx010-acs-4 WARNING pmon#sonic_y_cable: Failed to load chassis due to NameError("name 'STATUS_LED_COLOR_OFF' is not defined",)
Nov 19 20:50:24.142846 str-dx010-acs-4 WARNING pmon#xcvrd[30]: Failed to load chassis due to NameError("name 'STATUS_LED_COLOR_OFF' is not defined",)
Nov 19 20:50:24.190430 str-dx010-acs-4 NOTICE pmon#xcvrd[30]: :- loadRedisScript: lua script loaded, sha: a8da2cfe2f7323ca3ecee51ab8475add8368f8b7
Nov 19 20:50:25.612354 str-dx010-acs-4 NOTICE pmon#xcvrd[52]: :- loadRedisScript: lua script loaded, sha: a8da2cfe2f7323ca3ecee51ab8475add8368f8b7
Nov 19 20:50:25.617838 str-dx010-acs-4 INFO pmon#supervisord: xcvrd Process Process-1:
Nov 19 20:50:25.618088 str-dx010-acs-4 INFO pmon#supervisord: xcvrd Traceback (most recent call last):
Nov 19 20:50:25.618437 str-dx010-acs-4 INFO pmon#supervisord: xcvrd   File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Nov 19 20:50:25.618626 str-dx010-acs-4 INFO pmon#supervisord: xcvrd     self.run()
Nov 19 20:50:25.618790 str-dx010-acs-4 INFO pmon#supervisord: xcvrd   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Nov 19 20:50:25.618952 str-dx010-acs-4 INFO pmon#supervisord: xcvrd     self._target(*self._args, **self._kwargs)
Nov 19 20:50:25.619601 str-dx010-acs-4 INFO pmon#supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/xcvrd/xcvrd.py", line 952, in task_worker
Nov 19 20:50:25.620036 str-dx010-acs-4 INFO pmon#supervisord: xcvrd     status, port_dict = _wrapper_get_transceiver_change_event(timeout) 
Nov 19 20:50:25.620269 str-dx010-acs-4 INFO pmon#supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/xcvrd/xcvrd.py", line 179, in _wrapper_get_transceiver_change_event
Nov 19 20:50:25.620467 str-dx010-acs-4 INFO pmon#supervisord: xcvrd     return platform_sfputil.get_transceiver_change_event(timeout) 
Nov 19 20:50:25.620649 str-dx010-acs-4 INFO pmon#supervisord: xcvrd   File "/usr/share/sonic/platform/plugins/sfputil.py", line 204, in get_transceiver_change_event
Nov 19 20:50:25.620839 str-dx010-acs-4 INFO pmon#supervisord: xcvrd     raise NotImplementedError
Nov 19 20:50:25.621001 str-dx010-acs-4 INFO pmon#supervisord: xcvrd NotImplementedError
```
