### ISSUE TITLE
[Celestica] Missing 'sonic_platform' for Python 3

### ISSUE THREAD

**Issue by bingwang-ms** [Azure/sonic-buildimage#6068]
**Description**
```show platform firmware status``` throws exception due to lack of ```sonic_platform``` on Celestica-DX010.
```
admin@str-dx010-acs-4:/usr/local/lib/python3.7$ show platform firmware status
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fwutil/__init__.py", line 2, in <module>
    from sonic_platform.platform import Platform
ModuleNotFoundError: No module named 'sonic_platform'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fwutil", line 6, in <module>
    from fwutil.main import cli
  File "/usr/local/lib/python3.7/dist-packages/fwutil/__init__.py", line 5, in <module>
    raise ImportError("Required module not found: {}".format(str(e)))
ImportError: Required module not found: No module named 'sonic_platform'
```

**Steps to reproduce the issue:**
1. Run ```show platform firmware status```
2.
3.

**Describe the results you received:**
An exception is thrown.

**Describe the results you expected:**
No exception should be thrown.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
SONiC Software Version: SONiC.master.507-7f21c0be
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 7f21c0be
Build date: Sat Nov 28 05:39:42 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-cel_seastone-r0
HwSKU: Celestica-DX010-C32
ASIC: broadcom
Serial Number: DX010F2B118711MS100007
Uptime: 01:27:35 up  5:03,  1 user,  load average: 1.22, 2.18, 2.38

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-snmp                   latest                a2fe3c2c516c        485MB
docker-snmp                   master.507-7f21c0be   a2fe3c2c516c        485MB
docker-teamd                  latest                09f35b5fc3c2        492MB
docker-teamd                  master.507-7f21c0be   09f35b5fc3c2        492MB
docker-sonic-mgmt-framework   latest                c1366d8d7210        606MB
docker-sonic-mgmt-framework   master.507-7f21c0be   c1366d8d7210        606MB
docker-router-advertiser      latest                887805365101        448MB
docker-router-advertiser      master.507-7f21c0be   887805365101        448MB
docker-platform-monitor       latest                055b0288f0f8        571MB
docker-platform-monitor       master.507-7f21c0be   055b0288f0f8        571MB
docker-lldp                   latest                2d4aa9d9bd15        522MB
docker-lldp                   master.507-7f21c0be   2d4aa9d9bd15        522MB
docker-dhcp-relay             latest                cd53b2db068e        455MB
docker-dhcp-relay             master.507-7f21c0be   cd53b2db068e        455MB
docker-database               latest                949e756d2d50        448MB
docker-database               master.507-7f21c0be   949e756d2d50        448MB
docker-orchagent              latest                48b1543907ff        505MB
docker-orchagent              master.507-7f21c0be   48b1543907ff        505MB
docker-nat                    latest                e953b690bfc6        494MB
docker-nat                    master.507-7f21c0be   e953b690bfc6        494MB
docker-sonic-telemetry        latest                0ecb75631474        517MB
docker-sonic-telemetry        master.507-7f21c0be   0ecb75631474        517MB
docker-fpm-frr                latest                98188f687f8f        507MB
docker-fpm-frr                master.507-7f21c0be   98188f687f8f        507MB
docker-sflow                  latest                10667e9b9901        492MB
docker-sflow                  master.507-7f21c0be   10667e9b9901        492MB
docker-syncd-brcm             latest                88571f24fdf5        541MB
docker-syncd-brcm             master.507-7f21c0be   88571f24fdf5        541MB
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
@jleveque , is this dx010 platform specific problem?

**Comment by jleveque** [comment]
> @jleveque , is this dx010 platform specific problem?

No, a few vendors are not net installing a Python 3 version of their sonic-platform package. Mellanox is currently working on theirs.

**Comment by lguohan** [comment]
you mean yes? do we need to ask Celestica to fix this issue on their platform?

**Comment by jleveque** [comment]
I misinterpreted your question. This issue is specific to a few platforms, not only Celestica. Yes, we need to ask Celestica to create and install a Python 3 version of their sonic-platform wheel package.

**Comment by nasbdh9** [comment]
link https://github.com/Azure/sonic-buildimage/pull/6564
