### ISSUE TITLE
python-thrift is not installed for python3

### ISSUE THREAD

**Issue by msosyak** [Azure/sonic-buildimage#6077]
**Description**
python-thrift  is not installed for python3

**Steps to reproduce the issue:**
1. show version 

**Describe the results you received:**
```
admin@sonic:~$ show version 

SONiC Software Version: SONiC.master.49-dirty-20201127.033520
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 7f21c0be
Build date: Fri Nov 27 09:40:54 UTC 2020
Built by: johnar@jenkins-worker-7

Platform: x86_64-accton_wedge100bf_32x-r0
HwSKU: montara
ASIC: barefoot
Traceback (most recent call last):
  File "/usr/share/sonic/device/x86_64-accton_wedge100bf_32x-r0/plugins/eeprom.py", line 15, in <module>
    from pltfm_mgr_rpc.ttypes import *
  File "/usr/share/sonic/device/x86_64-accton_wedge100bf_32x-r0/plugins/pltfm_mgr_rpc/ttypes.py", line 9, in <module>
    from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
ModuleNotFoundError: No module named 'thrift'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/decode-syseeprom", line 171, in <module>
    exit(main())
  File "/usr/local/bin/decode-syseeprom", line 42, in main
    m = SourceFileLoader('eeprom','/'.join([platform_path, 'plugins', 'eeprom.py'])).load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/sonic/device/x86_64-accton_wedge100bf_32x-r0/plugins/eeprom.py", line 32, in <module>
    raise ImportError(str(e) + "- required module not found")
ImportError: No module named 'thrift'- required module not found
Serial Number: 
```

**Describe the results you expected:**
No exception during show version command

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    see above
    ```

    **Platform:**

    ```
device/barefoot/x86_64-accton_wedge100bf_32x-r0
    ```

**Comment by msosyak** [comment]
@jleveque could you have a look at this? As I see there are custom rules to build thrift from sources managed by MS I guess, and the update procedure is not clear for me.

**Comment by jleveque** [comment]
@msosyak: We did not intend for our custom-built thrift package to be used for anything other than saithrift. There should be no no need for you to use that package, the vanilla package should work fine. I have opened a PR which will hopefully address this. Can you please test it out?  https://github.com/Azure/sonic-buildimage/pull/6080

**Comment by jleveque** [comment]
@msosyak: Have you had a chance to test the changes in https://github.com/Azure/sonic-buildimage/pull/6080 to see if it resolves your issue?

**Comment by msosyak** [comment]
> @msosyak: Have you had a chance to test the changes in #6080 to see if it resolves your issue?

Yes, https://github.com/Azure/sonic-buildimage/pull/6080 fix this issue. Thank you
