### ISSUE TITLE
[python3] fdbshow not works in lattest master image, python3

### ISSUE THREAD

**Issue by bingwang-ms** [Azure/sonic-buildimage#6087]
**Description**
Command ```fdbshow``` throws exception on latest master image.
```
oot@str-dx010-acs-4:/var/log/swss# fdbshow 
Traceback (most recent call last):
  File "/usr/local/bin/fdbshow", line 147, in main
    fdb = FdbShow()
  File "/usr/local/bin/fdbshow", line 49, in __init__
    self.fetch_fdb_data()
  File "/usr/local/bin/fdbshow", line 75, in fetch_fdb_data
    br_port_id = ent[b"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID"][oid_pfx:]
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 345, in __getitem__
    return _swsscommon.FieldValueMap___getitem__(self, key)
TypeError: in method 'FieldValueMap___getitem__', argument 2 of type 'std::map< std::string,std::string >::key_type const &'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fdbshow", line 154, in <module>
    main()
  File "/usr/local/bin/fdbshow", line 150, in main
    print(e.message)
AttributeError: 'TypeError' object has no attribute 'message'
```
The bad code is in ```/usr/local/bin/fdbshow``` line 75.
```
br_port_id = ent[b"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID"][oid_pfx:]
ent_type = ent[b"SAI_FDB_ENTRY_ATTR_TYPE"]
```
It is because the interface ```_swsscommon.FieldValueMap___getitem__``` doesn't accept a ```bytes``` as arguments.

Two options to address the issue
1. Remove the ```b``` before ```SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID``` and ```SAI_FDB_ENTRY_ATTR_TYPE```. It may address this issue, but I'm afraid there are similar issues in other script
2. Add a macro in ```swsscommon.i```. Please refer http://www.swig.org/Doc3.0/Python.html#Python_nn77. 
```
#define SWIG_PYTHON_STRICT_BYTE_CHAR
```
Please note that with this macro, the python 3 bytes objects will be accepted and converted to a C/C++ string, but **any string returned from C/C++ will be converted to a bytes object in Python 3**. We must make sure that our python scripts accept this behavior change.
 

**Steps to reproduce the issue:**
1. Run fdbshow.
2.
3.

**Describe the results you received:**
Print fdb entries.

**Describe the results you expected:**
```fdbshow``` throws exceptions.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
SONiC Software Version: SONiC.master.507-7f21c0be
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 7f21c0be
Build date: Sat Nov 28 05:39:42 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-cel_seastone-r0
HwSKU: Celestica-DX010-C32
ASIC: broadcom
Serial Number: DX010F2B118711MS100007
Uptime: 08:05:16 up 11:42,  2 users,  load average: 4.42, 3.52, 3.08

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-snmp                   latest                a2fe3c2c516c        485MB
docker-snmp                   master.507-7f21c0be   a2fe3c2c516c        485MB
docker-teamd                  latest                09f35b5fc3c2        492MB
docker-teamd                  master.507-7f21c0be   09f35b5fc3c2        492MB
docker-sonic-mgmt-framework   latest                c1366d8d7210        606MB
docker-sonic-mgmt-framework   master.507-7f21c0be   c1366d8d7210        606MB
docker-router-advertiser      latest                887805365101        448MB
docker-router-advertiser      master.507-7f21c0be   887805365101        448MB
docker-platform-monitor       latest                055b0288f0f8        571MB
docker-platform-monitor       master.507-7f21c0be   055b0288f0f8        571MB
docker-lldp                   latest                2d4aa9d9bd15        522MB
docker-lldp                   master.507-7f21c0be   2d4aa9d9bd15        522MB
docker-dhcp-relay             latest                cd53b2db068e        455MB
docker-dhcp-relay             master.507-7f21c0be   cd53b2db068e        455MB
docker-database               latest                949e756d2d50        448MB
docker-database               master.507-7f21c0be   949e756d2d50        448MB
docker-orchagent              latest                48b1543907ff        505MB
docker-orchagent              master.507-7f21c0be   48b1543907ff        505MB
docker-nat                    latest                e953b690bfc6        494MB
docker-nat                    master.507-7f21c0be   e953b690bfc6        494MB
docker-sonic-telemetry        latest                0ecb75631474        517MB
docker-sonic-telemetry        master.507-7f21c0be   0ecb75631474        517MB
docker-fpm-frr                latest                98188f687f8f        507MB
docker-fpm-frr                master.507-7f21c0be   98188f687f8f        507MB
docker-sflow                  latest                10667e9b9901        492MB
docker-sflow                  master.507-7f21c0be   10667e9b9901        492MB
docker-syncd-brcm             latest                88571f24fdf5        541MB
docker-syncd-brcm             master.507-7f21c0be   88571f24fdf5        541MB
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by qiluo-msft** [comment]
The option #1 is actually fixed in https://github.com/Azure/sonic-utilities/pull/1280
Could you please verify again?

**Comment by bingwang-ms** [comment]
Thanks. The fix LGTM

**Comment by bingwang-ms** [comment]
Fixed in https://github.com/Azure/sonic-utilities/pull/1280
