### ISSUE TITLE
[nat] natshow throws exception in nat test

### ISSUE THREAD

**Issue by bingwang-ms** [Azure/sonic-buildimage#6391]
**Description**
```natshow``` throws exception in nat test
```
Traceback (most recent call last):
  File "/usr/local/bin/natshow", line 412, in <module>
    main()
  File "/usr/local/bin/natshow", line 408, in main
    raise e
  File "/usr/local/bin/natshow", line 394, in main
    nat.fetch_translations()
  File "/usr/local/bin/natshow", line 137, in fetch_translations
    ent = self.asic_db.get_all('ASIC_DB', s, blocking=True)
NameError: name 's' is not defined
```

The variable ```s``` is not defined. Is it an error caused by typo?

**Steps to reproduce the issue:**
1. Run ```test_dynamic_nat```
2.
3.

**Describe the results you received:**
An exception is thrown.

**Describe the results you expected:**
No exception should be thrown.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
SONiC Software Version: SONiC.HEAD.233-dirty-20210107.000421
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: a013b8c2
Build date: Thu Jan  7 00:11:52 UTC 2021
Built by: johnar@jenkins-worker-22

Platform: x86_64-cel_seastone-r0
HwSKU: Celestica-DX010-C32
ASIC: broadcom
ASIC Count: 1
Serial Number: DX010F2B118711MS100007
Uptime: 07:52:59 up  7:12,  2 users,  load average: 3.44, 3.99, 3.88

Docker images:
REPOSITORY                    TAG                              IMAGE ID            SIZE
docker-platform-monitor       HEAD.233-dirty-20210107.000421   096c49197689        590MB
docker-platform-monitor       latest                           096c49197689        590MB
docker-lldp                   HEAD.233-dirty-20210107.000421   4582f61b14e7        432MB
docker-lldp                   latest                           4582f61b14e7        432MB
docker-syncd-brcm             HEAD.233-dirty-20210107.000421   7a22c85d693e        638MB
docker-syncd-brcm             latest                           7a22c85d693e        638MB
docker-orchagent              HEAD.233-dirty-20210107.000421   8970484702b0        469MB
docker-orchagent              latest                           8970484702b0        469MB
docker-snmp                   HEAD.233-dirty-20210107.000421   00587fc9ac29        432MB
docker-snmp                   latest                           00587fc9ac29        432MB
docker-teamd                  HEAD.233-dirty-20210107.000421   711c30e91114        451MB
docker-teamd                  latest                           711c30e91114        451MB
docker-sonic-mgmt-framework   HEAD.233-dirty-20210107.000421   c1378fedfb0f        605MB
docker-sonic-mgmt-framework   latest                           c1378fedfb0f        605MB
docker-router-advertiser      HEAD.233-dirty-20210107.000421   5f92382f6b46        391MB
docker-router-advertiser      latest                           5f92382f6b46        391MB
docker-dhcp-relay             HEAD.233-dirty-20210107.000421   5741fd6b7455        398MB
docker-dhcp-relay             latest                           5741fd6b7455        398MB
docker-database               HEAD.233-dirty-20210107.000421   647e07b1074c        391MB
docker-database               latest                           647e07b1074c        391MB
docker-nat                    HEAD.233-dirty-20210107.000421   9a2bc3b878a9        454MB
docker-nat                    latest                           9a2bc3b878a9        454MB
docker-sonic-telemetry        HEAD.233-dirty-20210107.000421   2155a982c6f0        466MB
docker-sonic-telemetry        latest                           2155a982c6f0        466MB
docker-sflow                  HEAD.233-dirty-20210107.000421   a6a870a0105a        451MB
docker-sflow                  latest                           a6a870a0105a        451MB
docker-fpm-frr                HEAD.233-dirty-20210107.000421   3862bfc2dbce        470MB
docker-fpm-frr                latest                           3862bfc2dbce        470MB
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by maksymbelei95** [comment]
Dear @bingwang-ms,

The issue has introduced in https://github.com/Azure/sonic-utilities/commit/be63918dbba4b6329bddf090ac2f83522932ceb4.
I have prepared a fix for the issue: https://github.com/Azure/sonic-utilities/pull/1383
It seems I have some problem with configuring NAT entries. Command `config nat add` always returns `Max limit is reached for NAT entries, skipping adding the entry.` Due to this, could I ask you to review the PR and test it on your configuration?
