### ISSUE TITLE
sudo missing from VS docker image

### ISSUE THREAD

**Issue by kielfriedt** [Azure/sonic-buildimage#6401]
I am able to build the VS docker image on ARM but running show commands I keep getting sudo not found and other configure related issues. 

```
supervisorctl status all
arp_update                       RUNNING   pid 250, uptime 0:42:14
bgpd                             RUNNING   pid 380, uptime 0:30:20
buffermgrd                       RUNNING   pid 224, uptime 0:42:22
fpmsyncd                         RUNNING   pid 160, uptime 0:42:31
intfmgrd                         RUNNING   pid 184, uptime 0:42:27
natmgrd                          RUNNING   pid 239, uptime 0:42:16
natsyncd                         RUNNING   pid 244, uptime 0:42:15
nbrmgrd                          RUNNING   pid 227, uptime 0:42:20
neighsyncd                       RUNNING   pid 152, uptime 0:42:34
orchagent                        RUNNING   pid 131, uptime 0:42:37
portmgrd                         RUNNING   pid 181, uptime 0:42:28
portsyncd                        FATAL     Exited too quickly (process log may have details)
redis-server                     RUNNING   pid 100, uptime 0:42:40
restore_neighbors                EXITED    Jan 08 06:45 PM
rsyslogd                         RUNNING   pid 93, uptime 0:42:41
sflowmgrd                        RUNNING   pid 236, uptime 0:42:18
start.sh                         EXITED    Jan 08 06:03 PM
staticd                          RUNNING   pid 221, uptime 0:42:23
syncd                            RUNNING   pid 118, uptime 0:42:38
teammgrd                         RUNNING   pid 163, uptime 0:42:30
teamsyncd                        RUNNING   pid 157, uptime 0:42:33
vlanmgrd                         RUNNING   pid 198, uptime 0:42:25
vrfmgrd                          RUNNING   pid 168, uptime 0:42:29
vxlanmgrd                        RUNNING   pid 230, uptime 0:42:19
zebra                            RUNNING   pid 217, uptime 0:42:24
```

```
# show vlan brief
Warning: failed to retrieve PORT table from ConfigDB!
/bin/sh: 1: sudo: not found

# show version
Warning: failed to retrieve PORT table from ConfigDB!
/bin/sh: 1: sudo: not found

SONiC Software Version: SONiC.HEAD.0-dirty-20201211.141159
Traceback (most recent call last):
  File "/usr/bin/show", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 1932, in version
    click.echo("Distribution: Debian {}".format(version_info['debian_version']))
KeyError: 'debian_version'
```
im guessing this is related to portsyncd, this service is failing and is reporting that a port is not found in the configDB:
```
Jan  8 18:03:19.368373 ef2ea7100955 NOTICE #portsyncd: :- loadRedisScript: lua script loaded, sha: 88270a7c5c90583e56425aca8af8a4b8c39fe757
Jan  8 18:03:19.368996 ef2ea7100955 NOTICE #portsyncd: :- handlePortConfigFromConfigDB: Getting port configuration from ConfigDB...
Jan  8 18:03:19.369089 ef2ea7100955 INFO #supervisord: portsyncd Listen to link messages...
Jan  8 18:03:19.369548 ef2ea7100955 ERR #portsyncd: :- main: ConfigDB does not have port information, exiting...
Jan  8 18:03:19.369823 ef2ea7100955 INFO #supervisord: portsyncd No port configuration in ConfigDB
Jan  8 18:03:19.369858 ef2ea7100955 INFO #supervisord: portsyncd Exception ":- main: ConfigDB does not have port information, exiting..." was thrown in daemon
```
Can someone help me with the port configure. Im trying to find documentation to show me where to put this port.

**Comment by lguohan** [comment]
can you supply tech support?

**Comment by kielfriedt** [comment]
> can you supply tech support?

Iguohan, I'm not sure what you mean. But ill make whatever changes you request. My goal is to get this VS image running and working.

**Comment by yangxile** [comment]
hi Kiel @kielfriedt ,
You can try to execute "show techsupport" to collect what lguohan mentioned.

admin@sonic:~$ show -?
Usage: show [OPTIONS] COMMAND [ARGS]...
  SONiC command line - 'show' command

Options:
  -?, -h, --help  Show this message and exit.

Commands:
  aaa                   Show AAA configuration
  acl                   Show ACL related information
  arp                   Show IP ARP table
  clock                 Show date and time
  ecn                   Show ECN configuration
  environment           Show environmentals (voltages, fans, temps)
  feature               Show feature status
  interfaces            Show details of the network interfaces
  ip                    Show IP (IPv4) commands
  ipv6                  Show IPv6 commands
  kubernetes            Show kubernetes commands
  line                  Show all /dev/ttyUSB lines and their info
  lldp                  LLDP (Link Layer Discovery Protocol)...
  logging               Show system log
  mac                   Show MAC (FDB) entries
  mirror_session        Show existing everflow sessions
  mmu                   Show mmu configuration
  muxcable              Show muxcable information
  nat                   Show details of the nat
  ndp                   Show IPv6 Neighbour table
  ntp                   Show NTP information
  pfc                   Show details of the priority-flow-control...
  platform              Show platform-specific hardware info
  priority-group        Show details of the PGs
  processes             Display process information
  queue                 Show details of the queues
  reboot-cause          Show cause of most recent reboot
  route-map             show route-map
  runningconfiguration  Show current running configuration...
  services              Show all daemon services
  startupconfiguration  Show startup configuration information
  system-memory         Show memory information
  tacacs                Show TACACS+ configuration
  techsupport           Gather information for troubleshooting
  uptime                Show system uptime

**Comment by kielfriedt** [comment]
Sorry about that:
```show techsupport
Warning: failed to retrieve PORT table from ConfigDB!
/bin/sh: 1: sudo: not found```

**Comment by matti125** [comment]
I have the same issue with a version build number 20220917.5, or thereabouts. It is hard to tell the version, as the container does not show the version. "sudo" exists on the VM from the same build, but is missing in the container (docker) version

**Comment by sajusal** [comment]
Was there a fix for this issue? I am getting similar errors.

**Comment by gnaaman-dn** [comment]
`sudo` is still missing from the image, but my impression is that it is not completely unintentional.
A lot of commands are dependent on a real SONiC setup that contains multiple containers.

For example `show lldp neighbors` will run `sudo docker exec lldp lldpctl` under the hood.
No part of this command makes sense in docker-sonic, since it does not have an lldp container. or the `docker`, or  `lldpctl`, or `lldp` running.

The container itself is not broken, though, just has reduced functionality.
I accepted it and moved-on to use a [VM-container](https://containerlab.dev/manual/kinds/sonic-vm/) when deploying with containerlab.
