### ISSUE TITLE
Collecting bitarray  Downloading bitarray-1.6.2.tar.gz error out during "make configure PLATFORM=xxx" BRCM, MLNX all failed the same way

### ISSUE THREAD

**Issue by gechiang** [Azure/sonic-buildimage#6512]
**Description**
Git Cloned sonic-buildimage that I created today. Facing problem with both “make configure PLATFORM=Broadcom” and “make configure PLATFORM=mellanox” with the following error:
```
...
Collecting pyangbind==0.8.1
  Downloading pyangbind-0.8.1.tar.gz (48 kB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pyangbind==0.8.1) (1.10.0)
Collecting bitarray
  Downloading bitarray-1.6.2.tar.gz (55 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5hlmrydp/bitarray_50eb38fb7d9f400cae2d92b4dced7751/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5hlmrydp/bitarray_50eb38fb7d9f400cae2d92b4dced7751/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-iivc7ld2
         cwd: /tmp/pip-install-5hlmrydp/bitarray_50eb38fb7d9f400cae2d92b4dced7751/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5hlmrydp/bitarray_50eb38fb7d9f400cae2d92b4dced7751/setup.py", line 13, in <module>
        data = open('bitarray/bitarray.h').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'bitarray/bitarray.h'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip3 install pyangbind==0.8.1' returned a non-zero code: 1
Unable to find image 'sonic-slave-stretch:b1cd979d656' locally
Error response from daemon: pull access denied for sonic-slave-stretch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: No such container:path: sonic-slave-stretch:/etc/os-release
Error: No such container:path: sonic-slave-stretch:/usr/local/share/buildinfo/pre-versions
Error: No such container:path: sonic-slave-stretch:/usr/local/share/buildinfo/post-versions
Error: No such container: sonic-slave-stretch
Image sonic-slave-stretch-gechiang:109fdea9740 not found. Building...
Sending build context to Docker daemon  45.06kB
Step 1/18 : ARG slave_base_tag_ref=latest
Step 2/18 : FROM sonic-slave-stretch:${slave_base_tag_ref}
pull access denied for sonic-slave-stretch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Unable to find image 'sonic-slave-stretch-gechiang:109fdea9740' locally
docker: Error response from daemon: pull access denied for sonic-slave-stretch-gechiang, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Makefile.work:264: recipe for target 'configure' failed
make[1]: *** [configure] Error 125
make[1]: Leaving directory '/home/gechiang/sonic-buildimage'
Makefile:33: recipe for target 'configure' failed
make: *** [configure] Error 2
```

**Steps to reproduce the issue:**
1. git clone https://github.com/Azure/sonic-buildimage.git
2. make init
3. make configure PLATFORM=xxx where xxx could be broadcom or mellanox
4. See the failure above.

This is with the master branch.

**Comment by lguohan** [comment]
fixed by upstream. https://pypi.org/project/bitarray/1.6.3/
