### ISSUE TITLE
'show ip bgp summary' returns failure in certain cases

### ISSUE THREAD

**Issue by prsunny** [Azure/sonic-buildimage#6697]
**Description**

With SLB routes present, 'show ip bgp summary' is returning 'AddressValueError'. It looks like the issue happens if output has asterisks. (Details below)

**Steps to reproduce the issue:**
1. Run bgp speaker test
2. While test announce routes, login to dut and execute 'show ip bgp summary'
3.

**Describe the results you received:**

```
str-22$ show ip bgp summ
Traceback (most recent call last):
  File "/usr/bin/show", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/show/bgp_frr_v4.py", line 26, in summary
    bgp_summary = bgp_util.get_bgp_summary_from_all_bgp_instances(constants.IPV4,  namespace,display)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 196, in get_bgp_summary_from_all_bgp_instances
    process_bgp_summary_json(bgp_summary, cmd_output_json[key], device)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 298, in process_bgp_summary_json
    peer_ip, static_neighbors, dynamic_neighbors)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 90, in get_bgp_neighbor_ip_to_name
    elif is_ipv4_address(unicode(ip)):
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 23, in is_ipv4_address
    except ipaddress.AddressValueError as err:
AttributeError: 'unicode' object has no attribute 'AddressValueError'
```

VTYSH output
=========

```
vtysh 

Hello, this is FRRouting (version 7.2.1-sonic).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

str-22# show ip bgp summary 

IPv4 Unicast Summary:
BGP router identifier 10.1.0.32, local AS number 65100 vrf-id 0
BGP table version 8178
RIB entries 12811, using 2302 KiB of memory
Peers 7, using 143 KiB of memory
Peer groups 4, using 256 bytes of memory

Neighbor        V         AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd
*10.255.0.1     4      64523       5    3207        0    0    0 00:00:06            1
*10.255.0.2     4      64523       5    1413        0    0 1794 00:00:02            1
*192.168.0.2    4      64523       6    3208        0    0    0 00:01:01            1
10.0.0.57       4      64600    3305    3961        0    0    0 01:40:43         6400
10.0.0.59       4      64600    3305    3961        0    0    0 01:40:44         6400
10.0.0.61       4      64600    3305    3961        0    0    0 01:40:43         6400
10.0.0.63       4      64600    3305    3961        0    0    0 01:40:44         6400
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    SONiC.20191130.60
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by prsunny** [comment]
@rlhui , @abdosi for viz

**Comment by arlakshm** [comment]
This issue is fixed in this PR https://github.com/Azure/sonic-utilities/pull/1194. This PR is now included in 201911. Closing this issue.
