### ISSUE TITLE
[DPB] "[ERROR] Port breakout Failed" when configuring consecutive breakouts on ports with dependencies

### ISSUE THREAD

**Issue by slutati1536** [Azure/sonic-buildimage#6720]
**Description**

when configuring multiple breakouts one after the other with force on ports that have dependencies, we get the following error:
" [ERROR] Port breakout Failed!!! Opting Out
Failed to break out Port. Error:"
and the feature is stops working.

when configuring the breakout with 3 seconds delay this error doesn't reproduce.

**Steps to reproduce the issue:**

1. sudo config vlan add 1996
2. sudo config vlan member add --untagged 1996 Ethernet220
3. sudo config vlan member add --untagged 1996 Ethernet224
4. sudo config vlan member add --untagged 1996 Ethernet232
5. sudo config vlan member add --untagged 1996 Ethernet228
6. sudo config portchannel add PortChannel0001
7. sudo config portchannel member add PortChannel0001 Ethernet220
8. sudo config portchannel add PortChannel0002
9. sudo config portchannel member add PortChannel0002 Ethernet224
10. sudo config portchannel add PortChannel0003
11. sudo config portchannel member add PortChannel0003 Ethernet232
12. sudo config portchannel add PortChannel0004
13. sudo config portchannel member add PortChannel0004 Ethernet228
14. sudo config interface breakout Ethernet220 2x50G[40G,25G,10G,1G] -y -f
15. sudo config interface breakout Ethernet224 2x50G[40G,25G,10G,1G] -y -f
16. sudo config interface breakout Ethernet232 4x25G[10G,1G] -y -f
17. sudo config interface breakout Ethernet228 4x25G[10G,1G] -y -f

**Describe the results you received:**
```
sudo config interface breakout Ethernet220 2x50G[40G,25G,10G,1G] -y -f

Running Breakout Mode : 1x100G[50G,40G,25G,10G,1G] 
Target Breakout Mode : 2x50G[40G,25G,10G,1G]

Ports to be deleted : 
 {
    "Ethernet220": "100000"
}
Ports to be added : 
 {
    "Ethernet220": "50000",
    "Ethernet222": "50000"
}

After running Logic to limit the impact

Final list of ports to be deleted : 
 {
    "Ethernet220": "100000"
} 
Final list of ports to be added :  
 {
    "Ethernet220": "50000",
    "Ethernet222": "50000"
}
Loaded below Yang Models
['sonic-acl', 'sonic-breakout_cfg', 'sonic-crm', 'sonic-device_metadata', 'sonic-device_neighbor', 'sonic-extension', 'sonic-flex_counter', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-versions', 'sonic-vlan']
Note: Below table(s) have no YANG models:
PORTCHANNEL_MEMBER, FEATURE, SNMP_COMMUNITY, SNMP, TELEMETRY, 
Below Config can not be verified, It may cause harm to the system
 {
  "PORTCHANNEL_MEMBER": {
    "PortChannel0001|Ethernet220": {}
  }
}
Do you wish to Continue? [y/N]: y
Breakout process got successfully completed.
Please note loaded setting will be lost after system reboot. To preserve setting, run `config save`.
```
```
sudo config interface breakout Ethernet224 2x50G[40G,25G,10G,1G] -y -f

Running Breakout Mode : 1x100G[50G,40G,25G,10G,1G] 
Target Breakout Mode : 2x50G[40G,25G,10G,1G]

Ports to be deleted : 
 {
    "Ethernet224": "100000"
}
Ports to be added : 
 {
    "Ethernet224": "50000",
    "Ethernet226": "50000"
}

After running Logic to limit the impact

Final list of ports to be deleted : 
 {
    "Ethernet224": "100000"
} 
Final list of ports to be added :  
 {
    "Ethernet224": "50000",
    "Ethernet226": "50000"
}
Loaded below Yang Models
['sonic-acl', 'sonic-breakout_cfg', 'sonic-crm', 'sonic-device_metadata', 'sonic-device_neighbor', 'sonic-extension', 'sonic-flex_counter', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-versions', 'sonic-vlan']
Note: Below table(s) have no YANG models:
PORTCHANNEL_MEMBER, FEATURE, SNMP_COMMUNITY, SNMP, TELEMETRY, 
Below Config can not be verified, It may cause harm to the system
 {
  "PORTCHANNEL_MEMBER": {
    "PortChannel0002|Ethernet224": {}
  }
}
Do you wish to Continue? [y/N]: y
Breakout process got successfully completed.
Please note loaded setting will be lost after system reboot. To preserve setting, run `config save`.
```
```
 sudo config interface breakout Ethernet232 4x25G[10G,1G] -y -f

Running Breakout Mode : 1x100G[50G,40G,25G,10G,1G] 
Target Breakout Mode : 4x25G[10G,1G]

Ports to be deleted : 
 {
    "Ethernet232": "100000"
}
Ports to be added : 
 {
    "Ethernet232": "25000",
    "Ethernet233": "25000",
    "Ethernet234": "25000",
    "Ethernet235": "25000"
}

After running Logic to limit the impact

Final list of ports to be deleted : 
 {
    "Ethernet232": "100000"
} 
Final list of ports to be added :  
 {
    "Ethernet232": "25000",
    "Ethernet233": "25000",
    "Ethernet234": "25000",
    "Ethernet235": "25000"
}
Loaded below Yang Models
['sonic-acl', 'sonic-breakout_cfg', 'sonic-crm', 'sonic-device_metadata', 'sonic-device_neighbor', 'sonic-extension', 'sonic-flex_counter', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-versions', 'sonic-vlan']
Note: Below table(s) have no YANG models:
PORTCHANNEL_MEMBER, FEATURE, SNMP_COMMUNITY, SNMP, TELEMETRY, 
Below Config can not be verified, It may cause harm to the system
 {
  "PORTCHANNEL_MEMBER": {
    "PortChannel0003|Ethernet232": {}
  }
}
Do you wish to Continue? [y/N]: y
Breakout process got successfully completed.
Please note loaded setting will be lost after system reboot. To preserve setting, run `config save`.
```
```
sudo config interface breakout Ethernet228 4x25G[10G,1G] -y -f

Running Breakout Mode : 1x100G[50G,40G,25G,10G,1G] 
Target Breakout Mode : 4x25G[10G,1G]

Ports to be deleted : 
 {
    "Ethernet228": "100000"
}
Ports to be added : 
 {
    "Ethernet228": "25000",
    "Ethernet229": "25000",
    "Ethernet230": "25000",
    "Ethernet231": "25000"
}

After running Logic to limit the impact

Final list of ports to be deleted : 
 {
    "Ethernet228": "100000"
} 
Final list of ports to be added :  
 {
    "Ethernet228": "25000",
    "Ethernet229": "25000",
    "Ethernet230": "25000",
    "Ethernet231": "25000"
}
Loaded below Yang Models
['sonic-acl', 'sonic-breakout_cfg', 'sonic-crm', 'sonic-device_metadata', 'sonic-device_neighbor', 'sonic-extension', 'sonic-flex_counter', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-versions', 'sonic-vlan']
Note: Below table(s) have no YANG models:
PORTCHANNEL_MEMBER, FEATURE, SNMP_COMMUNITY, SNMP, TELEMETRY, 
Below Config can not be verified, It may cause harm to the system
 {
  "PORTCHANNEL_MEMBER": {
    "PortChannel0004|Ethernet228": {}
  }
}
Do you wish to Continue? [y/N]: [ERROR] Port breakout Failed!!! Opting Out
Failed to break out Port. Error: 
```

 ```
docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
5186211b1238        docker-snmp:latest                   "/usr/local/bin/supe…"   2 hours ago         Up 10 minutes                           snmp
679a797b171f        docker-sonic-mgmt-framework:latest   "/usr/local/bin/supe…"   2 hours ago         Up 2 hours                              mgmt-framework
083a11f2e0af        docker-sonic-telemetry:latest        "/usr/local/bin/supe…"   2 hours ago         Up 10 minutes                           telemetry
ecd170d5ccde        docker-router-advertiser:latest      "/usr/bin/docker-ini…"   2 hours ago         Up 10 minutes                           radv
8873344180b9        docker-dhcp-relay:latest             "/usr/bin/docker_ini…"   2 hours ago         Up 10 minutes                           dhcp_relay
0f316de35dad        docker-lldp:latest                   "/usr/bin/docker-lld…"   2 hours ago         Up 10 minutes                           lldp
669456fdba2b        docker-platform-monitor:latest       "/usr/bin/docker_ini…"   2 hours ago         Up 10 minutes                           pmon
69201a096836        docker-syncd-mlnx:latest             "/usr/local/bin/supe…"   2 hours ago         Up 10 minutes                           syncd
a4b6243a7a6c        docker-teamd:latest                  "/usr/local/bin/supe…"   2 hours ago         Up 10 minutes                           teamd
8c3846043159        docker-orchagent:latest              "/usr/bin/docker-ini…"   2 hours ago         Up 11 minutes                           swss
8e403bbcf2ab        docker-fpm-frr:latest                "/usr/bin/docker_ini…"   2 hours ago         Up 10 minutes                           bgp
211d9ce54b2d        docker-database:latest               "/usr/local/bin/dock…"   2 hours ago         Up 2 hours                              database
```
 
```
show interfaces status 
Traceback (most recent call last):
  File "/usr/local/bin/intfutil", line 521, in <module>
    main()
  File "/usr/local/bin/intfutil", line 513, in main
    interface_stat.display_intf_status()
  File "/usr/local/bin/intfutil", line 354, in display_intf_status
    self.get_intf_status()
  File "/usr/local/lib/python3.7/dist-packages/utilities_common/multi_asic.py", line 137, in wrapped_run_on_all_asics
    func(self,  *args, **kwargs)
  File "/usr/local/bin/intfutil", line 435, in get_intf_status
    self.portchannel_speed_dict = po_speed_dict(self.po_int_dict, self.db)
  File "/usr/local/bin/intfutil", line 249, in po_speed_dict
    interface_speed = '{}G'.format(interface_speed[:-3])
TypeError: 'NoneType' object is not subscriptable
```

**Describe the results you expected:**
the consecutive configuration of breakout should succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
SONiC Software Version: SONiC.dpb_qa_image.0-23134a64
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 23134a64
Build date: Fri Jan 15 08:52:11 UTC 2021
Built by: vadymh@r-build-sonic03

Platform: x86_64-mlnx_msn3420-r0
HwSKU: ACS-MSN3420
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2019X13878
Uptime: 11:37:06 up  2:02,  1 user,  load average: 0.76, 1.72, 1.89

Docker images:
REPOSITORY                    TAG                       IMAGE ID            SIZE
docker-syncd-mlnx             dpb_qa_image.0-23134a64   72cd4f0bad6c        540MB
docker-syncd-mlnx             latest                    72cd4f0bad6c        540MB
docker-sflow                  dpb_qa_image.0-23134a64   070e94ad45b1        465MB
docker-sflow                  latest                    070e94ad45b1        465MB
docker-snmp                   dpb_qa_image.0-23134a64   4513d9bbede9        436MB
docker-snmp                   latest                    4513d9bbede9        436MB
docker-dhcp-relay             dpb_qa_image.0-23134a64   e9f74defdbed        402MB
docker-dhcp-relay             latest                    e9f74defdbed        402MB
docker-teamd                  dpb_qa_image.0-23134a64   4432208a6469        463MB
docker-teamd                  latest                    4432208a6469        463MB
docker-nat                    dpb_qa_image.0-23134a64   b0f25765961f        466MB
docker-nat                    latest                    b0f25765961f        466MB
docker-router-advertiser      dpb_qa_image.0-23134a64   875949f0ef94        395MB
docker-router-advertiser      latest                    875949f0ef94        395MB
docker-platform-monitor       dpb_qa_image.0-23134a64   77567d9ce67c        683MB
docker-platform-monitor       latest                    77567d9ce67c        683MB
docker-lldp                   dpb_qa_image.0-23134a64   9bba135a3864        435MB
docker-lldp                   latest                    9bba135a3864        435MB
docker-database               dpb_qa_image.0-23134a64   ae8be589a33c        394MB
docker-database               latest                    ae8be589a33c        394MB
docker-sonic-mgmt-framework   dpb_qa_image.0-23134a64   9f7fe89d1421        608MB
docker-sonic-mgmt-framework   latest                    9f7fe89d1421        608MB
docker-orchagent              dpb_qa_image.0-23134a64   5928b24d51e3        481MB
docker-orchagent              latest                    5928b24d51e3        481MB
docker-macsec                 dpb_qa_image.0-23134a64   b255f6b0ccf1        466MB
docker-macsec                 latest                    b255f6b0ccf1        466MB
docker-sonic-telemetry        dpb_qa_image.0-23134a64   4e502f1867fd        469MB
docker-sonic-telemetry        latest                    4e502f1867fd        469MB
docker-fpm-frr                dpb_qa_image.0-23134a64   684115a1f6cc        480MB
docker-fpm-frr                latest                    684115a1f6cc        480MB

```

**Attach debug file `sudo generate_dump`:**
    
[dpb_error_consective_breakout.txt](https://github.com/Azure/sonic-buildimage/files/5943400/dpb_error_consective_breakout.txt)

**Comment by zhenggen-xu** [comment]
Can you verify this after https://github.com/Azure/sonic-buildimage/pull/7020 ? @slutati1536
