### ISSUE TITLE
Build break for 201911 branch

### ISSUE THREAD

**Issue by caizhenghui-juniper** [Azure/sonic-buildimage#6778]
#### Description
Build break for 201911 branch

#### Steps to reproduce the issue:
1. Try to build any target for 201911 branch with SNMP enabled.

#### Describe the results you received:
Build failure with 
distutils.errors.DistutilsError: Setup script exited with error: package directory 'find_namespace:' does not exist
When building target/python-wheels/asyncsnmp-2.1.0-py3-none-any.whl

#### Describe the results you expected:
Build successful.

#### Output of `show version`:

```
(paste your output here)
```

**Comment by kktheballer** [comment]
Hi, am experiencing this same issue also. Any suggestions would be appreciated

Traceback:
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    'Programming Language :: Python :: 3.5',
  File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 317, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 440, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 699, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 725, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 906, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1145, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1133, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
**_distutils.errors.DistutilsError: Setup script exited with error: package directory 'find_namespace:' does not exist
[  FAIL LOG END  ] [ target/python-wheels/asyncsnmp-2.1.0-py3-none-any.whl ]
slave.mk:465: recipe for target 'target/python-wheels/asyncsnmp-2.1.0-py3-none-any.whl' failed
make: *** [target/python-wheels/asyncsnmp-2.1.0-py3-none-any.whl] Error 1
make[1]: *** [Makefile.work:202: target/sonic-mellanox.bin] Error 2
make[1]: Leaving directory '/data/build/workspace/Build/mellanox/Buildimage-mlnx-all-internal-SAI-migration'
make: *** [Makefile:8: target/sonic-mellanox.bin] Error 2
Build step 'Execute shell' marked build as failure_**

**Comment by abdosi** [comment]
Fixed by https://github.com/Azure/sonic-buildimage/pull/6800
