### ISSUE TITLE
Traceback after "show interface status" command if LAG configured

### ISSUE THREAD

**Issue by Hedgehog-Guru** [Azure/sonic-buildimage#6816]
**Description**
After the reboot and config reload command "show interface status" provide Traceback instead for empty interface list before them loaded. It is reproducible 1:2 times.

**Steps to reproduce the issue**
1) Configure LAG interfaces:
```
config portchannel add PortChannel0001
config portchannel add PortChannel0002
```
2) Configure speed on 2 interfaces:
```
config int speed Ethernet80 10000
config int speed Ethernet88 10000
```
3) Configure LAG membership and save configuration:
```
config portchannel mem add PortChannel000 Ethernet80
config portchannel mem add PortChannel0001 Ethernet80
config save -y
```
4) Reboot the switch:
```
sudo reboot
```
5) Do configuration reload on the switch:
```
config reload -y
```

**Describe the results you received**
Traceback received:
```
root@sonic:/home/admin# show int status
Traceback (most recent call last):
  File "/usr/local/bin/intfutil", line 521, in <module>
    main()
  File "/usr/local/bin/intfutil", line 513, in main
    interface_stat.display_intf_status()
  File "/usr/local/bin/intfutil", line 354, in display_intf_status
    self.get_intf_status()
  File "/usr/local/lib/python3.7/dist-packages/utilities_common/multi_asic.py", line 137, in wrapped_run_on_all_asics
    func(self,  *args, **kwargs)
  File "/usr/local/bin/intfutil", line 435, in get_intf_status
    self.portchannel_speed_dict = po_speed_dict(self.po_int_dict, self.db)
  File "/usr/local/bin/intfutil", line 249, in po_speed_dict
    interface_speed = '{}G'.format(interface_speed[:-3])
TypeError: 'NoneType' object is not subscriptable
```

**Describe the results you expected**
The output of the command "show interface status" should not provide Traceback

**Output of show version**
```
SONiC Software Version: SONiC.SONIC.202012.10-d26a4af_Internal
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: d26a4aff
Build date: Thu Feb  4 15:28:36 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci02

Platform: x86_64-mlnx_msn3800-r0
HwSKU: ACS-MSN3800
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1937X00565
Uptime: 10:55:32 up 7 min,  1 user,  load average: 3.28, 2.78, 1.38

Docker images:
REPOSITORY                    TAG                                IMAGE ID            SIZE
docker-syncd-mlnx             SONIC.202012.10-d26a4af_Internal   b0775c41d0d0        542MB
docker-syncd-mlnx             latest                             b0775c41d0d0        542MB
docker-snmp                   SONIC.202012.10-d26a4af_Internal   bf1942e39970        438MB
docker-snmp                   latest                             bf1942e39970        438MB
docker-teamd                  SONIC.202012.10-d26a4af_Internal   4b51426a4f11        408MB
docker-teamd                  latest                             4b51426a4f11        408MB
docker-sonic-mgmt-framework   SONIC.202012.10-d26a4af_Internal   c4ed2967823f        616MB
docker-sonic-mgmt-framework   latest                             c4ed2967823f        616MB
docker-nat                    SONIC.202012.10-d26a4af_Internal   6f83852abace        411MB
docker-nat                    latest                             6f83852abace        411MB
docker-router-advertiser      SONIC.202012.10-d26a4af_Internal   d1c9b2a3ba6d        398MB
docker-router-advertiser      latest                             d1c9b2a3ba6d        398MB
docker-platform-monitor       SONIC.202012.10-d26a4af_Internal   2f9ba3b87a75        689MB
docker-platform-monitor       latest                             2f9ba3b87a75        689MB
docker-lldp                   SONIC.202012.10-d26a4af_Internal   57b6b48acc19        437MB
docker-lldp                   latest                             57b6b48acc19        437MB
docker-database               SONIC.202012.10-d26a4af_Internal   0c698fd3d04f        397MB
docker-database               latest                             0c698fd3d04f        397MB
docker-orchagent              SONIC.202012.10-d26a4af_Internal   86241aa41334        425MB
docker-orchagent              latest                             86241aa41334        425MB
docker-dhcp-relay             SONIC.202012.10-d26a4af_Internal   5fa3d131c72f        404MB
docker-dhcp-relay             latest                             5fa3d131c72f        404MB
docker-sonic-telemetry        SONIC.202012.10-d26a4af_Internal   36d5740d7971        471MB
docker-sonic-telemetry        latest                             36d5740d7971        471MB
docker-fpm-frr                SONIC.202012.10-d26a4af_Internal   a34711f7665f        425MB
docker-fpm-frr                latest                             a34711f7665f        425MB
docker-sflow                  SONIC.202012.10-d26a4af_Internal   166cfe57ddd3        408MB
docker-sflow                  latest                             166cfe57ddd3        408MB
```
Sysdump:
[sonic_dump_r-qa-sw-eth-2322_20210212_105159.tar.gz](https://github.com/Azure/sonic-buildimage/files/6000859/sonic_dump_r-qa-sw-eth-2322_20210212_105159.tar.gz)

**Comment by anshuv-mfst** [comment]
Issue triage meeting 3/3: seems to be fixed by #1442
