### ISSUE TITLE
warmboot error reported when checking WARM_RESTART_ENABLE_TABLE

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#7015]
#### Steps to reproduce the issue:
1. Cold reboot the DUT
2. Warm reboot
3. Errors are reported on stdout as below

#### Describe the results you received:
```
admin@str-s6100-acs-2:~$ sudo warm-reboot -vvv
Traceback (most recent call last):
  File "/usr/local/bin/sonic-db-cli", line 131, in <module>
    main()
  File "/usr/local/bin/sonic-db-cli", line 114, in main
    execute_cmd(args.db_or_op, args.cmd, args.namespace, args.unixsocket)
  File "/usr/local/bin/sonic-db-cli", line 73, in execute_cmd
    resp = client.execute_command(*cmd)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'hget' command
Thu 11 Mar 2021 02:46:17 AM UTC Saving counters folder before warmboot...
Thu 11 Mar 2021 02:46:20 AM UTC Pausing orchagent ...
Thu 11 Mar 2021 02:46:20 AM UTC Collecting logs to check ssd health before warm-reboot...
Thu 11 Mar 2021 02:46:20 AM UTC Stopping nat ...
Dumping conntrack entries failed
Error response from daemon: Cannot kill container: nat: No such container: nat
Thu 11 Mar 2021 02:46:20 AM UTC Stopped nat ...
Thu 11 Mar 2021 02:46:20 AM UTC Stopping radv service...
Thu 11 Mar 2021 02:46:21 AM UTC Stopped radv service...
Thu 11 Mar 2021 02:46:21 AM UTC Stopping bgp ...
Thu 11 Mar 2021 02:46:26 AM UTC Stopped bgp ...
Thu 11 Mar 2021 02:46:26 AM UTC Stopping sflow ...
Thu 11 Mar 2021 02:46:26 AM UTC Stopped sflow ...
Thu 11 Mar 2021 02:46:29 AM UTC Stopping swss service ...
Thu 11 Mar 2021 02:46:30 AM UTC Stopped swss service ...
Thu 11 Mar 2021 02:46:30 AM UTC Initialize pre-shutdown ...
Thu 11 Mar 2021 02:46:30 AM UTC Requesting pre-shutdown ...
Thu 11 Mar 2021 02:46:30 AM UTC Waiting for pre-shutdown ...
Thu 11 Mar 2021 02:46:31 AM UTC Pre-shutdown succeeded ...
Thu 11 Mar 2021 02:46:31 AM UTC Backing up database ...
Thu 11 Mar 2021 02:46:32 AM UTC Stopping teamd ...
Thu 11 Mar 2021 02:46:39 AM UTC Stopped teamd ...
Thu 11 Mar 2021 02:46:39 AM UTC Stopping syncd ...
Thu 11 Mar 2021 02:46:51 AM UTC Stopped syncd ...
Thu 11 Mar 2021 02:46:51 AM UTC Stopping all remaining containers ...
Thu 11 Mar 2021 02:46:53 AM UTC Stopped all remaining containers ...
Thu 11 Mar 2021 02:46:55 AM UTC updating ssd fw forwarm-reboot
Thu 11 Mar 2021 02:46:55 AM UTC Enabling Watchdog before warm-reboot
Watchdog armed for 180 seconds
Thu 11 Mar 2021 02:46:56 AM UTC Running x86_64-dell_s6100_c2538-r0 specific plugin...
Thu 11 Mar 2021 02:46:56 AM UTC Rebooting with /sbin/kexec -e to SONiC-OS-HEAD.487-377ea1a2 ...
```

#### Describe the results you expected:
`sonic-db-cli` errors should not be reported during warm-reboot

#### Output of `show version`:
```
$ show ver

SONiC Software Version: SONiC.HEAD.487-377ea1a2
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: 377ea1a2
Build date: Wed Mar 10 20:37:22 UTC 2021
Built by: johnar@jenkins-worker-22
```

**Comment by vaibhavhd** [comment]
This issue will not be seen in consecutive warmboot.
This is seen because the table contains no keys after cold reboot, and an empty key check should be added:

Repro, and cause:
```
admin@str-s6100-acs-2:~$ sonic-db-cli STATE_DB keys "WARM_RESTART_ENABLE_TABLE|*"
admin@str-s6100-acs-2:~$ 

$ sonic-db-cli STATE_DB keys "WARM_RESTART_ENABLE_TABLE|*" | while read key ; do echo "$(sonic-db-cli STATE_DB hget $key enable)"; done
Traceback (most recent call last):
  File "/usr/local/bin/sonic-db-cli", line 131, in <module>
    main()
  File "/usr/local/bin/sonic-db-cli", line 114, in main
    execute_cmd(args.db_or_op, args.cmd, args.namespace, args.unixsocket)
  File "/usr/local/bin/sonic-db-cli", line 73, in execute_cmd
    resp = client.execute_command(*cmd)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'hget' command
```

A check for empty keys should be put before doing hget
