### ISSUE TITLE
systemd segfault on switch boot

### ISSUE THREAD

**Issue by robocoder99** [Azure/sonic-buildimage#7179]
#### Description
Systemd was observed to crash on the boot of a Mellanox MSN2100 switch running SONiC 202012. During boot it reports a segfault and from that point no further sonic services / containers are able to start. 

It is worth noting that the segfault was immediately preceded by starting the `what-just-happened.timer` unit.

Here are the adjacent syslogs...
```
Mar 26 21:22:11.446462 r-bulldog-02 INFO /hostcfgd: Running cmd: 'sudo systemctl start what-just-happened.timer'
Mar 26 21:22:11.500378 r-bulldog-02 INFO systemd[1]: Started Delays what-just-happened container until SONiC has started.
Mar 26 21:22:11.768262 r-bulldog-02 INFO bgp#supervisord 2021-03-26 21:22:11,732 INFO spawned: 'zebra' with pid 33
Mar 26 21:22:11.768262 r-bulldog-02 INFO bgp#supervisord 2021-03-26 21:22:11,734 INFO success: zebra entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Mar 26 21:22:11.827598 r-bulldog-02 EMERG kernel: [  594.227984] systemd[1]: segfault at 358 ip 0000557256dd6442 sp 00007ffe0e364590 error 4 in systemd[557256d36000+b1000]
Mar 26 21:22:11.827636 r-bulldog-02 EMERG kernel: [  594.356311] Code: fd ff 41 89 c5 85 c0 0f 88 d1 00 00 00 48 8b 5c 24 10 48 85 db 0f 84 7d 02 00 00 4c 89 e7 e8 35 30 f6 ff 48 8b 53 08 48 8b 12 <48> 3b 82 58 03 00 00 0f 84 21 02 00 00 80 8b a5 00 00 00 01 48 8b
Mar 26 21:22:11.904300 r-bulldog-02 INFO bgp#supervisord 2021-03-26 21:22:11,897 INFO spawned: 'zsocket' with pid 34
Mar 26 21:22:11.904300 r-bulldog-02 INFO bgp#supervisord 2021-03-26 21:22:11,901 INFO success: zsocket entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Mar 26 21:22:11.939323 r-bulldog-02 INFO bgp#/supervisord: zebra 2021/03/26 21:22:11 ZEBRA: [EC 4043309111] Disabling MPLS support (no kernel support)
Mar 26 21:22:11.977146 r-bulldog-02 INFO bgp#root: It took 0.0167215 seconds to wait for zebra to be ready to accept connections
Mar 26 21:22:11.988025 r-bulldog-02 INFO bgp#supervisord 2021-03-26 21:22:11,980 INFO exited: zsocket (exit status 0; expected)
Mar 26 21:22:12.175365 r-bulldog-02 INFO bgp#supervisord 2021-03-26 21:22:12,169 INFO spawned: 'staticd' with pid 45
Mar 26 21:22:12.175365 r-bulldog-02 INFO bgp#supervisord 2021-03-26 21:22:12,171 INFO success: staticd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Mar 26 21:22:12.200265 r-bulldog-02 INFO bgp#supervisord 2021-03-26 21:22:12,196 INFO spawned: 'bgpd' with pid 46
Mar 26 21:22:12.200265 r-bulldog-02 INFO bgp#supervisord 2021-03-26 21:22:12,198 INFO success: bgpd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Mar 26 21:22:12.250444 r-bulldog-02 EMERG systemd[1]: Caught <SEGV>, dumped core as pid 21064.
Mar 26 21:22:12.250973 r-bulldog-02 EMERG systemd[1]: Freezing execution.
Mar 26 21:22:12.254599 r-bulldog-02 WARNING kernel: [  595.007554] systemd: 53 output lines suppressed due to ratelimiting
Mar 26 21:22:12.294203 r-bulldog-02 INFO networking[20897]: Failed to retrieve unit state: Connection reset by peer
Mar 26 21:22:12.295057 r-bulldog-02 INFO interfaces-config.sh[20480]: Warning! D-Bus connection terminated.
Mar 26 21:22:12.295218 r-bulldog-02 INFO interfaces-config.sh[20480]: Failed to wait for response: Connection reset by peer
Mar 26 21:22:12.299050 r-bulldog-02 INFO hostcfgd[20479]: Failed to start what-just-happened.timer: Connection reset by peer
Mar 26 21:22:12.299234 r-bulldog-02 INFO hostcfgd[20479]: See system logs and 'systemctl status what-just-happened.timer' for details.
Mar 26 21:22:12.302479 r-bulldog-02 ERR /hostcfgd: 'sudo systemctl start what-just-happened.timer' failed. RC: 1, output: None
Mar 26 21:22:12.302702 r-bulldog-02 ERR /hostcfgd: Feature 'what-just-happened.timer' failed to be  enabled and started
```

I have attached the systemd core dump and `show techsupport` to this issue. 

[systemd.1616793731.21064.core.gz](https://github.com/Azure/sonic-buildimage/files/6224334/systemd.1616793731.21064.core.gz)

[sonic_dump_r-bulldog-02_20210329_195332.tar.gz](https://github.com/Azure/sonic-buildimage/files/6224332/sonic_dump_r-bulldog-02_20210329_195332.tar.gz)

#### Steps to reproduce the issue:
This issue seems to occur with a very small probability on switch boot. Initially observed on a Mellanox MSN2100. No particular conditions have been observed to trigger this. 

#### Describe the results you received:
Systemd segfaults with:

```
[  594.227984] systemd[1]: segfault at 358 ip 0000557256dd6442 sp 00007ffe0e364590 error 4 in systemd[557256d36000+b1000]
```
This makes multiple services critical to sonic such as swss unable to start. 

#### Describe the results you expected:
No segfault.

#### Output of `show version`:

```
SONiC Software Version: SONiC.SONIC.202012.53-aee4892c_Internal
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: aee4892c
Build date: Thu Mar 25 07:17:58 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci03

Platform: x86_64-mlnx_msn2100-r0
HwSKU: ACS-MSN2100
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1851X13655
Uptime: 20:13:29 up 2 days, 23:01,  1 user,  load average: 1.12, 1.38, 1.59

Docker images:
REPOSITORY                    TAG                                 IMAGE ID            SIZE
docker-teamd                  SONIC.202012.53-aee4892c_Internal   1d73bce4fcd8        412MB
docker-teamd                  latest                              1d73bce4fcd8        412MB
docker-nat                    SONIC.202012.53-aee4892c_Internal   4b70ff56ef58        415MB
docker-nat                    latest                              4b70ff56ef58        415MB
docker-orchagent              SONIC.202012.53-aee4892c_Internal   b3ab4b23959b        431MB
docker-orchagent              latest                              b3ab4b23959b        431MB
docker-fpm-frr                SONIC.202012.53-aee4892c_Internal   8eedb2cefa34        431MB
docker-fpm-frr                latest                              8eedb2cefa34        431MB
docker-sflow                  SONIC.202012.53-aee4892c_Internal   f73678a4a5e4        413MB
docker-sflow                  latest                              f73678a4a5e4        413MB
docker-wjh                    202012.202012.0-e663b63             bbf69da66de2        441MB
docker-wjh                    latest                              bbf69da66de2        441MB
docker-platform-monitor       SONIC.202012.53-aee4892c_Internal   9431a24cce94        693MB
docker-platform-monitor       latest                              9431a24cce94        693MB
docker-syncd-mlnx             SONIC.202012.53-aee4892c_Internal   b435d0fb66dc        666MB
docker-syncd-mlnx             latest                              b435d0fb66dc        666MB
docker-snmp                   SONIC.202012.53-aee4892c_Internal   1186f8a7345a        442MB
docker-snmp                   latest                              1186f8a7345a        442MB
docker-sonic-mgmt-framework   SONIC.202012.53-aee4892c_Internal   f82c902ebc99        620MB
docker-sonic-mgmt-framework   latest                              f82c902ebc99        620MB
docker-router-advertiser      SONIC.202012.53-aee4892c_Internal   58926fcdf5f6        401MB
docker-router-advertiser      latest                              58926fcdf5f6        401MB
docker-lldp                   SONIC.202012.53-aee4892c_Internal   175e6dcfe231        441MB
docker-lldp                   latest                              175e6dcfe231        441MB
docker-database               SONIC.202012.53-aee4892c_Internal   586be7012094        401MB
docker-database               latest                              586be7012094        401MB
docker-sonic-telemetry        SONIC.202012.53-aee4892c_Internal   4232634fe32d        491MB
docker-sonic-telemetry        latest                              4232634fe32d        491MB
docker-dhcp-relay             SONIC.202012.53-aee4892c_Internal   06444d9dd53a        405MB
docker-dhcp-relay             latest                              06444d9dd53a        405MB
```

**Comment by anshuv-mfst** [comment]
Issue triage meeting 3/31: 
- Issue not consistently reproducible
- Confirm if issue is specific to platform (robocoder99 - please confirm and recreate in different DUT as well)
- Issue seen in 202012 image
- systemd doesnot have symbols loaded unlike other daemons. Need support for loading symbols for systemd

**Comment by robocoder99** [comment]
Was not able to reproduce on another platform. However, I do not think that indicates this is platform specific given the low frequency we see this problem at. 

I managed to compile the systemd symbols and load in the core dump and do a little more debugging. It was not all that fruitful. My findings are below....

Here is the backtrace from gdb
```
#0  0x00007f0f7df8ea97 in kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000557256de64f6 in crash (sig=11) at ../src/core/main.c:197
#2  <signal handler called>
#3  0x0000557256dd6442 in bus_job_track_sender (m=0x557257411ba0, j=0x557257442f40) at ../src/core/dbus-job.c:302
#4  bus_unit_queue_job (message=message@entry=0x557257411ba0, u=u@entry=0x5572574462a0, type=type@entry=JOB_START, mode=mode@entry=JOB_REPLACE, reload_if_possible=reload_if_possible@entry=false,
    error=error@entry=0x7ffe0e364720) at ../src/core/dbus-unit.c:1317
#5  0x0000557256dd6a0c in bus_unit_method_start_generic (message=0x557257411ba0, u=0x5572574462a0, job_type=JOB_START, reload_if_possible=<optimized out>, error=0x7ffe0e364720)
    at ../src/core/dbus-unit.c:374
#6  0x0000557256ddca00 in method_start_unit_generic (message=0x557257411ba0, m=0x5572572d8f60, job_type=JOB_START, reload_if_possible=<optimized out>, error=0x7ffe0e364720)
    at ../src/core/dbus-manager.c:546
#7  0x00007f0f7dd888c7 in method_callbacks_run (found_object=0x7ffe0e3647d7, require_fallback=<optimized out>, c=<optimized out>, m=0x557257411ba0, bus=0x55725746a230)
    at ../src/libsystemd/sd-bus/bus-objects.c:403
#8  object_find_and_run (bus=0x55725746a230, m=0x557257411ba0, p=<optimized out>, require_fallback=false, found_object=0x7ffe0e3647d7) at ../src/libsystemd/sd-bus/bus-objects.c:1266
#9  0x00007f0f7dd7f969 in bus_process_object (bus=0x55725746a230, m=0x557257411ba0) at ../src/libsystemd/sd-bus/bus-objects.c:1386
#10 0x00007f0f7dd74174 in process_message (m=0x557257411ba0, bus=0x55725746a230) at ../src/libsystemd/sd-bus/sd-bus.c:2703
#11 process_running (ret=0x0, priority=0, hint_priority=false, bus=0x55725746a230) at ../src/libsystemd/sd-bus/sd-bus.c:2745
#12 bus_process_internal (bus=bus@entry=0x55725746a230, hint_priority=hint_priority@entry=false, priority=priority@entry=0, ret=ret@entry=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:2963
#13 0x00007f0f7dd743ac in sd_bus_process (bus=bus@entry=0x55725746a230, ret=ret@entry=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:2990
#14 0x00007f0f7dd74478 in io_callback (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>, s=<optimized out>, fd=<optimized out>, revents=<optimized out>,
    userdata=<optimized out>) at ../src/libsystemd/sd-bus/sd-bus.c:3341
#15 0x00007f0f7dd44e20 in source_dispatch (s=s@entry=0x5572573fef10) at ../src/libsystemd/sd-event/sd-event.c:2821
#16 0x00007f0f7dd45111 in sd_event_dispatch (e=e@entry=0x5572572d9550) at ../src/libsystemd/sd-event/sd-event.c:3234
#17 0x00007f0f7dd452d8 in sd_event_run (e=0x5572572d9550, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:3291
#18 0x0000557256de3fe3 in manager_loop (m=0x5572572d8f60) at ../src/core/manager.c:2906
#19 invoke_main_loop (m=0x5572572d8f60, ret_reexecute=<optimized out>, ret_retval=<optimized out>, ret_shutdown_verb=0x7ffe0e364b88, ret_fds=0x7ffe0e364b78, ret_switch_root_dir=0x7ffe0e364b98,
    ret_switch_root_init=0x7ffe0e364b90, ret_error_message=0x7ffe0e364b80) at ../src/core/main.c:1842
#20 0x0000557256d3bc06 in main (argc=1, argv=<optimized out>) at ../src/core/main.c:2625
```

The cause of the segfault is that the job in question being queued does not have a valid unit associated with it. The system attempted to get the manager of the unit `j->unit->manager->api_bus` which is NULL (0x0) and is why we saw a segfault when attempting to access the expected offset of api_bus. 

Looking through the code, I cannot find a good reason behind this occurring. What is even more troubling is that the job in question has been installed and queued to start (as can be seen by the existence of `begin_usec`) however the job claims to not be installed. Based on the code the only time this condition could exist is if the job were also uninstalled, however the job is still in the JOB_WAITING state and it also has an invalid return code (176).

Dump of the job....
```
$8 = {manager = 0x557257360170, unit = 0x5572573be970, transaction_next = 0x0, transaction_prev = 0x0, run_queue_next = 0x0, run_queue_prev = 0x0, dbus_queue_next = 0x0, dbus_queue_prev = 0x0,
  gc_queue_next = 0x0, gc_queue_prev = 0x0, subject_list = 0x0, object_list = 0x0, marker = 0x0, generation = 2, id = 2039, type = JOB_START, state = JOB_WAITING, timer_event_source = 0x0,
  begin_usec = 593968968, begin_running_usec = 0, bus_track = 0x0, deserialized_clients = 0x0, result = 176, installed = false, in_run_queue = false, matters_to_anchor = false, in_dbus_queue = false,
  sent_dbus_new_signal = false, ignore_order = false, irreversible = false, in_gc_queue = false, ref_by_private_bus = false}
```

Dump of the job's unit...
```
$9 = {manager = 0x0, type = 1169, load_state = UNIT_STUB, merged_into = 0x557257442f30, id = 0x7f0f7e112ca0 "\300\325IWrU", instance = 0x0, names = 0x0, dependencies = {0x0 <repeats 22 times>},
  requires_mounts_for = 0x0, description = 0x0, documentation = 0x0, fragment_path = 0x0, source_path = 0x0, dropin_paths = 0x0, fragment_mtime = 0, source_mtime = 0, dropin_mtime = 0,
  transient_file = 0x0, job = 0x0, nop_job = 0x0, match_bus_slot = 0x0, bus_track = 0x0, deserialized_refs = 0x0, job_timeout = 0, job_running_timeout = 0, job_running_timeout_set = false,
  job_timeout_action = EMERGENCY_ACTION_NONE, job_timeout_reboot_arg = 0x0, refs_by_target = 0x0, conditions = 0x0, asserts = 0x0, condition_timestamp = {realtime = 0, monotonic = 0}, assert_timestamp = {
    realtime = 0, monotonic = 0}, state_change_timestamp = {realtime = 0, monotonic = 0}, inactive_exit_timestamp = {realtime = 0, monotonic = 0}, active_enter_timestamp = {realtime = 0, monotonic = 0},
  active_exit_timestamp = {realtime = 0, monotonic = 0}, inactive_enter_timestamp = {realtime = 0, monotonic = 0}, slice = {source = 0x0, target = 0x0, refs_by_target_next = 0x0,
    refs_by_target_prev = 0x0}, units_by_type_next = 0x0, units_by_type_prev = 0x0, load_queue_next = 0x0, load_queue_prev = 0x0, dbus_queue_next = 0x0, dbus_queue_prev = 0x0, cleanup_queue_next = 0x0,
  cleanup_queue_prev = 0x0, gc_queue_next = 0x0, gc_queue_prev = 0x0, cgroup_realize_queue_next = 0x0, cgroup_realize_queue_prev = 0x0, cgroup_empty_queue_next = 0x0, cgroup_empty_queue_prev = 0x0,
  target_deps_queue_next = 0x0, target_deps_queue_prev = 0x0, stop_when_unneeded_queue_next = 0x0, stop_when_unneeded_queue_prev = 0x0, pids = 0x0, sigchldgen = 0, notifygen = 0, gc_marker = 0,
  load_error = 0, start_limit = {interval = 0, begin = 0, burst = 0, num = 0}, start_limit_action = EMERGENCY_ACTION_NONE, success_action = EMERGENCY_ACTION_NONE, failure_action = EMERGENCY_ACTION_NONE,
  success_action_exit_status = 0, failure_action_exit_status = 0, reboot_arg = 0x0, auto_stop_ratelimit = {interval = 0, begin = 0, burst = 0, num = 0}, ref_uid = 0, ref_gid = 0,
  unit_file_state = UNIT_FILE_ENABLED, unit_file_preset = 0, cpu_usage_base = 0, cpu_usage_last = 0, cgroup_path = 0x0, cgroup_realized_mask = 0, cgroup_enabled_mask = 0, cgroup_invalidated_mask = 0,
  cgroup_members_mask = 0, cgroup_inotify_wd = 0, bpf_device_control_installed = 0x0, ip_accounting_ingress_map_fd = 0, ip_accounting_egress_map_fd = 0, ipv4_allow_map_fd = 0, ipv6_allow_map_fd = 0,
  ipv4_deny_map_fd = 0, ipv6_deny_map_fd = 0, ip_bpf_ingress = 0x0, ip_bpf_ingress_installed = 0x0, ip_bpf_egress = 0x0, ip_bpf_egress_installed = 0x0, ip_accounting_extra = {0, 0, 0, 0},
  rewatch_pids_event_source = 0x0, on_failure_job_mode = JOB_FAIL, collect_mode = COLLECT_INACTIVE, invocation_id = {bytes = "\000\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377", qwords = {
      0, 18446744073709551615}}, invocation_id_string = '\377' <repeats 33 times>, stop_when_unneeded = 255, default_dependencies = 255, refuse_manual_start = 255, refuse_manual_stop = 255,
  allow_isolate = 255, ignore_on_isolate = 255, condition_result = 255, assert_result = 255, transient = 255, perpetual = 255, in_load_queue = true, in_dbus_queue = true, in_cleanup_queue = true,
  in_gc_queue = true, in_cgroup_realize_queue = true, in_cgroup_empty_queue = true, in_target_deps_queue = true, in_stop_when_unneeded_queue = true, sent_dbus_new_signal = true, in_audit = true,
  on_console = true, cgroup_realized = true, cgroup_members_mask_valid = true, reset_accounting = true, start_limit_hit = true, coldplugged = true, bus_track_add = true, exported_invocation_id = true,
  exported_log_level_max = true, exported_log_extra_fields = true, exported_log_rate_limit_interval = true, exported_log_rate_limit_burst = true, last_section_private = -1}
```

Perhaps someone better versed in systemd could take a look here.  

Overall I'm not optimistic about locating the root cause without reproducing it and attaching gdb to a live system (which we have found very difficult to do). 

My personal suspicion here is a memory issue due to the invalid return on the job. There are also a few locations in the core dump which are showing as invalid as well. Either systemd has a leak where it is overwriting its own memory or we may have had a error in the hardware causing an overwrite.

Aforementioned errors...
```
(gdb) print *j->manager
$12 = {units = 0x0, units_by_invocation_id = 0x401, jobs = 0x5572572f0700, units_by_type = {0x557257442f30, 0x0, 0x0, 0x5572572f0750, 0x5572572f0780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, load_queue = 0x0,
  run_queue = 0x0, dbus_unit_queue = 0x0, dbus_job_queue = 0x0, cleanup_queue = 0x0, gc_unit_queue = 0x0, gc_job_queue = 0x0, cgroup_realize_queue = 0x0, cgroup_empty_queue = 0x0, target_deps_queue = 0x0,
  stop_when_unneeded_queue = 0x0, event = 0x0, watch_pids = 0x0, startup_units = 0x0, failed_units = 0x0, run_queue_event_source = 0x0, notify_socket = 0x0, notify_fd = 0, notify_event_source = 0x0,
  cgroups_agent_fd = 0, cgroups_agent_event_source = 0x0, signal_fd = 0, signal_event_source = 0x0, sigchld_event_source = 0x0, time_change_fd = 0, time_change_event_source = 0x0,
  timezone_change_event_source = 0x0, jobs_in_progress_event_source = 0x0, user_lookup_fds = {0, 0}, user_lookup_event_source = 0x0, sync_bus_names_event_source = 0x0, unit_file_scope = UNIT_FILE_SYSTEM,
  lookup_paths = {search_path = 0x0, persistent_config = 0x0, runtime_config = 0x0, persistent_attached = 0x0, runtime_attached = 0xd <error: Cannot access memory at address 0xd>,
    generator = 0x5572572f0710 "\240,\021~\017\177", generator_early = 0x0, generator_late = 0x0, transient = 0x0, persistent_control = 0x7a <error: Cannot access memory at address 0x7a>,
    runtime_control = 0x55 <error: Cannot access memory at address 0x55>, root_dir = 0x55 <error: Cannot access memory at address 0x55>, temporary_dir = 0x0}, unit_path_cache = 0x55725734a940,
  transient_environment = 0x0, client_environment = 0x55, runtime_watchdog = 0, shutdown_watchdog = 86, timestamps = {{realtime = 0, monotonic = 8589934591}, {realtime = 0, monotonic = 0}, {realtime = 0,
      monotonic = 0}, {realtime = 0, monotonic = 0}, {realtime = 0, monotonic = 0}, {realtime = 0, monotonic = 93949577260608}, {realtime = 0, monotonic = 0}, {realtime = 85, monotonic = 0}, {
      realtime = 0, monotonic = 0}, {realtime = 0, monotonic = 0}, {realtime = 0, monotonic = 0}, {realtime = 0, monotonic = 0}, {realtime = 0, monotonic = 93949577542096}, {realtime = 0, monotonic = 0}, {
      realtime = 0, monotonic = 0}, {realtime = 2, monotonic = 0}, {realtime = 0, monotonic = 0}, {realtime = 0, monotonic = 0}}, device_monitor = 0x0, devices_by_sysfs = 0x0, mount_monitor = 0x0,
  mount_event_source = 0x0, proc_swaps = 0x0, swap_event_source = 0x0, swaps_by_devnode = 0x0, api_bus = 0x0, system_bus = 0x0, private_buses = 0x101046c, private_listen_fd = 0,
  private_listen_event_source = 0x91, subscribed = 0x7f0f7e112ca0, deserialized_subscribed = 0x5572572f0700, pending_reload_message = 0x19006f0101, watch_bus = 0x6572662f67726f2f,
  send_reloading_done = 101, current_job_id = 1886352491, default_unit_job_id = 1937339183, dev_autofs_fd = 1684890996, cgroup_unit = 0x31, cgroup_supported = 7536898,
  cgroup_root = 0x656572662e67726f <error: Cannot access memory at address 0x656572662e67726f>, cgroup_inotify_fd = 1802724708, cgroup_inotify_event_source = 0x31646d6574737973,
  cgroup_inotify_wd_unit = 0x726567616e614d2e, cgroup_empty_event_source = 0x0, pin_cgroupfs_fd = 7536899, gc_marker = 10, etc_localtime_mtime = 8534160100831686474, etc_localtime_accessible = true,
  objective = -14, dispatching_load_queue = true, taint_usr = false, ready_sent = false, taint_logged = false, sysctl_pid_max_changed = true, test_run_flags = 12, return_value = 0 '\000',
  show_status = 1936684291, confirm_spawn = 0x400 <error: Cannot access memory at address 0x400>, no_console_output = 32, service_watchdogs = false, default_std_output = EXEC_OUTPUT_INHERIT,
  default_std_error = 1701669236, default_restart_usec = 27981945731575662, default_timeout_start_usec = 64, default_timeout_stop_usec = 257, default_start_limit_interval = 4294967296,
  default_start_limit_burst = 1462605136, default_cpu_accounting = 114, default_memory_accounting = 85, default_io_accounting = false, default_blockio_accounting = false, default_tasks_accounting = 160,
  default_ip_accounting = 98, default_tasks_max = 0, default_timer_accuracy_usec = 93949577790848, original_log_level = 227, original_log_target = LOG_TARGET_CONSOLE, log_level_overridden = false,
  log_target_overridden = false, rlimit = {0xffffffffffffffff, 0x0, 0x0, 0x0, 0x5572573fef10, 0x0, 0x557256d82be0 <timer_dispatch>, 0x22f64cae, 0x3938700, 0x100000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
  n_reloading = 0, n_installed_jobs = 0, n_failed_jobs = 0, n_running_jobs = 0, n_on_console = 0, jobs_in_progress_iteration = 0, have_ask_password = 0, ask_password_inotify_fd = 0,
  ask_password_event_source = 0x0, idle_pipe = {0, 0, 0, 0}, idle_pipe_event_source = 0x0, switch_root = 0x41 <error: Cannot access memory at address 0x41>,
  switch_root_init = 0x557257372910 "/org/freedesktop/systemd1/unit", units_requiring_mounts_for = 0x557257467fa0, polkit_registry = 0x557256df6e8d, dynamic_users = 0x55725741c220, uid_refs = 0x0,
  gid_refs = 0x557256e6c630 <bus_exec_vtable+1872>, exec_runtime_by_id = 0x0, ctrl_alt_del_ratelimit = {interval = 65, begin = 93949577865488, burst = 1464237984, num = 21874},
  cad_burst_action = 1457486903, unit_log_field = 0x55725741c220 "\200\226EWrU", unit_log_format_string = 0x0, invocation_log_field = 0x557256e6c660 <bus_exec_vtable+1920> "P\020",
  invocation_log_format_string = 0x0, first_boot = 81, prefix = {0x557257372910 "/org/freedesktop/systemd1/unit", 0x557257467fa0 "org.freedesktop.systemd1.Socket", 0x557256df88f9 "OOMScoreAdjust",
    0x55725741c220 "\200\226EWrU", 0x0}, sigchldgen = 1457964688, notifygen = 21874}
```
