### ISSUE TITLE
[Functional] initialize without ports on config_db.json - swss (portsyncd) failure

### ISSUE THREAD

**Issue by NoySa** [Azure/sonic-buildimage#7190]
#### Description
try to init with 0 ports on config_db.json leads to swss docker down (portsyncd failure)

manual testing. always reproduced. no degradation.

#### Steps to reproduce the issue:
1. Remove all ports from /etc/sonic/config_db.json from the PORT section
2. make sure no ports related configuration
3. reboot

#### Describe the results you received:
swss fails (portsyncd fails)

Warning appears on sonic shell after show commands (for example "show interfaces status"):
Warning: failed to retrieve PORT table from ConfigDB!

Errors on syslog:
Mar 30 11:52:53.936664 r-tigris-22 ERR swss#portsyncd: :- main: ConfigDB does not have port information, exiting...

Mar 30 12:51:43.874964 r-tigris-22 ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.7/dist-packages/ax_interface/mib.py", line 37, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 570, in reinit_data#012    _, _, _, self.oid_name_map = Namespace.get_sync_d_from_all_namespace(mibs.init_sync_d_interface_tables, self.db_conn)#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/__init__.py", line 563, in get_sync_d_from_all_namespace#012    ns_tuple = per_namespace_func(db_conn)#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/__init__.py", line 244, in init_sync_d_interface_tables#012    if_name_map_util, if_id_map_util = port_util.get_interface_oid_map(db_conn)#012  File "/usr/local/lib/python3.7/dist-packages/swsssdk/port_util.py", line 65, in get_interface_oid_map#012    if_name_map = db.get_all('COUNTERS_DB', 'COUNTERS_PORT_NAME_MAP', blocking=True)#012  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1588, in get_all#012    return dict(super(SonicV2Connector, self).get_all(db_name, _hash, blocking))#012  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1545, in get_all#012    return _swsscommon.SonicV2Connector_Native_get_all(self, db_name, _hash, blocking)#012RuntimeError: Key '{COUNTERS_PORT_NAME_MAP}' unavailable in database '{COUNTERS_DB}'

#### Describe the results you expected:
no errors. swss docker is stable

#### Output of `show version`:
SONiC Software Version: SONiC.SONIC.202012.52-50e4cc15_Internal
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: 50e4cc15
Build date: Tue Mar 23 10:25:18 UTC 2021
Built by: sw-r2d2-bot@r-build-sonic-ci03

Platform: x86_64-mlnx_msn3800-r0
HwSKU: ACS-MSN3800
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1937X00537
Uptime: 13:07:08 up 54 min,  1 user,  load average: 1.25, 1.58, 1.60

Docker images:
REPOSITORY                    TAG                                 IMAGE ID            SIZE
docker-teamd                  SONIC.202012.52-50e4cc15_Internal   e404a957f154        412MB
docker-teamd                  latest                              e404a957f154        412MB
docker-nat                    SONIC.202012.52-50e4cc15_Internal   060b170d465d        415MB
docker-nat                    latest                              060b170d465d        415MB
docker-platform-monitor       SONIC.202012.52-50e4cc15_Internal   866984132b08        693MB
docker-platform-monitor       latest                              866984132b08        693MB
docker-orchagent              SONIC.202012.52-50e4cc15_Internal   2da47edc09a5        431MB
docker-orchagent              latest                              2da47edc09a5        431MB
docker-fpm-frr                SONIC.202012.52-50e4cc15_Internal   12a1712803da        431MB
docker-fpm-frr                latest                              12a1712803da        431MB
docker-sflow                  SONIC.202012.52-50e4cc15_Internal   6205a14bb9df        413MB
docker-sflow                  latest                              6205a14bb9df        413MB
docker-syncd-mlnx             SONIC.202012.52-50e4cc15_Internal   f5386fd640ba        666MB
docker-syncd-mlnx             latest                              f5386fd640ba        666MB
docker-dhcp-relay             SONIC.202012.52-50e4cc15_Internal   cb5a7323aeb9        409MB
docker-dhcp-relay             latest                              cb5a7323aeb9        409MB
docker-snmp                   SONIC.202012.52-50e4cc15_Internal   8df6c0d14af7        438MB
docker-snmp                   latest                              8df6c0d14af7        438MB
docker-sonic-mgmt-framework   SONIC.202012.52-50e4cc15_Internal   4881ef3e8dc7        616MB
docker-sonic-mgmt-framework   latest                              4881ef3e8dc7        616MB
docker-router-advertiser      SONIC.202012.52-50e4cc15_Internal   7e59764069ca        398MB
docker-router-advertiser      latest                              7e59764069ca        398MB
docker-lldp                   SONIC.202012.52-50e4cc15_Internal   33da46fe8a7f        438MB
docker-lldp                   latest                              33da46fe8a7f        438MB
docker-database               SONIC.202012.52-50e4cc15_Internal   e65ccc177592        398MB
docker-database               latest                              e65ccc177592        398MB
docker-sonic-telemetry        SONIC.202012.52-50e4cc15_Internal   5e079afb02ab        487MB
docker-sonic-telemetry        latest                              5e079afb02ab        487MB

**Comment by NoySa** [comment]
[files.zip](https://github.com/Azure/sonic-buildimage/files/6229256/files.zip)

**Comment by anshuv-mfst** [comment]
@dprital - could you please look into the issue, thanks.

**Comment by liorghub** [comment]
@anshuv-mfst 
@NoySa 
@dprital 

The fix is merged, see https://github.com/Azure/sonic-swss/pull/1808.
Please close this bug.
