### ISSUE TITLE
removing an ip from interface with multiple, SONiC Cli removes all ips from interface

### ISSUE THREAD

**Issue by fire-ant** [Azure/sonic-buildimage#7365]
#### Description

When running the docker-sonic-vs docker image taken from https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-all/lastSuccessfulBuild/artifact/target/docker-sonic-vs.gz in a docker I noticed that when an interface is given multiple IP's it is possible to remove the high addressed ip by removing the lower address ip. Whilst this is an unexpected and unlikely edge case I want to understand if its expected as it could lead to confusion. As its a container inside a vm it will take a little more effort to extract logs (or I can script their upload to this ticket), but I think the commands should suffice for reproduction purposes.
#### Steps to reproduce the issue:
1. root@s1:/# show ip int
Interface    Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
-----------  --------  -------------------  ------------  --------------  -------------
Ethernet0              192.168.1.1/24       up/up         N/A             N/A
eth0                   172.20.20.2/24       up/up         N/A             N/A
lo                     127.0.0.1/8          up/up         N/A             N/A
2. root@s1:/# config interface ip add Ethernet0 192.168.1.2/24
3. root@s1:/# config interface ip remove Ethernet0 192.168.1.1/24
4. root@s1:/# show ip int
Interface    Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
-----------  --------  -------------------  ------------  --------------  -------------
eth0                   172.20.20.2/24       up/up         N/A             N/A
lo                     127.0.0.1/8          up/up         N/A             N/A
5. root@s1:/# config interface ip add Ethernet0 192.168.1.1/24
6. root@s1:/# show ip int
Interface    Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
-----------  --------  -------------------  ------------  --------------  -------------
Ethernet0              192.168.1.1/24       up/up         N/A             N/A
eth0                   172.20.20.2/24       up/up         N/A             N/A
lo                     127.0.0.1/8          up/up         N/A             N/A
7. root@s1:/# config interface ip add Ethernet0 192.168.1.2/24
8. root@s1:/# show ip int
Interface    Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
-----------  --------  -------------------  ------------  --------------  -------------
Ethernet0              192.168.1.1/24       up/up         N/A             N/A
                       192.168.1.2/24       up/up         N/A             N/A
eth0                   172.20.20.2/24       up/up         N/A             N/A
lo                     127.0.0.1/8          up/up         N/A             N/A
9. root@s1:/# config interface ip remove Ethernet0 192.168.1.1/24
10. root@s1:/# show ip int
Interface    Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
-----------  --------  -------------------  ------------  --------------  -------------
eth0                   172.20.20.2/24       up/up         N/A             N/A
lo                     127.0.0.1/8          up/up         N/A             N/A

#### Describe the results you received:

Ethernet0 is removed from the ip interfaces table and has no associated IP.

#### Describe the results you expected:

Expected the interface ip of 192.168.1.2/24  to remain configured.

#### Output of `show version`:

```
root@s1:/# show ver  
/bin/sh: 1: sudo: not found

SONiC Software Version: SONiC.
Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/show/main.py", line 1136, in version
    click.echo("Distribution: Debian {}".format(version_info['debian_version']))
KeyError: 'debian_version'
```

**Comment by prsunny** [comment]
This is an unlikely use-case. Orchagent doesn't support overlapping of IP address ([overlap check](https://github.com/Azure/sonic-swss/blob/master/orchagent/intfsorch.cpp#L473)). Currently a limitation.

**Comment by anshuv-mfst** [comment]
Hi @fire-ant - could you please provide more input on the usecase?

**Comment by fire-ant** [comment]
Im concerned that if we automate the assignment of IP's to interfaces for uses such as anycast that in the event I'd like to migrate or add more IP's I can't remove prior ones without the possibility of removing all addresses. This isn't necessarily what I'd want to have to consider when I am running the correct commands to remove single addresses from an interface.
