### ISSUE TITLE
[201911/201811] Build failure 

### ISSUE THREAD

**Issue by zhenggen-xu** [Azure/sonic-buildimage#7449]
#### Describe the results you received:
Upstream build failure:
https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-201911/190/console

```
Setting up libpython3.6-dev:amd64 (3.6.0-1) ...
 ---> 6dc4802a5d4a
Removing intermediate container 3729ff147a5a
Step 33/57 : RUN curl https://bootstrap.pypa.io/get-pip.py | python3.6
 ---> Running in 8f37712f62fb
[91m  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[0m[91m
 79 1891k   79 1503k    0     0  2615k      0 --:--:-- --:--:-- --:--:-- 2614k[0m[91m
100 1891k  100 1891k    0     0  3019k      0 --:--:-- --:--:-- --:--:-- 3016k
[0m[91mTraceback (most recent call last):
  File "<stdin>", line 24298, in <module>
  File "<stdin>", line 139, in main
  File "<stdin>", line 115, in bootstrap
  File "<stdin>", line 96, in monkeypatch_for_cert
  File "/tmp/tmpkhimupph/pip.zip/pip/_internal/commands/__init__.py", line 9, in <module>
  File "/tmp/tmpkhimupph/pip.zip/pip/_internal/cli/base_command.py", line 12, in <module>
  File "/tmp/tmpkhimupph/pip.zip/pip/_internal/cli/cmdoptions.py", line 30, in <module>
  File "/tmp/tmpkhimupph/pip.zip/pip/_internal/utils/hashes.py", line 2, in <module>
ImportError: cannot import name 'NoReturn'
[0mThe command '/bin/sh -c curl https://bootstrap.pypa.io/get-pip.py | python3.6' returned a non-zero code: 1
[  FAIL LOG END  ] [ target/docker-snmp-sv2.gz ]
```

This should be applicable to 201811 branch too.

#### Describe the results you expected:
Build should be successful.

**Comment by caizhenghui-juniper** [comment]
likely need python 3.6.2 and above.

**Comment by abdosi** [comment]
[201911] is fixed https://github.com/Azure/sonic-buildimage/pull/7452
For 201811 @yxieca need to cheery-pick this.
