### ISSUE TITLE
decode-syseeprom error in snmp.sh

### ISSUE THREAD

**Issue by SuvarnaMeenakshi** [Azure/sonic-buildimage#7862]
#### Steps to reproduce the issue:
1. Boot a single asic or multi-asic VS image with any latest master branch image. 
 ./testbed-cli.sh -t vtestbed.csv -m veos_vtb -k ceos add-topo vms-kvm-t0 password.txt 
2. Load configuration to bring up all services. 
./testbed-cli.sh -t vtestbed.csv -m veos_vtb deploy-mg vms-kvm-t0 lab password.txt   
3. Check journalctl log of snmp service or check syslog after services are started. 

#### Describe the results you received:
The below error is seen due to decode-syseeprom.
sudo journalctl -u snmp
-- Journal begins at Mon 2021-06-14 06:49:27 UTC, ends at Mon 2021-06-14 15:55:09 UTC. --
J..
Jun 14 15:50:58 vlab-01 snmp.sh[1599761]: Traceback (most recent call last):
Jun 14 15:50:58 vlab-01 snmp.sh[1599761]:   File "/usr/local/bin/decode-syseeprom", line 18, in <module>
Jun 14 15:50:58 vlab-01 snmp.sh[1599761]:     import sonic_platform
Jun 14 15:50:58 vlab-01 snmp.sh[1599761]: ModuleNotFoundError: No module named 'sonic_platform'
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]: Traceback (most recent call last):
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:   File "/usr/local/bin/sonic-db-cli", line 131, in <module>
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:     main()
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:   File "/usr/local/bin/sonic-db-cli", line 114, in main
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:     execute_cmd(args.db_or_op, args.cmd, args.namespace, args.unixsocket)
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:   File "/usr/local/bin/sonic-db-cli", line 73, in execute_cmd
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:     resp = client.execute_command(*cmd)
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:   File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 901, in execute_command
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:     return self.parse_response(conn, command_name, **options)
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:   File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 915, in parse_response
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:     response = connection.read_response()
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:   File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 756, in read_response
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]:     raise response
Jun 14 15:50:59 vlab-01 snmp.sh[1599773]: redis.exceptions.ResponseError: wrong number of arguments for 'hset' command
Jun 14 15:50:59 vlab-01 snmp.sh[1599670]: Starting existing snmp container with HWSKU Force10-S6000
Jun 14 15:51:01 vlab-01 /container[1599786]: container_start: BEGIN

#### Describe the results you expected:
The syseeprom-decode error should not be seen in journalctl log or syslog. snmp.sh traceback should not be seen.
Fixing syseeprom-decode error should fix the traceback seen.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@SuvarnaMeenakshi  platform specific issue. Talk to Joe on this.
