### ISSUE TITLE
[show bgp] show ip bgp "network" broken 

### ISSUE THREAD

**Issue by prsunny** [Azure/sonic-buildimage#7935]
#### Description

`show ip bgp network`  is broken with following error:

```
show ip bgp network 
Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/show/bgp_frr_v4.py", line 128, in network
    output  =  bgp_util.run_bgp_command(command, namespace)
  File "/usr/local/lib/python3.7/dist-packages/utilities_common/bgp_util.py", line 181, in run_bgp_command
    multi_asic.get_asic_id_from_name(bgp_namespace))
  File "/usr/local/lib/python3.7/dist-packages/sonic_py_common/multi_asic.py", line 135, in get_asic_id_from_name
    if asic_name.startswith(ASIC_NAME_PREFIX):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

#### Steps to reproduce the issue:
1. Execute `show ip bgp network`
2.
3.

#### Describe the results you received:
Backtrace

#### Describe the results you expected:
Valid output

#### Output of `show version`:

```
show version 

SONiC Software Version: SONiC.master.20565-4c4799ed4
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: 4c4799ed4
Build date: Sun Jun 20 12:19:26 UTC 2021
Built by: AzDevOps@sonic-build-workers-000EIW
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prsunny** [comment]
@rlhui for viz

**Comment by zhangyanzhao** [comment]
@arlakshm please take a look

**Comment by prsunny** [comment]
Fix PR merged
