### ISSUE TITLE
Image installation failure caused by sonic-package-manager

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#8032]
#### Description

Master image installation fails with errors from `sonic-package-manager`.

#### Steps to reproduce the issue:
1. Install latest master on SONiC device.
2. The installation will fail with errors from sonic-package-manager.
3.

#### Describe the results you received:
```
Downloading image...
...99%, 876 MB, 64084 KB/s, 0 seconds left...    
No errors detected in compressed data of /tmp/sonic_image.swi.
Installing image SONiC-OS-master.21764-101b1fa08 and setting it as default...
Command: /usr/bin/unzip -od /tmp /tmp/sonic_image.swi boot0
Archive:  /tmp/sonic_image.swi
  inflating: /tmp/boot0              

Command: swipath=/tmp/sonic_image.swi target_path=/host sonic_upgrade=1 . /tmp/boot0
+ true
+ unzip -ql /tmp/sonic_image.swi
+ swi_installed=0
+ is_swi_installed /tmp/sonic_image.swi
+ local swi_path=/tmp/sonic_image.swi
+ unzip -qp /tmp/sonic_image.swi .imagehash
+ local swi_version=master.21764-101b1fa08
+ cat /host/image-master.21764-101b1fa08/.imagehash
+ :
+ local local_version=
+ [ -z  ]
+ return 1
+ swi_installed=1
+ [ 1 -ne 0 ]
+ [ 1 -eq 2 ]
+ [ -n  ]
+ [ 1 -ne 3 ]
+ false
+ false
+ regular_install
+ [ -e /host/image-master.21764-101b1fa08 ]
+ mkdir -p /host/image-master.21764-101b1fa08
+ info Generating boot-config, machine.conf and cmdline
+ cut -f1 -d  /proc/uptime
+ printf %04.2f: Generating boot-config, machine.conf and cmdline\n 55192.98
+ write_regular_configs /host/image-master.21764-101b1fa08
+ write_common_configs
+ write_default_cmdline
+ local delimiter=cmdline-aboot-end
+ cmdline_clear
+ echo -n
+ false
+ grep -q cmdline-aboot-end /proc/cmdline
+ cat /proc/cmdline
+ sed -E s/^(.*) cmdline-aboot-end .*$/\1/
+ tr   \n
+ cmdline_append
+ cat
+ cmdline_add cmdline-aboot-end
+ echo cmdline-aboot-end
+ write_platform_specific_cmdline
+ cmdline_get platform
+ sed -nr s/.*platform=([^ ]+).*/\1/p /tmp/append
+ tail -n 1
+ local platform=crow
+ cmdline_get sid
+ sed s/Ssd$//
+ sed -nr s/.*sid=([^ ]+).*/\1/p /tmp/append
+ tail -n 1
+ local sid=Lodoga
+ local varlog_size=100
+ sonic_mode=fixed
+ supervisor_mode=supervisor
+ linecard_mode=linecard
+ df /host
+ tail -1
+ tr -s  
+ cut -f2 -d 
+ local flash_size=30364
+ [ crow = raven ]
+ [ crow = crow ]
+ aboot_machine=arista_7050_qx32s
+ flash_size=3700
+ cmdline_add modprobe.blacklist=radeon,sp5100_tco
+ echo modprobe.blacklist=radeon,sp5100_tco
+ [ Lodoga = Upperlake ]
+ [ Lodoga = UpperlakeES ]
+ [ Lodoga = UpperlakePlus ]
+ [ Lodoga = Gardena ]
+ [ Lodoga = GardenaE ]
+ [ Lodoga = Alhambra ]
+ [ Lodoga = Mineral ]
+ [ Lodoga = MineralD ]
+ [ Lodoga = Lodoga ]
+ aboot_machine=arista_7050cx3_32s
+ flash_size=3700
+ [ Lodoga = Marysville ]
+ [ Lodoga = Marysville10 ]
+ [ Lodoga = BlackhawkO ]
+ [ Lodoga = BlackhawkDD ]
+ [ Lodoga = BlackhawkDDM ]
+ [ Lodoga = Smartsville ]
+ [ Lodoga = SmartsvilleBK ]
+ [ Lodoga = SmartsvilleBkMs ]
+ [ Lodoga = SmartsvilleBkMsTpm ]
+ [ Lodoga = SmartsvilleDD ]
+ [ Lodoga = SmartsvilleDDBK ]
+ [ Lodoga = SmartsvilleDDBkMs ]
+ [ Lodoga = SmartsvilleDDBkMsTpm ]
+ [ Lodoga = Clearwater2 ]
+ [ Lodoga = Clearwater2Ms ]
+ [ Lodoga = OtterLake ]
+ [ Lodoga = SmartsvilleBkMs ]
+ in_array crow rook magpie woodpecker sprucefish
+ local value=crow
+ shift
+ [ crow = rook ]
+ [ crow = magpie ]
+ [ crow = woodpecker ]
+ [ crow = sprucefish ]
+ return 1
+ in_array crow rook sprucefish
+ local value=crow
+ shift
+ [ crow = rook ]
+ [ crow = sprucefish ]
+ return 1
+ in_array crow crow magpie
+ local value=crow
+ shift
+ [ crow = crow ]
+ return 0
+ cmdline_add amd_iommu=off
+ echo amd_iommu=off
+ cmdline_add modprobe.blacklist=snd_hda_intel,hdaudio
+ echo modprobe.blacklist=snd_hda_intel,hdaudio
+ read_system_eeprom
+ [ -x /bin/readprefdl ]
+ [ -f /etc/prefdl ]
+ in_array crow woodpecker
+ local value=crow
+ shift
+ [ crow = woodpecker ]
+ return 1
+ in_array crow lorikeet hedgehog
+ local value=crow
+ shift
+ [ crow = lorikeet ]
+ [ crow = hedgehog ]
+ return 1
+ [ 3700 -ge 28000 ]
+ [ 3700 -ge 3700 ]
+ varlog_size=400
+ cmdline_add varlog_size=400
+ echo varlog_size=400
+ cmdline_add sonic.mode=fixed
+ echo sonic.mode=fixed
+ write_image_specific_cmdline
+ cmdline_add security=apparmor
+ echo security=apparmor
+ cmdline_add apparmor=1
+ echo apparmor=1
+ cmdline_add rw
+ echo rw
+ cmdline_add net.ifnames=0
+ echo net.ifnames=0
+ cmdline_add systemd.unified_cgroup_hierarchy=0
+ echo systemd.unified_cgroup_hierarchy=0
+ cmdline_add quiet
+ echo quiet
+ cmdline_add systemd.show_status=auto
+ echo systemd.show_status=auto
+ [ -f /sys/class/net/ma1/address ]
+ [ -f /sys/class/net/eth0/address ]
+ cat /sys/class/net/eth0/address
+ cmdline_add hwaddr_ma1=94:8e:d3:05:34:e4
+ echo hwaddr_ma1=94:8e:d3:05:34:e4
+ mount
+ grep  /host 
+ local mountstr=/dev/sda1 on /host type ext4 (rw,relatime)
+ echo /dev/sda1 on /host type ext4 (rw,relatime)
+ cut -f1 -d 
+ local rootdev=/dev/sda1
+ echo /dev/sda1 on /host type ext4 (rw,relatime)
+ cut -f5 -d 
+ local rootfstype=ext4
+ get_uuid_for /dev/sda1
+ local dev=/dev/sda1
+ type lsblk
+ lsblk /dev/sda1 -n --output UUID
+ local rootuuid=1160a1cc-0e0a-4c4c-9d96-71ea62ae5ebb
+ [ -z 1160a1cc-0e0a-4c4c-9d96-71ea62ae5ebb ]
+ [ ext4 = vfat ]
+ cmdline_add root=UUID=1160a1cc-0e0a-4c4c-9d96-71ea62ae5ebb
+ echo root=UUID=1160a1cc-0e0a-4c4c-9d96-71ea62ae5ebb
+ write_machine_config
+ cmdline_get Aboot
+ sed s/^.*norcal.-//
+ sed+ tail -n 1
 -nr s/.*Aboot=([^ ]+).*/\1/p /tmp/append
+ aboot_version=6.1.11-18938843
+ [ -x /bin/sysinit ]
+ aboot_build_date=unknown
+ cat
+ chmod a+r /host/machine.conf
+ cmdline_add loop=image-master.21764-101b1fa08/fs.squashfs
+ echo loop=image-master.21764-101b1fa08/fs.squashfs
+ cmdline_add loopfstype=squashfs
+ echo loopfstype=squashfs
+ write_cmdline
+ [ -f /host/kernel-params ]
+ [ -f /host/image-master.21764-101b1fa08/kernel-cmdline ]
+ cmdline_echo
+ cat /tmp/append
+ tr \n  
+ echo reboot=p console=ttyS0 acpi=on Aboot=Aboot-norcal6-6.1.11-18938843 net_ma1=pci0000:00/0000:00:02.4/.*$ platform=crow block_usb1=pci0000:00/0000:00:12.0/usb1/1-1/1-1.1/.*$ block_usb2=pci0000:00/0000:00:12.0/usb1/1-1/1-1.4/.*$ block_flash=pci0000:00/0000:00:11.0/.*host./target.:0:0/.*$ sid=LodogaSsd cmdline-aboot-end modprobe.blacklist=radeon,sp5100_tco amd_iommu=off modprobe.blacklist=snd_hda_intel,hdaudio varlog_size=400 sonic.mode=fixed security=apparmor apparmor=1 rw net.ifnames=0 systemd.unified_cgroup_hierarchy=0 quiet systemd.show_status=auto hwaddr_ma1=94:8e:d3:05:34:e4 root=UUID=1160a1cc-0e0a-4c4c-9d96-71ea62ae5ebb loop=image-master.21764-101b1fa08/fs.squashfs loopfstype=squashfs
+ cmdline_echo
+ sed s/ cmdline-aboot-end.*$//
+ cat+  /tmp/appendtr
 \n  
+ echo reboot=p console=ttyS0 acpi=on Aboot=Aboot-norcal6-6.1.11-18938843 net_ma1=pci0000:00/0000:00:02.4/.*$ platform=crow block_usb1=pci0000:00/0000:00:12.0/usb1/1-1/1-1.1/.*$ block_usb2=pci0000:00/0000:00:12.0/usb1/1-1/1-1.4/.*$ block_flash=pci0000:00/0000:00:11.0/.*host./target.:0:0/.*$ sid=LodogaSsd cmdline-aboot-end modprobe.blacklist=radeon,sp5100_tco amd_iommu=off modprobe.blacklist=snd_hda_intel,hdaudio varlog_size=400 sonic.mode=fixed security=apparmor apparmor=1 rw net.ifnames=0 systemd.unified_cgroup_hierarchy=0 quiet systemd.show_status=auto hwaddr_ma1=94:8e:d3:05:34:e4 root=UUID=1160a1cc-0e0a-4c4c-9d96-71ea62ae5ebb loop=image-master.21764-101b1fa08/fs.squashfs loopfstype=squashfs
+ info Installing image under /host/image-master.21764-101b1fa08
+ cut -f1 -d  /proc/uptime
+ printf %04.2f: Installing image under /host/image-master.21764-101b1fa08\n 55193.02
+ extract_image
+ info Moving swi to a tmpfs
+ cut -f1 -d  /proc/uptime
+ printf %04.2f: Moving swi to a tmpfs\n 55193.02
+ move_swi_to_tmpfs /tmp/sonic_image.swi
+ local oldswi=/tmp/sonic_image.swi
+ is_file_in_memory /tmp/sonic_image.swi
+ local file=/tmp/sonic_image.swi
+ mountpoint_for_file /tmp/sonic_image.swi
+ local file=/tmp/sonic_image.swi
+ df /tmp/sonic_image.swi+ 
tail -1
+ tr -s  
+ cut -d   -f6
+ local filemnt=/boot
+ mount
+ grep  /boot 
+ cut -f5 -d 
+ local filemntfs=ext4
+ return 1
+ get_tmpfs
+ mktemp -d
+ local tmpfs=/tmp/tmp.yILvCgR8JR
+ mkdir -p /tmp/tmp.yILvCgR8JR
+ false
+ mount
+ grep -q  /tmp type tmpfs
+ dirname /tmp/tmp.yILvCgR8JR
+ mount -t tmpfs /tmp /tmp/tmp.yILvCgR8JR
+ echo /tmp/tmp.yILvCgR8JR
+ local tmpfs=/tmp/tmp.yILvCgR8JR
+ basename /tmp/sonic_image.swi
+ local newswi=/tmp/tmp.yILvCgR8JR/sonic_image.swi
+ mv /tmp/sonic_image.swi /tmp/tmp.yILvCgR8JR/sonic_image.swi
+ echo /tmp/tmp.yILvCgR8JR/sonic_image.swi
+ swipath=/tmp/tmp.yILvCgR8JR/sonic_image.swi
+ info Extracting swi content
+ cut -f1 -d  /proc/uptime
+ printf %04.2f: Extracting swi content\n 55194.07
+ unzip -oq /tmp/tmp.yILvCgR8JR/sonic_image.swi -x boot0 dockerfs.tar.gz -d /host/image-master.21764-101b1fa08
+ grep  /host  /proc/mounts
+ cut -d  -f3
+ rootfs_type=ext4
+ info Extracting dockerfs.tar.gz from swi
+ cut -f1 -d  /proc/uptime
+ printf %04.2f: Extracting dockerfs.tar.gz from swi\n 55198.10
+ [ ext4 != vfat ]
+ cmdline_has docker_inram=on
+ grep -q docker_inram=on /tmp/append
+ mkdir -p /host/image-master.21764-101b1fa08/docker
+ [ -n 1 ]
+ TAR_EXTRA_OPTION=--numeric-owner --warning=no-timestamp
+ unzip -oqp /tmp/tmp.yILvCgR8JR/sonic_image.swi dockerfs.tar.gz
+ tar xzf - -C /host/image-master.21764-101b1fa08/docker --numeric-owner --warning=no-timestamp
+ false
+ info Remove installer
+ cut -f1 -d  /proc/uptime
+ printf %04.2f: Remove installer\n 55213.13
+ cleanup_swi_tmpfs /tmp/tmp.yILvCgR8JR/sonic_image.swi
+ rm -f /tmp/tmp.yILvCgR8JR/sonic_image.swi
+ mountpoint_for_file /tmp/tmp.yILvCgR8JR/sonic_image.swi
+ local file=/tmp/tmp.yILvCgR8JR/sonic_image.swi
+ df /tmp/tmp.yILvCgR8JR/sonic_image.swi
+ tr -s  
+ tail -1
df: /tmp/tmp.yILvCgR8JR/sonic_image.swi+ : No such file or directorycut -d  
 -f6
+ clean_tmpfs 
+ local tmpfs=
+ return 0
+ local swi_boot_path=flash:image-master.21764-101b1fa08/.sonic-boot.swi
+ update_boot_config SWI flash:image-master.21764-101b1fa08/.sonic-boot.swi
+ local key=SWI
+ local value=flash:image-master.21764-101b1fa08/.sonic-boot.swi
+ grep SWI /host/boot-config
+ sed -i s#^SWI=.*$#SWI=flash:image-master.21764-101b1fa08/.sonic-boot.swi# /host/boot-config
+ update_boot_config SWI_DEFAULT flash:image-master.21764-101b1fa08/.sonic-boot.swi
+ local key=SWI_DEFAULT
+ local value=flash:image-master.21764-101b1fa08/.sonic-boot.swi
+ grep SWI_DEFAULT /host/boot-config
+ sed -i s#^SWI_DEFAULT=.*$#SWI_DEFAULT=flash:image-master.21764-101b1fa08/.sonic-boot.swi# /host/boot-config
+ sync
+ run_hooks post-install
+ [ -d /host/image-master.21764-101b1fa08/platform/hooks/post-install ]
+ false
55192.98: Generating boot-config, machine.conf and cmdline
55193.02: Installing image under /host/image-master.21764-101b1fa08
55193.02: Moving swi to a tmpfs
55194.07: Extracting swi content
55198.10: Extracting dockerfs.tar.gz from swi
55213.13: Remove installer

Command: config-setup backup
Taking backup of current configuration

Command: mkdir -p /tmp/image-master.21764-101b1fa08-fs
Command: mount -t squashfs /host/image-master.21764-101b1fa08/fs.squashfs /tmp/image-master.21764-101b1fa08-fs
Command: sonic-cfggen -d -y /tmp/image-master.21764-101b1fa08-fs/etc/sonic/sonic_version.yml -t /tmp/image-master.21764-101b1fa08-fs/usr/share/sonic/templates/sonic-environment.j2
Command: umount -r -f /tmp/image-master.21764-101b1fa08-fs
Command: rm -rf /tmp/image-master.21764-101b1fa08-fs
Command: mkdir -p /tmp/image-master.21764-101b1fa08-fs
Command: mount -t squashfs /host/image-master.21764-101b1fa08/fs.squashfs /tmp/image-master.21764-101b1fa08-fs
Command: mkdir -p /host/image-master.21764-101b1fa08/rw
Command: mkdir -p /host/image-master.21764-101b1fa08/work
Command: mkdir -p /tmp/image-master.21764-101b1fa08-fs
Command: mount overlay -t overlay -o rw,relatime,lowerdir=/tmp/image-master.21764-101b1fa08-fs,upperdir=/host/image-master.21764-101b1fa08/rw,workdir=/host/image-master.21764-101b1fa08/work /tmp/image-master.21764-101b1fa08-fs
Command: mkdir -p /tmp/image-master.21764-101b1fa08-fs/var/lib/docker
Command: mount --bind /host/image-master.21764-101b1fa08/docker /tmp/image-master.21764-101b1fa08-fs/var/lib/docker
Command: chroot /tmp/image-master.21764-101b1fa08-fs mount proc /proc -t proc
Command: chroot /tmp/image-master.21764-101b1fa08-fs mount sysfs /sys -t sysfs
Command: chroot /tmp/image-master.21764-101b1fa08-fs /usr/lib/docker/docker.sh start
mount: /sys/fs/cgroup/cpu: cgroup already mounted on /sys/fs/cgroup.
mount: /sys/fs/cgroup/cpuacct: cgroup already mounted on /sys/fs/cgroup.
Command: cp /var/lib/sonic-package-manager/packages.json /tmp/image-master.21764-101b1fa08-fs/tmp/packages.json
Command: touch /tmp/image-master.21764-101b1fa08-fs/tmp/docker.sock
Command: mount --bind /var/run/docker.sock /tmp/image-master.21764-101b1fa08-fs/tmp/docker.sock
Command: chroot /tmp/image-master.21764-101b1fa08-fs sh -c command -v sonic-package-manager
Command: chroot /tmp/image-master.21764-101b1fa08-fs sonic-package-manager migrate /tmp/packages.json --dockerd-socket /tmp/docker.sock -y
Traceback (most recent call last):
  File "/usr/local/bin/sonic-package-manager", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sonic_package_manager/main.py", line 149, in cli
    ctx.obj = PackageManager.get_manager()
  File "/usr/local/lib/python3.7/dist-packages/sonic_package_manager/manager.py", line 928, in get_manager
    PackageDatabase.from_file(),
  File "/usr/local/lib/python3.7/dist-packages/sonic_package_manager/database.py", line 212, in from_file
    db_content = json.load(db)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Command: chroot /tmp/image-master.21764-101b1fa08-fs /usr/lib/docker/docker.sh stop
Command: umount -f -R /tmp/image-master.21764-101b1fa08-fs
Command: umount -r -f /tmp/image-master.21764-101b1fa08-fs
Command: rm -rf /tmp/image-master.21764-101b1fa08-fs
Traceback (most recent call last):
  File "/usr/local/bin/sonic_installer", line 8, in <module>
    sys.exit(sonic_installer())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sonic_installer/main.py", line 439, in install
    migrate_sonic_packages(bootloader, binary_image_version)
  File "/usr/local/lib/python3.7/dist-packages/sonic_installer/main.py", line 358, in migrate_sonic_packages
    "-y"])
  File "/usr/local/lib/python3.7/dist-packages/sonic_installer/common.py", line 41, in run_command_or_raise
    raise SonicRuntimeException("Failed to run command '{0}'".format(argv))
sonic_installer.exception.SonicRuntimeException: Failed to run command '['chroot', '/tmp/image-master.21764-101b1fa08-fs', 'sonic-package-manager', 'migrate', '/tmp/packages.json', '--dockerd-socket', '/tmp/docker.sock', '-y']'
```

#### Describe the results you expected:

Image installation should succeed without errors.

#### Output of `show version`:

Issue seen on `SONiC-OS-master.21764-101b1fa08`

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vaibhavhd** [comment]
@volodymyrsamotiy pointed out that this issue is a regression after this PR: #7598 
"After these changes “packages.json” generation is broken."

**Comment by judyjoseph** [comment]
I see that this sonic_install failure happens when we install a new version of master image - with the DUT already running master. 

Sonic_install works fine when upgrading from older version like 201811/201911 --> this master image

   On a code browse, I see this as one of the probable reasons. The logic in this new file files/build_templates/packages.json.j2 needs to be updated with the _MACHINE check which was added as part of #7598 here sonic-buildimage/sonic_debian_extension.j2 at master · Azure/sonic-buildimage (github.com) ? Please share if that is the case.

**Comment by judyjoseph** [comment]
Closing the issue as fix is merged viz commit https://github.com/Azure/sonic-buildimage/pull/8044
