### ISSUE TITLE
[watchdog reboot] platform_pcieutil throws errors and DUT becomes unreachable

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#8190]
#### Description

Watchdog reboot invokes platform_pcieutil which throws errors and further DUT becomes unreachable via SSH or console.
pcied TypeError: get_pcie_aer_stats() got an unexpected keyword argument 'dev'

#### Steps to reproduce the issue:
1. Run `platform_tests/test_reboot.py::test_watchdog_reboot`
2. Soon after the test, the DUT will become unreachable - both on SSH and console.
3. PDU powercycle the DUT, and check syslog for errors.
3. The failure is inconsistent so far, but more tests on latest images are needed to decide the reproducibility.

#### Describe the results you received:

```
Jul 14 21:36:09.496932 str-s6100-acs-4 INFO ansible-command: Invoked with creates=None executable=None _uses_shell=False strip_empty_ends=True _raw_params=watchdogutil status removes=None argv=None warn=True chdir=None stdin_add_newline=True stdin=None
Jul 14 21:36:11.664452 str-s6100-acs-4 INFO ansible-command: Invoked with creates=None executable=None _uses_shell=False strip_empty_ends=True _raw_params=date +"%Y-%m-%d %H:%M:%S" removes=None argv=None warn=True chdir=None stdin_add_newline=True stdin=None
Jul 14 21:36:12.383612 str-s6100-acs-4 INFO ansible-command: Invoked with creates=None executable=None _uses_shell=False strip_empty_ends=True _raw_params=watchdogutil arm -s 5 removes=None argv=None warn=True chdir=None stdin_add_newline=True stdin=None
Jul 14 21:36:22.841998 str-s6100-acs-4 INFO pmon#/supervisord: pcied /usr/local/lib/python2.7/dist-packages/sonic_platform_base/sonic_pcie/pcie_common.py:30: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Jul 14 21:36:22.841998 str-s6100-acs-4 INFO pmon#/supervisord: pcied   self.confInfo = yaml.load(conf_file)
Jul 14 21:36:22.869606 str-s6100-acs-4 INFO pmon#/supervisord: pcied Traceback (most recent call last):
Jul 14 21:36:22.869835 str-s6100-acs-4 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 215, in <module>
Jul 14 21:36:22.869976 str-s6100-acs-4 INFO pmon#/supervisord: pcied     sys.exit(main())
Jul 14 21:36:22.870107 str-s6100-acs-4 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 207, in main
Jul 14 21:36:22.870240 str-s6100-acs-4 INFO pmon#/supervisord: pcied     while pcied.run():
Jul 14 21:36:22.870368 str-s6100-acs-4 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 194, in run
Jul 14 21:36:22.870530 str-s6100-acs-4 INFO pmon#/supervisord: pcied     self.check_pcie_devices()
Jul 14 21:36:22.870670 str-s6100-acs-4 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 167, in check_pcie_devices
Jul 14 21:36:22.870811 str-s6100-acs-4 INFO pmon#/supervisord: pcied     self.check_n_update_pcie_aer_stats(Bus, Dev, Fn)
Jul 14 21:36:22.870955 str-s6100-acs-4 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 133, in check_n_update_pcie_aer_stats
Jul 14 21:36:22.871102 str-s6100-acs-4 INFO pmon#/supervisord: pcied     self.aer_stats = platform_pcieutil.get_pcie_aer_stats(bus=Bus, dev=Dev, func=Fn)
Jul 14 21:36:22.871255 str-s6100-acs-4 INFO pmon#/supervisord: pcied TypeError: get_pcie_aer_stats() got an unexpected keyword argument 'dev'
Jul 14 21:36:22.918817 str-s6100-acs-4 INFO pmon#supervisord 2021-07-14 21:36:22,918 INFO exited: pcied (exit status 1; not expected)
Jul 14 21:36:23.922674 str-s6100-acs-4 INFO pmon#supervisord 2021-07-14 21:36:23,921 INFO spawned: 'pcied' with pid 124
```

#### Describe the results you expected:
Watchdog reboot should not fail, and DUT should not become unreachable.

#### Output of `show version`:

```
SONIC_VERSION=master.23634-709d0f4fb
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vaibhavhd** [comment]
This issue is also seen on other platforms. I noticed it on 7050CX3 and 7260 platforms.

```
Jul 20 17:01:54.366120 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied /usr/local/lib/python2.7/dist-packages/sonic_platform_base/sonic_pcie/pcie_common.py:30: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Jul 20 17:01:54.366120 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied   self.confInfo = yaml.load(conf_file)
Jul 20 17:01:54.466710 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied Failed to load platform Pcie module. Error : No module named pcie, Fallback to default module
Jul 20 17:01:54.466710 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied Traceback (most recent call last):
Jul 20 17:01:54.466710 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 217, in <module>
Jul 20 17:01:54.466710 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied     sys.exit(main())
Jul 20 17:01:54.466710 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 209, in main
Jul 20 17:01:54.466710 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied     while pcied.run():
Jul 20 17:01:54.466753 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 196, in run
Jul 20 17:01:54.466753 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied     self.check_pcie_devices()
Jul 20 17:01:54.466753 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 169, in check_pcie_devices
Jul 20 17:01:54.466753 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied     self.check_n_update_pcie_aer_stats(Bus, Dev, Fn)
Jul 20 17:01:54.466753 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied   File "/usr/local/bin/pcied", line 135, in check_n_update_pcie_aer_stats
Jul 20 17:01:54.466766 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied     self.aer_stats = platform_pcieutil.get_pcie_aer_stats(bus=Bus, dev=Dev, func=Fn)
Jul 20 17:01:54.466766 str2-7260cx3-acs-9 INFO pmon#/supervisord: pcied TypeError: get_pcie_aer_stats() got an unexpected keyword argument 'dev'
Jul 20 17:01:54.504287 str2-7260cx3-acs-9 INFO pmon#supervisord 2021-07-20 17:01:54,503 INFO exited: pcied (exit status 1; not expected)
```

**Comment by sujinmkang** [comment]
@vaibhavhd The pcied error should be fixed in the latest image that is caused by the mismatch between platform api and the pcied call. But I don't think that is related to the watchdog_reboot test issue which is DUT unreachable issue. Do you have the console output or full device log available for the issue?

**Comment by vaibhavhd** [comment]
Thanks @sujinmkang. This may be coincidental that PCIE error was seen at the same time when 1) `watchdogutil arm -s 5 ` command was issued as part of reboot and 2) DUT also became unreachable.

For the watchdog reboot issue, we can continue discussing on the email thread with Dell. We can close this issue here if PCIE errors are fixed in the latest master image.

Can you link the PR that fixed the pcie issue?
