### ISSUE TITLE
[6100] Show version fails with eeprom permission errors

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#8204]
#### Description

`show version` and `show platform summary` commands fail with permission errors in eeprom file.

#### Steps to reproduce the issue:
1. Install latest master image on a Dell device.
2. Do `show version`
3.

#### Describe the results you received:

```
admin@str-s6100-acs-4:~$ show ver
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sonic_eeprom/eeprom_base.py", line 243, in read_eeprom_bytes
    F = self.open_eeprom()
  File "/usr/local/lib/python3.7/dist-packages/sonic_eeprom/eeprom_base.py", line 231, in open_eeprom
    return io.open(eeprom_file, "rb")
PermissionError: [Errno 13] Permission denied: '/sys/class/i2c-adapter/i2c-2/2-0050/eeprom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/eeprom.py", line 35, in __init__
    self.eeprom_data = self.read_eeprom()
  File "/usr/local/lib/python3.7/dist-packages/sonic_eeprom/eeprom_tlvinfo.py", line 258, in read_eeprom
    h = self.read_eeprom_bytes(self._TLV_INFO_HDR_LEN)
  File "/usr/local/lib/python3.7/dist-packages/sonic_eeprom/eeprom_base.py", line 266, in read_eeprom_bytes
    raise IOError("Failed to read eeprom : %s" % (str(e)))
OSError: Failed to read eeprom : [Errno 13] Permission denied: '/sys/class/i2c-adapter/i2c-2/2-0050/eeprom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sonic_eeprom/eeprom_base.py", line 243, in read_eeprom_bytes
    F = self.open_eeprom()
  File "/usr/local/lib/python3.7/dist-packages/sonic_eeprom/eeprom_base.py", line 231, in open_eeprom
    return io.open(eeprom_file, "rb")
PermissionError: [Errno 13] Permission denied: '/sys/class/i2c-adapter/i2c-2/2-0050/eeprom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/eeprom.py", line 39, in __init__
    self.eeprom_data = self.read_eeprom()
  File "/usr/local/lib/python3.7/dist-packages/sonic_eeprom/eeprom_tlvinfo.py", line 258, in read_eeprom
    h = self.read_eeprom_bytes(self._TLV_INFO_HDR_LEN)
  File "/usr/local/lib/python3.7/dist-packages/sonic_eeprom/eeprom_base.py", line 266, in read_eeprom_bytes
    raise IOError("Failed to read eeprom : %s" % (str(e)))
OSError: Failed to read eeprom : [Errno 13] Permission denied: '/sys/class/i2c-adapter/i2c-2/2-0050/eeprom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/show/main.py", line 960, in version
    chassis_info = platform.get_chassis_info()
  File "/usr/local/lib/python3.7/dist-packages/show/platform.py", line 27, in get_chassis_info
    platform_chassis = sonic_platform.platform.Platform().get_chassis()
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/platform.py", line 24, in __init__
    self._chassis = Chassis()
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/chassis.py", line 73, in __init__
    self._eeprom = Eeprom()
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/eeprom.py", line 41, in __init__
    raise RuntimeError("Eeprom is not Programmed")
RuntimeError: Eeprom is not Programmed
admin@str-s6100-acs-4:~$ 
```

Same failures are seen when `show platform summary` command is executed.

#### Describe the results you expected:
`show version` or `show platform summ` commands should not fail.

#### Output of `show version`:

```
This fails
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vaibhavhd** [comment]
This appears to be file permission change that caused the commands to fail. The same commands when executed with sudo permissions pass.
```
admin@str-s6100-acs-2:~$ ls -l /sys/class/i2c-adapter/i2c-2/2-0050/eeprom
-rw------- 1 root root 256 Jul 19 16:33 /sys/class/i2c-adapter/i2c-2/2-0050/eeprom
```

```
admin@str-s6100-acs-2:~$ sudo show ver

SONiC Software Version: SONiC.master.24404-c89b62e4d
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: c89b62e4d
Build date: Sun Jul 18 14:49:19 UTC 2021
Built by: AzDevOps@sonic-build-workers-000ICG

Platform: x86_64-dell_s6100_c2538-r0
HwSKU: Force10-S6100
ASIC: broadcom
ASIC Count: 1
Serial Number: F3CD9Z2
Model Number: 0F6N2R
Hardware Revision: N/A
Uptime: 17:27:57 up 55 min,  1 user,  load average: 1.74, 1.61, 1.65

Docker images:
REPOSITORY                    TAG                      IMAGE ID            SIZE
docker-platform-monitor       latest                   b07aae3df65c        627MB
docker-platform-monitor       master.24404-c89b62e4d   b07aae3df65c        627MB
docker-dhcp-relay             latest                   71a4a85e07f1        420MB
docker-snmp                   latest                   046b29ae5d5e        454MB
docker-snmp                   master.24404-c89b62e4d   046b29ae5d5e        454MB
docker-sflow                  latest                   0e9df60461b7        425MB
docker-sflow                  master.24404-c89b62e4d   0e9df60461b7        425MB
docker-teamd                  latest                   c1d7e401db7e        424MB
docker-teamd                  master.24404-c89b62e4d   c1d7e401db7e        424MB
docker-nat                    latest                   96d7ca5cec32        427MB
docker-nat                    master.24404-c89b62e4d   96d7ca5cec32        427MB
docker-sonic-mgmt-framework   latest                   1a3987f825f2        569MB
docker-sonic-mgmt-framework   master.24404-c89b62e4d   1a3987f825f2        569MB
docker-lldp                   latest                   f7154c057265        453MB
docker-lldp                   master.24404-c89b62e4d   f7154c057265        453MB
docker-macsec                 latest                   2a1f35b73d0f        428MB
docker-macsec                 master.24404-c89b62e4d   2a1f35b73d0f        428MB
docker-database               latest                   6789248aaa3f        413MB
docker-database               master.24404-c89b62e4d   6789248aaa3f        413MB
docker-orchagent              latest                   44bc82b15bea        443MB
docker-orchagent              master.24404-c89b62e4d   44bc82b15bea        443MB
docker-sonic-telemetry        latest                   31a0a0c32691        501MB
docker-sonic-telemetry        master.24404-c89b62e4d   31a0a0c32691        501MB
docker-fpm-frr                latest                   e712eda2854e        443MB
docker-fpm-frr                master.24404-c89b62e4d   e712eda2854e        443MB
docker-syncd-brcm             latest                   83c790134330        709MB
docker-syncd-brcm             master.24404-c89b62e4d   83c790134330        709MB
docker-router-advertiser      latest                   5e6ac3d53963        413MB
docker-router-advertiser      master.24404-c89b62e4d   5e6ac3d53963        413MB

admin@str-s6100-acs-2:~$ 
```

**Comment by vaibhavhd** [comment]
This is due to PR - https://github.com/Azure/sonic-utilities/pull/1624

The root cause was explained in https://github.com/Azure/sonic-utilities/pull/1624#discussion_r681860907

The fix is work in progress by Mellanox.

**Comment by santhosh-kt** [comment]
This issue got fixed in PR https://github.com/Azure/sonic-utilities/pull/1751
