### ISSUE TITLE
[Celestica] Seastone 2 DX030 missing `sonic_platform`

### ISSUE THREAD

**Issue by bluecmd** [Azure/sonic-buildimage#8212]
#### Description

I have a Celestica Seastone 2 DX030.  When booting it the first time after installation I get the message that says that `sonic_platform` cannot be installed for this platform:

```
[   10.804959] rc.local[434]: + systemctl daemon-reload
[   11.133796] rc.local[434]: + [ -f /host/image-202012.24235-763fcd7ee/platform/firsttime ]
[   11.153524] rc.local[434]: + echo First boot detected. Performing first boot tasks...
[   11.170733] rc.local[434]: First boot detected. Performing first boot tasks...
[   11.184943] rc.local[434]: + [ -n  ]
[   11.196967] rc.local[434]: + [ -n x86_64-cel_seastone_2-r0 ]
[   11.213133] rc.local[434]: + platform=x86_64-cel_seastone_2-r0
[   11.225795] rc.local[434]: + [ -d /host/old_config ]
[   11.236984] rc.local[434]: + [ -f /host/minigraph.xml ]
[   11.252861] rc.local[434]: + [ -n  ]
[   11.264891] rc.local[434]: + touch /tmp/pending_config_initialization
[   11.300244] rc.local[434]: + touch /tmp/notify_firstboot_to_platform
[   11.317743] rc.local[434]: + [ ! -d /host/reboot-cause/platform ]
[   11.328913] rc.local[434]: + mkdir -p /host/reboot-cause/platform
[   11.340854] rc.local[434]: + [ -d /host/image-202012.24235-763fcd7ee/platform/x86_64-cel_seastone_2-r0 ]
[   11.356955] rc.local[434]: + dpkg -i /host/image-202012.24235-763fcd7ee/platform/x86_64-cel_seastone_2-r0/platform-modules-seastone2_0.9_amd64.deb
[   11.480030] rc.local[547]: Selecting previously unselected package platform-modules-seastone2.
[   11.861265] c3xxx 0000:01:00.0: Failed to send admin msg to accelerator
[   11.868067] c3xxx 0000:01:00.0: Failed to send init message
[   13.388957] rc.local[547]: (Reading database ... 29897 files and directories currently installed.)
[   13.405084] rc.local[547]: Preparing to unpack .../platform-modules-seastone2_0.9_amd64.deb ...
[   13.417100] rc.local[547]: Unpacking platform-modules-seastone2 (0.9) ...
[   13.557387] rc.local[547]: Setting up platform-modules-seastone2 (0.9) ...
[   22.217135] rc.local[633]: Synchronizing state of platform-modules-seastone2.service with SysV service script with /lib/systemd/systemd-sysv-install.
[   22.237033] rc.local[633]: Executing: /lib/systemd/systemd-sysv-install enable platform-modules-seastone2
[   29.525709] rc.local[720]: ERROR: sonic_platform-1.0-py2-none-any.whl is not a supported wheel on this platform.
```

#### Steps to reproduce the issue:
1. Install SONiC 202012 on a DX030
2. Observe error message on first boot
3. Run `show platform firmware`

#### Describe the results you received:

```
admin@sonic:~$ show platform firmware
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fwutil/__init__.py", line 2, in <module>
    from sonic_platform.platform import Platform
ModuleNotFoundError: No module named 'sonic_platform'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fwutil", line 5, in <module>
    from fwutil.main import cli
  File "/usr/local/lib/python3.7/dist-packages/fwutil/__init__.py", line 5, in <module>
    raise ImportError("Required module not found: {}".format(str(e)))
ImportError: Required module not found: No module named 'sonic_platform'
```

#### Describe the results you expected:

Successful invocation of command.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

N/A 

#### Additional information you deem important (e.g. issue happens only occasionally):

It happens on a fresh installed 202012 SONiC release.

**Comment by zhangyanzhao** [comment]
Need check with Celestica. Ying will help. Thanks.

**Comment by bluecmd** [comment]
https://github.com/Azure/sonic-buildimage/pull/9660 might fix this

**Comment by bluecmd** [comment]
Indeed, that fix is a step in the right direction - however it seems some code need to be py3-ified.

E.g. https://github.com/Azure/sonic-buildimage/blob/master/platform/broadcom/sonic-platform-modules-cel/services/platform_api/sonic_platform/__init__.py#L1 uses absolute imports but should be `from . import common`.
