### ISSUE TITLE
[202012] ThermalCtrl

### ISSUE THREAD

**Issue by gechiang** [Azure/sonic-buildimage#8230]
#### Description
Observed the following when warm-reboot a S6100 device:
```
Jul 20 18:19:11.502997 str-s6100-acs-2 INFO pmon#supervisord 2021-07-20 18:19:11,501 WARN received SIGTERM indicating exit request 

Jul 20 18:19:11.502997 str-s6100-acs-2 INFO pmon#supervisord 2021-07-20 18:19:11,502 INFO waiting for supervisor-proc-exit-listener, rsyslogd, xcvrd, psud, syseepromd, thermalctld to die 

Jul 20 18:19:12.502893 str-s6100-acs-2 INFO containerd[455]: time="2021-07-20T18:19:12.501878296Z" level=info msg="shim reaped" id=d0159c1ef97b16cc5a5e8f12d34a7e9b9bc2f1151bcca52a1f3b49114e5db079 

Jul 20 18:19:12.504135 str-s6100-acs-2 INFO pmon#thermalctld: Caught signal 'SIGTERM' - exiting... 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld Traceback (most recent call last): 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld   File "/usr/local/bin/thermalctld", line 867, in <module> 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld     sys.exit(main()) 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld   File "/usr/local/bin/thermalctld", line 856, in main 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld     while thermal_control.run(): 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld   File "/usr/local/bin/thermalctld", line 824, in run 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld     if self.stop_event.wait(self.wait_time): 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld   File "/usr/lib/python3.7/threading.py", line 552, in wait 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld     signaled = self._cond.wait(timeout) 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld   File "/usr/lib/python3.7/threading.py", line 300, in wait 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld     gotit = waiter.acquire(True, timeout) 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld   File "/usr/local/bin/thermalctld", line 811, in signal_handler 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld     self.thermal_manager.stop() 

Jul 20 18:19:12.511901 str-s6100-acs-2 INFO pmon#/supervisord: thermalctld AttributeError: 'NoneType' object has no attribute 'stop' 

Jul 20 18:19:12.515761 str-s6100-acs-2 INFO dockerd[563]: time="2021-07-20T18:19:12.514600728Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete" 

Jul 20 18:19:12.550068 str-s6100-acs-2 INFO pmon#supervisord 2021-07-20 18:19:12,549 INFO stopped: thermalctld (exit status 1) 

Jul 20 18:19:12.550599 str-s6100-acs-2 INFO pmon#syseepromd[48]: Caught signal 'SIGTERM' - exiting... 

Jul 20 18:19:12.550953 str-s6100-acs-2 INFO pmon#syseepromd[48]: Shutting down... 
```

#### Steps to reproduce the issue:
1. on S6100 boot up with 202012 image ( I used an internal MSFT 202012 image .09 but it should be repeatable on public 202012 as well)
2. issue "sudo warm-reboot -vvv"
3. Take a look into syslog for the above issue.

#### Describe the results you expected:
Thermalctld should not crash

#### Output of `show version`:

```
(paste your output here)
```

**Comment by zhangyanzhao** [comment]
@sujinmkang please help to take a look. Thanks.

**Comment by sujinmkang** [comment]
thermal_manager is not available for all platform and this is only place which is missing to check if it exists before calling the thermal_manager.stop() in thermalctld.
