### ISSUE TITLE
[DellEMC S5232F-ON] `show system-health summary` broken in 202012

### ISSUE THREAD

**Issue by bluecmd** [Azure/sonic-buildimage#8261]
#### Steps to reproduce the issue:
1. Run a Dell EMC S5232F-ON
2. Run `show system-health summary`

#### Describe the results you received:

```
$ sudo show system-health summary
chassis.set_status_led is not implemented
Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/show/system_health.py", line 46, in summary
    chassis.initizalize_system_led()
AttributeError: 'Chassis' object has no attribute 'initizalize_system_led'
```

#### Describe the results you expected:

A system health summary.

#### Output of `show version`:

```
SONiC Software Version: SONiC.202012.24235-763fcd7ee
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: 763fcd7ee
Build date: Fri Jul 16 15:45:08 UTC 2021
Built by: AzDevOps@sonic-build-workers-000I4L

Platform: x86_64-dellemc_s5232f_c3538-r0
HwSKU: DellEMC-S5232f-P-25G
ASIC: broadcom
ASIC Count: 1
Serial Number: [redacted]
Uptime: 22:03:25 up 11 min,  1 user,  load average: 0.90, 1.01, 0.69

Docker images:
REPOSITORY                    TAG                      IMAGE ID            SIZE
docker-sonic-mgmt-framework   202012.24235-763fcd7ee   acd941cfaa38        620MB
docker-sonic-mgmt-framework   latest                   acd941cfaa38        620MB
docker-teamd                  202012.24235-763fcd7ee   81d59c66ae77        411MB
docker-teamd                  latest                   81d59c66ae77        411MB
docker-orchagent              202012.24235-763fcd7ee   0e58d52e245f        429MB
docker-orchagent              latest                   0e58d52e245f        429MB
docker-nat                    202012.24235-763fcd7ee   8c16019a7557        414MB
docker-nat                    latest                   8c16019a7557        414MB
docker-sonic-telemetry        202012.24235-763fcd7ee   ba060994e711        490MB
docker-sonic-telemetry        latest                   ba060994e711        490MB
docker-sflow                  202012.24235-763fcd7ee   80b2440337c9        412MB
docker-sflow                  latest                   80b2440337c9        412MB
docker-platform-monitor       202012.24235-763fcd7ee   e3a74ce2a75f        608MB
docker-platform-monitor       latest                   e3a74ce2a75f        608MB
docker-fpm-frr                202012.24235-763fcd7ee   62ce91a1f878        429MB
docker-fpm-frr                latest                   62ce91a1f878        429MB
docker-syncd-brcm             202012.24235-763fcd7ee   08de050f811d        693MB
docker-syncd-brcm             latest                   08de050f811d        693MB
docker-router-advertiser      202012.24235-763fcd7ee   7f6f8c4a3685        401MB
docker-router-advertiser      latest                   7f6f8c4a3685        401MB
docker-snmp                   202012.24235-763fcd7ee   a324ae727e7e        442MB
docker-snmp                   latest                   a324ae727e7e        442MB
docker-lldp                   202012.24235-763fcd7ee   540880495898        441MB
docker-lldp                   latest                   540880495898        441MB
docker-database               202012.24235-763fcd7ee   9e56853a122e        401MB
docker-database               latest                   9e56853a122e        401MB
docker-dhcp-relay             202012.24235-763fcd7ee   4e880736890c        408MB
docker-dhcp-relay             latest                   4e880736890c        408MB

```
#### Output of `show techsupport`:

N/A

#### Additional information you deem important (e.g. issue happens only occasionally):

I think this PR needs to be applied for S5232F-ON as well, and backported: https://github.com/Azure/sonic-buildimage/pull/6788

**Comment by Staphylo** [comment]
This is likely to be an issue for all platform vendors that have not tested this command or did not want to implement something out of spec.
It also feels weird that a `show` command actually changes hardware state by initializing the system leds every time it is invoked.

The failing method `initizalize_system_led` is not part of the `sonic_platform` API as of today https://github.com/Azure/sonic-platform-common/blob/master/sonic_platform_base/chassis_base.py
This common code should have therefore not be calling an undefined API call before adding it as part of `ChassisBase` in the `sonic_platform` package. The naming of the API should also be fixed since there is an obvious typo.

**Comment by chitra-raghavan** [comment]
Dell is working on this.

**Comment by imthatoneguy** [comment]
Also impacts Celestica Seastone-DX010 (Broadcom) SONiC.master.646-990b1127.
