### ISSUE TITLE
arm64 build failure

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#8312]
#### Steps to reproduce the issue:
1. https://dev.azure.com/mssonic/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/26609/logs/9
2.
3.

#### Describe the results you received:
```
2021-08-02T10:25:50.7025437Z + sudo cp files/build_templates/docker_image_ctl.j2 ./fsroot-centec-arm64/usr/share/sonic/templates/docker_image_ctl.j2
2021-08-02T10:25:50.7026087Z + sudo LANG=C chroot ./fsroot-centec-arm64 /usr/local/bin/generate_shutdown_order.py
2021-08-02T10:25:50.7026715Z Traceback (most recent call last):
2021-08-02T10:25:50.7027350Z   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
2021-08-02T10:25:50.7027710Z     chunked=chunked,
2021-08-02T10:25:50.7028269Z   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
2021-08-02T10:25:50.7028693Z     conn.request(method, url, **httplib_request_kw)
2021-08-02T10:25:50.7029045Z   File "/usr/lib/python3.7/http/client.py", line 1260, in request
2021-08-02T10:25:50.7030202Z     self._send_request(method, url, body, headers, encode_chunked)
2021-08-02T10:25:50.7030697Z   File "/usr/lib/python3.7/http/client.py", line 1306, in _send_request
2021-08-02T10:25:50.7031116Z     self.endheaders(body, encode_chunked=encode_chunked)
2021-08-02T10:25:50.7031555Z   File "/usr/lib/python3.7/http/client.py", line 1255, in endheaders
2021-08-02T10:25:50.7031997Z     self._send_output(message_body, encode_chunked=encode_chunked)
2021-08-02T10:25:50.7032433Z   File "/usr/lib/python3.7/http/client.py", line 1030, in _send_output
2021-08-02T10:25:50.7032915Z     self.send(msg)
2021-08-02T10:25:50.7033211Z   File "/usr/lib/python3.7/http/client.py", line 970, in send
2021-08-02T10:25:50.7033517Z     self.connect()
2021-08-02T10:25:50.7034160Z   File "/usr/local/lib/python3.7/dist-packages/docker/transport/unixconn.py", line 43, in connect
2021-08-02T10:25:50.7034545Z     sock.connect(self.unix_socket)
2021-08-02T10:25:50.7034875Z FileNotFoundError: [Errno 2] No such file or directory
```

#### Describe the results you expected:
for arm64 build, need to use native dockerd for dockerfs. generate_shutdown_order.py needs to provide option.

docker **-H unix:///dockerfs/var/run/docker.sock** info

```
2021-08-02T10:25:50.6681234Z + sudo chroot ./fsroot-centec-arm64 docker -H unix:///dockerfs/var/run/docker.sock info
2021-08-02T10:25:50.6682684Z time="2021-08-02T10:23:06Z" level=error msg="failure getting variant" error="getCPUInfo for pattern: Cpu architecture: not found"
2021-08-02T10:25:50.6683298Z Containers: 0
2021-08-02T10:25:50.6683697Z  Running: 0
2021-08-02T10:25:50.6683938Z  Paused: 0
2021-08-02T10:25:50.6684193Z  Stopped: 0
2021-08-02T10:25:50.6684444Z Images: 0
2021-08-02T10:25:50.6684703Z Server Version: 20.10.7
2021-08-02T10:25:50.6685004Z Storage Driver: overlay2
2021-08-02T10:25:50.6685310Z  Backing Filesystem: extfs
2021-08-02T10:25:50.6685600Z  Supports d_type: true
2021-08-02T10:25:50.6686032Z  Native Overlay Diff: false
2021-08-02T10:25:50.6686361Z  userxattr: false
2021-08-02T10:25:50.6686981Z Logging Driver: json-file
2021-08-02T10:25:50.6687515Z Cgroup Driver: cgroupfs
2021-08-02T10:25:50.6688018Z Plugins:
2021-08-02T10:25:50.6688508Z  Volume: local
2021-08-02T10:25:50.6688980Z  Network: bridge host ipvlan macvlan null overlay
2021-08-02T10:25:50.6690223Z  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
2021-08-02T10:25:50.6690967Z Swarm: inactive
2021-08-02T10:25:50.6691327Z Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
2021-08-02T10:25:50.6691677Z Default Runtime: runc
2021-08-02T10:25:50.6692397Z Init Binary: docker-init
2021-08-02T10:25:50.6692991Z containerd version: e25210fe30a0a703442421b0f60afac609f950a3
2021-08-02T10:25:50.6693732Z runc version: v1.0.1-0-g4144b63
2021-08-02T10:25:50.6694164Z init version: de40ad0
2021-08-02T10:25:50.6694484Z Security Options:
2021-08-02T10:25:50.6694854Z  apparmor
2021-08-02T10:25:50.6695094Z  seccomp
2021-08-02T10:25:50.6695406Z   Profile: default
2021-08-02T10:25:50.6696010Z Kernel Version: 5.8.0-1039-azure
2021-08-02T10:25:50.6696518Z Operating System: Ubuntu 20.04.2 LTS
2021-08-02T10:25:50.6696994Z OSType: linux
2021-08-02T10:25:50.6697275Z Architecture: x86_64
2021-08-02T10:25:50.6697636Z CPUs: 8
2021-08-02T10:25:50.6697926Z Total Memory: 31.36GiB
2021-08-02T10:25:50.6698443Z Name: sonic-build-workers-0000F6
2021-08-02T10:25:50.6698852Z ID: 3ZK7:4GZQ:6BGX:WDVZ:MNLN:CJL6:DDD6:34NQ:B5ZV:XTAV:HYGA:7GHD
2021-08-02T10:25:50.6699266Z Docker Root Dir: /tmp/d/d/var/lib/docker/
2021-08-02T10:25:50.6699602Z Debug Mode (client): false
2021-08-02T10:25:50.6699904Z Debug Mode (server): false
2021-08-02T10:25:50.6700508Z Registry: https://index.docker.io/v1/
2021-08-02T10:25:50.6700973Z Labels:
2021-08-02T10:25:50.6701316Z Experimental: false
2021-08-02T10:25:50.6701599Z Insecure Registries:
2021-08-02T10:25:50.6701845Z  127.0.0.0/8
2021-08-02T10:25:50.6702119Z Live Restore Enabled: false
```

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by lguohan** [comment]
this affects armhf as well.
