### ISSUE TITLE
[202012 platform_tests] TestFanDrawerFans failures on vms20-t0-7050cx3-1

### ISSUE THREAD

**Issue by vdahiya12** [Azure/sonic-buildimage#8460]
#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vdahiya12** [comment]
on 2012 this seems to be problem.
RCA 
admin@10.3.146.65's password: 
Linux str2-7050cx3-acs-04 4.19.0-12-2-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
You are on
  ____   ___  _   _ _  ____
 / ___| / _ \| \ | (_)/ ___|
 \___ \| | | |  \| | | |
  ___) | |_| | |\  | | |___
 |____/ \___/|_| \_|_|\____|

-- Software for Open Networking in the Cloud --

Unauthorized access and/or use are prohibited.
All access and/or use are subject to monitoring.

Help:      http://azure.github.io/SONiC/
Wiki:      https://microsoft.sharepoint.com/teams/WAG/AzureNetworking/Wiki/SONiC.aspx
On-Call:   https://portal.microsofticm.com/imp/v3/oncall/current?serviceId=10045&teamIds=26162
Dashboard: https://aka.ms/sonic-dri
Contact:   sonicdev@microsoft.com

Last login: Fri Aug 13 18:07:40 2021 from 10.3.145.33
admin@str2-7050cx3-acs-04:~$ sudo python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> platform_chassis = sonic_platform.platform.Platform().get_chassis()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'sonic_platform' is not defined
>>> import sonic_platform.platform
>>> platform_chassis = sonic_platform.platform.Platform().get_chassis()
>>> m = platform_chassis.get_fan_drawer(0)
>>> s = (m.get_fan(0))
>>>  print(s.get_name())
  File "<stdin>", line 1
    print(s.get_name())
    ^
IndentationError: unexpected indent
>>> print(s.get_name())
Fan1
>>> exit()
admin@str2-7050cx3-acs-04:~$ show version

SONiC Software Version: SONiC.20201231.15
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: 1798fba1e0
Build date: Tue Aug 10 13:42:07 UTC 2021
Built by: AzDevOps@sonic-int-build-workers-0002K7

Platform: x86_64-arista_7050cx3_32s
HwSKU: Arista-7050CX3-32S-D48C8
ASIC: broadcom
ASIC Count: 1
Serial Number: JPE21030951
Uptime: 19:27:17 up 2 days, 22:29,  1 user,  load average: 0.30, 0.37, 0.51

admin@str2-7050cx3-acs-04:~$ 

admin@str2-7050cx3-acs-12:/usr/share/sonic/device/x86_64-arista_7050cx3_32s$ cd
admin@str2-7050cx3-acs-12:~$ sudo python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sonic_platform.platform
>>> import sonic_platform.platform

>>> platform_chassis = sonic_platform.platform.Platform().get_chassis()

                     

>>> m = platform_chassis.get_fan_drawer(0)
>>> m.get_name()
'slot1'
>>> m.get_fan()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_fan() missing 1 required positional argument: 'index'
>>> m.get_fan(0)
<arista.utils.sonic_platform.fan.Fan object at 0x7f21585ff550>
>>> dir(m.get_fan(0))
['DEFAULT_TOLERANCE', 'DEVICE_TYPE', 'FAN_DIRECTION_EXHAUST', 'FAN_DIRECTION_INTAKE', 'FAN_DIRECTION_NOT_APPLICABLE', 'STATUS_LED_COLOR_AMBER', 'STATUS_LED_COLOR_GREEN', 'STATUS_LED_COLOR_OFF', 'STATUS_LED_COLOR_RED', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_fan', '_parent', '_target_speed', 'fanDirectionConversion', 'get_direction', 'get_interrupt_file', 'get_model', 'get_name', 'get_position_in_parent', 'get_presence', 'get_revision', 'get_serial', 'get_speed', 'get_speed_tolerance', 'get_status', 'get_status_led', 'get_target_speed', 'is_replaceable', 'set_speed', 'set_status_led']
>>> s = (m.get_fan(0))
>>> print(s.get_name())
fan1
>>> exit()
admin@str2-7050cx3-acs-12:~$ show version

SONiC Software Version: SONiC.master.0-a53f01df5
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: a53f01df5
Build date: Thu Aug 12 06:01:12 UTC 2021
Built by: vdahiya@vdahiya-vm2

Platform: x86_64-arista_7050cx3_32s
HwSKU: Arista-7050CX3-32S-D48C8
ASIC: broadcom
ASIC Count: 1
Serial Number: JPE21130975
Model Number: DCS-7050CX3-32S
Hardware Revision: N/A
Uptime: 19:24:56 up 23:22,  1 user,  load average: 0.90, 0.64, 0.52
