### ISSUE TITLE
[TH3] [Platform API] "watchdogutil arm 5" not working on z9332F platforms

### ISSUE THREAD

**Issue by gechiang** [Azure/sonic-buildimage#8534]
#### Description
While running reboot_test testcase against a z9332f DUT the testcase failed executing watchdog reboot test:
```
platform_tests/test_reboot.py::test_watchdog_reboot[str2-z9332f-05]
--------------------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------------------
19:20:35 reboot.reboot                            L0143 ERROR  | reboot result: {'stderr_lines': [], u'cmd': [u'watchdogutil', u'arm', u'-s', u'5'], u'end': u'2021-08-19 19:15:38.021751', '_ansible_no_log': False, u'stdout': u'Watchdog armed for 30 seconds', u'changed': True, u'rc': 0, u'start': u'2021-08-19 19:15:35.406950', u'stderr': u'', u'delta': u'0:00:02.614801', u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': False, u'strip_empty_ends': True, u'_raw_params': u'watchdogutil arm -s 5', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin_add_newline': True, u'stdin': None}}, 'stdout_lines': [u'Watchdog armed for 30 seconds'], 'failed': False} on str2-z9332f-05
19:20:35 __init__.pytest_runtest_call             L0039 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/var/src/Networking-acs-sonic-mgmt/tests/platform_tests/test_reboot.py", line 248, in test_watchdog_reboot
    reboot_and_check(localhost, duthost, conn_graph_facts["device_conn"][duthost.hostname], xcvr_skip_list, REBOOT_TYPE_WATCHDOG)
  File "/var/src/Networking-acs-sonic-mgmt/tests/platform_tests/test_reboot.py", line 60, in reboot_and_check
    reboot(dut, localhost, reboot_type=reboot_type, reboot_helper=reboot_helper, reboot_kwargs=reboot_kwargs)
  File "/var/src/Networking-acs-sonic-mgmt/tests/common/reboot.py", line 144, in reboot
    raise Exception('DUT {} did not shutdown'.format(hostname))
Exception: DUT str2-z9332f-05 did not shutdown
```
It looks like this platform is not honoring any "time" specification as part of the API parameter:
Also it appears even with default 180 second it is not taking effect...

```
admin@str2-z9332f-05:~$ sudo watchdogutil arm -s 5
Watchdog armed for 30 seconds
admin@str2-z9332f-05:~$
admin@str2-z9332f-05:~$ date
Fri 20 Aug 2021 01:34:07 AM UTC
admin@str2-z9332f-05:~$ date
Fri 20 Aug 2021 01:34:19 AM UTC
admin@str2-z9332f-05:~$ date
Fri 20 Aug 2021 01:34:30 AM UTC
admin@str2-z9332f-05:~$ date
Fri 20 Aug 2021 01:34:40 AM UTC
admin@str2-z9332f-05:~$ date
Fri 20 Aug 2021 01:34:48 AM UTC
admin@str2-z9332f-05:~$ date
Fri 20 Aug 2021 01:34:58 AM UTC
admin@str2-z9332f-05:~$ date
Fri 20 Aug 2021 01:35:04 AM UTC
admin@str2-z9332f-05:~$ date
Fri 20 Aug 2021 01:35:06 AM UTC
admin@str2-z9332f-05:~$ date
Fri 20 Aug 2021 01:35:07 AM UTC
admin@str2-z9332f-05:~$
```

#### Steps to reproduce the issue:
1. run the test_reboot testcase and observe the watchdog test failure OR just issue the mentioned API on the DUT directly to see parameter is not honored... it did not trigger a watchdog shutdown after 30 seconds.
2.
3.

#### Describe the results you expected:
Expect the utility to allow user specify the time and shutdown triggered.

#### Output of `show version`:
```
admin@str2-z9332f-05:~$ show ver

SONiC Software Version: SONiC.20201231.18
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: 67ec0a56e3
Build date: Wed Aug 18 14:13:16 UTC 2021
Built by: AzDevOps@sonic-int-build-workers-0002UW

Platform: x86_64-dellemc_z9332f_d1508-r0
HwSKU: DellEMC-Z9332f-M-O16C64
ASIC: broadcom
ASIC Count: 1
Serial Number: TH04CN21CET0004K0123
Uptime: 01:29:25 up  5:53,  1 user,  load average: 0.52, 0.99, 1.21

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by gechiang** [comment]
@sujinmkang Please help track this issue with the DELL team.
Thanks!
