### ISSUE TITLE
[warm-reboot] Warm upgrade from 201811 to 202012 on SN-2700 results in SDK error and orchagent crash

### ISSUE THREAD

**Issue by tjchadaga** [Azure/sonic-buildimage#8570]
#### Description

Warm-reboot with upgrade from 201811 to 202012 on Mellanox-SN2700 platform failed with SDK errors while getting attribute SAI_PORT_ATTR_ADMIN_STATE. This resulted in orchagent crash

#### Steps to reproduce the issue:
1. warm-reboot -f on SN2700 loaded with 201811 image, next image set to 202012

#### Describe the results you received:
SDK errors in syslog:

```
Aug 23 19:39:31.238374 str-msn2700-20 ERR syncd#SDK: [PORT.ERR] Can't get Port 0x00013D00 state when port is swid-unbound. (Entry Not Bound)
Aug 23 19:39:31.239509 str-msn2700-20 ERR syncd#SDK: [SAI_PORT.ERR] mlnx_sai_port.c[1764]- mlnx_port_state_get: Failed to get port state - Entry Not Bound.
Aug 23 19:39:31.239689 str-msn2700-20 ERR syncd#SDK: [SAI_UTILS.ERR] mlnx_sai_utils.c[2268]- get_dispatch_attribs_handler: Failed getting attrib SAI_PORT_ATTR_ADMIN_STATE
Aug 23 19:39:31.239829 str-msn2700-20 ERR syncd#SDK: [SAI_UTILS.ERR] mlnx_sai_utils.c[2386]- sai_get_attributes: Failed attribs dispatch
Aug 23 19:39:31.240478 str-msn2700-20 NOTICE swss#portsyncd: :- onMsg: nlmsg type:16 key:Ethernet0 admin:0 oper:0 addr:1c:34:da:eb:bd:00 ifindex:50 master:0 type:sx_netdev
Aug 23 19:39:31.240619 str-msn2700-20 NOTICE swss#portsyncd: :- onMsg: Publish Ethernet0(ok) to state db
Aug 23 19:39:31.240736 str-msn2700-20 NOTICE swss#orchagent: :- addHostIntfs: Create host interface for port Ethernet0
Aug 23 19:39:31.240850 str-msn2700-20 ERR swss#orchagent: :- getPortAdminStatus: Failed to get admin status for port pid:1000000000576
Aug 23 19:39:31.240963 str-msn2700-20 ERR swss#orchagent: :- initializePort: Failed to get initial port admin status Ethernet0
Aug 23 19:39:31.241074 str-msn2700-20 ERR swss#orchagent: :- initPort: Failed to initialize port Ethernet0
Aug 23 19:39:31.241823 str-msn2700-20 INFO swss#/supervisord: orchagent terminate called after throwing an instance of 'std::runtime_error'
Aug 23 19:39:31.242087 str-msn2700-20 INFO swss#/supervisord: orchagent what(): PortsOrch initialization failure.
```
Orchagent crash:
```
Core was generated by `/usr/bin/orchagent -d /var/log/swss -b 8192 -s'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f987a2ff7bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x7f9879effbc0 (LWP 41))]
(gdb) bt
#0  0x00007f987a2ff7bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f987a2ea535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f987a6b4983 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f987a6ba8c6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f987a6ba901 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f987a6bab34 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000055e7c0567edc in PortsOrch::doPortTask (this=0x55e7c11d98a0, consumer=...) at /usr/include/c++/8/ext/new_allocator.h:86
#7  0x000055e7c05ff076 in PortsOrch::doTask (this=0x55e7c11d98a0, consumer=...) at portsorch.cpp:3335
#8  0x000055e7c05ec9f1 in PortsOrch::doTask (this=0x55e7c11d98a0) at /usr/include/c++/8/ext/new_allocator.h:81
#9  0x000055e7c05a73fb in OrchDaemon::warmRestoreAndSyncUp (this=0x55e7c11cea80) at orchdaemon.cpp:633
#10 0x000055e7c05aa326 in OrchDaemon::init (this=this@entry=0x55e7c11cea80) at orchdaemon.cpp:482
#11 0x000055e7c0585c0f in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:411

```
#### Output of `show version`:

```
SONiC Software Version: SONiC.20201231.16
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: decfa37df2
Build date: Wed Aug 11 17:02:31 UTC 2021
Built by: AzDevOps@sonic-int-build-workers-0002KZ

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700-D48C8
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2028X35361
Uptime: 20:12:03 up 33 min,  4 users,  load average: 3.15, 2.40, 1.80

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-mlnx          20201231.16         528d8d8b9cba        951MB
docker-syncd-mlnx          latest              528d8d8b9cba        951MB
docker-teamd               20201231.16         cc6e6686072d        412MB
docker-teamd               latest              cc6e6686072d        412MB
docker-router-advertiser   20201231.16         90910f68b4f8        402MB
docker-router-advertiser   latest              90910f68b4f8        402MB
docker-platform-monitor    20201231.16         12337850a855        723MB
docker-platform-monitor    latest              12337850a855        723MB
docker-lldp                20201231.16         e82cbcf99b6d        442MB
docker-lldp                latest              e82cbcf99b6d        442MB
docker-database            20201231.16         a8084f82c7c1        402MB
docker-database            latest              a8084f82c7c1        402MB
docker-orchagent           20201231.16         dfc57b884cbd        431MB
docker-orchagent           latest              dfc57b884cbd        431MB
docker-snmp                20201231.16         468cf280dd36        443MB
docker-snmp                latest              468cf280dd36        443MB
docker-sonic-telemetry     20201231.16         fdbd5b46b9b6        491MB
docker-sonic-telemetry     latest              fdbd5b46b9b6        491MB
docker-dhcp-relay          20201231.16         b07c78456555        409MB
docker-dhcp-relay          latest              b07c78456555        409MB
docker-mux                 20201231.16         ef605c8b0c04        454MB
docker-mux                 latest              ef605c8b0c04        454MB
docker-fpm-frr             20201231.16         0e3b235d1b25        430MB
docker-fpm-frr             latest              0e3b235d1b25        430MB
docker-sonic-restapi       20201231.16         21f1ef8bdaa1        352MB
docker-sonic-restapi       latest              21f1ef8bdaa1        352MB
docker-acms                20201231.16         afb6eac3b1c7        197MB
docker-acms                latest              afb6eac3b1c7        197MB
k8s.gcr.io/pause           3.4.1               0f8457a4c2ec        683kB
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

[mellanox - 2700.zip](https://github.com/Azure/sonic-buildimage/files/7042214/mellanox.-.2700.zip)

**Comment by zhangyanzhao** [comment]
@volodymyrsamotiy would you please update this ticket with your finding and ETA? Thanks.

**Comment by qiluo-msft** [comment]
@prsunny would you like to close this issue?

**Comment by tjchadaga** [comment]
Issue is resolved
