### ISSUE TITLE
Build Failure: 202012 [ Broadcom] "Make all" fails 

### ISSUE THREAD

**Issue by ksubashh** [Azure/sonic-buildimage#8751]
#### Description

     Tried to make all for broadcom Platform [202012].
Getting dh_install failed error

#### Steps to reproduce the issue:
1. cd sonic-buildimage
2. make init
3.make configure PLATFORM=broadcom
4. Make all

#### Describe the results you received:

ake[2]: Leaving directory '/sonic/platform/broadcom/sonic-platform-modules-dell'
   dh_install
cat: '/sys/class/i2c-adapter/i2c-2/i2c-11/11-004c/hwmon/hwmon*/temp1_max': No such file or directory
cat: '/sys/class/i2c-adapter/i2c-2/i2c-11/11-004d/hwmon/hwmon*/temp1_max': No such file or directory
cat: '/sys/class/i2c-adapter/i2c-2/i2c-11/11-004e/hwmon/hwmon*/temp1_max': No such file or directory
s6000/scripts/fancontrol.sh: line 68: /sys/class/i2c-adapter/i2c-2/i2c-11/11-004c/hwmon/hwmon*/temp1_max: No such file or directory
s6000/scripts/fancontrol.sh: line 69: /sys/class/i2c-adapter/i2c-2/i2c-11/11-004d/hwmon/hwmon*/temp1_max: No such file or directory
s6000/scripts/fancontrol.sh: line 70: /sys/class/i2c-adapter/i2c-2/i2c-11/11-004e/hwmon/hwmon*/temp1_max: No such file or directory
s6000/systemd/platform-modules-s6000.service: 1: s6000/systemd/platform-modules-s6000.service: [Unit]: not found
s6000/systemd/platform-modules-s6000.service: 2: s6000/systemd/platform-modules-s6000.service: S6000: not found
s6000/systemd/platform-modules-s6000.service: 4: s6000/systemd/platform-modules-s6000.service: determine-reboot-cause.service: not found
s6000/systemd/platform-modules-s6000.service: 6: s6000/systemd/platform-modules-s6000.service: [Service]: not found
Couldn't find an alternative telinit implementation to spawn.
s6000/systemd/platform-modules-s6000.service: 9: s6000/systemd/platform-modules-s6000.service: deinit: not found
s6000/systemd/platform-modules-s6000.service: 12: s6000/systemd/platform-modules-s6000.service: [Install]: not found
s6000/systemd/fancontrol.service: 1: s6000/systemd/fancontrol.service: [Unit]: not found
s6000/systemd/fancontrol.service: 2: s6000/systemd/fancontrol.service: S6000: not found
s6000/systemd/fancontrol.service: 6: s6000/systemd/fancontrol.service: [Service]: not found
s6000/systemd/fancontrol.service: 11: s6000/systemd/fancontrol.service: [Install]: not found
Traceback (most recent call last):
  File "s6000/scripts/platform_reboot_override", line 27, in <module>
    io_reg_write(PORT_RES, RESET_REG, COLD_RESET)
  File "s6000/scripts/platform_reboot_override", line 12, in io_reg_write
    fd = os.open(resource, os.O_RDWR)
PermissionError: [Errno 13] Permission denied: '/dev/port'
Traceback (most recent call last):
  File "s6000/scripts/platform_update_reboot_cause", line 25, in <module>
    io_reg_write(NVRAM_RES, 0x49, COLD_RESET)
  File "s6000/scripts/platform_update_reboot_cause", line 11, in io_reg_write
    fd = os.open(resource, os.O_RDWR)
PermissionError: [Errno 13] Permission denied: '/dev/nvram'
s6000/scripts/override.conf: 1: s6000/scripts/override.conf: [Service]: not found
/sonic/platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6000.install: 11: /sonic/platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6000.install: s6000/modules/sonic_platform-1.0-py2-none-any.whl: Permission denied
/sonic/platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6000.install: 12: /sonic/platform/broadcom/sonic-platform-modules-dell/debian/platform-modules-s6000.install: s6000/modules/sonic_platform-1.0-py3-none-any.whl: Permission denied
dh_install: debian/platform-modules-s6000.install is marked executable but does not appear to an executable config.
dh_install:
dh_install: If debian/platform-modules-s6000.install is intended to be an executable config file, please ensure it can
dh_install: be run as a stand-alone script/program (e.g. "./debian/platform-modules-s6000.install")
dh_install: Otherwise, please remove the executable bit from the file (e.g. chmod -x "debian/platform-modules-s6000.install")
dh_install:
dh_install: Please see "Executable debhelper config files" in debhelper(7) for more information.
dh_install:
dh_install: debian/platform-modules-s6000.install (executable config) returned exit code 126
make[1]: *** [debian/rules:12: binary] Error 25
make[1]: Leaving directory '/sonic/platform/broadcom/sonic-platform-modules-dell'
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
[  FAIL LOG END  ] [ target/debs/buster/platform-modules-z9100_1.1_amd64.deb ]
make: *** [slave.mk:466: target/debs/buster/platform-modules-z9100_1.1_amd64.deb] Error 1
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Makefile.work:289: recipe for target 'all' failed
make[1]: *** [all] Error 2

Anything missing from my end?

**Comment by ksubashh** [comment]
Issue resolved
