### ISSUE TITLE
[AS7326-56x] syncd does not start up after a clean install. switch creation failure.

### ISSUE THREAD

**Issue by zebracrowd** [Azure/sonic-buildimage#9177]
#### Description

orchagent and syncd fail to startup on the as7326 platform (cannot check on other accton devices at this time). This is a switch just imaged and not configured yet. The image is compiled from the master branch. 

The last commit for which i can start the switch normally is: a99d78dedb838644d13150f5946a962a80ebacab
The sai update that follows seems to be the cause/trigger.

#### Steps to reproduce the issue:
1. onie uninstall nos
2. onie install sonic-broadcom.bin
3. look at syslog and witness the fail loop

#### Describe the results you received:

The system logs show:

Sep 27 15:50:25.590944 sonic DEBUG syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_log_set:470 SAI Enter sai_log_set
Sep 27 15:50:25.591667 sonic NOTICE syncd#syncd: :- Syncd: command line:  EnableDiagShell=YES EnableTempView=YES DisableExitSleep=NO EnableUnittests=NO EnableConsistency
Check=NO EnableSyncMode=YES RedisCommunicationMode=redis_async EnableSaiBulkSuport=NO StartType=cold ProfileMapFile=/etc/sai.d/sai.profile GlobalContext=0 ContextConfig=
 BreakConfig=
Sep 27 15:50:25.591700 sonic NOTICE syncd#syncd: :- loadFromFile: no context config specified, will load default context config
Sep 27 15:50:25.591700 sonic NOTICE syncd#syncd: :- insert: added switch: idx 0, hwinfo ''
Sep 27 15:50:25.591700 sonic WARNING syncd#syncd: :- Syncd: enable sync mode is deprecated, please use communication mode, FORCING redis sync mode
Sep 27 15:50:25.593073 sonic NOTICE syncd#syncd: :- RedisSelectableChannel: opened redis channel
Sep 27 15:50:25.594725 sonic NOTICE syncd#syncd: :- isVeryFirstRun: First Run: True
Sep 27 15:50:25.595432 sonic INFO syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_initialize:364 BRCM SAI ver: [6.0.0.10], OCP SAI ver: [1.9.1], SDK ver: [sdk-6.5.23]
Sep 27 15:50:25.595454 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:413 Invalid sai_api_t 47 passed to sai_api_query
Sep 27 15:50:25.596655 sonic NOTICE syncd#syncd: :- sai_metadata_apis_query: :- failed to query api SAI_API_BMTOR: SAI_STATUS_INVALID_PARAMETER (-5)
Sep 27 15:50:25.596720 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:413 Invalid sai_api_t 46 passed to sai_api_query
Sep 27 15:50:25.596720 sonic NOTICE syncd#syncd: :- sai_metadata_apis_query: :- failed to query api SAI_API_IPSEC: SAI_STATUS_INVALID_PARAMETER (-5)
Sep 27 15:50:25.596734 sonic NOTICE syncd#syncd: :- sai_metadata_apis_query: :- failed to query api SAI_API_MY_MAC: SAI_STATUS_NOT_IMPLEMENTED (-15)
Sep 27 15:50:25.596734 sonic NOTICE syncd#syncd: :- initialize: sai_api_query failed for 3 apis
Sep 27 15:50:25.596758 sonic NOTICE syncd#syncd: :- Syncd: syncd started
Sep 27 15:50:25.596893 sonic NOTICE syncd#syncd: :- onSyncdStart: performing hard reinit since COLD start was performed
Sep 27 15:50:25.597019 sonic NOTICE syncd#syncd: :- readAsicState: loaded 0 switches
Sep 27 15:50:25.597033 sonic NOTICE syncd#syncd: :- readAsicState: read asic state took 0.000128 sec
Sep 27 15:50:25.597121 sonic NOTICE syncd#syncd: :- onSyncdStart: hard reinit succeeded
Sep 27 15:50:25.597134 sonic NOTICE syncd#syncd: :- onSyncdStart: on syncd start took 0.000254 sec
Sep 27 15:50:25.597230 sonic NOTICE syncd#syncd: :- run: syncd listening for events
Sep 27 15:50:25.597242 sonic NOTICE syncd#syncd: :- run: starting main loop

...

Sep 27 15:50:27.265857 sonic WARNING kernel: [   43.929752] linux-bcm-knet (5791): bkn_knet_dev_inst_set sinfo->inst_id -1 d 0 inst -1
Sep 27 15:50:27.265892 sonic WARNING kernel: [   43.929762] linux-bcm-knet (5848): bkn_get_next_dma_event dev 0 evt_idx 0
Sep 27 15:50:27.265896 sonic WARNING kernel: [   43.929766] linux-bcm-knet (5848): dev_no 0 dev_evt 0 wait queue index 0
Sep 27 15:50:27.265898 sonic WARNING kernel: [   43.930087] linux-kernel-bde (5791): _interrupt_connect d 0
Sep 27 15:50:27.265901 sonic WARNING kernel: [   43.930088] linux-kernel-bde (5791): _interrupt_connect:isr_active = 1
Sep 27 15:50:27.265903 sonic WARNING kernel: [   43.930089] linux-kernel-bde (5791): connect secondary isr
Sep 27 15:50:27.438665 sonic ERR syncd#syncd: [none] SAI_API_SWITCH:platform_process_command:443 Platform command "init bcm" failed, rc = -1.
Sep 27 15:50:27.438665 sonic CRIT syncd#syncd: [none] SAI_API_SWITCH:platformInit:2046 initialization command "init bcm" failed, rc = -1 (Internal error).
Sep 27 15:50:27.438665 sonic CRIT syncd#syncd: [none] SAI_API_SWITCH:sai_driver_init:531 Error initializing driver, rc = -1.
Sep 27 15:50:27.438665 sonic CRIT syncd#syncd: [none] SAI_API_SWITCH:brcm_sai_create_switch:1115 initializing SDK failed with error Operation failed (0xfffffff5).
Sep 27 15:50:27.438665 sonic ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_CREATE failed in syncd mode: SAI_STATUS_FAILURE
Sep 27 15:50:27.438948 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_INIT_SWITCH: true
Sep 27 15:50:27.438948 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_FDB_EVENT_NOTIFY: 0x5611967d85b0
Sep 27 15:50:27.438948 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_PORT_STATE_CHANGE_NOTIFY: 0x5611967d85c0
Sep 27 15:50:27.438948 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_SWITCH_SHUTDOWN_REQUEST_NOTIFY: 0x5611967d85d0
Sep 27 15:50:27.438978 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_SRC_MAC_ADDRESS: B8:6A:97:E2:58:9C
Sep 27 15:50:27.439311 sonic ERR swss#orchagent: :- create: create status: SAI_STATUS_FAILURE
Sep 27 15:50:27.439341 sonic ERR swss#orchagent: :- main: Failed to create a switch, rv:-1

#### Describe the results you expected:

Without any specific configuration, the switch should come up and the orchagent/syncd services should not fail loop

#### Output of `show version`:

admin@sonic:~$ show version

SONiC Software Version: SONiC.HEAD.0-dirty-20211104.093945
Distribution: Debian 10.11
Kernel: 4.19.0-12-2-amd64
Build commit: 10fab1356
Build date: Thu Nov  4 18:47:20 UTC 2021
Built by: jnormand@test4

Platform: x86_64-accton_as7326_56x-r0
HwSKU: Accton-AS7326-56X
ASIC: broadcom
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 16:02:01 up 12 min,  2 users,  load average: 0.31, 0.42, 0.38

Docker images:
REPOSITORY                    TAG                            IMAGE ID            SIZE
docker-dhcp-relay             latest                         95dc5f4212be        435MB
docker-platform-monitor       HEAD.0-dirty-20211104.093945   1e93804feff8        685MB
docker-platform-monitor       latest                         1e93804feff8        685MB
docker-snmp                   HEAD.0-dirty-20211104.093945   cc425a2cada5        464MB
docker-snmp                   latest                         cc425a2cada5        464MB
docker-fpm-frr                HEAD.0-dirty-20211104.093945   358306d71f5b        452MB
docker-fpm-frr                latest                         358306d71f5b        452MB
docker-lldp                   HEAD.0-dirty-20211104.093945   b0f3438b4ef3        462MB
docker-lldp                   latest                         b0f3438b4ef3        462MB
docker-syncd-brcm             HEAD.0-dirty-20211104.093945   d1bed553e375        738MB
docker-syncd-brcm             latest                         d1bed553e375        738MB
docker-gbsyncd-credo          HEAD.0-dirty-20211104.093945   04d4c47fba73        470MB
docker-gbsyncd-credo          latest                         04d4c47fba73        470MB
docker-sonic-mgmt-framework   HEAD.0-dirty-20211104.093945   0e24237bd1fd        576MB
docker-sonic-mgmt-framework   latest                         0e24237bd1fd        576MB
docker-database               HEAD.0-dirty-20211104.093945   2e5be4b961e7        422MB
docker-database               latest                         2e5be4b961e7        422MB
docker-orchagent              HEAD.0-dirty-20211104.093945   479b13c4b613        452MB
docker-orchagent              latest                         479b13c4b613        452MB
docker-nat                    HEAD.0-dirty-20211104.093945   78d179985f69        437MB
docker-nat                    latest                         78d179985f69        437MB
docker-sflow                  HEAD.0-dirty-20211104.093945   9700770014b1        435MB
docker-sflow                  latest                         9700770014b1        435MB
docker-macsec                 HEAD.0-dirty-20211104.093945   a13489f17e46        437MB
docker-macsec                 latest                         a13489f17e46        437MB
docker-teamd                  HEAD.0-dirty-20211104.093945   12ccf9613a91        434MB
docker-teamd                  latest                         12ccf9613a91        434MB
docker-sonic-telemetry        HEAD.0-dirty-20211104.093945   db23dd04ca17        510MB
docker-sonic-telemetry        latest                         db23dd04ca17        510MB
docker-router-advertiser      HEAD.0-dirty-20211104.093945   51ff57231304        422MB
docker-router-advertiser      latest                         51ff57231304        422MB
docker-mux                    HEAD.0-dirty-20211104.093945   d820145a0d93        474MB
docker-mux                    latest                         d820145a0d93        474MB

**Comment by zebracrowd** [comment]
[sonic_dump_sonic_20210927_160239.tar.gz](https://github.com/Azure/sonic-buildimage/files/7479363/sonic_dump_sonic_20210927_160239.tar.gz)
show techsupport

**Comment by toreanderson** [comment]
Can confirm. Lastest `master` does not work. I have tried:

* `SONiC.master.46904-dirty-20211028.153400` (the version linked from https://github.com/Azure/SONiC/wiki/Supported-Devices-and-Platforms)
* `SONiC.master.49714-dirty-20211109.140810` (the last build available from https://sonic-build.azurewebsites.net/ui/sonic/pipelines/138/builds?branchName=master at the time of writing)

Latest available pre-built image that works appears to be `SONiC.202106.49731-99724508f` (available from https://sonic-build.azurewebsites.net/ui/sonic/pipelines/138/builds?branchName=202106).

# Debug info

Below is the debug info requested at https://github.com/azure/sonic/wiki#report-issues

## `show version`

```
SONiC Software Version: SONiC.master.49714-dirty-20211109.140810
Distribution: Debian 10.11
Kernel: 4.19.0-12-2-amd64
Build commit: 07038a022
Build date: Tue Nov  9 14:24:03 UTC 2021
Built by: AzDevOps@sonic-build-workers-000VIO

Platform: x86_64-accton_as7326_56x-r0
HwSKU: Accton-AS7326-56X
ASIC: broadcom
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 15:48:35 up 24 min,  1 user,  load average: 0.95, 0.34, 0.23

Docker images:
REPOSITORY                    TAG                                  IMAGE ID            SIZE
docker-dhcp-relay             latest                               61623582cc8d        435MB
docker-platform-monitor       latest                               fc6f5bd0d309        686MB
docker-platform-monitor       master.49714-dirty-20211109.140810   fc6f5bd0d309        686MB
docker-snmp                   latest                               8b9de827de7d        464MB
docker-snmp                   master.49714-dirty-20211109.140810   8b9de827de7d        464MB
docker-sflow                  latest                               e636a9f90367        435MB
docker-sflow                  master.49714-dirty-20211109.140810   e636a9f90367        435MB
docker-teamd                  latest                               06f9f3e16f76        434MB
docker-teamd                  master.49714-dirty-20211109.140810   06f9f3e16f76        434MB
docker-macsec                 latest                               70522b28a5de        437MB
docker-macsec                 master.49714-dirty-20211109.140810   70522b28a5de        437MB
docker-lldp                   latest                               162a52385c4c        462MB
docker-lldp                   master.49714-dirty-20211109.140810   162a52385c4c        462MB
docker-sonic-mgmt-framework   latest                               2d3ffa0e1786        577MB
docker-sonic-mgmt-framework   master.49714-dirty-20211109.140810   2d3ffa0e1786        577MB
docker-database               latest                               97325b1db068        422MB
docker-database               master.49714-dirty-20211109.140810   97325b1db068        422MB
docker-orchagent              latest                               59a93df8ad6d        453MB
docker-orchagent              master.49714-dirty-20211109.140810   59a93df8ad6d        453MB
docker-nat                    latest                               188f29736bc3        437MB
docker-nat                    master.49714-dirty-20211109.140810   188f29736bc3        437MB
docker-sonic-telemetry        latest                               748390874646        510MB
docker-sonic-telemetry        master.49714-dirty-20211109.140810   748390874646        510MB
docker-fpm-frr                latest                               af74019793f3        452MB
docker-fpm-frr                master.49714-dirty-20211109.140810   af74019793f3        452MB
docker-mux                    latest                               c2e32855b282        474MB
docker-mux                    master.49714-dirty-20211109.140810   c2e32855b282        474MB
docker-syncd-brcm             latest                               b771aea35bf1        738MB
docker-syncd-brcm             master.49714-dirty-20211109.140810   b771aea35bf1        738MB
docker-gbsyncd-credo          latest                               51e3fb711b85        470MB
docker-gbsyncd-credo          master.49714-dirty-20211109.140810   51e3fb711b85        470MB
docker-router-advertiser      latest                               8aefb5962d1e        422MB
docker-router-advertiser      master.49714-dirty-20211109.140810   8aefb5962d1e        422MB
```

## `show techsupport`

[sonic_dump_l1-g5-osl2.n.bitbit.net_20211110_154900.tar.gz](https://github.com/Azure/sonic-buildimage/files/7514073/sonic_dump_l1-g5-osl2.n.bitbit.net_20211110_154900.tar.gz)

## `sudo generate_dump`

[sonic_dump_l1-g5-osl2.n.bitbit.net_20211110_155216.tar.gz](https://github.com/Azure/sonic-buildimage/files/7514087/sonic_dump_l1-g5-osl2.n.bitbit.net_20211110_155216.tar.gz)


This script output a few error messages to the console while it was running:

```
Traceback (most recent call last):
  File "/usr/local/bin/portstat", line 662, in <module>
    main()
  File "/usr/local/bin/portstat", line 653, in main
    portstat.cnstat_print(cnstat_dict, ratestat_dict, intf_list, use_json, print_all, errors_only, rates_only, detail)
  File "/usr/local/bin/portstat", line 319, in cnstat_print
    print(tabulate(table, header, tablefmt='simple', stralign='right'))
  File "/usr/local/lib/python3.7/dist-packages/tabulate.py", line 1247, in tabulate
    tabular_data, headers, showindex=showindex)
  File "/usr/local/lib/python3.7/dist-packages/tabulate.py", line 932, in _normalize_tabular_data
    headers = list(map(_text_type,headers))
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/bin/decode-syseeprom", line 18, in <module>
    import sonic_platform
ModuleNotFoundError: No module named 'sonic_platform'
can't get debug descriptor: Resource temporarily unavailable
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
ERR: RC:-1 observed on line 466
conntrack v1.4.5 (conntrack-tools): 0 flow entries have been shown.
conntrack v1.4.5 (conntrack-tools): 0 flow entries have been shown.
conntrack v1.4.5 (conntrack-tools): 381 flow entries have been shown.
conntrack v1.4.5 (conntrack-tools): 381 flow entries have been shown.
bfdd is not running
bfdd is not running
bfdd is not running
bfdd is not running
Error response from daemon: Container 5ef255a8d25124b978ec39d0b5caefa2632bfb16fcefaaff9a0265e3ecd0fe4a is not running
Error response from daemon: Container 5ef255a8d25124b978ec39d0b5caefa2632bfb16fcefaaff9a0265e3ecd0fe4a is not running
Command: sudo docker exec syncd touch /var/log/diagrun.log timedout after 5 minutes.
Command: sudo docker cp syncd:/var/log/diagrun.log /var/log/diagrun.log timedout after 5 minutes.
Error response from daemon: Container 5ef255a8d25124b978ec39d0b5caefa2632bfb16fcefaaff9a0265e3ecd0fe4a is not running
Command: sudo docker exec syncd touch /var/log/bcm_diag_post timedout after 5 minutes.
Error: No such container:path: syncd:/var/log/bcm_diag_post
Command: sudo docker cp syncd:/var/log/bcm_diag_post /var/log/bcm_diag_post timedout after 5 minutes.
Traceback (most recent call last):
  File "/usr/local/bin/portstat", line 662, in <module>
    main()
  File "/usr/local/bin/portstat", line 653, in main
    portstat.cnstat_print(cnstat_dict, ratestat_dict, intf_list, use_json, print_all, errors_only, rates_only, detail)
  File "/usr/local/bin/portstat", line 319, in cnstat_print
    print(tabulate(table, header, tablefmt='simple', stralign='right'))
  File "/usr/local/lib/python3.7/dist-packages/tabulate.py", line 1247, in tabulate
    tabular_data, headers, showindex=showindex)
  File "/usr/local/lib/python3.7/dist-packages/tabulate.py", line 932, in _normalize_tabular_data
    headers = list(map(_text_type,headers))
TypeError: 'NoneType' object is not iterable
Remove secret from etc files.
sed: can't read /var/dump/sonic_dump_l1-g5-osl2.n.bitbit.net_20211110_155216/etc/pam_radius_auth.d/*.conf: No such file or directory
HW Mgmt dump script /usr/bin/hw-management-generate-dump.sh does not exist
```

**Comment by zhangyanzhao** [comment]
Possibly because the SAI header issue, can you please retry the latest image.

**Comment by toreanderson** [comment]
@zhangyanzhao I have now tested [SONiC.master.50075-dirty-20211110.132837](https://sonic-build.azurewebsites.net/ui/sonic/pipelines/138/builds/50075/artifacts/96082?branchName=master&artifactName=sonic-buildimage.broadcom), which is the latest image at the time of writing. I do not see any improvement, unfortunately:

```
admin@l1-g5-osl2:~$ sudo accton_as7326_util.py show
System's not ready.
Please install first!
admin@l1-g5-osl2:~$ sudo accton_as7326_util.py install
Checking system....
No driver, installing....
Failed :modprobe accton_i2c_cpld
admin@l1-g5-osl2:~$ sudo accton_as7326_util.py show
System's not ready.
Please install first!
admin@l1-g5-osl2:~$ show interfaces status
  Interface    Lanes    Speed    MTU    FEC    Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  -------  -------  -----  -----  -------  ------  ------  -------  ------  ----------
admin@l1-g5-osl2:~$ sudo docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED              STATUS                      PORTS               NAMES
87a6cc243d33        docker-snmp:latest                   "/usr/local/bin/supe…"   About a minute ago   Up About a minute                               snmp
04489ee041a2        docker-sonic-telemetry:latest        "/usr/local/bin/supe…"   About a minute ago   Up About a minute                               telemetry
8d050062cd65        docker-sonic-mgmt-framework:latest   "/usr/local/bin/supe…"   About a minute ago   Up About a minute                               mgmt-framework
84c3678465c7        docker-router-advertiser:latest      "/usr/bin/docker-ini…"   4 minutes ago        Exited (0) 35 seconds ago                       radv
2a5ad950547f        docker-lldp:latest                   "/usr/bin/docker-lld…"   4 minutes ago        Up 4 minutes                                    lldp
c9d8384ad837        docker-syncd-brcm:latest             "/usr/local/bin/supe…"   4 minutes ago        Exited (0) 30 seconds ago                       syncd
849cec49591f        docker-teamd:latest                  "/usr/local/bin/supe…"   4 minutes ago        Exited (0) 37 seconds ago                       teamd
50a2518ddea9        docker-orchagent:latest              "/usr/bin/docker-ini…"   4 minutes ago        Exited (0) 44 seconds ago                       swss
82270274a7e8        docker-fpm-frr:latest                "/usr/bin/docker_ini…"   4 minutes ago        Up 4 minutes                                    bgp
7ca92ef4df0b        docker-platform-monitor:latest       "/usr/bin/docker_ini…"   4 minutes ago        Up 4 minutes                                    pmon
7f396a830ba9        docker-database:latest               "/usr/local/bin/dock…"   4 minutes ago        Up 4 minutes                                    database
admin@l1-g5-osl2:~$ show techsupport
```

`show techsupport` result: [sonic_dump_l1-g5-osl2.n.bitbit.net_20211111_063034.tar.gz](https://github.com/Azure/sonic-buildimage/files/7518281/sonic_dump_l1-g5-osl2.n.bitbit.net_20211111_063034.tar.gz)

**Comment by toreanderson** [comment]
For what it is worth, the latest `master` image that works is [SONiC.master.43924-dirty-20211016.142146](https://sonic-build.azurewebsites.net/api/sonic/artifacts?branchName=master&platform=broadcom&buildId=43924&target=target%2Fsonic-broadcom.bin).

**Comment by zebracrowd** [comment]
I tried an image based off of 8219975d6fb35fcaed458401468c2673a7181179 and it is still failing. I have a new build based off of 5826a5c4e751124e2552c78ef826248b49071379 (after the bullseye upgrade) compiling, will update when i am done with the test.

**Comment by zebracrowd** [comment]
results of the test on 5826a5c4e751124e2552c78ef826248b49071379 => still seeing the same failure

**Comment by toreanderson** [comment]
Just tested [df12ac5abd](https://sonic-build.azurewebsites.net/api/sonic/artifacts?branchName=master&platform=broadcom&buildId=51044&target=target%2Fsonic-broadcom.bin), still does not work.

**Comment by danninov** [comment]
I have this problem too, trying with latest build 51255 [db0b789b73](https://github.com/Azure/sonic-buildimage/commit/db0b789b73c56fe9d62831d2422439ef6d7a2f77), still doesn't work. 

```
admin@sonic:~$ show interfaces status
  Interface    Lanes    Speed    MTU    FEC    Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  -------  -------  -----  -----  -------  ------  ------  -------  ------  ----------
```

**Comment by zebracrowd** [comment]
```
Setting up sonic-platform-accton-as7326-56x (1.1) ...
[FAILED] Failed to start PDDF modul…device initialization service.
[   10.016354] rc.local[934]: Job for pddf-platform-init.service failed because the
 control process exited with error code.
[   10.038942] rc.local[934]: See "systemctl status pddf-platform-init.service" and
 "journalctl -xe" for details.
```
I wonder if this is not the cause of the failure. 

```
admin@sonic:~$ sudo /usr/local/bin/pddf_util.py install
  File "/usr/local/bin/pddf_util.py", line 160
    except OSError, e:
                  ^
SyntaxError: invalid syntax
```

**Comment by toreanderson** [comment]
@zebracrowd Huh, that is weird. Just installed db0b789b73 (using [this sonic-broadcom.bin](https://sonic-build.azurewebsites.net/api/sonic/artifacts?branchName=master&platform=broadcom&buildId=51255&target=target%2Fsonic-broadcom.bin)) to try to debug this, but it turns out that file is not even present on the system:

```
$ sudo journalctl -u pddf-platform-init.service -o cat
Starting PDDF module and device initialization service...
pddf-platform-init.service: Failed to locate executable /usr/local/bin/pddf_util.py: No such file or directory
pddf-platform-init.service: Failed at step EXEC spawning /usr/local/bin/pddf_util.py: No such file or directory
pddf-platform-init.service: Main process exited, code=exited, status=203/EXEC
pddf-platform-init.service: Failed with result 'exit-code'.
Failed to start PDDF module and device initialization service.
$ show ver | head

SONiC Software Version: SONiC.master.51255-dirty-20211115.182321
Distribution: Debian 11.1
Kernel: 5.10.0-8-2-amd64
Build commit: db0b789b7
Build date: Mon Nov 15 18:45:14 UTC 2021
Built by: AzDevOps@sonic-build-workers-000WAE

Platform: x86_64-accton_as7326_56x-r0
HwSKU: Accton-AS7326-56X

```

**Comment by zebracrowd** [comment]
on the master branch pddf is enabled by default. The script lives there `./platform/pddf/i2c/utils/pddf_util.py` maybe your image is compiled without that option?
In the mean time, there are a _lot_ of pending PR from accton regarding pddf on this platform. They are not updating this util specifically though. Trying to fix this code to actually run and see where i land. But we might want to ask @jostar-yang for help, since he seems to be the author of most of the pddf pr from accton

**Comment by toreanderson** [comment]
I am using the official builds found at https://sonic-build.azurewebsites.net/ui/sonic/Pipelines, I do not know which options it is compiled with but I would assume it is supposed to work…

**Comment by zebracrowd** [comment]
that makes sense, I am still digging into the details but i suspect that this is a red herring again. I patched (hacked) the pddf utils and parse scripts to make them py3 compatible and fix all those mixed tab and spaces. I am still fighting with a missing kernel module but i am starting to think that the asic specific parts are set elsewhere so this pddf issue should not impact the switch itself, only the led/fan/etc,...

**Comment by zebracrowd** [comment]
I am able to start syncd on master after ddfe87a71a84b7ce47324f178b4aeb5192887cf1 and 6ed0c434b3496ae7afd273d634724e80fab94ffb

**Comment by ITJamie** [comment]
I just installed latest build for broadcom. Interfaces now show up 🎉 . 
But still no system details / fan control. attempting to start the pddf-platform-init service still shows missing files stopping service from starting
```
admin@spine-sw02:~$ show interfaces status
  Interface            Lanes    Speed    MTU    FEC            Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  ---------------  -------  -----  -----  ---------------  ------  ------  -------  ------  ----------
  Ethernet0          1,2,3,4     100G   9100    N/A    Eth1/1(Port1)  routed    down       up     N/A         N/A
  Ethernet4          5,6,7,8     100G   9100    N/A    Eth2/1(Port2)  routed    down       up     N/A         N/A
  Ethernet8       9,10,11,12     100G   9100    N/A    Eth3/1(Port3)  routed    down       up     N/A         N/A
 Ethernet12      13,14,15,16     100G   9100    N/A    Eth4/1(Port4)  routed    down       up     N/A         N/A
 Ethernet16      17,18,19,20     100G   9100    N/A    Eth5/1(Port5)  routed    down       up     N/A         N/A
 Ethernet20      21,22,23,24     100G   9100    N/A    Eth6/1(Port6)  routed    down       up     N/A         N/A
 Ethernet24      25,26,27,28     100G   9100    N/A    Eth7/1(Port7)  routed    down       up     N/A         N/A
 Ethernet28      29,30,31,32     100G   9100    N/A    Eth8/1(Port8)  routed    down       up     N/A         N/A
 Ethernet32      33,34,35,36     100G   9100    N/A    Eth9/1(Port9)  routed    down       up     N/A         N/A
 Ethernet36      37,38,39,40     100G   9100    N/A  Eth10/1(Port10)  routed    down       up     N/A         N/A
 Ethernet40      41,42,43,44     100G   9100    N/A  Eth11/1(Port11)  routed    down       up     N/A         N/A
 Ethernet44      45,46,47,48     100G   9100    N/A  Eth12/1(Port12)  routed    down       up     N/A         N/A
 Ethernet48      49,50,51,52     100G   9100    N/A  Eth13/1(Port13)  routed    down       up     N/A         N/A
 Ethernet52      53,54,55,56     100G   9100    N/A  Eth14/1(Port14)  routed    down       up     N/A         N/A
 Ethernet56      57,58,59,60     100G   9100    N/A  Eth15/1(Port15)  routed    down       up     N/A         N/A
 Ethernet60      61,62,63,64     100G   9100    N/A  Eth16/1(Port16)  routed    down       up     N/A         N/A
 Ethernet64      65,66,67,68     100G   9100    N/A  Eth17/1(Port17)  routed    down       up     N/A         N/A
 Ethernet68      69,70,71,72     100G   9100    N/A  Eth18/1(Port18)  routed    down       up     N/A         N/A
 Ethernet72      73,74,75,76     100G   9100    N/A  Eth19/1(Port19)  routed    down       up     N/A         N/A
 Ethernet76      77,78,79,80     100G   9100    N/A  Eth20/1(Port20)  routed    down       up     N/A         N/A
 Ethernet80      81,82,83,84     100G   9100    N/A  Eth21/1(Port21)  routed    down       up     N/A         N/A
 Ethernet84      85,86,87,88     100G   9100    N/A  Eth22/1(Port22)  routed    down       up     N/A         N/A
 Ethernet88      89,90,91,92     100G   9100    N/A  Eth23/1(Port23)  routed    down       up     N/A         N/A
 Ethernet92      93,94,95,96     100G   9100    N/A  Eth24/1(Port24)  routed    down       up     N/A         N/A
 Ethernet96     97,98,99,100     100G   9100    N/A  Eth25/1(Port25)  routed    down       up     N/A         N/A
Ethernet100  101,102,103,104     100G   9100    N/A  Eth26/1(Port26)  routed    down       up     N/A         N/A
Ethernet104  105,106,107,108     100G   9100    N/A  Eth27/1(Port27)  routed    down       up     N/A         N/A
Ethernet108  109,110,111,112     100G   9100    N/A  Eth28/1(Port28)  routed    down       up     N/A         N/A
Ethernet112  113,114,115,116     100G   9100    N/A  Eth29/1(Port29)  routed    down       up     N/A         N/A
Ethernet116  117,118,119,120     100G   9100    N/A  Eth30/1(Port30)  routed    down       up     N/A         N/A
Ethernet120  121,122,123,124     100G   9100    N/A  Eth31/1(Port31)  routed    down       up     N/A         N/A
Ethernet124  125,126,127,128     100G   9100    N/A  Eth32/1(Port32)  routed    down       up     N/A         N/A
admin@spine-sw02:~$ uname -a
Linux spine-sw02.bk3.39122.as 5.10.0-8-2-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
admin@spine-sw02:~$ show platform fan
Fan Not detected
admin@spine-sw02:~$ show platform psustatus
Error: Failed to get the number of PSUs
Error: Failed to get PSU status
Error: failed to get PSU status from state DB
admin@spine-sw02:~$ show platform summary
Platform: x86_64-accton_as7726_32x-r0
HwSKU: Accton-AS7726-32X
ASIC: broadcom
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
```
attempting to start pddf service
```
root@spine-sw02:/usr/local/bin# service pddf-platform-init status
● pddf-platform-init.service - PDDF module and device initialization service
     Loaded: loaded (/lib/systemd/system/pddf-platform-init.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-02-13 01:07:57 UTC; 2s ago
    Process: 6523 ExecStartPre=/usr/local/bin/pre_pddf_init.sh (code=exited, status=0/SUCCESS)
    Process: 6524 ExecStart=/usr/local/bin/pddf_util.py install (code=exited, status=203/EXEC)
   Main PID: 6524 (code=exited, status=203/EXEC)

Feb 13 01:07:57 spine-sw02.bk3.39122.as systemd[1]: Starting PDDF module and device initialization service...
Feb 13 01:07:57 spine-sw02.bk3.39122.as systemd[6523]: pddf-platform-init.service: Executable /usr/local/bin/pre_pddf_init.sh missing, skipping: No such file or directory
Feb 13 01:07:57 spine-sw02.bk3.39122.as systemd[6524]: pddf-platform-init.service: Failed to locate executable /usr/local/bin/pddf_util.py: No such file or directory
Feb 13 01:07:57 spine-sw02.bk3.39122.as systemd[6524]: pddf-platform-init.service: Failed at step EXEC spawning /usr/local/bin/pddf_util.py: No such file or directory
Feb 13 01:07:57 spine-sw02.bk3.39122.as systemd[1]: pddf-platform-init.service: Main process exited, code=exited, status=203/EXEC
Feb 13 01:07:57 spine-sw02.bk3.39122.as systemd[1]: pddf-platform-init.service: Failed with result 'exit-code'.
Feb 13 01:07:57 spine-sw02.bk3.39122.as systemd[1]: Failed to start PDDF module and device initialization service.
```
