### ISSUE TITLE
Insufficient sonic_platform support for as7315_27xb - no module named sonic_platform

### ISSUE THREAD

**Issue by sif7en** [Azure/sonic-buildimage#9765]
Hi,

#### Description

I have a problem with missing module sonic_platform
Consenquently we  have a dropp of watchdog-control and swss services

Swss or switch stateservice is keep dropping because of control-watchdog service claiming it can't import sonic-platform:

-- Logs begin at Fri 2022-01-14 10:18:00 UTC, end at Fri 2022-01-14 10:48:37 UTC. --
Jan 14 10:18:26 sonic systemd[1]: Started watchdog control service.
Jan 14 10:18:26 sonic root[2004]: /usr/local/bin/watchdog-control.sh : Disabling Watchdog during bootup after cold
Jan 14 10:18:26 sonic watchdog-control.sh[1995]: Traceback (most recent call last):
Jan 14 10:18:26 sonic watchdog-control.sh[1995]:   File "/usr/bin/watchdogutil", line 8, in <module>
Jan 14 10:18:26 sonic watchdog-control.sh[1995]:     from watchdogutil.main import watchdogutil
Jan 14 10:18:26 sonic watchdog-control.sh[1995]:   File "/usr/lib/python2.7/dist-packages/watchdogutil/main.py", line 15, in <module>
Jan 14 10:18:26 sonic watchdog-control.sh[1995]:     raise ImportError("%s - required module not found" % str(e))
Jan 14 10:18:26 sonic watchdog-control.sh[1995]: ImportError: No module named sonic_platform - required module not found
Jan 14 10:18:26 sonic systemd[1]: watchdog-control.service: Main process exited, code=exited, status=1/FAILURE
Jan 14 10:18:26 sonic systemd[1]: watchdog-control.service: Unit entered failed state.
Jan 14 10:18:26 sonic systemd[1]: watchdog-control.service: Failed with result 'exit-code'.
-- Logs begin at Fri 2022-01-14 10:18:00 UTC, end at Fri 2022-01-14 10:48:37 UTC. --
Jan 14 10:18:23 sonic systemd[1]: Starting switch state service...
Jan 14 10:18:23 sonic swss.sh[1780]: True
Jan 14 10:18:23 sonic swss.sh[1780]: True
Jan 14 10:18:24 sonic swss.sh[1780]: True
Jan 14 10:18:24 sonic swss.sh[1780]: True
Jan 14 10:18:24 sonic swss.sh[1780]: True
Jan 14 10:18:25 sonic swss.sh[1780]: Starting existing swss container with HWSKU Accton-AS7315-27XB
Jan 14 10:18:25 sonic swss.sh[1780]: swss
Jan 14 10:18:26 sonic systemd[1]: Started switch state service.
Jan 14 10:18:39 sonic root[3071]: Stopping swss service...
Jan 14 10:18:39 sonic root[3074]: Locking /tmp/swss-syncd-lock from swss service
Jan 14 10:18:40 sonic swss.sh[3070]: swss
Jan 14 10:19:18 sonic systemd[1]: swss.service: Service hold-off time over, scheduling restart.
Jan 14 10:19:18 sonic systemd[1]: Stopped switch state service.
Jan 14 10:19:18 sonic systemd[1]: Starting switch state service...
Jan 14 10:19:19 sonic swss.sh[3408]: True
Jan 14 10:19:19 sonic swss.sh[3408]: True
Jan 14 10:19:19 sonic swss.sh[3408]: True
Jan 14 10:19:19 sonic swss.sh[3408]: True
Jan 14 10:19:19 sonic swss.sh[3408]: True
Jan 14 10:19:20 sonic swss.sh[3408]: Starting existing swss container with HWSKU Accton-AS7315-27XB
Jan 14 10:19:21 sonic swss.sh[3408]: swss
Jan 14 10:19:21 sonic systemd[1]: Started switch state service.
Jan 14 10:25:38 sonic root[11039]: Warm boot flag: swss false.
Jan 14 10:25:38 sonic swss.sh[11024]: swss
Jan 14 10:25:38 sonic root[11052]: Stopped swss service...
Jan 14 10:25:38 sonic root[11060]: Unlocking /tmp/swss-syncd-lock (10) from swss service
Jan 14 10:26:20 sonic systemd[1]: swss.service: Service hold-off time over, scheduling restart.
Jan 14 10:26:21 sonic systemd[1]: Stopped switch state service.
Jan 14 10:26:21 sonic systemd[1]: Starting switch state service...
Jan 14 10:26:22 sonic root[11613]: Warm boot flag: swss false.
Jan 14 10:26:22 sonic root[11616]: Flushing APP, ASIC, COUNTER, CONFIG, and partial STATE databases ...
Jan 14 10:26:22 sonic swss.sh[11551]: True
Jan 14 10:26:22 sonic swss.sh[11551]: True
Jan 14 10:26:22 sonic swss.sh[11551]: True
Jan 14 10:26:22 sonic swss.sh[11551]: True
Jan 14 10:26:23 sonic swss.sh[11551]: True
Jan 14 10:26:24 sonic swss.sh[11551]: Starting existing swss container with HWSKU Accton-AS7315-27XB
Jan 14 10:26:24 sonic swss.sh[11551]: swss
Jan 14 10:26:25 sonic systemd[1]: Started switch state service.
Jan 14 10:26:36 sonic root[12543]: Stopping swss service...
Jan 14 10:26:36 sonic root[12546]: Locking /tmp/swss-syncd-lock from swss service
Jan 14 10:26:36 sonic root[12550]: Locked /tmp/swss-syncd-lock (10) from swss service
Jan 14 10:26:36 sonic swss.sh[12542]: swss
Jan 14 10:26:36 sonic root[12574]: Stopped swss service...
Jan 14 10:27:12 sonic systemd[1]: swss.service: Service hold-off time over, scheduling restart.
Jan 14 10:27:14 sonic systemd[1]: Stopped switch state service.
Jan 14 10:27:14 sonic systemd[1]: Starting switch state service...
Jan 14 10:27:14 sonic root[12920]: Starting swss service...
Jan 14 10:27:14 sonic swss.sh[12918]: True
Jan 14 10:27:15 sonic swss.sh[12918]: True
Jan 14 10:27:15 sonic swss.sh[12918]: True
Jan 14 10:27:15 sonic swss.sh[12918]: True
Jan 14 10:27:15 sonic swss.sh[12918]: True
Jan 14 10:27:16 sonic swss.sh[12918]: Starting existing swss container with HWSKU Accton-AS7315-27XB
Jan 14 10:27:16 sonic swss.sh[12918]: swss
Jan 14 10:27:17 sonic root[13095]: Unlocking /tmp/swss-syncd-lock (10) from swss service
Jan 14 10:27:17 sonic systemd[1]: Started switch state service.
Jan 14 10:27:30 sonic swss.sh[13995]: swss
Jan 14 10:28:06 sonic systemd[1]: swss.service: Service hold-off time over, scheduling restart.
Jan 14 10:28:09 sonic systemd[1]: Stopped switch state service.
Jan 14 10:28:09 sonic systemd[1]: swss.service: Start request repeated too quickly.
Jan 14 10:28:09 sonic systemd[1]: Failed to start switch state service.
Jan 14 10:28:09 sonic systemd[1]: swss.service: Unit entered failed state.
Jan 14 10:28:09 sonic systemd[1]: swss.service: Failed with result 'start-limit-hit'

Consenquently we're not able to config interface status.

#### Steps to reproduce the issue:
1. boot to SONIC-OS ....
2.
3.

#### Describe the results you received:

MIssing module for sonic_platform
watchdog_control and swss service dropped

#### Describe the results you expected:
All services running, able to config interfaces

#### Output of `show version`:

```
[version_output.txt](https://github.com/Azure/sonic-buildimage/files/7869437/version_output.txt)

(paste your output here)
```
#### Output of `show techsupport`:

```
[techsupport_output.txt](https://github.com/Azure/sonic-buildimage/files/7869434/techsupport_output.txt)

(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

[generate_dump_output.txt](https://github.com/Azure/sonic-buildimage/files/7869451/generate_dump_output.txt)

**Comment by zhangyanzhao** [comment]
@wally-wang-accton

**Comment by wally-wang-accton** [comment]
Accton added this platform 2 years ago.  At that time, we think Broadcom may support BCM88470 (Qumran AX) in bcmsai later.
Unfortunately, bcmsai does not support it till now.  So, you can't execute SONiC on this AS7315-27XB.

**Comment by sif7en** [comment]
Do you have any plans to provide SONiC support for AS7315-27XB? Is there any roadmap available ?

**Comment by wally-wang-accton** [comment]
It needs to ask Broadcom, because bcmsai is released by them.

**Comment by sif7en** [comment]
Please do so, since my company is interested in purchasing the device in question.

**Comment by wally-wang-accton** [comment]
As I know, Broadcom does not have roadmap for Qumran SAI.  Maybe you can consider TD3 platforms, AS7326-56X or AS5835-54X.

**Comment by sif7en** [comment]
We have in mind AS4630-54TE.

Regarding this device, please let me know if SONiC SDK is supported and if
we can install a custom app, like wireshark server for example ?

V V čet., 20. jan. 2022 ob 11:55 je oseba Wally Wang <
***@***.***> napisala:

**Comment by wally-wang-accton** [comment]
Yes, you can use AS4630-54TE if its hardware features are enough for you.
Please note it, it still has some open PRs if you test its SONiC image.  
https://github.com/Azure/sonic-buildimage/pulls?q=is%3Apr+is%3Aopen+AS4630-54TE

**Comment by sif7en** [comment]
Hi,

One more question from my side.

I am trying to boot latest ONIE sw on as7315_27xb via USB, However it
appears the Bios is locked.

Ia there a way unlock it or reset it ?

Regards,
Peter

V V čet., 20. jan. 2022 ob 04:12 je oseba Wally Wang <
***@***.***> napisala:
