### ISSUE TITLE
Some iptables rules can't be removed after "acl-loader delete" three cacl tables on multi asic testbed.

### ISSUE THREAD

**Issue by ZhaohuiS** [Azure/sonic-buildimage#9824]
#### Description

Some iptables rules can't be removed after "acl-loader delete" three cacl tables on multi asic testbed.
Load scale cacl rules with json file on asic0, there are many corresponding iptables rules are created on asic0.
Clear cacl table with "acl-loader delete" command, there are some iptables rules can't be cleaned. 

#### Steps to reproduce the issue:
1. Load multiple rules(50 rules for each cacl table) with json file on asic0:
sudo ip netns exec asic0  acl-loader update full /tmp/scale_cacl.json
2. check iptables rules are created on asci0
sudo ip netns exec asic0 iptables -S
3. Delete cacl table rules one by one
sudo ip netns exec asic0 acl-loader delete SSH_ONLY
sudo ip netns exec asic0 acl-loader delete SNMP_ACL
sudo ip netns exec asic0 acl-loader delete NTP_ACL

4. check some iptables rules are still existing on asci0
```
sudo ip netns exec asic0 iptables -S
...
-A INPUT -s 20.0.0.2/32 -p udp -m udp --dport 123 -j DROP
-A INPUT -s 20.0.0.3/32 -p udp -m udp --dport 123 -j DROP
-A INPUT -s 20.0.0.4/32 -p udp -m udp --dport 123 -j DROP
-A INPUT -s 20.0.0.5/32 -p udp -m udp --dport 123 -j DROP
-A INPUT -s 20.0.0.6/32 -p udp -m udp --dport 123 -j DROP
-A INPUT -s 20.0.0.7/32 -p udp -m udp --dport 123 -j DROP
-A INPUT -s 20.0.0.8/32 -p udp -m udp --dport 123 -j DROP
...
```
#### Output of `show version`:

traceback found in /var/log/syslog
```
WARNING swss2#orchagent: :- removeAclRule: Skip removing rule RULE_11 from ACL table NTP_ACL. Table does not exist
INFO caclmgrd[22796]: Exception in thread Thread-9:
INFO caclmgrd[22796]: Traceback (most recent call last):
INFO caclmgrd[22796]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
INFO caclmgrd[22796]:     self.run()
INFO caclmgrd[22796]:   File "/usr/lib/python2.7/threading.py", line 754, in run
INFO caclmgrd[22796]:     self.__target(*self.__args, **self.__kwargs)
INFO caclmgrd[22796]:   File "/usr/bin/caclmgrd", line 618, in check_and_update_control_plane_acls
INFO caclmgrd[22796]:     self.update_control_plane_acls(namespace)
INFO caclmgrd[22796]:   File "/usr/bin/caclmgrd", line 574, in update_control_plane_acls
INFO caclmgrd[22796]:     self.update_control_plane_nat_acls(namespace, service_to_source_ip_map)
INFO caclmgrd[22796]:   File "/usr/bin/caclmgrd", line 584, in update_control_plane_nat_acls
INFO caclmgrd[22796]:     iptables_cmds = self.generate_fwd_traffic_from_namespace_to_host_commands(namespace, 
INFO caclmgrd[22796]:   File "/usr/bin/caclmgrd", line 305, in generate_fwd_traffic_from_namespace_to_host_commands
INFO caclmgrd[22796]:     nat_source_ipv4_set = acl_source_ip_map[acl_service]["ipv4"] if acl_source_ip_map and lse { "0.0.0.0/0" }
INFO caclmgrd[22796]: KeyError: 'SSH'
INFO caclmgrd[22796]: Exception in thread Thread-8:
INFO caclmgrd[22796]: Traceback (most recent call last):
```
#### Output of `show techsupport`:

```
show version

SONiC Software Version: SONiC.20191130.80
Distribution: Debian 9.13
Kernel: 4.9.0-14-2-amd64
Build commit: a84572e58f
Build date: Thu Nov 25 04:50:32 UTC 2021
Built by: cloudtest@2d06b628c000001

Platform: x86_64-n3164-r0
HwSKU: Nexus-3164
ASIC: broadcom
Serial Number: SAL2025S727
Uptime: 10:20:00 up  4:27,  2 users,  load average: 2.80, 3.24, 3.00

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-fpm-frr             20191130.80         c21e6ce07c90        326MB
docker-fpm-frr             latest              c21e6ce07c90        326MB
docker-orchagent           20191130.80         7a8835b91d50        334MB
docker-orchagent           latest              7a8835b91d50        334MB
docker-teamd               20191130.80         e4c41f47778e        315MB
docker-teamd               latest              e4c41f47778e        315MB
docker-syncd-brcm          20191130.80         ae67e8202d59        437MB
docker-syncd-brcm          latest              ae67e8202d59        437MB
docker-platform-monitor    20191130.80         97597c7a36d6        358MB
docker-platform-monitor    latest              97597c7a36d6        358MB
docker-acms                20191130.80         d34e7fc4adf6        184MB
docker-acms                latest              d34e7fc4adf6        184MB
docker-lldp-sv2            20191130.80         592f21c2a159        312MB
docker-lldp-sv2            latest              592f21c2a159        312MB
docker-snmp-sv2            20191130.80         60cb171584f2        353MB
docker-snmp-sv2            latest              60cb171584f2        353MB
docker-sonic-telemetry     20191130.80         d278a6505e07        354MB
docker-sonic-telemetry     latest              d278a6505e07        354MB
docker-router-advertiser   20191130.80         6cee444d93be        290MB
docker-router-advertiser   latest              6cee444d93be        290MB
docker-dhcp-relay          20191130.80         3197d2c19c7e        300MB
docker-dhcp-relay          latest              3197d2c19c7e        300MB
docker-database            20191130.80         83b2f5af91cc        290MB
docker-database            latest              83b2f5af91cc        290MB
k8s.gcr.io/pause           3.2                 80d28bedfe5d        683kB

```

**Comment by zhangyanzhao** [comment]
Is this a regression issue?

**Comment by ZhaohuiS** [comment]
@zhangyanzhao I think so. It needs a design improvement to fix this issue.
